### ISSUE TITLE
FIDO2 on Trezor One

### ISSUE THREAD

**Issue by 1000i100** [trezor/trezor-firmware#1000]
U2F authentication is check in your website for Trezor One but not FIDO2.
Is there hardware limit about this ?

I would like to use FIDO2 on a cheaper device than Model T.

There is some word about it in #39 after it have been closed.

**Comment by prusnak** [comment]
Currently, FIDO2 is supported only on Trezor Model T.

**Comment by My1** [comment]
a better answer than in 2019 when it was not even planned, but still kinda sad it's just on the (kinda expensive) model T

**Comment by m5x** [comment]
Is FIDO2 still coming to Trezor One? It would be great to have it, Trezor T is too bulky for my usage.

**Comment by prusnak** [comment]
> Is FIDO2 still coming to Trezor One? It would be great to have it, Trezor T is too bulky for my usage.

Yes, but no ETA yet

**Comment by aasami** [comment]
Another year passed. Still no support? This feels like hydrogen fuel adoption. Forever the fuel of the future.

**Comment by My1** [comment]
I guess it's 2023 now. would be really cool for having FIDO2 on The T1.

**Comment by Jordo0G** [comment]
Any update? 2024 and Trezor One is still a great device. I know the Safe 3 is now the flagship, but there's so many One's out there just waiting to be used for FIDO2.

**Comment by prusnak** [comment]
FIDO2 is not coming to Trezor One. Get a Trezor Safe 3 if you want FIDO2 on smaller device than Trezor Model T.
