### ISSUE TITLE
Reuse derived Shamir seed in Cardano app

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#1007]
With the introduction of session cache, we stopped caching plaintext of the passphrase. That means that with Single backup (BIP39), we need to ask for passphrase separately in the Cardano app -- because Cardano derives the root from the mnemonic via a different algorithm than BIP39.

This is no longer true with SLIP39+SLIP23: the SLIP39 Master Secret (which already incorporates the passphrase) is used for deriving the Cardano root directly.

Our code does not take advantage of this; instead, it asks the user for a passphrase in all cases, and re-derives the Master Secret.

In case the device is using Shamir backup, we should reuse the cached Master Secret instead of prompting for passphrase separately.

**Comment by tsusanka** [comment]
## QA

Please try Cardano signing at adalite.io. Notice you exceptionally need to use master (59b8a5a) not what we have frozen.

**Comment by tsusanka** [comment]
Cardano signing tested as part of _Freeze_. See [testpad](https://satoshilabs.ontestpad.com/script/266#6/3/).

@bosomt could you please test one more thing here and that's:
- Take latest FW 2.3.4.
- Recover Trezor with some mnemonic (whatever).
- Use some passphrase (whatever).
- Get Cardano address via adalite.
- Do the very same thing with 2.3.5 RC, same mnemonic, same passphrase.
- Verify the addresses match.

Thanks!

**Comment by bosomt** [comment]
@tsusanka ON IT

**Comment by bosomt** [comment]
i see tx history, addresses and funds with same mnemonic and passphrase

**regular-2.3.5-889a3699**

![image](https://user-images.githubusercontent.com/31506317/103207746-626b6d80-48ff-11eb-8899-2556bb400b54.png)

**public 2.3.4**

![image](https://user-images.githubusercontent.com/31506317/103208131-2be22280-4900-11eb-871f-923c4d78f028.png)

**Comment by bosomt** [comment]
and now wish Shamir seed :)

**2.3.4**

addr1qydjh946sw6d83tg5v6x0z8f0zayd68xpjefwxv9ulf7ke76fr6d4ccs5gfn4aduwg8f2dx370m2gynhlzdzkcnrlwzs0x9hja

![image](https://user-images.githubusercontent.com/31506317/103210018-c2184780-4904-11eb-8864-661db2f9824c.png)

**regular-2.3.5-889a3699**

addr1qydjh946sw6d83tg5v6x0z8f0zayd68xpjefwxv9ulf7ke76fr6d4ccs5gfn4aduwg8f2dx370m2gynhlzdzkcnrlwzs0x9hja

![image](https://user-images.githubusercontent.com/31506317/103210672-a9109600-4906-11eb-84af-b484368c299d.png)

**Comment by tsusanka** [comment]
Great, thank you!
