### ISSUE TITLE
Figure out translations data blob signing process

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1016]
In #988 we are implementing the translations data blob. In this issue we should figure out how to sign the blob.

- Are we going to use another key than what is used to sign the firmware? Probably yes.
- Should this be auto-signed on Gitlab? Probably no.
- We might come up with a similar mechanism as firmware has but lower the signature threshold. In another words, only one of @prusnak / @slush0 is required to generate a valid signature.

---

Part of #987. Related #988.

**Comment by Hannsek** [comment]
We will sign it as the eth definitions, right? @matejcik 
I believe we can close this.

**Comment by matejcik** [comment]
yup, this is basically done as part of #3206 / #3491
