### ISSUE TITLE
Update Theta from supported coins

### ISSUE THREAD

**Issue by cryptomar1o** [trezor/trezor-firmware#1023]
Theta did launch a new main net token that is no longer using ERC20 token standard. Theta team decided to use the same address format that is used by Ethereum. They are also using the very same derivation path as Ethereum for their standard address (m’/44’/60’/0’/0 - at least this derivation path is used by their Theta Wallet application).

It is possible to access Theta network with Trezor device by using Theta Wallet application (https://wallet.thetatoken.org/) through Trezor Connect.

The information about Theta from supported coins & tokens (https://trezor.io/coins/#THETA) should be updated, Theta token on the main net token to be added or the support to be removed. Otherwise users and 3rd party services can be easily mistaken.

**Comment by matejcik** [comment]
Removing THETA ERC token seems like a thing we should definitely do.

If Theta mainnet currently works by pretending to be Ethereum, I presume that's Theta's call. That's of course discouraged by us, and it might fail in the future when we enforce coin separation.
