### ISSUE TITLE
Allow only BIP69 transactions?

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#1029]
Do we want to allow only BIP69 transactions? (lexicographically sorted inputs and outputs).

Our web wallet already does this, but what about the others?

- [x] Trezor Wallet
- [x] Trezor Suite
- [x] Trezor Connect
- [ ] Bitcoin Core
- [x] Electrum - yes https://github.com/spesmilo/electrum/commit/e2c05c2400399fe24ddacfe114673cd75b9ba3c1
- [ ] Wasabi - no https://docs.wasabiwallet.io/using-wasabi/BIPs.html + https://medium.com/@nopara73/wasabileaks-is-wasabi-wallet-deanonymized-5e3f679d866e
- [x] Samourai - yes https://github.com/Samourai-Wallet/samourai-wallet-android#bip69
- [ ] PSBT
- [ ] Payjoin - no https://docs.btcpayserver.org/Payjoin-spec/#increasing-privacy-of-clients-using-bip69

**Comment by destrys** [comment]
Is the proposal here to have Trezor devices only able to sign BIP69 transactions?

If so, I think this isn't a good idea.
BIP69 isn't part of consensus, it's still just proposed.
I don't see a convincing reason to have a hardware wallet add a layer of restriction. 
It seems to me that BIP69 is a wallet spec, not a keystore spec.

Interestingly, this would introduce a tiny data leak, any non-BIP69 transaction would be known to be signed by a non-Trezor.

**Comment by prusnak** [comment]
Yes, this was a meta-task to document the current state of things. I still think BIP69 is good, but we will not enforce it in Trezor for now.
