### ISSUE TITLE
Closer integration of FIDO and configurable auto-lock

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#1041]
With #75 done, the state of FIDO is that it does not request PIN for a maximum of fixed **3 minutes** after it was last entered.

If an auto-lock engages before that, FIDO will reprompt. If autolock is set to a later time (e.g., the default 10 minutes), FIDO will ask for PIN sooner.

**Notably,** FIDO will ask for PIN after 3 minutes from last entry, regardless of whether the user is actively using the device.

Is this a behavior that we want to keep or change?

Other options:
- ignore user activity but reprompt after &lt;autolock-timeout> seconds
- keep fixed 3 minutes, do not ignore user activity
- do not ignore user activity, reprompt after &lt;autolock-timeout> seconds

**Comment by matejcik** [comment]
time has shown that nobody cares.

we can fix any issue if it ever arises

**Comment by knaperek** [comment]
I care. This would be great for devices w/o touch screen, please.
