### ISSUE TITLE
Investigate coverage drop

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#1051]
It seems the coverage (in the `core unix coverage posttest` CI target) has dropped to 17%. My guess is something got broken in the coverage itself.

Let's find out what exactly it was and maybe introduce a rule which fails the coverage target in the CI if the percentage is decreased (or below a fixed value).

**Comment by tsusanka** [comment]
@mmilata this is something you might look at in case you find yourself eager to do some github issue :). Might be good to grasp another parts of the code.

**Comment by mmilata** [comment]
The coverage records contain out-of-range line numbers. This is caused by `mpy-tool.py` corrupting the line number information during module freezing. Opened upstream PR to fix it:  micropython/micropython#6335

**Comment by tsusanka** [comment]
Btw we are using our forked micropython. So @prusnak should @mmilata file the PR into trezor/micropython as well and we merge it there?

**Comment by prusnak** [comment]
Yes, @mmilata send PR against https://github.com/trezor/micropython - `trezor-v1.12` branch. Once merged here, we'll update the https://github.com/trezor/trezor-firmware/pull/1185 to use this updated branch.
