### ISSUE TITLE
Implement the CoinJoin signing flow

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1053]
Implement the CoinJoin signing flow in Trezor.

**Comment by andrewkozlik** [comment]
@hiviah 

**Documentation copied from the PR:**

The implementation enables the following flow:
1. The client application sends an `AuthorizeCoinJoin` message. The parameters for user approval include:
    - The coordinator name, e.g. "www.trezor.io".
    - The maximum total fee.
    - BIP32 account path of the inputs and their script type.
    - Optionally the fee per anonymity set as a uint32 in units of 10^-9 percent. So 0.003 % would be given as 3000000 and the maximum fee that can be set is approximately 4.29 %. I didn't want to use floats to avoid showing something like 0.00299999 on the display, plus we don't support floats in our protobuf implementation anyway.
2. User confirms the message parameters (coordinator name, fee per anonymity set, maximum total fee, possibly a non-standard BIP32 account path). 
![image](https://user-images.githubusercontent.com/42678794/88309375-82728180-cd0e-11ea-9122-da49f323401c.png) ![image](https://user-images.githubusercontent.com/42678794/88309397-8b635300-cd0e-11ea-9265-10bda34bc80b.png)
3. The client application can now issue certain commands without requiring any user interaction. The commands work even in soft-locked mode. To do this the client takes the following steps:
    i. Client sends a `DoPreauthorized` message (no parameters).
    ii. If there is an active authorization, then the client receives a `PreauthorizedRequest` message from the device, otherwise `ProcessError`.
    iii. Client sends the desired command and communication continues as usual for that command.

At most one authorization per session is allowed to exist at any one time. If a new authorization is confirmed, it replaces any previous one. Multiple authorizations are currently possible by having them in different sessions. The `DoPreauthorized` flow can be performed multiple times for one authorization. It supports two commands:
- `GetOwnershipProof`:
    - The coin and BIP32 account path must match the authorized values.
    - The commitment data must begin with the authorized coordinator name followed by any 32 byte value, which should be a CoinJoin round ID randomly generated by the coordinator.
    - The `user_confirmed` bit can and should be set to True, indicating that the user confirmed participation in any CoinJoin round organized by the given coordinator.
- `SignTx`:
    - This command can be issued repeatedly until the authorized fees are depleted, i.e. every time a transaction is signed, the overall fee is deducted from the authorized fee amount.
    - The outputs must be ordered so that the CoinJoined outputs are grouped by amount.
    - All of the user's inputs must come from the authorized BIP32 account path and have the approved script type.
    - Each of the user's outputs must satisfy the conditions for being a change output, otherwise it is treated as an external output. This mainly means the user's outputs have to go back into the same account the inputs came from.
    - The transaction will be declined if any of the following conditions are met:
        - The transaction doesn't increase the anonymity of the user's outputs.
        - The overall mining fee exceeds the standard threshold for which we would normally show a warning.
        - The user's fees exceed his fair share of coordinator and mining fees.
        - The user's total fees exceed the authorized fee amount.
        - The transaction has non-zero `nLockTime`.
