### ISSUE TITLE
Truncated Stellar destination address

### ISSUE THREAD

**Issue by tokyotechlab** [trezor/trezor-firmware#107]
Hi,

When making a transaction for Stellar, the destination address is gets truncated. 
https://imgur.com/a/tcxJCCX

Unless there are measures taken to make sure the truncation would not result in sending funds to incorrect address, the UI should be made scroll-able?

**Comment by tsusanka** [comment]
You're correct, the whole address should be visible. We're waiting for an overhall UI redesign, tracked in #53. I've added the issue there. Thanks.
