### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#108]
Loosely based on priority.

- [x] Propagate tests results into GitHub (the state).
- [x] Add python tests (@matejcik)
<s>- [ ] Add clang to tests. (@prusnak)</s> tracked https://github.com/trezor/trezor-firmware/issues/44
- [x] Add trezor-storage tests.
- [x] Remove all unused files. (@matejcik)
  - [x] Remove other Pipfiles (I suggest to have just one for the whole monorepo).
  - [x] Remove all `.travis.yml`
  - [x] Remove all other files that are not needed anymore by introducing pipenv everywhere, if there are any.
- [x] Investigate if `ITERS=10` is run under pipenv (see 'test crypto' job) (@matejcik)
- [x] Split .gitlab-ci into several files using `include`. (@tsusanka)
- [x] Unify setup.cfg (@matejcik)
- [x] Can we remove setup.cfg's tool:pytest section? (@matejcik)
  - @matejcik due to this setup it was impossible to run tests in crypto/, because `--pyargs trezorlib.tests.device_tests` is always attached. Is it safe to remove it completely?
- [x] Cache python's pipenv/virtualenv cache. (@tsusanka)
- [x] Cache submodules/vendor. (@tsusanka)
<s>- [ ] Make sure Pull Requests from external contributors are ran on CI.</s> Will be solved by paid GitLab instance
<s>- [ ] Propagate full tests results log into GitHub for external contributors.</s> Will be solved by paid GitLab instance
- [x] Add sanitizer tools</s> tracked https://github.com/trezor/trezor-firmware/issues/44
- [x] Each job should have its own make target. (@matejcik)
- [x] Move `make templates_check` from core to root (@matejcik)
- [x] Consider replacing `image: python` with `image: debian` in Dockerfile (@tsusanka)
- [x] Fix legacy build passing. (@tsusanka)
- [x] Add prebuild stage (@tsusanka)
- [x] Replace manual "environment" build with automatic one. Docker should know quite quickly it doesn't have to be updated.
- [x] Set GIT_SUBMODULE_STRATEGY to none or similar, where not needed.
- [x] Look into https://github.com/trezor/trezor-firmware/commit/fe3d67e259003a0edf676f36acbdca7c82f33098 comments if needed (@tsusanka)

Build improvements:

- [x] unify `legacy/build.sh` and `core/build-docker.sh` into a single `/build.sh` which builds both legacy+core via Docker (using the same image used for the CI) (@matejcik ?)
- [x] clean up the `legacy/script` madness (@matejcik ?)  #507

**Comment by tsusanka** [comment]
> Replace manual "environment" build with automatic one. Docker should know quite quickly it doesn't have to be updated.

We have to think this one through. Although it is true that the job is pretty quick, in the current settings it tags the build as `$CONTAINER_NAME:$CI_COMMIT_SHA`, in other words using the commit hash. That means that it gets uploaded into the registry every time, which could bloat pretty quickly. So we need to tag it differently or come up with another solution.

**Comment by tsusanka** [comment]
Note: to force pipenv to cache files in the current folder instead of HOME we need to use both `PIPENV_CACHE_DIR="dir"` and `PIPENV_VENV_IN_PROJECT=true`.

**Comment by matejcik** [comment]
i removed the `setup.cfg` in core, and left a `pytest.ini` in its place for convenient running of device tests from the `core` subdir. The global setup.cfg has configs for pyflake and isort.

python-trezor still has its own setup.cfg because there are slight differences and I don't think it's possible to inherit the identical parts from parent directory.
