### ISSUE TITLE
T1 firmware update via trezorctl incorrectly throws "Invalid firmware data." if firmware image is too small

### ISSUE THREAD

**Issue by hiviah** [trezor/trezor-firmware#1082]
**Describe the bug**
Updating T1 via `trezorctl firmware-update -f trezor.bin` throws `Invalid firmware data` if firmware is too small (I guess less than a full chunk). See attached small sample firmware that just shows trezor logo.

**Firmware version and revision**
Bootloader must be at least 1.8.0. Revision tested 6ebb38890557a33ea3ba15414b7148d6bcfc107e

**To Reproduce**
1. go to bootloader
1. `trezorctl firmware-update -f trezor.bin`
1. throws `Invalid firmware data`
1. if you comment out throwing the exception in `python/src/trezorlib/firmware.py` and try again, the flashing will succeed and firmware will run

**Additional context**
To create similar small T1 firmware, just put `while(1);` after `oledRefresh` in `main` of `trezor.c` and build with `MEMORY_PROTECT=0`

[trezor.zip](https://github.com/trezor/trezor-firmware/files/4826603/trezor.zip)

**Comment by matejcik** [comment]
fwiw you can use `firmware-update --skip-check` to side-step the error
