### ISSUE TITLE
Provide an option to retrieve the autolock delay setting

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1088]
To provide a good experience in Suite for https://github.com/trezor/trezor-suite/issues/1946 we need to publish the autolock delay setting in Trezor. Both in T1 and TT.

We might add it to Features but introducing something like `GetSettings` sounds more reasonable not to bloat them.

**Comment by tsusanka** [comment]
Let's ask Suite team, because we do not care that much.

**Comment by mroz22** [comment]
I dont like GetSettings very much for this. All other "options" are already present in Features.
Or do you mean introducing something like BasicFeatures containing only neccessary fields and then something like ExtendedFeatures with everything accessible via separate call? That sounds reasonable.

**Comment by tsusanka** [comment]
Let's add it to Features the usual way for now. As discussed some time ago we can also approach the bloating features by answering Success to Initialize but that would require a breaking change. So let's postpone for now.

**Comment by tsusanka** [comment]
@mmilata I think this one is a low-hanging issue as well.
