### ISSUE TITLE
Confirm auto-lock delay timeout on T1 screen

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1097]
As commented by @sorooris in https://github.com/trezor/trezor-firmware/issues/1066#issuecomment-651803034:

Comparison of model T (2.3.2 24f803e9) and T1 (1.9.2 24f803e9) dialogue (both after entering the same command `trezorctl set auto-lock-delay 10`):

 T1|TT
 -|-
![image](https://user-images.githubusercontent.com/10185314/86131749-50db1180-bae6-11ea-8717-c245c105cd5e.png)|![image](https://user-images.githubusercontent.com/10185314/86133487-a44e5f00-bae8-11ea-9bb2-4c2a2437029e.png)

Model T asks the user to confirm the time on-screen, T1 does not.

---

I am proposing not to fix this at the moment and fix this by doing _Port_. I will discuss this briefly with Product as well but let me know if you disagree.

**Comment by prusnak** [comment]
This has been fixed in 48e1dc957f
