### ISSUE TITLE
bump nanopb to 0.4.3

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#1105]
using protobuf fields with default values is currently impossible, because legacy's nanopb 0.4.1 will barf in some cases: https://github.com/nanopb/nanopb/issues/487

nanopb 0.4.2 was released a couple weeks ago which should include the fix
we need it in order to proceed with #379 / #1001

**Comment by prusnak** [comment]
0.4.3 was included in the meantime

**Comment by tsusanka** [comment]
Does this need QA?

**Comment by matejcik** [comment]
not separately. QA will test this as a part of normal `legacy` release run
