### ISSUE TITLE
Replace use_passphrase with setup_client in tests

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1110]
After #1107 is merged, let's replace `client.use_passphrase("passphrase")` with `setup_client(passphrase="passphrase")` where applicable.

**Comment by tsusanka** [comment]
Also let's drop support for "True" in the passphrase argument and replace all usages of `passphrase=True` with strings. If there are tests that need passphrase enabled but not prefilled let's make them do that call explicitly.

**Comment by matejcik** [comment]
done in #1801
