### ISSUE TITLE
model T responds with firmware error when loading white noise homescreen

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#1114]
**Describe the bug**
model T with 2.3.2 responds with firmware error when loading white noise homescreen
`Homescreen change failed.
Error details: Firmware error`
Default homescreens: `Success
Homescreen has been changed.`

with production FW 2.3.1 works fine

**Firmware version and revision**
FW 2.3.2 Revision e70811c

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: web wallet b3f18eb73765f92dd35eff2c562ef1edb5dd9fa3 
 - OS: Nixos
 - Browser CHromium
 - Version 83.0.4103.116

**To Reproduce**
1. wallet/suite/trerzorctl 
2. connect device with 2.3.2 revision e70811c
3.try to load custom background

**Expected behavior**

**Screenshots**

**Additional context**

wallet log: 
["log","Mon, 20 Jul 2020 12:17:16 GMT","[trezor.js] [call] Received","Failure",{"code":"Failure_FirmwareError","message":"Firmware error"}]
["log","Mon, 20 Jul 2020 12:17:16 GMT","[trezor.js] [session] releasing"]

trezorctl error:

ash-4.4$ trezorctl set homescreen -f ./Downloads/white-noise.toif 
Error: FirmwareError: Firmware error
bash-4.4$ trezorctl set homescreen -f ./Downloads/white-noise.toif 
Error: FirmwareError: Firmware error

**Comment by bosomt** [comment]
works ok with current master
trezor-fw-regular-2.3.2-bcd044a4.bin

**Comment by matejcik** [comment]
it seems that we're (still) running out of memory.
@bosomt please check if the issue persists if you do this on a freshly plugged-in Trezor

**Comment by matejcik** [comment]
if not, please continue testing with the whitenoise background set

**Comment by bosomt** [comment]
**QA OK**

@matejcik 
works fine now with same commit e70811c
i wiped device to bootloader, loaded FW and created new seed
do you want to close this issue ?

trezorctl set homescreen -f ./Downloads/white-noise.toif
Please confirm action on your Trezor device.
Settings applied

suite: Settings changed successfully

**Comment by matejcik** [comment]
i'll lower severities for now and see what we'll do about this

**Comment by tsusanka** [comment]
Related to #590.

**Comment by bosomt** [comment]
@tsusanka @matejcik 

we are running out of memory again, when you set white noise Homescreen device will freeze after load.
Device will freeze when you try to sign BTC tx later or when you try to load white noise homescreen again.
Homescreen size: 63400 B

FW 2.3.5 commit ffa96205f

**screenshots**

$ trezorctl set homescreen white-noise.png
Error: DataError: Failed to decode message: memory allocation failed, allocating 16849 bytes

![image](https://user-images.githubusercontent.com/31506317/106425767-ae608380-6464-11eb-821c-a39f0350798d.png)

![image](https://user-images.githubusercontent.com/31506317/106425795-b6202800-6464-11eb-892d-9b111d96e984.png)

**Comment by guiambros** [comment]
Same here, with a fresh new Trezor T. It fails when trying to upload a custom homescreen, both jpg as well as png 144x144. It returns "Firmware error", both through Trezor Suite and wallet.trezor.io. I'm using stock firmware 2.3.4.

![Screenshot from 2021-02-07 21-50-00](https://user-images.githubusercontent.com/205000/107170801-3bd53380-698f-11eb-939b-005d70df22d6.png)
