### ISSUE TITLE
Passphrase dialogue after disabling PIN

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-firmware#113]
TT (2.1.1), passphrase and PIN enabled
Chromium, any wallet

After successfully setting up a PIN on a device and leaving the onboarding process, disabling the PIN in the advanced settings tab, a page dialogue and a device prompt for passphrase entry are displayed. Could be reproduced only sometimes (after clearing cache/storage) and refreshing the page.
1) Selecting Host entry hides the dialogue and continues normally.
2) Selecting Device entry and entering a correct passphrase continues normally.
3) Selecting Device entry and entering an incorrect passphrase freezes the device until another prompt is sent to the device.
![passphrase after disabling PIN](https://user-images.githubusercontent.com/10185314/56885306-71d04e80-6a6c-11e9-8c3a-5042d721fbb3.jpg)

**Comment by prusnak** [comment]
This does not seem like a firmware issue, but rather a web wallet issue.

**Comment by tsusanka** [comment]
Might be connected to https://github.com/trezor/trezor-firmware/issues/75#issuecomment-486690410

**Comment by sorooris** [comment]
Closing and moving into the wallet repo (https://github.com/satoshilabs/mytrezor/issues/753).
