### ISSUE TITLE
Strengthen soft-checks in get_address and similar

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1137]
Follow-up of #1064. Let's strengthen soft-checks in get_address and similar to a hard fail unless the "safety_checks" setting is not set.

Let me discuss this in Product first, this can be sensitive for some 3rd parties.

**Comment by tsusanka** [comment]
`trezorctl btc get-address -n "m/33'/0'/0'/0/0"` should raise an error unless the `safety_checks` are enabled.

**Comment by matejcik** [comment]
can we maybe close this in favor of #1135 ?
PR: #1184
