### ISSUE TITLE
Initialize all local variables explicitly in extmod C code

### ISSUE THREAD

**Issue by invd** [trezor/trezor-firmware#1149]
During security research, I recently noticed that the C code in modtrezorcrypto does not explicitly initialize all local variables, which it should after #571. 

Example:
https://github.com/trezor/trezor-firmware/blob/741fca01567151fa9dad2e9d25db7236169fb697/core/embed/extmod/modtrezorcrypto/modtrezorcrypto-monero.h#L524-L526

Other extmod modules such as modtrezorui contain uninitialized variables as well.

I've discussed this with @andrewkozlik and we're not aware of a strong technical reason to keep them uninitialized _(if there is, please let us know.)_. We're both in favor of initialization wherever possible.

@onvej-sl: can you take a quick look at this and give some feedback whether this was covered by #571 or left out intentionally?

Categorization: I see this as a low-priority core / crypto task with no impact to the legacy code.

**Comment by onvej-sl** [comment]
Thank you for the report, @invd. This is not covered by #571 by mistake. It looks like I forgot about extmod modules (see https://github.com/trezor/trezor-firmware/issues/571#issuecomment-538419102).

I'll make a pull request.
