### ISSUE TITLE
Documentation update - trezorctl webauthn-list-credentials

### ISSUE THREAD

**Issue by guiand88** [trezor/trezor-firmware#1172]
Apologies if this is not the right place where to post this.   
The documentation at https://wiki.trezor.io/FIDO2_Credentials would need an update as it still refers to the deprecated command `trezorctl webauthn-list-credentials` .

> There was a major overhaul of the trezorctl commands, about which I am not too happy myself. Here is the new form of the FIDO-related commands:
> 
> `trezorctl fido credentials list`
> `trezorctl fido credentials add <HEX_CREDENTIAL_ID>`
> `trezorctl fido credentials remove -i <index>`

_Originally posted by @andrewkozlik in https://github.com/trezor/trezor-firmware/issues/698#issuecomment-603138026_

**Comment by prusnak** [comment]
Updated, thanks! (It will take some time until the change is propagated to the public wiki, but it's been changed already)
