### ISSUE TITLE
Confusing Version Group ID error message

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#1177]
Log from the wallet:

```
...Sending","TxAck",{"tx":{"version":1,"lock_time":0,"inputs_cnt":1,"outputs_cnt":2,"version_group_id":0}}]
...Received","Failure",{"code":"Failure_DataError","message":"Version group ID must be set when version >= 3."}]
```

The following check, while technically correct, spits confusing error message when `version<3` and `version_group_id==0` is provided:

https://github.com/trezor/trezor-firmware/blob/1e58c86a9af9b891abe13fad7866f5852786941f/legacy/firmware/signing.c#L1335-L1341

We can either make the wording less confusing

`Version and version_group_id mismatch` (is that even less confusing? :thinking: :laughing:)

or split this into two checks with the following error messages:

* `Version group ID must be set when version >= 3.`
* `Version group ID must be unset when version < 3.`

As this is an error caused by a programmer of the wallet, not wallet's users, I am fine with just changing the wording and not introducing two different checks. But I leave the final decision to you.

**Comment by prusnak** [comment]
There is a pending fix for trezor.js here: https://github.com/trezor/trezor.js/pull/113

**Comment by tsusanka** [comment]
## QA

Try ZCASH signing please on Wallet and Suite. Notice you exceptionally need to use master (59b8a5a) not what we have frozen.

**Comment by tsusanka** [comment]
Zcash tested as part of _Freeze_. See [testpad](https://satoshilabs.ontestpad.com/script/266#6/3/).
