### ISSUE TITLE
Don't show wrong address path warning when show_display is False in get_address

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1206]
In Legacy we do not show warning on Trezor if an address and path mismatch occurs and the check on display is not required.

For `trezorctl get-address -c Bcash -t address -n "m/44'/0'/0'/0/0" -d` you get the warning but for `trezorctl get-address -c Bcash -t address -n "m/44'/0'/0'/0/0"` you do not (notice the `-d` is missing).

I think the warning should still be present, shouldn't it? Because the host requires some unusual action.

**Comment by tsusanka** [comment]
We have concluded this does not pose any risks since nothing is displayed on Trezor. Let's investigate if this happens on Core as well and then considering closing this.

**Comment by tsusanka** [comment]
As agreed: this is correct behavior. In Core this gets a bit more complicated as due to the Keychain. We need to skip the check for cases when the `-d` is missing. That way the check dialog won't be displayed as well and it will be in sync with T1. The only difference is that in Core this will lead to an error (because of the Keychain) which is the correct behavior anyway.

So tl;dr: we need to skip the dialog when `-d` is missing and that's it.

**Comment by bosomt** [comment]
QA OK

Nixos
Suite be4e3a36f7dbe15b2b203f66de11edc50a6665b8
Device: fw-regular-2.3.5-889a3699
