### ISSUE TITLE
Initializing base classes

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#1207]
As someone who is coming from C++ I would like to see us calling `super().__init__()` every time we define an initializer in a derived class to ensure proper initialization of the parent's variables. See https://github.com/trezor/trezor-firmware/pull/1180 for a concrete example where this would make sense in my opinion. To me it seems counterintuitive not to initialize the parent by default, but maybe the pythonic way of thinking about this is different? Let's discuss IRL.

**Comment by tsusanka** [comment]
Let's see if flake or similar can check this. Related to #132.

**Comment by mmilata** [comment]
pylint [can check this](https://pylint.readthedocs.io/en/latest/technical_reference/features.html#classes-checker-messages):

> super-init-not-called (W0231):
>    \_\_init__ method from base class %r is not called
>    Used when an ancestor class method has an \_\_init__ method which is not called by a derived class.
