### ISSUE TITLE
Github U2F verification error

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-firmware#121]
T1 (fw 1.8.0, 1.8.1)
github login, github password reset

U2F on T1 with 1.8.0 and 1.8.1 versions of firmware returns a fail message on both password reset and login with a message "Security key authentication failed". Setting a higher U2F counter did not help.

TT 2.1.1 had the same error yesterday, worked today (tested 2.1.0 and was okay).

![image](https://user-images.githubusercontent.com/10185314/56961528-46c12a00-6b54-11e9-80ba-4c7ad4e858d5.png)

**Comment by onvej-sl** [comment]
Solved by setting the U2F counter to the current unix timestamp :
`trezorctl set-u2f-counter $(date +%s)`

Closing.
