### ISSUE TITLE
U2F: Proper error Message for trying to register where already done.

### ISSUE THREAD

**Issue by My1** [trezor/trezor-firmware#1213]
**Describe the bug**
If trying to login somewhere where the T1 was not registered, the Trezor rightfully says that another U2F device was used to register for that. however when trying to register where you have already done so, it asks to authenticate, which is weird to say the least.

**Firmware version and revision**
Version is 1.9.2, no idea where the revision is written.

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: dies not Apply
 - OS: Windows 8.1 
 - Browser: Brave
 - Version: 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)

**To Reproduce**
1. Go to some place with U2F/webauthn support
2. Register your T1
3. Try to register the same T1 onto the same account again.

**Expected behavior**
Rather say something like "This device was already used to register for this application" or something along these lines.

**Comment by andrewkozlik** [comment]
As explained [above](https://github.com/trezor/trezor-firmware/issues/1213#issuecomment-678346078), I believe there is absolutely nothing we can do in Trezor to make this behavior any better. If anybody finds otherwise, feel free to reopen this issue.
