### ISSUE TITLE
Redesign pagination for TT

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1215]
We want to limit the number of dots on the right side to three. If more than three items are included in the pagination a small arrow will appear. The following screens show a case where there are eight pages:

![Screenshot_2020-07-23 Zeplin - Projects](https://user-images.githubusercontent.com/1835345/88266208-17558a80-cccf-11ea-824c-fc435f1f7609.png) ![Screenshot_2020-07-23 Zeplin - Projects(1)](https://user-images.githubusercontent.com/1835345/88266232-29372d80-cccf-11ea-99e6-a331c9f55995.png)  ![image](https://user-images.githubusercontent.com/1835345/88266188-09a00500-cccf-11ea-8249-c5e2a4ac78a7.png)

## Notes

- The number of items may be changed later (e.g. to five) and the icons are not yet finalized. We need to take into account that these small nuances might change in the final review. Let's do it as designed on the screens for now though.
- The First screen, Fourth screen etc. are some kind of headers and are used in many other components. The code should reflect that.

**Comment by matejzak** [comment]
Design done, new issues to be create for the implementation part.
