### ISSUE TITLE
Add ILCoin Support

### ISSUE THREAD

**Issue by ILCoinDevTeam** [trezor/trezor-firmware#123]
![ilcoin](https://user-images.githubusercontent.com/48028026/56992939-cb19aa00-6b60-11e9-84c2-262247100644.png)

Hi we are the ILCoin Development Team.

We are a Bitcoin clone cryptocurrency, but also continue developing adding new features and we would like to be supported by Trezor. 

ILCoin cryptocurrency supports the new protocol C2P that solves the problem of the 51 % attack and is also certified by Palo Alto as Quantum resistance cryptocurrency.

Please check this articles about it.
https://www.newsbtc.com/2019/04/23/upgraded-pow-protocol-gives-hackers-a-run-for-their-money/
https://cointelegraph.com/news/crypto-project-takes-on-nonethical-hackers-with-tech-to-stop-51-attacks

Block Explorer: https://ilcoinexplorer.com/
Web Page: https://ilcoincrypto.com
Web Wallet: https://ilcoinwebwallet.com/
Windows Qt-wallet: https://ilcoincrypto.com/download/ILCoin-Qt.exe
OSX Qt-wallet: https://ilcoincrypto.com/download/ILCoin-Qt.dmg
Android Wallet: https://play.google.com/store/apps/details?id=ilcbtc.wallet

You also may notice that in the very near future we have plans to add the smart contracts functionalities.

We are in several top exchange sites with huge daily volumes:
https://www.digifinex.com/en-ww/trade/BTC/ILC
https://www.cointiger.com/en-us/#/trade_pro?coin=ilc_btc
https://www.bw.com/trade/ilc_btc
https://www.bit-z.com/exchange/ilc_btc
https://www.bitker.com/#/bbTrades/ilc_btc
https://www.idax.pro/#/exchange?pairname=ILC_BTC
https://www.fubt.co/#/TradeCenter/ilcbtc
https://app.stex.com/en/trade/pair/BTC/ILC
https://www.coinexchange.io/market/ILC/BTC
https://tradesatoshi.com/Exchange/?market=ILC_BTC
https://crex24.com/es/exchange/ILC-BTC
https://graviex.net/markets/ilcbtc
https://freiexchange.com/market/ILC/BTC

And very soon in: Dobi Exchange, Coinlim and Coineal. And continue growing.

We have been in the Top 100 CMC several times and working to be in the Top 30 and soon the Top 10.

Here in Top 100
![2019-04-30 16 36 10](https://user-images.githubusercontent.com/48028026/56995028-3c0f9080-6b66-11e9-96b3-f55dffb3c90d.jpg)

Here in Top 100 again
![2019-04-30 16 35 56](https://user-images.githubusercontent.com/48028026/56995039-3f0a8100-6b66-11e9-85c3-2d19b77acc4d.jpg)

We have already prepared the ilcoin.json and ilcoin.png as well as the Git branch to do the Pull Request. But currently I am not able to upload it. 

Hoping you take the right decision to support us and grow together, receive our best regards and our thanks in advance.

Sincerely 
ILCoin Dev Team

**Comment by prusnak** [comment]
Send a Pull Request when your coin is in the TOP 30
