### ISSUE TITLE
Add support for TRON(TRX)

### ISSUE THREAD

**Issue by Starsakary** [trezor/trezor-firmware#1247]
Hi. We are from TRON. TRON is a robust blockchain ecosystem with multiple kinds of products involved in TRON ecosystem, including public chain, wallet client, decentralized applications(DAPPs), Etc. We are now ranked 12th on CoinMarketCap. We very much hope that TRX and Trezor-firmware can reach cooperation.

1. This is our [official website](https://tron.network/).

2. The signature algorithm of Tron is ECDSA, and the selected curve is SECP256K1. The private key is a random number, and the public key is a point on the elliptic curve. The generation process is: first generate a random number d as the private key, and then calculate P = d * G as the public key; where G is the base point of the elliptic curve.

3. Sure we have a great front end wallet [Tronlink](https://www.tronlink.org/) and will support Trezor soon.

4. We have a [TRON Developer Hub](https://developers.tron.network/) that includes almost all documents needed for development. This is the [link](https://developers.tron.network/docs/account) of the account address and signature.

5. We have a blockchain explorer [Tronscan](https://tronscan.org/#/).

**Comment by prusnak** [comment]
There is already a work in progress for Tron here: https://github.com/trezor/trezor-firmware/pull/259

Feel free to help with finishing this PR
