### ISSUE TITLE
Firmware 2.3.1 cannot sign arbitrary paths

### ISSUE THREAD

**Issue by cantilope** [trezor/trezor-firmware#1255]
In versions 2.3.0 and prior with Electrum, it was possible to sign arbitrary paths. For example a segwit Bitcoin wallet with m/84'/9999'/0'/0/0. Since firmware 2.3.1, the trezor device returns "Forbidden key path". As a result the Trezor can no longer be used with wallets that use arbitrary paths. I am using Electrum 4.0.3 and can confirm I am able to sign a transaction with firmware 2.3.0 but not 2.3.1.

**Comment by prusnak** [comment]
1) always use the latest firmware (which is 2.3.3 at the moment, not 2.3.1)
2) you can turn off this safety checks via `trezorctl set safety-checks prompt` (make sure you have the latest python-trezor 0.12.2)
