### ISSUE TITLE
Add firmware update scenario to CI

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#126]
To catch issues like https://github.com/trezor/trezor-firmware/issues/122 which do not appear unless the storage has the format of a previous firmware release.

Once https://github.com/trezor/trezor-firmware/issues/125 is implemented we can cache emulator binaries of older firmware builds and perform tests across two versions.

**Comment by prusnak** [comment]
Most of this is already done.

**Comment by tsusanka** [comment]
Patching the library seems not enough to run the binaries on [CI](https://gitlab.corp.sldev.cz/trezor/trezor-firmware/-/jobs/25711). CI runs on Debian Stretch and there is some glibc mismatch:

`/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found`

I believe the best way to solve this is to rebuild the binaries using docker (with the same image as is on CI or do it directly there).

cc @1000101

**Comment by tsusanka** [comment]
Discussed with admins that:

- firmware-dev website will be locked for internal use
- We'll copy the current emulator binaries from trezor-public/artificats to this page
- I'll finish the CI job, which tests the upgrades. It will not use the trezor-public/artificats repository as a submodule, rather it wil download these binaries from this page.
- Also, I'll add a job, which in case a commit is tagged will build the emulator and  upload to this website for further use.

**Comment by 1000101** [comment]
> Discussed with admins that:
> 
>     * firmware-dev website will be locked for internal use
> 
TBD
>     * We'll copy the current emulator binaries from trezor-public/artificats to that page
> 
Done.

**Comment by tsusanka** [comment]
I've rebuild the core builds again, because of https://github.com/trezor/trezor-firmware/commit/779ff86214eb6856ee0cb1e6aca697b006ab9e11 . Otherwise, this is almost done apart from:
- [ ] solve matejcik's point on version check (https://github.com/trezor/trezor-firmware/pull/214#discussion_r289803698)
- [ ] solve how to pass authentication details or how to download from the server directly (TBD with admins)
- [ ] put on CI
- [ ] profit

**Comment by tsusanka** [comment]
Unless, there are some specific reasons this assigned to @matejcik, I believe I should finish this one.

**Comment by matejcik** [comment]
i don't know of anything, please go ahead :)
