### ISSUE TITLE
Add Binance as available wallet for Binance coin

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-firmware#1269]
**Is your feature request related to a problem? Please describe.**
https://trezor.io/coins/#BNB says no wallet available, however Trezor T can be used with Binance app https://docs.binance.org/tutorial/trezor-model-t-user-guide.html

**Describe the solution you'd like**
Ass Binace as a supported platform on the list

**Comment by prusnak** [comment]
Fixed in fc5847854bae78a2b79ad588957c9e736dba621d

t.io/coins will be updated soon
