### ISSUE TITLE
Update micropython to 1.13

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1273]
As @prusnak wrote the interesting changes are:

- PEP 526 has been implemented which adds new syntax for variable annotations, such as `x:int = 1`
- PEP 572 has also been implemented, which adds the := operator for assignment expressions, such as `if x := 1:`

See https://github.com/micropython/micropython/releases/tag/v1.13

**Comment by prusnak** [comment]
MicroPython v1.13 + modutimeq.discard patch prepared here https://github.com/trezor/micropython/tree/trezor-v1.13

**Comment by prusnak** [comment]
After some fiddling I prepared the update branch here: https://github.com/trezor/trezor-firmware/tree/upy-v1.13

**Comment by prusnak** [comment]
Fixed by https://github.com/trezor/trezor-firmware/pull/1280
