### ISSUE TITLE
Security feature - PIN SCRAMBLE

### ISSUE THREAD

**Issue by rigking** [trezor/trezor-firmware#1282]
Is there a plan to implement scrambling the code pad . . . pin pad . . . ??  

the displayed numbers used to unlock the Trezor One

If the ?key pad? . . . the numbers; changed each time you entered on of them

Maybe this could just be an option

this would add an extra level of security for those of us with a pin that has the same number more than once

**Comment by prusnak** [comment]
We considered this, tested that with users and they found this very very confusing. That's why we don't scramble the PIN in-between. If you are worried about security please use a PIN that does not repeat the same number more than once.
