### ISSUE TITLE
Not able to send timelocked transactions 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#1287]
**Describe the bug**

Not able to send timelocked transactions for years. 
See issue that I sent year and half ago https://github.com/satoshilabs/mytrezor/issues/736
All firmwares including T1 and TT.
Same problem in suite and wallet and in send raw transaction tool.

**Firmware version and revision**
1.9.2 commit 0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea,

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: current wallet /commit 0ce221e99a33c1a8c728f7dbea79d85ae7851ac3/ and suite 
 - OS: Nixos
 - Browser Chromium 85
 - Version 85

**To Reproduce**
1. load wallet or suite
2. use locktime function
3. try to send transaction
4. See error [account] Failed to send transaction",{"message":"-26: non-final"},

**Expected behavior**
You are able to send locktimed transaction

**Screenshots**

![image](https://user-images.githubusercontent.com/31506317/94534730-08480700-0241-11eb-8f22-cc885b82f052.png)

![image](https://user-images.githubusercontent.com/31506317/94535974-7a6d1b80-0242-11eb-8fcc-17dcb5704f7b.png)

![image](https://user-images.githubusercontent.com/31506317/94536873-26af0200-0243-11eb-846b-76d66e9d0b2f.png)

**Comment by matejcik** [comment]
this does not look like a firmware problem, and ISTM it is expected behavior, despite the error message being confusing

transacitions where `lock_time` > `current block height` are going to be refused by the network. that is the whole point of `lock_time`

try using locktime lower than current block height

**Comment by bosomt** [comment]
worked fined when i used locktime that already happened `  "locktime": 650489,` 
https://btc3.trezor.io/tx/1edcddd0991df80843313e06b9a5a5218ce7897ec0d63e348894d980b4065a69

**Comment by tsusanka** [comment]
Let's improve the error message then. Do we know where from this error comes? Maybe blockbook?

**Comment by matejcik** [comment]
pretty sure it's straight out of bitcoin core

i'm not sure where it should be handled, but my intuition is that it should be in Wallet/Suite

**Comment by tsusanka** [comment]
I've opened issue in Suite https://github.com/trezor/trezor-suite/issues/2463.

**Comment by MichielBruijn** [comment]
> this does not look like a firmware problem, and ISTM it is expected behavior, despite the error message being confusing
> 
> transacitions where `lock_time` > `current block height` are going to be refused by the network. that is the whole point of `lock_time`
> 
> try using locktime lower than current block height

What's the point of locktime lower than current block height?
I want to understand

**Comment by matejcik** [comment]
> What's the point of locktime lower than current block height?

none except for testing that transactions with locktime are signed correctly.

**Comment by MichielBruijn** [comment]
> > What's the point of locktime lower than current block height?
> 
> none except for testing that transactions with locktime are signed correctly.

So why is locktime higher than current block height not working and gives errors?

**Comment by matejcik** [comment]
i suggest you read up on what "lock time" means and does, and it will hopefully clear up your confusion

**Comment by MichielBruijn** [comment]
[This page](https://wiki.trezor.io/Locktime) says:

_Locktime is an optional part of Bitcoin. It sets the earliest time a transaction can be mined into a block. It is possible to use locktime with Trezor to make sure that a transaction is locked until a specific block height or a point in time._

So, locktime > current block height is how it's suposed to work but it's not possible to broadcast the transaction until current block height > locktime.
So, the broadcast button in trezor suite is confusing when using locktime > current block height.

I was under the impression that locktime was a feature to "lock" the coins on the chain until a specific point in (block) time where they come available again.

**Comment by prusnak** [comment]
You can't broadcast a transaction when timelock has not been reached.

**Comment by sime** [comment]
@MichielBruijn You might be thinking of OP_CHECKLOCKTIMEVERIFY and OP_CHECKSEQUENCEVERIFY. Trezor doesn't support these, and they behave differently than LockTime.

**Comment by MichielBruijn** [comment]
Ah, that explains. I was indeed thinking about OP_CHECKLOCKTIMEVERIFY aka OP_HODL
Thanks for clearing up.
Do you know if those features are going to be implemented into Trezor in the futre?
