### ISSUE TITLE
Trezor Model T not working with Samsung galaxy z fold 2 at all

### ISSUE THREAD

**Issue by baro0k** [trezor/trezor-firmware#1289]
Hello, I bought your Trezor model T long time ago and it works great on a PC however I use my android Samsung galaxy z fold 2 phone on the go. what I found before purchasing the phone beta wallet worked fine with android phones and what I find it's not working with my device. The Trezor manager finds my device but not able to send or receive the address. How do I get support on this? Thank you for your time.

**Comment by matejcik** [comment]
This is a firmware development forum. Please contact customer support at https://trezor.io/support

FWIW you are supposed to use https://wallet.trezor.io/ in your phone's browser, not the Trezor Manager app
