### ISSUE TITLE
Show fee rate on Trezor

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#1294]
It might be convenient for users to show them the fee rate on the singing confirmation screen. On the TT we have one spare line at the bottom, where we can put this information:

![image](https://user-images.githubusercontent.com/42678794/94820735-16dd1c80-0401-11eb-900c-7162b9c0108f.png)

Not sure how to do this on the T1 though:

![image](https://user-images.githubusercontent.com/42678794/94823360-0da17f00-0404-11eb-916e-4a99b244d770.png)

We could get rid of the "from your wallet?", so we would have

```
Confirm sending:
0.01610436 TEST
including fee:
0.00005436 TEST
(83 sat/B)
```

The implementation would be pretty easy, but I would like to double-check the way we calculate the transaction weight in Trezor and in Wallet/Suite to ensure that the computation is the same, so that we avoid showing a different fee rate on Trezor in some odd cases. The differences in computation would probably be minimal, boiling down to the things which are unknown before the transaction is signed, i.e. the signature length - do we take the average length or the upper bound?

**Comment by sime** [comment]
@STew790 Since you tested the Suite side of things, could you also test firmware as well?

**Comment by STew790** [comment]
**QA OK**

T1:
![image](https://user-images.githubusercontent.com/48477147/175539874-b0816f76-e541-406a-bb68-5f0ae455c65e.png)
TT:
![image](https://user-images.githubusercontent.com/48477147/175539934-52707ff7-a943-462c-922d-8207af1a11c7.png)


**Info:**
 - Suite version: web 22.7.0 (a92092adee0fc61f4bc2c8a404f40e47323c1450)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.11.2 regular (revision 468bcfd61a870dc11ca6c5e8555947bf05de4a57)
 - Device: model T 2.5.2 regular (revision 468bcfd61a870dc11ca6c5e8555947bf05de4a57)
 - Transport: bridge 2.0.31
