### ISSUE TITLE
Make use of pylint

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#132]
This should be easy even without using static analyzer such as MyPy.

**Comment by prusnak** [comment]
`NameError: local variable referenced before assignment`

We could avoid bugs like https://github.com/trezor/trezor-firmware/issues/122

**Comment by prusnak** [comment]
Just figured out this is not easy at all as the problem is much more complicated. Let's try to finish typing ASAP.

**Comment by matejcik** [comment]
let's keep this open for the purpose of enabling at least some pylint warnings

**Comment by prusnak** [comment]
OK. Just a note: error in #122 would not be caught by PyLint, it could've been discovered only via typing.

**Comment by tsusanka** [comment]
The current upgrade bug from 2.0.10 to 2.1.4/master where we access a const() variable with an underscore in its name (see [here](https://github.com/trezor/trezor-firmware/blob/core/v2.1.4/core/src/apps/common/storage/__init__.py#L30
)), might have been caught with pylint.

**Comment by tsusanka** [comment]
It would be nice to do this iteratively. That means put pytlint into CI with a few checks and add them gradually.

**Comment by hynek-jina** [comment]
@matejcik

**Comment by matejcik** [comment]
pylint was enabled in #1848
