### ISSUE TITLE
some settings stay on after wipe until device is rebooted

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#1322]
e.g., device rotation and auto-lock delay will stay with the same configuration, because the value is erased from storage but remains in effect in separate objects.

Ideal solution would be to reboot the device after wipe, but that is impractical from a technical standpoint.

As an interim solution, we could introduce something like `apply_settings_from_storage()` which would be called both at end of `ApplySettings` handler and `WipeDevice` handler

**Comment by matejcik** [comment]
experimental flags are probably also affected

**Comment by bosomt** [comment]
**QA OK**

i was not able to replicate it anymore, rotation and autolock is forgotten even when device is not reconnected
 
Nixos 
Suite be4e3a36f7dbe15b2b203f66de11edc50a6665b8
Device: fw-regular-2.3.5-889a3699
