### ISSUE TITLE
Trezor Model T shows whitescreen

### ISSUE THREAD

**Issue by finndev** [trezor/trezor-firmware#1329]
After one year of usage my Trezor Model T screen is completely white. I am unable to enter my pin. I am unable to use trezorctl to enter my pin and access my funds. The device is just completely useless and broken after such a short time despite being stored properly.

There is no connection detected on dmesg either when connecting the device.

I now have to buy a new device and use my recovery seed.

Is this the quality standard of a Trezor?

I suggest everyone to regularly check if your recovery seed is at the correct place and still present to prevent any loss of coins, because this hardware wallet is the opposite of safe.

![Screenshot 2020-10-27 at 21 53 34](https://user-images.githubusercontent.com/4342644/97360746-e1600d80-189e-11eb-96b0-13274e053f0b.png)

**Comment by prusnak** [comment]
Please contact our support https://trezor.io/support/ - they will handle this case for you
