### ISSUE TITLE
Firmware update cancel  T vs. One inconcistencies 

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-firmware#1334]
How to reproduce:

1. Init firmware update
1. Cancel on device
1. Observe inconcistencies between models

Model T	

```
{
  "type": "Failure",
  "message": {
    "code": "Failure_ActionCancelled",
    "message": "Firmware install cancelled"
  }
}
```

Model One
```
{
  "type": "Failure",
  "message": {
    "code": "Failure_FirmwareError",
    "message": null
  }
}
```

These are objects parsed by trezor-link. Inconcistencies:
- Same action on device, two different codes: `Failure_ActionCancelled`, `Failure_FirmwareError`
- Model One does not send message

**Comment by tsusanka** [comment]
This goes from the bootloader right? :-/

**Comment by mroz22** [comment]
> This goes from the bootloader right? :-/

Yes. We can live with it, but it is suboptimal (see the linked trezor-connect PR)

**Comment by prusnak** [comment]
PR in https://github.com/trezor/trezor-firmware/pull/1347
