### ISSUE TITLE
Looser checks for replay-protected Ethereum networks

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#1335]
With the introduction of strict keychain namespacing, Trezor T stopped working with several not officially supported Ethereum-based networks: see #1326, #1332, #1331 

We believe it is safe to explicitly re-enable support for such networks in the future. There is strong replay protection in the form of EIP-155 chain ID, we use currency symbol `UNKN`, and we can display a warning about "Unknown chain ID" or "Unknown network", whichever seems more user-friendly.

The only open issue is what SLIP44 identifier to use for such networks. We do not want to allow just any, and we can't use chain id in place of SLIP44 because there are mismatches in practice.

One possibility is always using `60`, which is Ethereum id, and the networks often use it in practice. (fwiw, #1184 allows this explicitly, because some networks want cross-signing and token compatibility)
Another is always showing path warning regardless of provided path.

**Comment by My1** [comment]
> Another is always showing path warning regardless of provided path.

this may get chaotic fast when people have strict path checks on **which is the default**, like is it supposed to block there and encourage users to get prompts or disable path checks altogether lowering the security?

or should it create a prompt instead thereby creating surprising behavior, which doesnt help users which are confused about enough things already.

in fact a path warning regardless of the setting would be confusing as they would think they are on the "right" path.

https://en.wikipedia.org/wiki/Principle_of_least_astonishment

it should probably rather just have its own warning.

**Comment by bosomt** [comment]
@matejcik is there anything that can/need to be tested by QA dept. ?

**Comment by matejcik** [comment]
@bosomt it would be nice to have this tested, presumably through MEW, but we'd need to find an unsupported Ethereum-like network. And we also added support for all the major ones, so :woman_shrugging: 

i don't even have a good idea where to go looking.

**Comment by matejcik** [comment]
Maybe a good idea is to test EWC with derivation path `44'/60'/0'` and `44'/246'/0'`, both should work without warnings.
This is already integrated in MyCrypto, but I'm not sure how to go about changing the derivation path, as I never used the application

**Comment by bosomt** [comment]
@matejcik 

I was able to derive 44'/246'/0' addresses without any problem/warning via mycrypto.
BUT it worked with 2.3.4 public version too 

**2.3.5**
![image](https://user-images.githubusercontent.com/31506317/103534531-52b7d000-4e8f-11eb-8573-6a579cb8f199.png)

**2.3.4 - both paths**

![image](https://user-images.githubusercontent.com/31506317/103534718-b6da9400-4e8f-11eb-93d0-aaff6b783f4e.png)

![image](https://user-images.githubusercontent.com/31506317/103534803-e2f61500-4e8f-11eb-978a-1f6489dfd7fa.png)

mycrypto beta

![image](https://user-images.githubusercontent.com/31506317/103535159-90692880-4e90-11eb-98c0-828a68642e64.png)

**Comment by matejcik** [comment]
> I was able to derive 44'/246'/0' addresses without any problem/warning via mycrypto.
> BUT it worked with 2.3.4 public version too

you would need to send a transaction, the `EthereumGetAddress` call does not differentiate between networks

also this should work for both `44'/246'/0'` and `44'/60'/0'`
