### ISSUE TITLE
Add BSC and BEP20 TWT

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#1338]
More info:
* https://github.com/ethereum-lists/tokens/pull/435
* https://github.com/ethereum-lists/chains/blob/master/_data/chains/56.json

**Comment by matejcik** [comment]
should we use the chains repo to autogenerate our Ethereum networks?

**Comment by prusnak** [comment]
> should we use the chains repo to autogenerate our Ethereum networks?

I think that's a good idea

**Comment by matejcik** [comment]
what is the SLIP44 ID for binance?
are they using the same 714 for this and their native chain? i don't think that's a particularly good idea

**Comment by matejcik** [comment]
they also seem to use the same BNB symbol. not that great either, seeing as there's currently no way for the user to distinguish between the network they're transacting on

**Comment by matejcik** [comment]
BNB smartchain is added in #1345 

we are waiting for https://github.com/ethereum-lists/tokens/pull/435, this is waiting for Trustwallet's modifications

**Comment by Hannsek** [comment]
We already have the data from coingecko, so the token is now supported.
