### ISSUE TITLE
Inconsistent account types compared with Suite

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#1341]
**Describe the bug**
Suite types of account doesn't match types on device display

Address | Firmware | Suite
------------ | ------------ | -------------
bc1 | Segwit account | "Normal" account
3 | "Normal" account | Segwit account

**Firmware version and revision**
1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Suite commit 513631a9fa62c438e60397a9942b04275bcd621a
 - OS: Nixos
 - Browser Firefox 
 - Version 82.0 (64-bit)

**To Reproduce**
1. Load device 
2. Show full address on device Normal and Segwit
3. Compare account type on device and on computer 

**Expected behavior**
Device types in firmware match types in Suite

**Screenshots**
![image](https://user-images.githubusercontent.com/31506317/98385440-465df500-204f-11eb-8125-9024c3802d70.png)
![image](https://user-images.githubusercontent.com/31506317/98386085-106d4080-2050-11eb-9f3f-dcfed8a1b135.png)

**Comment by tsusanka** [comment]
Ping @matejzak.
