### ISSUE TITLE
Mask input using asterisks while entering passphrase

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1348]
From feedback on social media. They were also some claiming that we already did this but I have tried 2.1.0, 2.2.0 and 2.3.0 and it wasn't there.

**Comment by tsusanka** [comment]
I do not have a strong preference. Feel free to decide as you wish. We can also consider moving this to Notion as it does not have a clear decission or next step.

**Comment by sime** [comment]
Closing for now.

**Comment by prusnak** [comment]
> Passphrases are unforgiving when entered wrongly. I'd side with providing as much user feedback as possible when entering something mission critical as a passphrase.

Agreed. Let's not mask the passphrases since it's making he whole process more error prone.
