### ISSUE TITLE
Increase the minimum autolock delay to 1 minute

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1351]
Increase the minimum autolock delay from 10 seconds to 1 minute. See [this comment](https://github.com/trezor/trezor-firmware/issues/1154#issuecomment-729544338) for rationale.

**Comment by bosomt** [comment]
**QA OK**

`trezorctl set auto-lock-delay 10 
Error: ProcessError: Auto-lock delay too short`

Nixos
trezorctl 0.13.0
Device: fw-regular-2.3.5-889a3699 + trezor-fw-regular-1.9.4-889a3699
