### ISSUE TITLE
EthereumAddress message changed

### ISSUE THREAD

**Issue by ligi** [trezor/trezor-firmware#136]
it seems the protobuf message for EthereumAddress has changed:

new:

https://github.com/trezor/trezor-firmware/blob/master/common/protob/messages-ethereum.proto#L46

old:

https://github.com/trezor/trezor-common/blob/dd8ec3231fb5f7992360aff9bdfe30bb58130f4b/protob/messages.proto#L337

this is quite bad as this makes it really ugly to support TREZOR devices with old and new firmware. I kind of tend to now drop support for the old firmware. But it would be great to avoid such things in the future. Ideally by not changing an existing message - but when needing to change introduce a new message.

**Comment by matejcik** [comment]
the protobuf message itself is actually backwards-compatible; you see the bytes field has id 1 and the string field has id 2.
We should have left the old field in the definition, then you would be able to test and use whichever is set. You can still do that, but you have to hack the proto definition :/

perhaps it's worth returning the field?

**Comment by ligi** [comment]
> perhaps it's worth returning the field?

that would actually be great!

btw. what is the best way to find the protobuf definitions for firmware 2.1.0? As far as I see for that version it still links to trezor-common - but there are no tags in there.

**Comment by matejcik** [comment]
the only way is to checkout tag `core/2.1.0` and get the submodule commit from there

**Comment by ligi** [comment]
ah - it's a submodule - that makes sense

**Comment by ligi** [comment]
and PS: by all the criticism I had over the recent changes - really like how you split the proto files so I can only pick the ethereum relevant ones ..
