### ISSUE TITLE
trezorctl list hangs when T1 in bootloader mode is connected

### ISSUE THREAD

**Issue by mmilata** [trezor/trezor-firmware#1379]
**Describe the bug**
Command `trezorctl list` hangs indefinitely when T1 in bootloader mode is connected.

**Firmware version and revision**
* Stable FW 1.9.3.
* Bootloader 1.8.0.
* `trezorctl` from master @ dab353f888a3d46ddd45714b87428e750fe69391

**Desktop/smartphone setup (please complete the following information):**
 - OS: NixOS 20.09

**To Reproduce**
1. disable `trezord`
2. connect T1 in bootloader mode
3. run `trezorctl list` from repo
4. see following output, trezorctl ends up waiting on USB file descriptor and must be killed:
```
$ trezorctl list
webusb:002:2 - Trezor 1 bootloader
```

**Expected behavior**
No hang.

**Additional context**
Trezorctl version 0.12.2 seems to behave correctly.

I'm guessing that bootloader doesn't like the `EndSession` message. Reverting 4f92d2b14db6d87ec1470a7b1677cc3ec971598a restores trezorctl termination.

**Comment by prusnak** [comment]
> I'm guessing that bootloader doesn't like the `EndSession` message

Yes. Unknown messages in T1 bootloaders (1.8.0 and older) are ignored.

TT bootloader and T1 bootloader (1.8.1 unreleased and newer) respond with Unexpected message error.
