### ISSUE TITLE
Calculate the seed checksum for the user

### ISSUE THREAD

**Issue by dpc** [trezor/trezor-firmware#1381]
**Is your feature request related to a problem? Please describe.**
I was looking at the https://twitter.com/kallerosenbaum/status/1335185904667942920 where the author expressed frustration with the checksum being an obstacle to generating seeds entirely offline using dice.

**Describe the solution you'd like**
After a bit of thinking it seems to me that the best approach would be for the wallet to just tell the user what the last word should actually be (if it was incorrect). This would allow people to just generate all words randomly without even being aware of checksum, and then fix the last word when they are trying the seed for the first time.

This even works if the user already did multiple copies of the seed etc. Any time they enter the seed, the checksum suggested is going to be deterministic.

Possibly the wallet should require the user start from scratch with the fixed word, just to make sure the wrong checksum wasn't just a typo.

Please forgive me if that's how the Trezor actually works already. I assume it's not.

**Describe alternatives you've considered**

All alternatives seem to require invasive changes which are undesirable. This one is a simple UX improvement.

**Comment by prusnak** [comment]
This is really out of scope, but we might consider diceware initialization in the future - https://github.com/trezor/trezor-firmware/issues/1293
