### ISSUE TITLE
wrong path to file options.h

### ISSUE THREAD

**Issue by skyeatshorizon** [trezor/trezor-firmware#1383]
on executing make 'ed25519.h' is referencing a file with a wrong path

**To Reproduce**
1. Go to 'crypto'
2. rum 'make'

fix:
in: 'crypto/ed25519-donna/ed25519.h' change #include "options.h" to #include "../options.h"

**Comment by prusnak** [comment]
Using relative paths in include is a no-no.

Besides, `cd crypto ; make` works for me.
