### ISSUE TITLE
toif documentation outdated

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-firmware#1385]
There is a link to toif_convert tool on:

https://docs.trezor.io/trezor-firmware/misc/toif.html

![image](https://user-images.githubusercontent.com/30367552/102098345-5ffd1400-3e27-11eb-8571-9f9eee4a5f07.png)

Link takes you to https://docs.trezor.io/trezor-firmware/tools/toif_convert.py which does not exist at the moment. 

Not sure if this is a bug or a feature request :thinking: 

Maybe the tool does not exists anymore?

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-firmware/commit/d9a8194e14b31f64fb3a443f4f97acf0b24ef427

(use absolute link instead of relative)

**Comment by mroz22** [comment]
ah it lives here https://github.com/trezor/trezor-firmware/blob/master/core/tools/toif_convert.py

**Comment by mroz22** [comment]
thanks!! that was fast
