### ISSUE TITLE
No device label character limit in trezorctl 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#1399]
**Describe the bug**
There is no character limit in trezorctl  and device recovery  in Electrum and you can set or try to set device label as long as you want.
omdel One end with `Error: DataError: string overflow` and model T long label is applied.
Some apps like Suite are not expecting it and it's breaking it's grafics

**Firmware version and revision**
Model T 2.3.5 commit 889a369
Model One 1.9.4 commit 889a369

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: trezorctl 0.12.2
 - OS: Nixos
 
**To Reproduce**
1. Set model T device label via trezorctl
2. Check device screen or go to https://suite.trezor.io/web/ and observe

**Expected behavior**
There is same character limit as in Suite and wallet.

**Screenshots**
![IMG_20201227_122254](https://user-images.githubusercontent.com/31506317/103170980-c3843a00-4848-11eb-8daf-c06538facefe.jpg)
![image (2)](https://user-images.githubusercontent.com/31506317/103171127-f2e77680-4849-11eb-961e-b0f3a9d46221.png)

![image](https://user-images.githubusercontent.com/31506317/103171914-0c8bbc80-4850-11eb-9f63-ceca381f8abb.png)

**Note(s):**

**Model One**
trezorctl set label 12345678912345678912345678933333333333333333333333333333355555555555555555555555555555555555555555DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
WebUSB transport is disabled: libusb-1.0.so: cannot open shared object file: No such file or directory
Error: DataError: string overflow
(trezor-firmware)

**Model T** 
[tbosansk@tbosansk:/home/tbosansk/Downloads/trezor-firmware]$ trezorctl set label 12345678912345678912345678933333333333333333333333333333355555555555555555555555555555555555555555DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
WebUSB transport is disabled: libusb-1.0.so: cannot open shared object file: No such file or directory
Please confirm action on your Trezor device.
Settings applied
(trezor-firmware)

**Comment by prusnak** [comment]
For reference: label in the legacy firmware is limited to 32 characters (33 bytes of zero-terminated string)

**Comment by matejcik** [comment]
@bosomt please re-test on master?

**Comment by matejcik** [comment]
reopening for `Error: DataError: string overflow` on T1
not sure if that is worth fixing, will discuss

**Comment by bosomt** [comment]
**QA OK**

**info**
Nixos
FW 2.3.5   model T  revision: 9 bytes b'ffa96205f',
trezorctl version 0.13.0
