### ISSUE TITLE
Investigate dropping required fields

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#14]
and replacing them with optional.

We need to asses the impact on Trezor code and other parts (wallet, connect, etc.)

**Comment by prusnak** [comment]
this is a pre-requisite for https://github.com/trezor/trezor-firmware/issues/16

**Comment by matejcik** [comment]
If i understand protobuf correctly, we are not using the required/optional dichotomy for anything anyway. Changing `required` to `optional` in the defs is for free. The only thing that `required` does is failing to parse a message that does not contain that field.

That means: if our code sends the required field, it will be in the message, so non-updated parsers will work fine.
If our code does NOT send the field, non-updated parsers are failing right now anyway.

**Comment by prusnak** [comment]
Yes, all code needs to correctly handle the default values in case the field is not present.

**Comment by ZdenekSL** [comment]
Closed because of #379
