### ISSUE TITLE
chain-ID error EWC will instead be integrated in #1345

### ISSUE THREAD

**Issue by bartcoelus** [trezor/trezor-firmware#1405]
Still having this invalid cain-ID error for whatever network (VOLTA or EWC) I'm trying to transact with and for whatever derivation path... 

I see the fixes should be integrated, but they don't work :( is this new firmware pushed already to the production? Tested on 2.3.4 

------------
EWC will instead be integrated in #1345

_Originally posted by @matejcik in https://github.com/trezor/trezor-firmware/issues/1326#issuecomment-726127051_

**Comment by prusnak** [comment]
No, the change will be released in half of february in firmware 2.3.5
