### ISSUE TITLE
Marcineczek

### ISSUE THREAD

**Issue by MGmarcineczek** [trezor/trezor-firmware#1407]
**Describe the bug**

**Firmware version and revision**
Describe firmware version and revision you are using when encountering the bug.

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: [e.g. Trezor Wallet, Trezor Beta Wallet, Trezor Suite, Electrum]
 - OS: [e.g. Windows, macOS, Linux, Android]
 - Browser [e.g. chrome, firefox, safari]
 - Version [e.g. 42]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by MGmarcineczek** [comment]
Where are can interesting use my ekont

**Comment by MGmarcineczek** [comment]
J hawe problem for all my works j don can send my money for wallet and can
not use my money.
Give me answer why are can not use.

śr., 6 sty 2021, 21:51 użytkownik Pavol Rusnak <notifications@github.com>
napisał:

**Comment by prusnak** [comment]
Github is not a support channel.

Please contact our support via https://trezor.io/support/technical/issue/

**Comment by MGmarcineczek** [comment]
Nice weekend we can lettel rest and give Ace rest too mirrow. As job is not easy but said when do t be hawe help from frends c a n not be live be that hight be. All still going will be  next pokolenie mbeda   już all atomatuc and
