### ISSUE TITLE
Tezos delegation requirements not given result in msg: Error while applying operation

### ISSUE THREAD

**Issue by ckorder** [trezor/trezor-firmware#1413]
**Describe the bug**
Tezos delegation requirements not given result in

>   Warning

    kind: temporary
    id: failure
    msg: Error while applying operation XCXCF71QaVbqqYDeAAivagQTgmx9vptfmY1oAvQHhVpLFMXCXC: branch refused (Error: Counter XCX0384 already used for contract tz1ZBh54JHA1pLDSCACGGAGre4pP2kK7cdZA (expected XCX0386) ) 

No more further actions can be done within the tezos wallet, no funds can be moved or delegated. Everytime it uses the old counter for the failed action of delegation towards a pool where you are not fitting the requirements.

**Firmware version and revision**
Trezor Model T (latest stable firmware)

**Desktop/smartphone setup**
 - Wallet software: https://wallet.simplestaking.com
 - OS: Linux
 - Browser Firefox
 - Version latest

**To Reproduce**
1. Go to https://wallet.simplestaking.com/tezos/wallet/detail/walletid
2. Click on Delegation 
3. Select a Pool on https://mytezosbaker.com/ with a minimum of required tezos which is more than you have in the wallet.
4. Delegate towards the pool id.

**Additional context**
I don't know how long this error will exist and if its persistent. All i know for sure is that my funds are already locked for a few hours without me being able to send or delegate my tezos using the Trezor Model T.

**Comment by matejcik** [comment]
It's unclear that the problem is on Trezor side. Please report the issue to Simplestaking software authors and let them report the problem back to us if they can determine the cause more precisely.
