### ISSUE TITLE
build-docker.sh fails on --platform docker setting

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1425]
./build-docker.sh is failing to me on `"--platform" is only supported on a Docker daemon with experimental features enabled`. @prusnak you have introduced the `--platform` in https://github.com/trezor/trezor-firmware/commit/453df567d3614c6df50a7765ee9ef548e08cce1c, do we really need it? 

Full log:
<details>
./build-docker.sh secfix/21.02                   
File ‘ci/alpine-minirootfs-3.12.3-x86_64.tar.gz’ already there; not retrieving.

Sending build context to Docker daemon  13.79MB
Step 1/13 : FROM scratch
 ---> 
Step 2/13 : ARG ALPINE_VERSION=3.12.3
 ---> Using cache
 ---> 8408278bf58f
Step 3/13 : ARG ALPINE_ARCH=x86_64
 ---> Using cache
 ---> a4a022a564bc
Step 4/13 : ADD alpine-minirootfs-${ALPINE_VERSION}-${ALPINE_ARCH}.tar.gz /
 ---> Using cache
 ---> 369880215086
Step 5/13 : RUN apk add --no-cache --update openssl   && echo hosts: dns files > /etc/nsswitch.conf
 ---> Using cache
 ---> f992ea649e6e
Step 6/13 : ARG NIX_VERSION=2.3.10
 ---> Using cache
 ---> 53fd120e6763
Step 7/13 : RUN wget https://nixos.org/releases/nix/nix-${NIX_VERSION}/nix-${NIX_VERSION}-${ALPINE_ARCH}-linux.tar.xz   && tar xf nix-${NIX_VERSION}-${ALPINE_ARCH}-linux.tar.xz   && addgroup -g 30000 -S nixbld   && for i in $(seq 1 30); do adduser -S -D -h /var/empty -g "Nix build user $i" -u $((30000 + i)) -G nixbld nixbld$i ; done   && mkdir -m 0755 /etc/nix   && echo 'sandbox = false' > /etc/nix/nix.conf   && mkdir -m 0755 /nix && USER=root sh nix-${NIX_VERSION}-${ALPINE_ARCH}-linux/install   && ln -s /nix/var/nix/profiles/default/etc/profile.d/nix.sh /etc/profile.d/   && rm -r /nix-${NIX_VERSION}-${ALPINE_ARCH}-linux*   && rm -rf /var/cache/apk/*   && /nix/var/nix/profiles/default/bin/nix-collect-garbage --delete-old   && /nix/var/nix/profiles/default/bin/nix-store --optimise   && /nix/var/nix/profiles/default/bin/nix-store --verify --check-contents
 ---> Using cache
 ---> 8b93725d9b10
Step 8/13 : ENV     USER=root     PATH=/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/bin:/sbin:/usr/bin:/usr/sbin     GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt     NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt     NIX_PATH=/nix/var/nix/profiles/per-user/root/channels
 ---> Using cache
 ---> 9538a6479603
Step 9/13 : COPY shell.nix shell.nix
 ---> Using cache
 ---> 2d397a835dfc
Step 10/13 : ARG FULLDEPS_TESTING=0
 ---> Using cache
 ---> f4378d170317
Step 11/13 : ENV FULLDEPS_TESTING=${FULLDEPS_TESTING}
 ---> Using cache
 ---> 7c42165738d8
Step 12/13 : RUN nix-shell --arg fullDeps "$([ ${FULLDEPS_TESTING} = 1 ] && echo true || echo false)" --run "echo deps pre-installed"
 ---> Using cache
 ---> 2653a8a1be7d
Step 13/13 : CMD [ "nix-shell" ]
 ---> Using cache
 ---> 7f4153782f3a
Successfully built 7f4153782f3a
Successfully tagged trezor-firmware-env.nix:latest
"--platform" is only supported on a Docker daemon with experimental features enabled
</details>

**Comment by prusnak** [comment]
Sorry about that. Fixed in https://github.com/trezor/trezor-firmware/commit/250f09245b657e29ae339f748b8ff2b3902dc350 in master and cherry-picked to the release branch
