### ISSUE TITLE
introduce a protocol version

### ISSUE THREAD

**Issue by ligi** [trezor/trezor-firmware#143]
context https://gitter.im/trezor/community?at=5cd2e2b5f251e60ffa47c64a
and 
https://gitter.im/trezor/community?at=5cd2e2b5f251e60ffa47c64a

TLDR: currently you need to track and check for model+version which is quite cumbersome. Ideally there would be a protocol version. Even better - reduce the amount of protocol breaking changes ..-)

**Comment by prusnak** [comment]
Duplicate of https://github.com/trezor/trezor-firmware/issues/79

**Comment by ligi** [comment]
@prusnak can you explain how this is a duplicate of #79 ?

**Comment by prusnak** [comment]
redesigned protocol will contain a protocol version number

**Comment by ligi** [comment]
OK - did not see this in the issue - but looking forward to this change
