### ISSUE TITLE
Verifying Stellar Wallet Address is cut off on Trezor One Device Screen

### ISSUE THREAD

**Issue by dereileak** [trezor/trezor-firmware#1453]
While using Exodus to receive Stellar coins on the Trezor One, viewing the wallet address on the device to receive causes the end of the address to be cut off while verifying

Trezor Firmware:  1.9.3.

 - Wallet software: Exodus
 - OS: Mac Catalina 10.15.7
 - Exodus Version: 21.1.29 

Reproduce:
1) Connect wallet and put in passphrase, testing with no passphrase
2) Click wallet link button to view contents
3) Click Stellar coins to receive
4) click receive then review on device
5) Address will be presented in the app
![Screen Shot 2021-02-06 at 2 19 20 PM](https://user-images.githubusercontent.com/9966028/107130055-5a500780-6887-11eb-8618-b374075a5046.png)
6) Device will show cut off Address
![trezorBug](https://user-images.githubusercontent.com/9966028/107130045-4906fb00-6887-11eb-82d3-ec311e686eb3.jpg)

Expected behavior:
The full address should be viewable on the trezor device

**Comment by bosomt** [comment]
I was able to reproduce issue in Exodus 21.12.17 and in https://accountviewer.stellar.org/dashboard
Last characters of address are missing on Trezor One 1.10.2

**Comment by sime** [comment]
Similar issue on MATIC. ETH is also reported.

![P_20221215_170149](https://user-images.githubusercontent.com/216917/214056646-41d7dda4-8750-40d8-9881-ae4c664b80bd.jpg)

**Comment by Hannsek** [comment]
related?: https://github.com/trezor/trezor-firmware/issues/1212

**Comment by bosomt** [comment]
**QA NOK**

```
 ~/Downloads  trezorctl stellar get-address                                                                                                                           
GAXSFOOGF4ELO5HT5PTN23T5XE6D5QWL3YBHSVQ2HWOFEJNYYMRJENBV
```

but on display i see `GAXSFOOGF4ELO5HT5PTN23T5XE6D5QWL3YBHSVQ2HWOFEJNYYMRJE` im missing 3 last characters ;(

 - Device: model 1 1.11.3 Universal (revision 5e8f3238de9c9527648950d93c9c444a74d043ef)

**Comment by matejcik** [comment]
that could be because this will be fixed in the upcoming release

**Comment by bosomt** [comment]
**QA OK**

sorry wrong branch ;)

 - Device: model 1 1.11.3 Universal (revision be920d7cec2495d82496af500cbdeec6b945c505)
