### ISSUE TITLE
Model T no longer allows signing for arbitrary deriviation paths below `m/45'`

### ISSUE THREAD

**Issue by dhruvbansal** [trezor/trezor-firmware#1467]
**Describe the bug**

Signing for arbitrary public keys with deriviation paths under `m/45'` used to work -- it no longer does.

**Firmware version and revision**
Model T 2.3.5

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Unchained Capital platform & Caravan
 - OS: Seen on macOS but believed to be OS-independent issue
 - Browser: Seen on Chrome 87, but believed to be browser-independent issue

**To Reproduce**
1. Construct a transaction using public keys derived from a path such as `m/45'/0'/0'/0/0/0`(6 path components which, indeed is different than the BIP45 spec).
2. Sign the transaction with a pre-2.3.5 model T or with a Trezor ONE -- it works.
3. Sign the same transaction with a 2.3.5 model T, we get `Forbidden key path` error.

**Expected behavior**
We expected to be able to continue to sign for arbitrary derivation paths below `m/45'`.  This changed without any notification in advance, breaking signing for many of our customers.

**Screenshots**
Below is a screenshot of Caravan's [functional test suite](https://unchained-capital.github.io/caravan/#/test)
![gscreenshot_2021-02-10-112401](https://user-images.githubusercontent.com/6796/107577927-ae752780-6bb8-11eb-8d8c-1fda13773bde.png)

Below are two screenshot of Unchained Capital's (test) application, first when signing for a transaction
![gscreenshot_2021-02-10-114442](https://user-images.githubusercontent.com/6796/107577932-afa65480-6bb8-11eb-96d8-888b4ff80ac5.png)

And then when confirming an address.
![gscreenshot_2021-02-10-114557](https://user-images.githubusercontent.com/6796/107577934-afa65480-6bb8-11eb-8186-690f7838df15.png)

**Comment by prusnak** [comment]
Suggestion from Unchained Capital mentioned on Slack:

```
PATTERN_UNCHAINED_A = "m/45'/coin_type'/account'/[0-1000000]/change/address_index"
PATTERN_UNCHAINED_B = "m/45'/coin_type/account/[0-1000000]/change/address_index"
PATTERN_UNCHAINED_C = "m/45'/coin_type’/account’/[0-1000000]/address_index"
```

@dhruvbansal range `[0-1000000]` seems a little bit excessive - are you really using that wide range?

**Comment by prusnak** [comment]
Fixed via https://github.com/trezor/trezor-firmware/pull/1473
