### ISSUE TITLE
Trezor T with 3rd party wallet Qtum-Electrum - unknown path m/44'/88’/0’/0/0

### ISSUE THREAD

**Issue by SereFF1984** [trezor/trezor-firmware#1471]
Hello! 
Trezor Model T, firmware 2.3.5
Trezor One, firmware 1.9.4
Qtum-electrum-v4.0.11

Trezor support Qtum via Qtum-Electrum.
![1](https://user-images.githubusercontent.com/78924710/107679928-3be67380-6cae-11eb-82a5-484b8b645ebf.png)
In March 2020 was created new wallet in Qtum-electrum 0.18.16 with Trezor.
Selected legacy(p2pkh) with default path: m/44’/88’/0’
![7](https://user-images.githubusercontent.com/78924710/107680281-b1eada80-6cae-11eb-8dca-54a34442de00.png)
The wallet was created successfully and I deposit some Qtum coins to it. The coins were deposited successfully.
![9](https://user-images.githubusercontent.com/78924710/107680303-b9aa7f00-6cae-11eb-9b87-7664896602fc.png)
![12](https://user-images.githubusercontent.com/78924710/107680313-bca56f80-6cae-11eb-88dc-16a9e4e054e7.png)
Today I tried to send coins from this wallet but I got an unknown path m/44’/88’/0’/0/0 in Trezor T
![WhatsApp Image 2021-02-11 at 21 46 08](https://user-images.githubusercontent.com/78924710/107685025-8d91fc80-6cb4-11eb-83cb-185eb3948dd3.jpeg)
and error in Qtum-Electrum. So coins didn't send.
![15](https://user-images.githubusercontent.com/78924710/107684851-57ed1380-6cb4-11eb-8a3c-b758224538d4.png)
Tried to do something in Trezor One (firmware 1.9.4) but got the following errors:
![19](https://user-images.githubusercontent.com/78924710/107685758-6b4cae80-6cb5-11eb-8b47-068288782ebb.png)
![20](https://user-images.githubusercontent.com/78924710/107685771-6e479f00-6cb5-11eb-931e-3dd77b6479db.png)
and error in Qtum-Electrum:
![11](https://user-images.githubusercontent.com/78924710/107685836-891a1380-6cb5-11eb-9253-f4b1108b5a4f.png)
Is there a solution to solve this problem with wrong address part in Trezor?

**Comment by prusnak** [comment]
According to SLIP-0044: https://github.com/satoshilabs/slips/blob/master/slip-0044.md

the correct value for QTUM is 2301, not 88

Developers of Qtum fixed that in October 2019 in Qtum-Electrum 4.0.0 - see here https://github.com/qtumproject/qtum-electrum/commit/3e9cd1d78057681da6a0e2c466501580b21cabab

So I am not sure how you managed to create these addresses on wrong paths, since the issue should have been fixed already.

To get around the limitation you can switch the Trezor safety checks to prompt via:

`trezorctl set safety-checks prompt`

See https://wiki.trezor.io/Using_trezorctl_commands_with_Trezor#Safety-checks for more info

**Comment by icodeface** [comment]
Hi @prusnak, `trezorctl set safety-checks prompt` seems not work on Trezor One using firmware 1.9.4 , I got `Error: DataError: No setting provided`.

**Comment by prusnak** [comment]
@icodeface This works only with Trezor Model T. The setting can't be applied for Trezor One.

**Comment by icodeface** [comment]
> @icodeface This works only with Trezor Model T. The setting can't be applied for Trezor One. With Trezor One you have three options:
> 
> * try downgrading to firmware 1.9.0 (`trezorctl firmware-update -v 1.9.0`)
> * get Trezor Model T and import the seed
> * import the seed into Electrum (not recommended as this exposes all your coins to the computer which might be running malware)

Thanks for replying, is there any possibility add the safety-checks level function to Trezor One in the next firmware release ?

**Comment by prusnak** [comment]
> Thanks for replying, is there any possibility add the safety-checks level function to Trezor One in the next firmware release ?

No
