### ISSUE TITLE
Installing trezorctl on Windows - not working

### ISSUE THREAD

**Issue by SereFF1984** [trezor/trezor-firmware#1472]
Trezor Model T, firmware 2.3.5
Trezor One, firmware 1.9.4
Bridge 2.0.27
Windows 10 64bit

Installing trezorctl on Windows as on instruction at
https://wiki.trezor.io/Installing_trezorctl_on_Windows
1. Installed Python 3.7.4 64bit with "Add Python 3.7 to PATH" option;
![1](https://user-images.githubusercontent.com/78924710/107707069-5fbbb080-6cd2-11eb-8eb3-f55e2e9698c9.png)
2. After setup was successful, opened cmd;
3. In cmd typed "pip install trezor", installation finished complitely;
![2](https://user-images.githubusercontent.com/78924710/107707110-6a764580-6cd2-11eb-9214-a873f52d014f.png)
4. Trying to some sample commands, example trezorctl list and see this:
![3](https://user-images.githubusercontent.com/78924710/107707122-6f3af980-6cd2-11eb-8d75-62147fc35bf2.png)
Trying with Trezor One and Trezor T on PC with W10 64bit, Notebook with W10 64bit and Notebook with W7 (Python 3.7.4) but nothing changed.
Is there a solution to solve this problem? Thanks!

**Comment by prusnak** [comment]
`pip3 install attrs`
