### ISSUE TITLE
My device already updated to 2.3.6

### ISSUE THREAD

**Issue by peter22z** [trezor/trezor-firmware#1484]
My device was updated to firmware version 2.3.6 about 24 hours ago. I didn't found any info about this release - no git tag, no git release, no blog post, no any info. My device is Trezor T. I am worrying about non original firmware.

**Comment by prusnak** [comment]
This one is legit - it contained only a single fix for Unchained Capital - so it was not announced via our social media.

I created the tag, but I forgot to push it - I did it now: https://github.com/trezor/trezor-firmware/releases/tag/core%2Fv2.3.6

Thanks for the notice!
