### ISSUE TITLE
incorrect address / amount in Trezor One final confirmation screen

### ISSUE THREAD

**Issue by GordonGit** [trezor/trezor-firmware#1495]
Using Electrum with a Trezor One, the final  device confirmation screen on the Trezor device displays an a different address (a change address owned by the Electrum wallet) and an incorrect, higher amount of BTC to send. 

Firmware version 1.9.1

Electrum 4.0.2 / 4.0.9
Windows 10

Open Electrum
Enter Trezor PIN to unlock wallet
Go to Electrum "Send" tab, enter destination address and amount
Click "Pay"
Click "Finalize" if using advanced payment settings
Click "Sign"
Enter PIN
Confirm on 1st Trezor confirmation screen (details correct)
2nd confirmation screen displays different address and amount
Cancel transaction

I expected both confirmation screens to match, as per usual.

![electrum tx construction](https://user-images.githubusercontent.com/7726900/108604827-eea68800-73b8-11eb-9ed2-cb695cf2e71f.jpg)

![confirm screen 1](https://user-images.githubusercontent.com/7726900/108604819-e51d2000-73b8-11eb-92bf-e73595c24367.jpg)

![confirm screen 2 (unexpected result)](https://user-images.githubusercontent.com/7726900/108604823-eb130100-73b8-11eb-8e8d-8b723bf5700a.jpg)

It seems the final confirm screen is showing an output to a change address owned by the wallet (compare red arrows in confirm screen 2 pic to electrum construction pic). This is unexpected and a bit disconcerting - I expect the tx would work out OK but I'm not comfortable risking it.

**Comment by prusnak** [comment]
you can't have more than one change address - otherwise you need to confirm all change addresses - even if they belong to you

**Comment by prusnak** [comment]
FTR this was caused by a setting in Electrum:

```
"Preferences">"Transactions">"Use multiple change addresses"
```
