### ISSUE TITLE
Unable to Transfer Funds with Trezor Model T from a Metamask Account on Binance (BSC) Network

### ISSUE THREAD

**Issue by casoCornelius** [trezor/trezor-firmware#1501]
I have a latest version Trezor (20.12.1), Trezor Model T. I set up my Metamask account on the Binance Smart Chain (BSC) Network. When I attempt to withdraw funds from that account (Trezor-protected), I get "Tx Failed. Unknown Chain ID). I read online that someone who downgraded their Trezor firmware to 20.3.0, he could make it work that way. Can someone please assist me in downgrading my Trezor firmware from 20.12.1 to 20.3.0? Appreciations

**Comment by prusnak** [comment]
Latest version of Firmware is 2.3.6. Please install that one - instructions - https://wiki.trezor.io/User_manual:Updating_the_Trezor_device_firmware

**Comment by casoCornelius** [comment]
i will but do you think this is the error I'm causing?

**Comment by casoCornelius** [comment]
that was really helpful - i've solved my issue. Thank you!

**Comment by gipsonstella** [comment]
Has the error been solved?
