### ISSUE TITLE
add Tron (TRX) blockchain 

### ISSUE THREAD

**Issue by naminic** [trezor/trezor-firmware#1532]
**Is your feature request related to a problem? Please describe.**
yes transaction fee in TRX block chain is low so it is a good solution
**Describe the solution you'd like**
adding TRX support
**Describe alternatives you've considered**
I love trezor because it is open source and easy to use but not supporting TRX is a big issue for my community 
**Additional context**
as I believed nothing is impossible adding TRX is not a big deal for your professional team

**Comment by stepmes** [comment]
Thank you, @naminic, for submitting this request. I'm now adding the information you provided to our internal list of feature requests related to the support of new projects. This way, it will be included in the prioritization of future work on Suite. We need to run it through the prioritization before we make any decisions here. Thanks for understanding!
