### ISSUE TITLE
Uniswap says "soon" at https://trezor.io/coins/ while it!s ERC20 token

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-firmware#1572]
**Issue:** Uniswap is ERC20 token, hence supported by default, it's displayed with status "soon"
It's already recognized in Suite and can be added:
![image](https://user-images.githubusercontent.com/37402530/114881884-b1cc9f80-9e03-11eb-8d21-8daaf82f30dc.png)
URL: https://trezor.io/coins/#UNI

**Suggested solution:** change status to "Supported" and add available ETH wallet options.

**Comment by yohaaan** [comment]
Same goes for GRT https://trezor.io/coins/#GRT

**Comment by yohaaan** [comment]
And for AMP https://trezor.io/coins/#AMP

**Comment by matejcik** [comment]
tio/coins only show tokens as "supported" if Trezor will show the correct symbol/decimals.

support for UNI, GRT, AMP is tracked from v1.9.5/2.3.7, which is not out yet. So Trezor will show "UNKN" as the symbol. Hence, not technically supported.
