### ISSUE TITLE
Add support for Polkadot (DOT)

### ISSUE THREAD

**Issue by jziggas** [trezor/trezor-firmware#1574]
**Is your feature request related to a problem? Please describe.**
As a [Polkadot](https://polkadot.network/) (DOT) user I would like to store DOT coins on my Trezor Model T.

**Describe the solution you'd like**
The Trezor firmware supports 3rd party wallets for Polkadot (#&#8203;8  by market cap).

**Describe alternatives you've considered**
[Ledger Wallet](https://support.ledger.com/hc/en-us/articles/360016289919-Polkadot-DOT-)

**Additional context**
https://polkadot.network/

**Comment by prusnak** [comment]
Our current product goal is to unite what we support in firmware and in Trezor Suite and since firmware is way ahead of Suite we want to pause for a bit, implement the remaining coins into Suite and then consider adding new coins. Thank you for your understanding.

**Comment by jziggas** [comment]
I don't see a milestone for that in the trezor-suite repository. Is there a link or ticket that tracks feature parity between trezor-suite and trezor-firmware?

**Comment by prusnak** [comment]
Here is the public roadmap for the Suite - https://github.com/orgs/trezor/projects/28

Once everything from the Upcoming is cleared we might consider adding new coins.

**Comment by jziggas** [comment]
Ok thanks. So for posterity, only after these 15 issues are resolved would any new coins be considered:

https://github.com/trezor/trezor-suite/issues/3550

https://github.com/trezor/trezor-suite/issues/2770

https://github.com/trezor/trezor-suite/issues/3344

https://github.com/trezor/trezor-suite/issues/2736

https://github.com/trezor/trezor-suite/issues/2838

https://github.com/trezor/trezor-suite/issues/2740

https://github.com/trezor/trezor-suite/issues/2745

https://github.com/trezor/trezor-suite/issues/2918

https://github.com/trezor/trezor-suite/issues/2959

https://github.com/trezor/trezor-suite/issues/3002

https://github.com/trezor/trezor-suite/issues/3004

https://github.com/trezor/trezor-firmware/issues/1404

https://github.com/trezor/trezor-suite/issues/3016

https://github.com/trezor/trezor-suite/issues/3166

**Comment by shessam** [comment]
Pleaaase add Polkadot (DOT) on Trezor Model T.  
When :'(

**Comment by NoodleSploder** [comment]
Adding Cardano but not PolkaDot?  this is insanity.

**Comment by h4x3rotab** [comment]
@prusnak Now the dashboard doesn't have an "upcoming" column. What's the backlog now?

Btw, if someone contributes a PR, will Trezor team be willing to review?

**Comment by JiechengZhao** [comment]
+1 dot support needed.

**Comment by VadimChiritsa** [comment]
Could you please provide ETA for this?

**Comment by hynek-jina** [comment]
@VadimChiritsa 
There is no ETA for Polkadot support at this moment.

**Comment by timemaster5** [comment]
+1 I also vote for DOT

**Comment by Sm1le291** [comment]
Add support for dot please

**Comment by meehow** [comment]
@prusnak we (@weareseba) are willing to offer you some reasonable financial incentive or sponsor development of DOT and SOL in Trezor T wallet. I filled out a [from](https://trezor.io/enterprise/) on your website.

**Comment by KarpiuOPP** [comment]
Also waiting for DOT support :)

**Comment by anttivermas** [comment]
I am waiting for it also.

**Comment by JiechengZhao** [comment]
@prusnak Could you reopen the issue?

**Comment by sefechit** [comment]
+1 on DOT :(

**Comment by faisalthaheem** [comment]
+1 for dot

**Comment by Valcyclovir** [comment]
+1 for dot, ledger does it
