### ISSUE TITLE
Firmware 1.9.4 broke support for Firo /XZC/ and ZnodeMasternodetool - Firmware 1.9.3 work without issues

### ISSUE THREAD

**Issue by jTd7bPLFb** [trezor/trezor-firmware#1576]
Not possible to manage FIRO masternodes with firmware 1.9.4 and ZnodeMasternodeTool.

Not possible to sign transactions or send funds.
Problem is that transaction confirmation just flashes briefly in Trezor display and can not be confirmed with Trezor button.

Version 1.9.3 of Trezor Firmware works without issues though.

Testen on MacOS and Windows 10. Trezor fw 1.9.4 and 1.9.3.

debug file attached. The part where it breaks with 1.9.4.

[message.txt](https://github.com/trezor/trezor-firmware/files/6346388/message.txt)

**Comment by prusnak** [comment]
@a-bezrukov Can you have a look, please? You are listed as maintainer for Firo.

**Comment by prusnak** [comment]
From the log:

```
trezorlib.exceptions.TrezorFailure: DataError: Expected input with amount
```

The client now needs to provide amount for all inputs. Please open issue for ZnodeMasternodeTool.
