### ISSUE TITLE
Jump to bootloader trezorctl command

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1577]
Now that we have https://github.com/trezor/trezor-firmware/issues/1047 we have the ability to go to bootloader using [Protobuf message](https://github.com/trezor/trezor-firmware/blob/master/common/protob/messages-management.proto#L414). For testing purposes QA would really appreciate an easy command that would do this.

**Comment by tsusanka** [comment]
`trezorctl debug send-bytes 87 ""`should do the trick!

**Comment by tsusanka** [comment]
We can use that for QA purposes I believe that is enough.

**Comment by tsusanka** [comment]
Note that my instructions were incomplete (firmware sends a ButtonRequest after the aforementioned command which we need to confirm). The full tutorial is:

- Send `trezorctl debug send-bytes 87 ""`
- Do not confirm on Trezor and send `trezorctl debug send-bytes 27 ""`
- Confirm on Trezor
- Device should reboot

**Comment by prusnak** [comment]
> * Send `trezorctl debug send-bytes 87 ""`
> * Do not confirm on Trezor and send `trezorctl debug send-bytes 27 ""`

You can use message names too:

* Send `trezorctl debug send-bytes RebootToBootloader ""`
* Do not confirm on Trezor and send `trezorctl debug send-bytes ButtonAck ""`
