### ISSUE TITLE
PIN matrix randomization per input

### ISSUE THREAD

**Issue by NicolaiSoeborg** [trezor/trezor-firmware#158]
It would be nice with a _paranoid PIN setting_ which randomizes the PIN matrix on each input, such that repeated digits wouldn't be detected by any keyloggers/shoulder surfers.

This would allow for much better PINs, as currently repeated numbers will give no additional security against keyloggers / shoulder surfers.

Currently the advice is to "use as many numbers as possible", but it's better to "use as long a PIN as possible". Mandatory XKCD: https://xkcd.com/936/ .

The behavior might confuse some users, so the setting should probably be hidden under the "Advanced" menu.

**Comment by prusnak** [comment]
This was discussed in the past, original design behaved like this and it was VERY confusing, thus we are not changing that.

Btw, you can enter PIN directly on Trezor Model T touchscreen.
