### ISSUE TITLE
Unknown transactions shows up, can not see the amount 

### ISSUE THREAD

**Issue by hakonamatata** [trezor/trezor-firmware#1589]
Transactions does not show properly. Says just "Unknown Transaction".

**Firmware version and revision**

Trezor Model T
Firmware version
2.3.6 

**To Reproduce**
 These are payouts to masternodes for staking. So if you run a masternode these payouts come out on a regular basis. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4003969/116810161-696eea80-ab42-11eb-85d6-20a8a55b8fd3.png)

It does show properly using Electrum: 
![image](https://user-images.githubusercontent.com/4003969/116810215-d2eef900-ab42-11eb-9292-569de5499c08.png)

**Comment by prusnak** [comment]
Parsing this transaction is not supported. Use Electrum.
