### ISSUE TITLE
Add exception safety to Rust code

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#1598]
Currently Rust bindings calling Micropython functions do not install exception handlers. An exception raised by Micropython will skip and throw away the Rust context, which might lead to incorrectness in certain cases.

**Comment by matejcik** [comment]
Reading through https://github.com/rust-lang/rfcs/issues/2625 and https://github.com/rust-lang/rust/issues/58314, I'd be wary of using `nlr_push` in Rust directly.

For that matter, it prooobably means it's not safe to compile micropython with LLVM? Because `nlr_push` is not marked `returns_twice`. GCC also recognizes that attribute but per https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#returns_twice it doesn't do anything problematic as long as `nlr_push` is written correctly.

This means that we should trampoline through C, per @jpochyla's suggestion. That would entail either writing wrappers for all functions that can raise, or some macro magic, or maybe some sort of universal wrapper that takes a function pointer and variadic arguments??? Either way, it's not very nice.

**Comment by bosomt** [comment]
@matejcik can we move it to approved section ?

**Comment by matejcik** [comment]
done
