### ISSUE TITLE
Trezor T freezing during signing when custom homescreen is set

### ISSUE THREAD

**Issue by Saicere** [trezor/trezor-firmware#1605]
After updating a Trezor Model T to 2.3.6, it has started freezing during both BTC and BCH transaction signing whenever a custom homescreen is used, even after trimming the homescreen down to a <10 KB PNG. The freezes seem to be consistent for a given transaction even if I unplug and reinsert it, but some transactions work and some don't without any obvious pattern.

Not really sure why this would be an issue, seeing as the homescreen isn't even visible during transaction signing. I guess it should be fixable simply by unloading the homescreen from RAM while signing?

**Comment by prusnak** [comment]
Yes, please reset the home-screen to default and it should work again. We are working on improving the situation for the next firmware updates.
