### ISSUE TITLE
Add Labeler GitHub action

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#1607]
See https://github.com/actions/labeler for more details

This can automate labels for PRs by predefined rules - similar to CODEOWNERS but for labels.

**Comment by matejcik** [comment]
also would be nice if a similar thing existed for Projects. Notably I'd love every new PR to be added to Firmware Pull Requests project

**Comment by matejcik** [comment]
isn't this now solved with project automations + using labels differently than we used to?

**Comment by sime** [comment]
I concur.
