### ISSUE TITLE
SD card filesystem

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#162]
In order to use the SD card, we need to decide which filesystem will be used.

Currently I see two options:
* FAT32 - https://github.com/micropython/oofatfs
* LittleFS - https://github.com/ARMmbed/littlefs

FAT32 | LittleFS
----|----
:heavy_plus_sign: major OS support | :heavy_minus_sign: not supported on major OS
:heavy_minus_sign: complex | :heavy_plus_sign: simple
:heavy_minus_sign: not power-loss resilient | :heavy_plus_sign: power-loss resilience
:heavy_minus_sign: not optimized for SD cards | :heavy_plus_sign: dynamic wear leveling

There are also other options such as JFFS2 or YAFFS.

**Comment by ciny** [comment]
WSL2 should add full linux system call compatibility to windows 10 so FUSE should work [source](https://devblogs.microsoft.com/commandline/announcing-wsl-2/), hopefully [littlefs-fuse](https://github.com/ARMmbed/littlefs-fuse) will too. It won't be "out of the box" support but better than nothing.

**Comment by tuxxy** [comment]
I'm +1 on FAT32 because of the OS support.
Are there are other goals of including the SD card support that may sway me towards a different FS?

**Comment by prusnak** [comment]
Implemented in https://github.com/trezor/trezor-firmware/pull/264
