### ISSUE TITLE
Trezor t Shamir to 24 seed

### ISSUE THREAD

**Issue by sportvikings1981** [trezor/trezor-firmware#1636]
i’m trying to claim free flare spark tokens. I had my xRP on my trezor t at time of snap shot. I have 2 20 seed Shamir backup. If I can figure out how to create single 24 backup (from Shamir), I can link my trezor to a spark compatible wallet so flare can see Xrp was there at time of snapshot. Is this possible?

**Comment by prusnak** [comment]
No, this is not possible
