### ISSUE TITLE
Spaces lost in Shamir info texts

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#1643]
**Describe the bug**
See screenshots. Looks like we lost all spaces in Shamir info texts.

**Firmware version and revision**
major_version: 2,
    minor_version: 4,
    model: 'T',
    needs_backup: False,
    no_backup: False,
    passphrase_always_on_device: False,
    passphrase_protection: True,
    patch_version: 0,
    pin_protection: False,
    recovery_mode: False,
    revision: 9 bytes b'3204fd682',
    sd_card_present: False,
    sd_protection: False,
    unfinished_backup: True,
    unlocked: True,
    vendor: 'trezor.io',
    wipe_code_protection: False,

**Info:**
 - Suite version: web 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.4.0 Bitcoin only

**To Reproduce**
1. Start Shamir backup
2. Click on INFO button during backup
3. Observe

**Screenshots**
<img width="325" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120617281-df23ea00-c451-11eb-86b2-f07a4adf6bc6.png">

<img width="388" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120617252-d6331880-c451-11eb-927f-138bd5fb7a50.png">

**Comment by bosomt** [comment]
**QA OK**

fixed in trezor-fw-regular-2.4.0-ea3596ad.bin

**Comment by mmilata** [comment]
@bosomt thanks!
