### ISSUE TITLE
Support Taproot

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1656]
Support Taproot in firmware.

Tasks:
- [x] Make secp256k1-zkp default:
  - https://github.com/trezor/trezor-firmware/issues/1534
  - PR https://github.com/trezor/trezor-firmware/pull/1678
- [x] Support new transaction format
- [x] Decide BIP-44 paths
- [x] Implement Bech32m address format (bip-0350)

Docs:
- [BIP 340: Schnorr Signatures](https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki)
- [BIP 341: Taproot: SegWit version 1 spending rules](https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki)
- [BIP 342: Validation of Taproot Scripts](https://github.com/bitcoin/bips/blob/master/bip-0342.mediawiki)
- [BIP 350: Bech32m format for v1+ witness addresses](https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki)

**Comment by prusnak** [comment]
FTR:  Taproot softfork will activate in November.

**Comment by tsusanka** [comment]
@prusnak could you fill in the last bullet point please? I did catch it properly what was it.

**Comment by prusnak** [comment]
> @prusnak could you fill in the last bullet point please? I did not catch it properly what was it.

Done

**Comment by andrewkozlik** [comment]
Additional tasks:
- [ ] In `SignTx` implement the BIP-341 "common signature message" computation.
- [ ] In `SignTx` disable streaming of previous transactions if at least one input is taproot.
- [ ] Implement taproot support in `scripts.py`, i.e. `output_script_native_p2tr()` , `witness_p2tr()`, `parse_witness_p2tr()` etc.
- [ ] Decide how best to implement multisig for taproot in Trezor
    - MuSig (interactive signing) vs. unagreggated multisig (non-interactive).
    - Consider that taproot allows encoding more complicated schemes, e.g. with four keys A, B, C and D, we can have something like "A or (B and C) or (B and D)". This would require modifications to `MultisigRedeemScriptType`.
- [ ] Implement multisig scripts for taproot. 
- [ ] Use new Bech32m format in `GetAddress`.
- [ ] Support taproot scripts and Schnorr signatures in `SignatureVerifier`.
- [ ] Support taproot scripts and Schnorr signatures in `GetOwnershipProof` and in `verify_nonownership()`.
- [ ] Figure out how to deal with taproot in `SignMessage` and `VerifyMessage`. Bitcoin Core doesn't seem to use Schnorr signatures for signing messages. This is related to AOPP support https://github.com/trezor/trezor-firmware/issues/1586.

**Comment by prusnak** [comment]
> [ ] Decide how best to implement multisig for taproot in Trezor

I prefer to transfer the multisig related tasks to a separate topic (new epic issue) and focus this effort only for single-sig Taproot.

**Comment by andrewkozlik** [comment]
> - [ ] Decide BIP-44 paths

Andrew Chow is proposing to use a new purpose number for taproot paths:
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-June/019096.html
https://github.com/achow101/bips/blob/taproot-bip44/bip-taproot-bip44.mediawiki

**Comment by bosomt** [comment]
**QA OK**

**Comment by gruve-p** [comment]
Is the support for Taproot also being implemented for altcoins like GRS? GRS has activated Taproot since june 2021 and Electrum-GRS has support for sending to Taproot addresses.

**Comment by matejcik** [comment]
@gruve-p not at this time, but please create a separate issue. Enabling Taproot for other coins should not be difficult.

**Comment by tsusanka** [comment]
Let's close this and separate some of the subtasks from Andrew into new issues?

**Comment by andrewkozlik** [comment]
> Let's close this and separate some of the subtasks from Andrew into new issues?

Done: https://github.com/trezor/trezor-firmware/issues/1943, https://github.com/trezor/trezor-firmware/issues/1944, https://github.com/trezor/trezor-firmware/issues/1946.

**Comment by gruve-p** [comment]
@matejcik My attempt to enable Taproot for GRS: https://github.com/trezor/trezor-firmware/pull/2030
