### ISSUE TITLE
Errors when signing EOS transactions

### ISSUE THREAD

**Issue by cryptosig** [trezor/trezor-firmware#166]
on line 287 of eos.py:
header.max_net_usage_words = int(transaction["net_usage_words"])
however my cleos @1.72 is putting:
"max_net_usage_words": 0,
in the transaction which throws an error when you try to sign the transaction, because it is looking at a string that doesn't match.

**Comment by prusnak** [comment]
@matejcik is this intentional? https://github.com/trezor/trezor-firmware/blob/master/python/trezorlib/eos.py#L287

**Comment by matejcik** [comment]
the `net_usage_words` seems to be a deprecated name, i'd keep with what cleos produces.

i'll rename where appropriate

**Comment by prusnak** [comment]
Fixed in 94a8dc8e9d463d631a693708801d898715252541
