### ISSUE TITLE
OP_RETURN enforcing 0 value

### ISSUE THREAD

**Issue by sidhujag** [trezor/trezor-firmware#1661]
Hi there,

I noticed the firmware enforces OP_RETURN as 0 value https://github.com/trezor/trezor-firmware/blob/f93a8514e8e25b17b02360d9955c0a30999adf68/legacy/firmware/transaction.c#L207

This test confirms its not intended to work:
https://github.com/trezor/trezor-firmware/blob/f93a8514e8e25b17b02360d9955c0a30999adf68/tests/device_tests/test_op_return.py#L94

I think this was done way back when prior to version 1.9 that the OP_RETURN would mistakenly be used as change output if the values matched and since OP_RETURN wasn't confirmed allowed for situations where users had their coins unknowingly burned possibly.

Now there is a specific type for PAYTOOPRETURN and so I assume this would never be assigned as a change output in todays firmware? If that is the case it would be awesome if there a way we can allow > 0 OP_RETURN for provable burning use cases such as:

1) In Syscoin we create SPT's by provably burning SYS on the creation transaction
2) Bitcoin and other Bitcoin type coins just provably burning coins

If now there are no security vulnerability that would be created by allowing non-zero value OP_RETURNs as change would simply never be OutputScriptType_PAYTOOPRETURN is there a possibility it can be fixed so we can unlock these useful features?

Thanks!

**Comment by stepmes** [comment]
Thank you for the suggestion, we're noting it down and will consider it when we plan future development.
