### ISSUE TITLE
[Feature] 2FA TOTP for selected accounts

### ISSUE THREAD

**Issue by radeksvarz** [trezor/trezor-firmware#1662]
Model: Trezor T

PAIN:
Trezor's assets are as safe as is safe the weakest step for transaction confirmation.
Currently this is the PIN. A slight improvement is current digit rotation on the T screen.

Further hardening is enabled by the use of Passphrase, which is rather dangerous for common folks, since people forget such phrases. In such cases funds are non accessible even after the device recovery.

SOLUTION PROPOSAL:
Enable assigning 2FA TOTP to particular accounts for transaction confirmations.
Users are already used to TOTP using G. authenticator, Authy, ... or by Mobile banking apps. Thus the UX is easily explainable to the users.

In case of the device recovery, the TOTP would be reset during the recovery process. Thus mitigating the issue of the lost TOTP setup. This follows principle: "seed is the master key to everything".

Some accounts are considered for the longer storage (with significantly higher assets' value), while other accounts are used for frequent operations (with lower assets' value). 

2FA TOTP is therefore proposed to be selectable for particular accounts.

**Additional context**
By the result Trezor would have the following scale of confirmation hardening:

0 .. no PIN, no 2FA TOTP, no Passphrase (very bad idea)
1 .. PIN
2 .. PIN, 2FA TOTP (for selected accounts)
3 .. PIN, Passphrase, and or 2FA TOTP combinations

**Comment by stepmes** [comment]
Thank you for this idea and all the details. We're noting it down and will get back to it when we plan future improvements in this area.
