### ISSUE TITLE
Add TEO coins support

### ISSUE THREAD

**Issue by trustfarm-dev** [trezor/trezor-firmware#167]
TEO coins support .
PR is (#163 )

**Comment by prusnak** [comment]
No need to open issue for existing PR

**Comment by trustfarm-dev** [comment]
@prusnak  I step by step followed https://wiki.trezor.io/Developers_guide:Contributing 
If I missed issue raising.

**Comment by tsusanka** [comment]
If it's just a network/fork/derivate there's no need to open an issue as mentioned in the  'Adding a new coin' section.

**Comment by trustfarm-dev** [comment]
Thanks for your response.
