### ISSUE TITLE
[Feature] Support ar(weave) coins

### ISSUE THREAD

**Issue by hlolli** [trezor/trezor-firmware#1685]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like to store my ar coins safely inside my trezor wallet

**Describe alternatives you've considered**
none

**Additional context**
I'm happy to contribute or provide information about arweave if needed. If a wallet support for arweave is as easy as adding specifications for it in common/defs/misc/misc.json, I could definitely do that!

**Comment by prusnak** [comment]
Thank you for the suggestion, hlolli! Unfortunately, we are not adding new coins to Trezor at the moment.
If the coin makes it to Top 30 on CoinMarketCap we will revaluate.

Thank you for understanding!
