### ISSUE TITLE
make build_unix error

### ISSUE THREAD

**Issue by maltsevIvanReal** [trezor/trezor-firmware#1687]
Hey! I am trying to start the emulator using this instruction: https://docs.trezor.io/trezor-firmware/core/build/emulator.html . 
I get an error at the build stage. 
What could be the problem?

In addition, my goal is to launch the payment option on my site using trezor and for this I need an emulator to test transactions. Please tell me is it possible?
Maybe there is an alternative?

![image](https://user-images.githubusercontent.com/45118908/124256130-271f5500-db55-11eb-87d8-c8d6b39db067.png)

**Comment by prusnak** [comment]
`protoc command not found`

try the following:

```
sudo apt-get install protobuf-compiler
```
