### ISSUE TITLE
Add validation tests for protobuf definitions

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#17]
We should validate our protobuf definitons meet the following criteria:

* no required fields are used, only optional (this needs to be addressed first)
* only supported data types are used (uint32 uint64 sint32 sint64 bool string bytes)
* etc.

We can write a quick hack in bash, but I guess it's better to use python-protobuf to perform better checks.

**Comment by matejcik** [comment]
we haven't actually needed this since the issue was created, so let's just close and get back to it if the need ever arises
