### ISSUE TITLE
Trusted/Authorized hosts (storing the salt file on the host instead of the SD card)

### ISSUE THREAD

**Issue by ecuamobi** [trezor/trezor-firmware#1701]
**Is your feature request related to a problem? Please describe.**
I like the idea of adding extra security by storing a salt file on a micro SD card. When not in use I extract the SD card and store somewhere else. However if the attacker has enough time they could just keep looking until they find the card.

That's why I prefer to keep that file (the whole folder) on my (password-protected) computer and/or Android phone and remove it from the SD card. When I'm going to use my Trezor T I plug any FAT-formatted SD card into my computer or phone, copy the trezor folder, remove the SD card and plug it back into my Trezor. I remove that folder again afterwards.

I'm very happy with the achieved security but the process is cumbersome.

**Describe the solution you'd like**
I'd like to be able to store this salt file somewhere on my computer and/or Android device and have the Trezor automatically access it if the SD card is missing. That way the Trezor would effectively be usable only on my trusted devices, with the option of backing up the salt file to authorize other devices or to store it on an SD card if required.

**Comment by prusnak** [comment]
Duplicate of https://github.com/trezor/trezor-firmware/issues/32
