### ISSUE TITLE
Trezor Should Allow Configurable Pin Attempts

### ISSUE THREAD

**Issue by bonedaddy** [trezor/trezor-firmware#1703]
**Is your feature request related to a problem? Please describe.**

A default, and unchangeable 16 attempt threshold before wiping the device is IMO unacceptable. There is no reason why you shouldn't be allowed to lower the limit. 

**Describe the solution you'd like**

Allow users to configure the max pin retry count. The [max pin count is set as a constant in the python code](https://github.com/trezor/trezor-firmware/blob/f93a8514e8e25b17b02360d9955c0a30999adf68/storage/tests/python/src/consts.py#L34), and a [macro in the c code](https://github.com/trezor/trezor-firmware/blob/6fd4739c5c24ce93afdbe39af33f4a2bfae8ce45/storage/storage.c#L84) so realistically speaking it shouldn't be that difficult to implement, but would give a solid boost in security.

**Describe alternatives you've considered**

Passphrases can be used, sd card protection can be used, etc.. however there is still the matter of having a max pin retry count of 16. Not allowing this to be configured is ultimately detrimental to security.

**Comment by stepmes** [comment]
Thank you for your suggestion. We're noting it down to our list of feature ideas and will consider it when we next work on improving this area.
