### ISSUE TITLE
ClearSession has no effect on Model T

### ISSUE THREAD

**Issue by kklash** [trezor/trezor-firmware#171]
Steps to replicate:

1. Connect model T 
2. Unlock device PIN
3. Confirm you can get public keys: 
```
pipenv run trezorctl ethereum-get-address  -n "m/44'/60'/0'/0/0"
```
4. `pipenv run trezorctl clear-session`
5. Repeat step 3 - no difference. 

This is incongruous with the same steps performed on the Trezor One, which require the user to input their PIN between steps 4 and 5.

**Comment by prusnak** [comment]
Known issue. Will be addressed later.
