### ISSUE TITLE
Latest version 2.4.1 not on wiki

### ISSUE THREAD

**Issue by danger89** [trezor/trezor-firmware#1722]
**Describe the bug**
The latest version (2.4.1) is not yet displayed on the wiki page: https://wiki.trezor.io/Firmware_changelog

While the changelog does reflect those changes: https://github.com/trezor/trezor-firmware/blob/master/core/CHANGELOG.md

Regards,
Melroy

**Comment by alex-jerechinsky** [comment]
Updated now. Thanks, @danger89

**Comment by danger89** [comment]
You're welcome!
