### ISSUE TITLE
Entropy Specification

### ISSUE THREAD

**Issue by infosisio** [trezor/trezor-firmware#1733]
There used to be an option for trezorctl reset-device that was -e / --entropy and allowed specifying the entropy.

That option is now gone.

Reset_device was also gone from the trezorlib.client, making [this](https://gist.github.com/jhoenicke/939e58e26bc54ef46616a680eadcc368) approach dead as well.

I understand that this may have been done for security reasons, but there are a few testing scenarios when specifying the entropy is handy.

I was wondering if there was another way to do this, perhaps via trezorlib?

**Comment by matejcik** [comment]
you can manually send the appropriate message.
e.g. like this:
```python3
from trezorlib.client import get_default_client
from trezorlib import messages

client = get_default_client()
reset_msg = messages.ResetDevice(
	# ...your arguments go here
)
resp = client.call(reset_msg)
assert isinstance(resp, messages.EntropyRequest)
client.call(messages.EntropyAck(entropy=your_entropy_goes_here)
```

or you can mock out `os.urandom` (which really should be changed to `secrets`) for the reset call, like our unit tests do:
```
from unittest import mock
from trezorlib.client import get_default_client
from trezorlib.device import reset as reset_device

def external_entropy():
	entropy_hex = input("tell me your external entropy in hex:")
	return bytes.fromhex(entropy_hex)

client = get_default_client()
with mock.patch("os.urandom", external_entropy):
	reset_device(client, your_arguments_go_here)
```
