### ISSUE TITLE
Do not convert bech32 addresses to upper-case for QR code

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#1751]
Per https://www.qrcode.com/en/about/version.html, V3 QR code can fit 42 characters in BINARY mode, and V4 QR code can fit 62. This happens to match the length of Bitcoin segwit bech32 addresses for single-sig (42) and multisig (62) accounts.

Despite that, we convert bech32 addresses to uppercase. Ostensibly to lower complexity of the QR code, but this does not help in practice (V2 fits only 38 ALPHANUM so we need V3 anyway; conversely, V3 fits only 61 ALPHANUM so we need V4 anyway).

We should probably keep bech32 addresses as lowercase, for better compatibility.

How are the lengths of taproot addresses?

**Comment by prusnak** [comment]
> How are the lengths of taproot addresses?

The same as segwit v0 multisig. Here is a valid segwit v1 taproot address: `bc1pw508d6qejxtdg4y5r3zarvary0c5xw7kw508d6qejxtdg4y5r3zarvary0c5xw7kt5nd6y`

**Comment by matejcik** [comment]
QA instructions:

1. show QR codes for Segwit and Taproot addresses on device, scan them, ensure that the contents match the address and that the scanned text is in lower case.
2. show QR codes for different kinds of addresses (incl. other currencies than Bitcoin), ensure the QR codes can be scanned and are in the expected format

**Comment by bosomt** [comment]
On it
@matejcik just model T right ? i don't see any change of code in model One code

**Comment by matejcik** [comment]
exactly. For step 2 you can compare results to T1 if it's unclear what "expected format" is

**Comment by bosomt** [comment]
found one issue compared to 2.4.3
we lost BITCOINCASH: prefix in QR code 
so you will get different results on device display and different results displayed in suite
+ Suite can match this address to correct account 

<img width="425" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/157842108-a3a9a7d3-e125-402e-b985-6a0f7608c8df.png">


2.4.3: `BITCOINCASH:QPQ7CUGZRVNMKGFS3TG0H5YRF5M6NLNACYWR7UTCQT`
2.4.4: `qry3epyn9ulff5mnz7d89j3ks30acvmx5gx3tm3f62` displayed QR code and address

**Comment by matejcik** [comment]
is there a difference between previous a current FW?

**Comment by matejcik** [comment]
In case of vtc (and possible other bech32 currencies), it's another question -- as Bitcoin bech32 addresses are 42 characters but VTC is 43 -- so the QR code would actually need to be smaller (higher-res) to fit the lowercase encoding.

about BCH, please re-test with https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/pipelines/489913251

**Comment by matejcik** [comment]
Reopening the issue as the original description still applies for the VTC problem.

A Product decision is needed (cc @sime): how much do we care about (a) QR code legibility, which _may_ already be too low to be of concern, and (b) functioning of coins like VTC with regard to QR code format.

To add: while bech32 addresses are not case-sensitive, apparently some wallet software will reject upper-cased address variants.

**Comment by bosomt** [comment]
revision: 20 bytes 0x0bfdfbe925f64890619325cd0cc7f5c296f491da,

**VTC**: same behavior as 2.3.4
**BCH**: BITCOINCASH: prefix and UPPER CASE is back, but suite says invalid address

<img width="621" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/157870413-1fbbc19c-5a51-49a2-b1f3-9132c9ddfa9b.png">

**Comment by matejcik** [comment]
> BITCOINCASH: prefix and UPPER CASE is back, but suite says invalid address

did Suite previously accept this and now doesn't?

**Comment by bosomt** [comment]
yes :) and when i remove prefix it accepts it ;)

<img width="460" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/157870917-a7a69bd6-ab55-4ebf-b1c3-7d245baa9c0e.png">

**Comment by matejcik** [comment]
that's kind of weird.

To be extra clear: what is the contents of the QR code on 2.4.3 ? Does Suite accept it?
What is the contents of the QR code on T1? Does Suite accept it?

**Comment by bosomt** [comment]
so QR code for BCH is broken for a long time ;)
there was some time we had same problem with BTC B32 addresses so we introduced convert to lower case button
as soon i convert it Suite accepts it.

2.4.3: QR   - BITCOINCASH:QR0QACW7NPWZG7PUTA5XJFM3N8Y24DYSPUZTY804E6 - `Address is not valid`
2.4.3: Suite - bitcoincash:qr0qacw7npwzg7puta5xjfm3n8y24dyspuzty804e6

1.9.4 QR code - BITCOINCASH:QZNG9KY34PGAFJXNRAQTT59JGAA28LH84SPP3R64D4 - `Address is not valid`
1.9.4 Suite - bitcoincash:qzng9ky34pgafjxnraqtt59jgaa28lh84spp3r64d4

<img width="660" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/157899393-e82f623b-27b9-4a50-bdb4-c6a5990f86d5.png">

**Comment by bosomt** [comment]
2.4.4     revision: 20 bytes 0x0bfdfbe925f64890619325cd0cc7f5c296f491da,
same behavior for BCH address

<img width="563" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/157909523-6c11d8a9-1ae7-4062-bff3-85ff437f75a9.png">

**Comment by bosomt** [comment]
**QA OK**

retested with latest dev master
sent separate Suite issue to enable uppercase receive address conversion for BCH /other coins like VTC or LTC already enabled/
