### ISSUE TITLE
Trezor Froze on transaction, now device is bricked...

### ISSUE THREAD

**Issue by AquaWookie** [trezor/trezor-firmware#1766]
So I was attempting to sign a transaction on the hardware wallet (sending transaction via desktop app), at the step where you check the X or Checkmark, when I selected the Checkmark the device froze. I waited about 30 seconds, desktop client was frozen and hardware wallet was frozen. I disconnected the wallet, reconnected and the same transaction was still frozen in the App but the Hardware wallet acted as though it was just plugged in (and I entered PIN - sitting at start screen). Now the computer no longer recognizes the device. I don't know if this is firmware related or what but I'm really disappointed that the device is bricked and I likely have to get a new wallet and do a restore...

Any ideas?

**Comment by matejcik** [comment]
please contact customer support at https://trezor.io/support, or use the new forum at https://forum.trezor.io/

This is unfortunately not nearly enough information to be a valid github issue.
