### ISSUE TITLE
Would you accept a proper implementation of Solana

### ISSUE THREAD

**Issue by t-nelson** [trezor/trezor-firmware#1775]
Hi!  Sorry if I'm being dense, but from the [contributing guide](https://wiki.trezor.io/Developers_guide:Contributing) it is unclear to me whether a proper implementation of Trezor firmware support for Solana would be accepted at this time.  It looks like there have been a couple community false starts that have gone nowhere.  I'm an engineer with Solana Labs and a primary maintainer of our Ledger app.  We're interested in a Trezor implementation, but would like to confirm that it's something that you have capacity for before dedicating resources.  Please advise.

Thanks!

**Comment by mdhz** [comment]
Very good opportunity here for the Trezor team to work with. It's been the most requested chain from your users. Please do something. It's top 10 in the total market cap now.

**Comment by zhangcanaaa** [comment]
Totally. If I had to put my hands up, I'd put my hands up and my feet up!

**Comment by karamellar** [comment]
It's a shame that sol is missing considering it's such a popular chain

**Comment by xiaoyu2006** [comment]
Any updates?

Solana had grown quickly in the past week, so this altcoin should be a little more priority IMO.

**Comment by penilessquant** [comment]
2nd that. I love my Trezors but I am doing more and more in the SOL space and unfortunately am moving to the dark side...

**Comment by kdckrs** [comment]
@tsusanka Any news about this? SOL is now the 5th biggest token (market-cap wise) so it should be a big priority to add compatibility.

**Comment by g00nix** [comment]
I was about to buy a Trezor but I see it has no support for Solana. As soon as you add support, I am buying.

**Comment by abh1** [comment]
Same, need to secure my sol...trezor wont do

**Comment by alifarooq0** [comment]
Hello @prusnak, @tsusanka -- does the Trezor team have plans to support Solana in the upcoming Trezor model?

**Comment by amplicity** [comment]
Has there been any progress here?

**Comment by Hannsek** [comment]
In near future, unfortunately, Trezor will not support Solana.

**Comment by amplicity** [comment]
@Hannsek thanks for clarification --- any reasons as to why not, or is it just not a priority at this time?

**Comment by Hannsek** [comment]
No particular reason. Not a priority right now.

**Comment by cac-99** [comment]
Adapt or die, it's the free market.

**Comment by matejcik** [comment]
closing in favor of #3359
