### ISSUE TITLE
Update micropython to latest

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1789]
First [PR here](https://github.com/trezor/trezor-firmware/pull/1548) but needs to be updated.

This will also help https://github.com/satoshilabs/devops/issues/18.

**Comment by bosomt** [comment]
@matejcik @tsusanka anything needs to be tested on our side or we can move it to approved issues/PRs ?

**Comment by matejcik** [comment]
i moved to approved
