### ISSUE TITLE
BLS12-381 and Chia

### ISSUE THREAD

**Issue by hoffmang9** [trezor/trezor-firmware#1793]
I noted your conversation with a Solano developer in #1775 and also noted that there was an abandoned attempt to integrate BLST in https://github.com/trezor/trezor-firmware/pull/1024/files

We are certainly game to do a complete BLS integration and add the Chia specific items.

We are also game to be in the community firmware that @tsusanka mentioned in the Solano thread for now.

Please keep us in the loop as we have community demand and some important projects launching soon using Chialisp.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
