### ISSUE TITLE
Separate ButtonRequests in device

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-firmware#18]
We have 2 step verifying in this section(screenshot). First one is an address, second one is a message. We want to know which one is verifying. Currently both responses have "ButtonRequest_Other".

![image](https://user-images.githubusercontent.com/3112191/48568860-95f60400-e900-11e8-8a54-dabba7bdc399.png)

**Comment by prusnak** [comment]
Duplicate of https://github.com/trezor/trezor-firmware/issues/35
