### ISSUE TITLE
Locked out of EOS Wallet

### ISSUE THREAD

**Issue by cryptosig** [trezor/trezor-firmware#1814]
At some point the EOS wallet provider bloks.io and the firmware became incompatible. The wallet provider uses a non-standard bip44 derivation path now, using 44/194/0/INDEX/0, however that index will not go above a value of 1. As a value greater than 1 yields, 
`
trezorctl eos get-public-key -n "m/44'/194'/0'/2/1"
Consider installing rusty-rlp to improve pyrlp performance with a rust based backend
Error: DataError: Forbidden key path
`

This cannot be the original implementation, as I have personally checked and have several owner keys using the correct derivation path of "m/44'/194'/INDEX'/0/0", and can be confirmed with trezorctl eos get-public-key -n "m/44'/194'/2'/0/0". However now this creates a problem as I am locked out from the wallet with older accounts, and the newer accounts link to the 44/194/0/INDEX/0 path scheme. Thus if the wallet provider is to follow the correct derivation scheme as set by bip-44 and referenced https://docs.trezor.io/trezor-firmware/misc/coins-bip44-paths.html , than any new users will not be able to access their wallets. 

Whilst I understand that this is not completely a firmware issue of trezor, I am likely may not be the only user who was locked out, and the bip-44 docs are in trezor-firmware section, thus my posting here. It should likely be noted somewhere that any said users will need to know that this particular provider is not following the correct bip-44 scheme, and they will need to use command line trezorctl to recover any lost accounts. Furthermore should any other wallet providers decide to support Trezor + EOS, and choose to follow the correct bip-44 implementation, users will not be able to access their accounts that were tied to bloks.io. Additionally the bloks.io provider choosing the incorrect scheme is severely limiting because the maximum number of usable addresses is now two. Could a person tie multiple owner keys to the same private key, yes, but that creates a larger attack vector and privacy issues.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
