### ISSUE TITLE
Fatal error when upgrading firmware: embed/bootloader/messages.o'185

### ISSUE THREAD

**Issue by alexgleason** [trezor/trezor-firmware#1816]
**Describe the bug**
When upgrading my firmware on a Model T from v2.4.0 to v2.4.2 through Trezor Suite (web), it crashed and I saw the following screen:

![image](https://user-images.githubusercontent.com/3639540/133891219-04e7a922-95ed-4dba-9c39-a2a73b225451.png)

I disconnected and reconnected the Trezor, and it was factory reset. I was able to recover my wallet using the mneumonic seed and everything is fine.

**Firmware version and revision**
Upgrading from v2.4.0 to v2.4.2

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor Suite
 - OS: Linux
 - Browser: Brave

**Comment by prusnak** [comment]
Thanks for the report. This was caused by unstable USB connection. So this might've been a cable issue or a browser issue. (Brave is not officially supported).

**Comment by alexgleason** [comment]
Brave sucks, so that adds up.
