### ISSUE TITLE
EIP-1559 is broken in v2.4.2 

### ISSUE THREAD

**Issue by uj** [trezor/trezor-firmware#1817]
**Describe the bug**
Model T, v2.4.2.

Using Matic/Polygon with MetaMask, gets this error:
 "Invalid transaction params: params specify an EIP-1559 trans"

**Desktop/smartphone setup (please complete the following information):**
 - Current version of MetaMask
 - Windows 10 Chrome
 
**To Reproduce**
Try to do anything with the Matic Wallet in MetaMask that requires EIP-1559

**Additional context**
If you use an older version of MetaMask, which uses legacy transactions instead of EIP-1559 transactions, it works as expected.

This has been confirmed on multiple forums by many different people.

Here is a useful post:
https://www.reddit.com/r/0xPolygon/comments/pofr4d/funds_stuck_at_checkpoint_cant_withdraw_error/

**Comment by prusnak** [comment]
Quote from https://www.reddit.com/r/TREZOR/comments/ppbfgo/polygon_bridge_transfers_stuck_due_to_lack_of/hd2h07f/

> However, the corresponding functionality on Metamask side is missing, and there isn't even an issue for it on github. Maybe someone should create one :)
