### ISSUE TITLE
Fails to compile Model T firmware

### ISSUE THREAD

**Issue by ExperiBass** [trezor/trezor-firmware#1836]
**Describe the bug**
I can't seem to compile the Model T firmware. It seems to work and then stops with this error:
```
   Compiling lazycell v1.3.0
   Compiling lazy_static v1.4.0
   Compiling bitflags v1.3.2
   Compiling cty v0.2.1
error[E0463]: can't find crate for `core`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed

```
I ran `rustup target add thumbv7em-none-eabihf`, is there something im missing?

**Firmware version and revision**
None since it didnt compile, but latest master.

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Exodus v21.9.24
 - OS: Arch Linux 5.15.0-rc3-1-mainline
 - Browser: Firefox v92.0.1

**To Reproduce**
1. Follow the compilation instructions for the embedded firmware.

**Expected behavior**
Compilation to complete.

**Comment by ExperiBass** [comment]
Sorry, I recently broke my Linux install and I'm in the process of fixing it

**Comment by ExperiBass** [comment]
ok i finally fixed it! sorry @matejcik  D:

rustc version: 1.55.0
cargo version: 1.55.0

**Comment by prusnak** [comment]
> ok i finally fixed it!

You fixed your installation and you still have the build issue you reported or you fixed the build issue?

**Comment by prusnak** [comment]
What command are you running that results in the reported error?

**Comment by ExperiBass** [comment]
im running `make vendor build_boardloader build_bootloader build_firmware`

**Comment by matejcik** [comment]
I'm going to close this, as searching for the error message suggests that this is a problem with your Rust installation -- crate `core` is a builtin and nothing we do in our code should be able to cause an issue like this.

Looking at `rustup show` might help, also look at https://github.com/rust-lang/rust/issues/63519 for hints.
