### ISSUE TITLE
Device with Shamir backup does not show progress bar

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#1842]
The `progress` callback while deriving seed is completely missing in the Shamir case.

**To reproduce:**

1. configure your device with Shamir backup, e.g., `trezorctl device setup -b shamir`
2. unplug and re-plug the device to clear any caches
3. use the seed, e.g., `trezorctl btc get-address -n m/44h/0h/0h/0/0`

**Expected result:**

Screen shows "Please wait..." and a spinner that slowly fills up.

(see what happens on a device with Standard backup)

**Actual result:**

Screen shows "Please wait..." heading, but the rest of the screen is empty for several seconds until the result is returned.

Related: #671 because repeated derivation of the mnemonic is cached on the C level so the progress bar won't appear the second time.

**Comment by bosomt** [comment]
I was able to reproduce issue with latest dev master commit b6837d19
no spinner in sight during derivation, 

trezorctl get-features
WebUSB transport is disabled: dlopen(libusb-1.0.dylib, 6): image not found
Features (166 bytes) {
    backup_type: Slip39_Basic (1),
    device_id: '397F0ECEE6E3C47D1C9A8B55',
    flags: 0,
    initialized: True,
    language: 'en-US',
    major_version: 2,
    minor_version: 4,
    model: 'T',
    needs_backup: True,
    no_backup: False,
    passphrase_always_on_device: False,
    passphrase_protection: False,
    patch_version: 3,
    pin_protection: False,
    recovery_mode: False,
    revision: 20 bytes 0xb6837d19b7f5227170bcbb7e48e6a6297d4c95cb,
    safety_checks: Strict (0),
    sd_card_present: False,
    sd_protection: False,
    unfinished_backup: False,
    unlocked: True,
    vendor: 'trezor.io',
    wipe_code_protection: False,

**Comment by bosomt** [comment]
**QA OK**

`trezor-fw-regular-2.4.3-221977ad.bin `

major_version: 2,
    minor_version: 4,
    model: 'T',
    needs_backup: True,
    no_backup: False,
    passphrase_always_on_device: False,
    passphrase_protection: False,
    patch_version: 3,
    pin_protection: False,
    recovery_mode: False,
    revision: 20 bytes 0x221977ad9d034a9636db5279b4f1ab4a7d5e9e75,
    safety_checks: Strict (0),
    sd_card_present: False
