### ISSUE TITLE
Cannot use/find hardware wallet address in Metamask. 

### ISSUE THREAD

**Issue by HashBiz** [trezor/trezor-firmware#1850]
**$500 bounty to whoever provides the fix to retrieve my hardware wallet address.**

(I’m not technical, sorry if not explained well).

A simple explanation, I will create a detailed thread if needed:

I have a hardware wallet address in Metamask which I have used for 5 months. One day, I updated the firmware on Trezor, which required to restore it from seed. After restoring, I cannot send transactions from my hardware wallet address in Metamask (https://imgur.com/gallery/IByS3Qr).

On other browsers, i restored my Metamask Wallet from seed and tried to “Connect Hardware Wallet” (https://imgur.com/gallery/NncqScK), but the address is nowhere to be found (https://imgur.com/gallery/lPCAWPm). I then tried to change derivation paths on Metamask (https://imgur.com/gallery/Mg5obTF), but the addresses wouldn’t change so I tried MyEtherWallet, but same result. 

Also, I tried MyCrypto which indeed presented different addresses when changing the derivation path, however, only fresh addresses were shown - not the one I need. 

Additionally, I tried https://findeth.io/flow/address to find how that hardware wallet address was created, but again, no luck. 

Finally, I also tried to downgrade my Metamask version to 9.8.4, but my address still wouldn’t show up after clicking “Connect Hardware Wallet.”

 - Wallet software: Trezor Wallet/Trezor Suite & Metamask
 - OS: Windows
 - Browser: Brave, Chrome & Firefox
 - Version: All up to date versions as of 14/10/2021.

**Only viable explanations I can come up with:** 

- The Trezor firmware update somehow messed with my seed.

- Trezor previously converted that seed to a public key differently.

- The hardware wallet address in question was not created from the seed that I have (very very unlikely).

- The hardware wallet address was created from the seed that I have, but additionally there was a passphrase (impossible).

**Things to note:**

- My Trezor seed is 100% correct. All hard copies I created when I first set up my Trezor match and say the same thing. 

- Even if i somehow noted down the wrong seed phrase when I set up my Trezor 1.5 years ago (which is very very unlikely), I created the said hardware wallet address 5 months ago on Metamask. The address would be linked to the “incorrect” seed phrase - which I have noted down and have been using this entire time. 

- My Metamask seed is 100% correct. All hard copies match.

- I still have access to the “missing” & inaccessible hardware wallet address in Metamask on Brave, but it cannot sign any transactions.

**Comment by fili777** [comment]
did you solved it?? I have the same problem, my address was gone ...

**Comment by lf94** [comment]
@fili777 and @HashBiz I can probably help you - I thought the same happened to me awhile ago but it has to do purely with derivation paths. As long as you still have the same seeds you should absolutely be able to recover. 

If I recall correctly there are parameters which are erased from Metamask when re-initializing, and those parameters may be lost, but are easy to iterate over. I will reply with details over the weekend but I just wanted to give you both a heads up to not panic. I don't even want the money, but instead want to just increase trust in the system.

**Comment by fili777** [comment]
Thank for the hope, just let me know what to do, because I tried everything already. 
It would be nice if you can solve, I can give you a nice gift as reward.

**Comment by lf94** [comment]
I'm looking into it now. What version of Metamask did you use?

**Comment by fili777** [comment]
14,0

**Comment by lf94** [comment]
I know it's very old but please try something like this https://github.com/MetaMask/metamask-extension/releases/tag/v7.5.1 .

I'm arbitrarily picking something from the past, hoping the behavior is closer to what was experienced when the trezor was used with it. Unfortunately today I tried to build metamask locally but my mobile machine is too weak. I will only be able to try again next weekend.

**Comment by fili777** [comment]
So, just install this version is what you suggest me, and Trezor will
recognise the missed wallet? Or do I have something else?
Thanks for your help

**Comment by lf94** [comment]
Trezor will not recognize the missed wallet, but you will have to re-import the hardware wallet. I'm currently trying to re-create the issue so I really understand what could be happening. I remember awhile ago that there were two ways to import a hardware wallet, and if you didn't save your parameters it could be lost but retrievable with some changing of data.

**Comment by fili777** [comment]
Just tried and it didn’t work. Thanks
