### ISSUE TITLE
Crypto functions fail on big-endian systems

### ISSUE THREAD

**Issue by 2128675309** [trezor/trezor-firmware#1869]
**Describe the bug**
Multiple implementations in crypto/ do not produce correct calculation on big-endian systems, due to implementation assumptions that only work on little-endian.

I am using trezor-firmware/crypto/ on an IOT device that happens to be big-endian, and it is producing incorrect cryptography results.  Failures are verified via `test_check`.

**Firmware version and revision**
Github master branch latest checkout

**To Reproduce**
Build `test_check` on a big-endian system and then run it.
```
export CFLAGS="-DSPH_BIG_ENDIAN=1 -DSPH_LITTLE_ENDIAN=0 -DBYTE_ORDER=BIG_ENDIAN"
make tests/test_check
tests/test_check
```

`test_check` reports 81% success, 28 failures in areas of sha3, blake2b, blake2s, monero.  They are all traced back to hardcoded little-endian assumptions.

**Expected behavior**
Expect `test_check` to have 100% success

**Additional context**

Pull request / fix already submitted: https://github.com/trezor/trezor-firmware/pull/1868

That patch provides `test_check` 100% success on big-endian systems.

**Comment by prusnak** [comment]
Closed via https://github.com/trezor/trezor-firmware/pull/1868
