### ISSUE TITLE
Dry-run recovery

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#187]
# Steps to reproduce issue 

https://blog.trezor.io/test-your-seed-backup-dry-run-recovery-df9f2e9889

# Expected result 
 If the seeds match, the TREZOR Wallet will tell you your backup is okay. If it is not the same, then the Wallet will show you an error.

# Actual result 
freezing issue

# Other information 
- Reported by: Daria Roik 

- Test case number: TC03 

- Test run: [https://satoshilabs.testlodge.com/projects/32891/runs/399820?tab=2&run_section_id=582320#executed_case_17250491](https://satoshilabs.testlodge.com/projects/32891/runs/399820?tab=2&run_section_id=582320#executed_case_17250491)

**Comment by bosomt** [comment]
duplicity

**Comment by pankrats** [comment]
Sorry, false alarm

**Comment by bosomt** [comment]
An associated test has been re-run in TestLodge. 

**Result:** Skipped 

**Other information** 

- Update by: Sebastian Soroori 

- Test case number: TC03 

- Test run: https://satoshilabs.testlodge.com/projects/32891/runs/400303?tab=2&run_section_id=582968#executed_case_17272371
