### ISSUE TITLE
Device does not react when Simplestaking wallet asks to verify receive address

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-firmware#1878]
**Describe the bug**
When looking at receive address in Simplestaking wallet, wallet informs informs user, after clicking on Receive funds, to interact with the device saying "Password is required. Please wait for Trezor to start.". Device does not react, and user cannot reveal the receive address this way, it has to be manually copied from Wallet page without the verification.

**Firmware version and revision**
Describe firmware version and revision you are using when encountering the bug.

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: SimpleStaking Wallet  (web version)
 - OS: Windows10
 - Browser Chrome Version 95.0.4638.54 (Official Build) (64-bit) + trezord 2.0.27
 - Version TT 2.4.3 regular 47e17aab4d195e380a75bbd9a103f6507c9abd16

**To Reproduce**
1. Go to simplestaking wallet browser version
2. Access accounts from HW 
3. Click on Receive funds
4. Choose the account
5. Wait for "Password is required. Please wait for Trezor to start." message.
6. Wait forever?

**Expected behavior**
Device reacts and shows the receive address.

**Screenshots**
![image](https://user-images.githubusercontent.com/58593111/139487877-d0567cb9-3f58-4214-99c2-32e4432051ce.png)

**Video:** [here](https://watch.screencastify.com/v/IDDe1QkhQUCfPNMdwBBt)

**Comment by matejcik** [comment]
Is this a regression? i.e., does the same thing work with older firmware?

my first guess would be a problem in SimpleStaking

**Comment by wendys-cats** [comment]
Checked, also present with 2.3.6, 2.3.0, 2.1.6. Should be inform simplestaking?

**Comment by matejcik** [comment]
if we have a good way to contact them, yes

i'm closing the firmware issue as this is apparently not a regression and very likely not a problem on our end
