### ISSUE TITLE
"Verify message" does not display result on screen

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#1880]
This is the result of a counterintuitive flow: Trezor first verifies the message, and _only if the signature is OK_, shows the message and address on screen.

So if I'm seeing the message on Trezor screen, that means the signature is OK. An attacker cannot abuse this to claim that a bad signature is OK.
(They could abuse this to claim that an OK signature is bad, BUT they can do that anyway by corrupting the signature.)

However, from the user's point of view, the Trezor _never says that the signature is ok_.

A very simple improvement is to stick a pop-up "Signature is OK" at end.

In the new UI design, we might consider showing the message even if the signature is bad, so that the user gets feedback in such case. Currently, Trezor doesn't show anything and only Suite shows the failure.

**Comment by bosomt** [comment]
**QA OK**

`Signature is OK` displayed on both models

1.10.6 revision: 20 bytes 0x0e27423cffb3b6047028c61890bec43bf626adc7,
2.4.4 revision: 20 bytes 0x0e27423cffb3b6047028c61890bec43bf626adc7
