### ISSUE TITLE
los funds with MetaMask using avalanche chain with trezor

### ISSUE THREAD

**Issue by fili777** [trezor/trezor-firmware#1912]
los funds with MetaMask using avalanche chain with trezor

I tried to scan to address with crypto and findeth

scanned also with ledger with the same seed and trezor in metamask

looks like the address disappeared from my seed. 

i didn't use any passphrase

**Comment by matejcik** [comment]
Duplicate of #1910, which is a duplicate of #1850 

Please don't open more issues about the same thing.
