### ISSUE TITLE
Port to Raspberry Pico

### ISSUE THREAD

**Issue by willianpaixao** [trezor/trezor-firmware#1919]
Hi,

as a pet project, I've been porting basic features of the firmware to RP2040, Raspberry Pico's microcontroller.
Mostly the basics, key and mnemonic generation, key derivation, display addresses.

And as I believe this can Raspiberry's developer community into Trezor's codebase, I'd like to ask if those small patches (to the firmware) could be merged to this repository. In another word, if I send PRs would they be accepted?

**Comment by matejcik** [comment]
what sort of modifications would that be?

**Comment by marssystems** [comment]
Take a look at https://pitrezor.com which is a port to a raspberry pi zero and 4B.

**Comment by willianpaixao** [comment]
@matejcik so far has been adding something like

```c
#if defined(RASPBERRYPI_PICO)
#include "pico/stdlib.h"
#endif
```

To later use a function from its library.
Reference [here](https://raspberrypi.github.io/pico-sdk-doxygen/).

@marssystems yes, I know that project for a long time. But this is a little different, since both Pis are running Linux, while Pico is running a bootloader/firmware pretty much like Trezors.

**Comment by matejcik** [comment]
we can continue the discussion but i will close this issue for bookkeeping purposes

**Comment by prusnak** [comment]
I guess you want to include `"pico/stdlib.h"` in order to use some functions from that.

Can you indicate how will the changes look when using these functions?

**Comment by daxime** [comment]
Hi,
is there any progress in the porting on the Pico ?
