### ISSUE TITLE
Test the display

### ISSUE THREAD

**Issue by jpochyla** [trezor/trezor-firmware#192]
Let's add UI integration tests that compare all individual screens rendered in a test run against some expected output. It shouldn't require any changes on the `core` side.

1. In debug unix build, and if environment variable `TREZOR_SAVE_SCREEN` is set to non-zero, each screen change is saved into `$cwd/refresh_$counter.png`.
2. The test runner should gather the screens after each test and compare them against some fixtures committed inside the repository.

**Comment by tsusanka** [comment]
Related: https://github.com/trezor/trezor-firmware/pull/431

**Comment by tsusanka** [comment]
I have applied two fixes:

- skip when default task is running
- turn off Swipe button pulsing in debug (to be discussed)

Tests that are still failing:
- tests/device_tests/test_reset_recovery_slip39_advanced.py
- tests/device_tests/test_reset_recovery_bip39.py
- tests/device_tests/test_reset_backup.py

Might be solved by using `random_seed`, investigating further.

**Comment by tsusanka** [comment]
Hm this is probably true only for random-order-seed=0, there are more tests failing otherwise.

**Comment by tsusanka** [comment]
Closed by https://github.com/trezor/trezor-firmware/pull/784
