### ISSUE TITLE
Release `trezorctl` with taproot support

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#1923]
also ensure Electrum compatibility, etc.

**Comment by prusnak** [comment]
> also ensure Electrum compatibility, etc.

JFYI Electrum does not support Taproot yet and there is no ETA: https://github.com/spesmilo/electrum/issues/7544

However, there are some minor features (e.g. BTC/mBTC/uBTC/sats denomination selection, etc.) that are not present in 0.12.4 and Electrum would benefit from 0.13 release.

**Comment by matejcik** [comment]
fixed in #2004 
Electrum PR pending in https://github.com/spesmilo/electrum/pull/7590
