### ISSUE TITLE
Measure and plot code coverage

### ISSUE THREAD

**Issue by jpochyla** [trezor/trezor-firmware#193]
Running the test suite should output a code coverage document, describing the places in the codebase that were executed.

- Depends on #181 for monitoring the `core` code.
- Do we want to also measure the `python` side of things? @matejcik 
- Theres probably a lot of python code coverage infrastructure available (generating the reports etc.), can we use it with our monitoring code?

**Comment by matejcik** [comment]
it's already easy to generate coverage report from pytest run, with `pytest-cov` and `coverage`. having this automated would be nice.
