### ISSUE TITLE
Run Connect tests against our branches in CI

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1932]
Add jobs to our CI that would run the current firmware against Connect master. Let's also discuss what jobs should be run on every push.

Maybe let's do this along with https://github.com/trezor/trezor-user-env/issues/49.

**Comment by hynek-jina** [comment]
Blocked by https://github.com/trezor/trezor-user-env/issues/49

**Comment by grdddj** [comment]
This could be theoretically closed, as the `Connect` tests were already added into our `CI` in above-mentioned https://github.com/trezor/trezor-firmware/pull/1972 @hynek-jina @matejcik (if we do not want any improvements over current situation)

**Comment by matejcik** [comment]
right, let's close this
