### ISSUE TITLE
Package ‘libcxx-13.0.0’ in /nix/store/.../llvm/13/libcxx/default.nix:42 is marked as broken, refusing to evaluate

### ISSUE THREAD

**Issue by Sjors** [trezor/trezor-firmware#1934]
**Describe the bug**
`nix-shell` fails with an error about a broken llvm package.

**Firmware version and revision**
Master branch at d448d7b8416f2ee985ed078f482bf05ac49214c3 with up to date submodules.

**Desktop/smartphone setup (please complete the following information):**
 - OS: macOS Monterey 12.0.1
 - NixOS 2.4

**To Reproduce**

- `git submodule update --init --recursive --force`
- `poetry shell`
- `nix shell`

**Comment by prusnak** [comment]
Yes, I encountered this as well. Clang is broken on macOS darwin unfortunately.

Checkout this commit and it should work: 6eac12e80e622298d9f9f6a1a1aca7df55e69860

**Comment by hynek-jina** [comment]
This issue should be solved by upcoming release.

**Comment by prusnak** [comment]
It's not fixed yet, so please, let's keep this open.

**Comment by prusnak** [comment]
Fix in https://github.com/trezor/trezor-firmware/pull/1968

**Comment by prusnak** [comment]
> Fix in #1968

Edit: we will need to resolve this differently (wait until staging is merged into master in nixpkgs).

**Comment by prusnak** [comment]
Another PR in https://github.com/trezor/trezor-firmware/pull/1969
