### ISSUE TITLE
Add nightly job to build PRODUCTION versions

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#1937]
To make sure this doesn't bite us next time, we should periodically build the "full" firmware with `PRODUCTION=1`. There might be slight differences in what gets included compared to the usual unsigned firmware.

We _prooobably_ don't need this in every pipeline, so a nightly job that builds everyting (legacy, core firmware, core bootloader and boardloader separately maybe?) and makes sure it does build.

**Comment by yura-pakhuchiy** [comment]
Building tagged releases with `PRODUCTION=1` will provide additional source for fingerprint verification.
