### ISSUE TITLE
06/2019 Changelog

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#196]
### Firmware

* no release

### Bootloader

* no release

### Firmware

**To be released version 2.1.1**

*Most of the following points are from the previous 05/2019 sprint where we decided not to release eventually.*

User facing news:

* Tezos voting (trezor/trezor-firmware#41)
* fix swiping during cardano transactions signing (trezor/trezor-core#497)
* swiping now does not rotate screen, you have to use trezorctl and the setting is stored (trezor/trezor-core#162)
* improved UI messages in dry run recovery (trezor/trezor-core#534)
* hotfix freezing (https://github.com/trezor/trezor-firmware/issues/22, trezor/trezor-core#509, https://github.com/trezor/trezor-firmware/issues/144)
* **Monero fixes and UI improvements**
* fix flickering screen during PIN verification (trezor/trezor-core#495)
* ripple QR fix (#191)
* Cardano: small optimilization, which allows more inputs in a transaction (https://github.com/trezor/trezor-firmware/pull/130)

Internal ones:
* HID bridge for U2F testing
* Display Custom Locktime On Trezor when provided unusual locktime (trezor/trezor-core#506) (shouldn't concern traditional users)
* Path validation improved.
* secp256k1_zkp module
* U2F response properly zeroed (trezor/trezor-core#529)
* **SLIP-39 crypto** (the basic underlying work by Andrew)
* **EOS** (but no wallet yet)

More details in the [2019/05](https://github.com/trezor/trezor-firmware/milestone/3?closed=1) and [2019/06](https://github.com/trezor/trezor-firmware/milestone/2?closed=1) milestones.

### Bootloader

* no release

**Comment by prusnak** [comment]
Released
