### ISSUE TITLE
Options for saving T1 bootloader flash space

### ISSUE THREAD

**Issue by hiviah** [trezor/trezor-firmware#1962]
Currently we have a bit over 1100 B free in T1 bootloader after merging #1957.

Here is summary of options we have if we exceed the space in future:

* use slower `bn_inverse`, saves 700 B, but since there are 3 `ecdsa_verify_digest`, it would add about 0.5s on start (#1951 )
* freeze intermediate FW, drop `signatures_old_ok` checks, which means you should upgrade from very old FW versions only via the intermediate FW (through Suite), otherwise doing upgrade-downgrade-upgrade would erase seed; would save about ~200 B
* save space on icons somehow, for example the four gear icons have 1152 B in total
* use gcc 8 for build as workaround since it generates smaller code - may force us to upgrade if there is some bug later whose fix is not backported
* downgrading `-fstack-protector-all` to `-fstack-protector-strong` does significant size difference, 32668-28600=4068 B (gcc 10.2.1). Stack protector prelude is 36 bytes for a function.

It is not clear yet if we'd open up some attack vector by using "weaker" stack protector - everything is statically allocated, there is no heap, so no heap spraying possible. Any function that works with array or takes local address is also protected under "strong" version.

**Comment by matejcik** [comment]
Closing as this is not actionable right now. The information was copied over to Notion for reference.
