### ISSUE TITLE
./build-docker.sh dont work

### ISSUE THREAD

**Issue by behnamkk70** [trezor/trezor-firmware#1982]
when run ./build-docker.sh 
i have error
 ./tools/build_templates
Traceback (most recent call last):
  File "./tools/../vendor/trezor-common/tools/cointool.py", line 12, in <module>
    import click
ModuleNotFoundError: No module named 'click'

**Comment by prusnak** [comment]
This is not a support portal. Please join our community discussion on Gitter to get help with building our project: https://gitter.im/trezor/community
