### ISSUE TITLE
Test each and every operation in Stellar

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#2]
Some operations are not tested. I belive those are:

- StellarAllowTrustOp
- StellarPathPaymentOp
- StellarChangeTrustOp
- StellarCreatePassiveOfferOp
- StellarManageDataOp
- StellarManageOfferOp
- StellarPathPaymentOp

Could avoid https://github.com/trezor/connect/issues/382

**Comment by ZdenekSL** [comment]
Please, test all the scenarios above. Meet with @tsusanka if necessary.

**Comment by tsusanka** [comment]
Here by "tests" we mean automatic tests, sorry about that. Some operations are missing, see https://github.com/trezor/trezor-firmware/blob/master/python/trezorlib/tests/device_tests/test_msg_stellar_sign_transaction.py
