### ISSUE TITLE
ed25519-donna refactoring

### ISSUE THREAD

**Issue by onvej-sl** [trezor/trezor-firmware#20]
It's pain to write code using `ed25519-donna` since:
  * It's a one-purpose library aiming only at signing, verifying and performing Diffie-Hellman key exchange.
  * It has almost no abstraction for other functions (especially for private and public key operations).
  * It uses several number and point representations. 
  * It's badly documented. In particular, it's not clear what representations of inputs and outputs of functions are used.
  * It's difficult to review any code using the library.

I suggest creating a well-documented abstraction for private and public key operations.

**Comment by ZdenekSL** [comment]
Out of scope for now.
