### ISSUE TITLE
TREZER MODEL ONE NOT DETECTED

### ISSUE THREAD

**Issue by Zabbb** [trezor/trezor-firmware#2010]
**Describe the bug**
Hello so I have been using Trezer model one mainly for securing my ronin wallet so there has been an issue where in my trezor one model is not detected when specifically transferring an axie or any other erc-721 assets. Transferring of erc-20 tokens and logging in inside axie infinity is working properly using trezor.

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor One
 -  - OS:  Windows
 - Browser Brave, chrome
 - Version v 1.32.115

**To Reproduce**
1.  Log in into Axie Infinity marketplace
2. Try transferring an axie
3.  Sign thru ronin
4.  Sign thru trezor

**Expected behavior**
The trezor wallet should be detected and will be able to sign the transaction. But instead what happened is the trezor is not detected and was showed only as "Connect your wallet" on the page when it is refreshed in remains on loading.

**Comment by matejcik** [comment]
Hello, please open a support ticket through https://trezor.io/support, or refer to one of the many threads on this topic on the Trezor forum at https://forum.trezor.io
