### ISSUE TITLE
Broken links in changelogs

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#2011]
Github stopped redirecting from
e.g. [`https://github.com/trezor/trezor-firmware/issues/1227`](https://github.com/trezor/trezor-firmware/issues/1227)
to
[`https://github.com/trezor/trezor-firmware/pull/1227`](https://github.com/trezor/trezor-firmware/pull/1227)
😢 
(the other direction still works) 

We kind of relied on it in our changelogs as we always used the `/issues/` in our changelog URLs.

What needs to be fixed now:
 
- [ ] fix links in `core/CHANGELOG.md`
- [ ] fix links in `legacy/firmware/CHANGELOG.md`
- [ ] fix links in `python/CHANGELOG.md`
- [ ] update `tools/generate-changelog.py` to generate `/pull/` in the URL instead of `/issues/` when the referenced number is PR and not an issue

The rest of the changelogs do not contain broken links.

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this. Is there anyone doing it already?

**Comment by prusnak** [comment]
@Carlosbogo Not at this moment, please, go ahead!
