### ISSUE TITLE
EOS get-public-key options

### ISSUE THREAD

**Issue by cryptosig** [trezor/trezor-firmware#202]
Is it possible to have the trezorctl have options for returning a public key? Currently it accepts only a path, ie "m/44'/194'/0'/0/0", however is it possible to have it derive the address from a secondary optional parameters account name and key type. Such that I could ask the trezor to provide the public key in the following way:
```
trezorctl eos-get-public-key --account miniminimini --permission owner 

outputs:
Path: "m/44'/194'/x'/x/0"
WIF: EOS5PHaHGMyioSzWCjY84PFiZ6Mnn6KzY5by5G5v42AZeiaKzHzd8
Raw: 0241630cd74930361f2b90a07109ea614f0649c07ef52206891119cddc1ae4f5ff
```
or
```
trezorctl eos-get-public-key --account miniminimini --permission active

outputs:
Path: ""m/44'/194'/x'/x/1"
WIF: EOS8LhNcJV741ENnmMmC7ivRfcpyCQY9jdS433mJPQyk9aZ7AhBAZ
Raw: 03c6985372af863e1380ab893450d62d3fb2d53900018db2a031b93fe07cefc812
```

I realize this gets into some slip and bip44 stuff, because the name has to be hashed into a hardened path, so it may need more discussion.

**Comment by prusnak** [comment]
Unless this is standardized somehow (and this will never become a part of BIP44) I don't see this ever becoming a functionality of trezorctl. You might want to have a look at https://github.com/satoshilabs/slips/blob/master/slip-0048.md and discuss within your EOS community how to standardize this. Once standard is adopted, we can talk about implementation.
