### ISSUE TITLE
There was an error with your transaction. Please try again.  Opensea - Polygon

### ISSUE THREAD

**Issue by forexpiphunter** [trezor/trezor-firmware#2021]
I'm getting an error message "There was an error with your transaction. Please try again." when I sign a transaction on Opensea to sell my NFT on the Polygon network

**Firmware version and revision**
2.4.3

**Comment by prusnak** [comment]
I suppose you are using Metamask. Are you on the latest version of Metamask - that is 10.8.0 ?

**Comment by forexpiphunter** [comment]
Correct, 10.8.0

**Comment by prusnak** [comment]
In that case, please contact Metamask support.
