### ISSUE TITLE
Firmupdate broke the Metamask integration

### ISSUE THREAD

**Issue by Chuckie-Droid** [trezor/trezor-firmware#2022]
After the newest firmupdate, I'm not able to send funds from my trezor wallet to another via the Metamask browser extension.

**Firmware version and revision**
Describe firmware version and revision you are using when encountering the bug.

**Desktop/smartphone setup (please complete the following information):**
Metamask
Ubuntu 20.10
Brave
V1.33.106

1. Connect your trezor wallet to the metamask browser extension
2. Select your trezor wallet in metamask
3. Click on "send"
4. choose a wallet and enter an amount
5. get redirected to trezor to confirm the transaction with your pin and stuff
6. Optional: enter your passphrase
7. metamask browser window closes and you're not able to reopen metamask again until restart
8. transaction didnt go through even after waiting for a bit

I clearly expected my transaction to go through, another behaviour is not acceptable.

**Comment by prusnak** [comment]
Please update Metamask to the latest version 10.8.0. If you are on the latest version and still see the issue, please report it to the Metamask issue tracker here: https://github.com/MetaMask/metamask-extension
