### ISSUE TITLE
Trezor T countdown stuck during 15th wrong PIN timeout

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-firmware#203]
TT fw 2.1.1 (50cb440d), PIN on

**Steps to reproduce:**
- enter wrong PIN and wait for the timeout to end
- enter wrong PIN again (14 more times)
- observe
Note: because of the time-consuming nature of this bug I haven't reproduced it again, yet.

**Expected:**
The verifying PIN screen during timeout runs smoothly until the PIN entry screen is displayed again.

**Actual:**
Countdown got stuck during the 15th time (16384s timeout) at about 14000s mark
without touching the display.

**Comment by pankrats** [comment]
Finally tested this on fw 2.1.2 (ver 50f16366). I input the wrong PIN all 15 times till the device was wiped - noo freeze happened.
