### ISSUE TITLE
Move trezorlib/tests to root tests

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#208]
Tests that are common for T1 and T2 should be moved from `python/trezorlib/tests` to a seperate root directory `tests/` (e.g. burn tests, device tests..). Any objections against this?

**Comment by matejcik** [comment]
noting here that shamir-mnemonic and probably other deps might be moved out of python/setup.py when this is done

**Comment by tsusanka** [comment]
@matejcik didn't we forget to close this?

**Comment by matejcik** [comment]
fixed in master
