### ISSUE TITLE
[Feature] Allow (encrypted) SD card as a possible passphrase source on TT

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-firmware#2080]
As recent updates to Trezor Suite have enabled passphrases by default, more and more users are getting hit with off-by-one passphrase errors.  In an attempt to be more secure, users are choosing randomly generated Ascii85 strings instead of a safer diceware passphrase approach.  These user-generated random strings get more and more difficult to maintain and often users will transpose a single character (off-by-one) and not realize it.

The proposal is to expand the current passphrase sources, "device" and "host", to include a third choice "sd-card".  This choice would be added in the [Trezor Connect Popup dialog](https://github.com/trezor/connect/blob/b6aa014/src/html/popup.html#L235).  If "sd-card" passphrase sourcing is chosen, then an encrypted database would be read from the SD card at `/trezor/device_?????/passphrase.dat`.  The encryption of the database could be a combination of the seed-mnemonic and SD-Card salt file, though this would require `sd-protect` be enabled.

The passphrase database would contain a set of key-value pairs.  A passphrase label / hint and passphrase cipher text.  Though care should be given to remind the user to label passphrases in a way that doesn't leak data.  Once the database is parsed, the TrezorDevice simply displays the passphrase labels / hints for the user to select.

Pairing this feature with `sd-protect` is the most logical choice since `sd-protect` already encourages users to separate the TrezorDevice and sd-card when at rest.  Obviously if a user lost the TrezorDevice AND the sd-card, the attacker could proceed with a `wallet.fail` attack to gain seed-menmonic and passphrase.  If this risk is deemed to severe then the passphrase database could use a PIN in conjunction to the other secrets to decrypt the `passphrase.dat` file.

To populate `passphrase.dat` a new command will be added to `trezorctl` in the form of `trezorctl set passphrase --cached`.  This would trigger an on-device passphrase entry that will need to be done twice to ensure data-match.  Then an on-device dialog to provide a label/hint for the passphrase entry.

This feature would essentially provide passphrase functional parity with ColdCard.

**Comment by Hannsek** [comment]
Thanks for the issue. I am closing it as We are not expecting to work on anything regarding SD card soon. Feel free to continue the discussion below.
