### ISSUE TITLE
Ed448 - Goldilocks

### ISSUE THREAD

**Issue by raisty** [trezor/trezor-firmware#21]
Is Ed448 - Goldilocks implemented?
Some plans to do so?

I found out Ledger has support already: https://www.ledger.com/2018/03/06/new-firmware-update-1-4-1-available-for-the-nano-s/

**Comment by prusnak** [comment]
Not planned at the moment

**Comment by raisty** [comment]
Not in the roadmap? I can assist and help 🔨

**Comment by prusnak** [comment]
Send a Pull Request

**Comment by raisty** [comment]
Sure, we will contribute to this great project. Please, be patient with us. We are implementing whole cryptography and then propose integration.
