### ISSUE TITLE
Support Electrum signatures in VerifyMessage

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#2100]
Trezor supports message signing and verification in accordance with [BIP-137](https://github.com/bitcoin/bips/blob/master/bip-0137.mediawiki). The spec includes script type information to the first byte of the signature. Electrum does not include the script type information in the signature and is unable to verify message signatures produced by Trezor unless the `no_script_type` flag is set to `true` during signing (or unless the information is manually removed from the first byte). Similarly Trezor is unable to verify signatures generated by Electrum.

The script type information is actually not required in order to be able to verify the signature if the address is available to the verifier. In the case of Trezor the `address` field is required in `VerifyMessage`, so there is no reason why Trezor couldn't verify signatures generated by Electrum.

**Comment by bosomt** [comment]
**QA OK**

_message generated via T1 latest public version in Electrum 4.1.5_

**T1 1.10.6 0x0e27423cffb3b6047028c61890bec43bf626adc7**
Signature is valid + `Message verification successful`
**TT 2.4.4 0x0e27423cffb3b6047028c61890bec43bf626adc7**
Signature is valid + `Message verification successful`

_message generated in Electrum 4.1.5 from standard local wallet_

**T1 1.10.6 0x0e27423cffb3b6047028c61890bec43bf626adc7**
Signature is valid + `Message verification successful`
**TT 2.4.4 0x0e27423cffb3b6047028c61890bec43bf626adc7**
Signature is valid + `Message verification successful`

only way to generate signed message via Trezor was 1.10.5  T1 firmware version
