### ISSUE TITLE
Add support for TON Token (TON)

### ISSUE THREAD

**Issue by VadimChiritsa** [trezor/trezor-firmware#2145]
Is your feature request related to a problem? Please describe.
As a [TON](https://ton.org/) (TON) user I would like to store TON coins on my Trezor Model T.

Describe the solution you'd like
The Trezor firmware supports 3rd party wallets for TON.

Additional context
https://ton.org/

**Comment by prusnak** [comment]
We are currently not interested in adding coins that are not in the TOP 30 on Coinmarketcap. Should this situation change in the future we might reconsider.

**Comment by master88wi** [comment]
pls add toncoin

**Comment by chelsenok** [comment]
@prusnak 
Sep 2023 update.

TON coin market cap: $7,661,749,684

10th place.

**Comment by master88wi** [comment]
TON coin up
