### ISSUE TITLE
Show path for internal outputs in BTC signing for Model T

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#2152]
When Trezor signs a transaction which is transferring BTC to another of the user's own accounts, it requires user confirmation of the destination address even if the destination account is under the same seed and passphrase. Trezor T doesn't show any indication that the address belongs to the user. Trezor 1 handles this better. It requires the user to confirm the output, but adds information that it belongs to the user’s own legacy/SegWit/Taproot account #...

![image](https://user-images.githubusercontent.com/42678794/156577290-84c6488a-355c-4f6d-a20c-1cc2d14fdee9.png)

We should add the same feature in Trezor T. This will facilitate account migration from old account types to Taproot accounts, which is especially interesting for CoinJoin. We need to figure out how to fit this information on the confirmation screen, which is already quite full:
![image](https://user-images.githubusercontent.com/42678794/156578685-fe5a159d-1608-42f3-9317-c99219531595.png)
For internal outputs we could:
- <s>remove the address and show only the human readable account description `BTC Taproot account #1`,</s>
- show both the address and account, but shorten the address to two/three lines max with `...`,
- <s>show both the address and account in full and split over multiple pages if necessary.</s>

**Comment by sime** [comment]
Answering my own question, on the 'from' screen will show the amount.

**Comment by matejcik** [comment]
this is a great point, I didn't realize that the designs don't have the separate amount screen.
but I believe it was there at some point?
one total amount is not enough if you have multiple recipients

**Comment by andrewkozlik** [comment]
We certainly need to show the amount for each output, but to be clear I think both address and amount should be on one confirmation dialog, so that it's obvious to which address the amount belongs. (The dialog can be scrollable to multiple screens.)

I think we said that we don't need to show the currency in the account name "BTC L. SegWit" since the currency is the same for the entire transaction.

**Comment by sime** [comment]
Paying to self screen with amount included.

![tt-paying-to-self](https://user-images.githubusercontent.com/216917/171186769-cd298586-7431-4360-a64c-5fb63e1a8ef7.png)

**Comment by matejcik** [comment]
that works for pay-to-self but not for pay to others, where you want to show the full address.

**Comment by sime** [comment]
The following is the alternative. It can be used for both use cases. Paying to self and others. When paying others, omit the last line, and complete the address.

![tt-pay-to-everyone](https://user-images.githubusercontent.com/216917/171203593-4f1ab35d-dde1-416c-9d78-8626c39654be.png)

**Comment by Hannsek** [comment]
I think that the user should be able to see the whole address, no matter where he sends his money. I believe that we can put the account name right behind the address. If it won't fit on one screen, user will "scroll" to the second screen and pres `next` `(confirm) ` on the second screen.





![Image](https://user-images.githubusercontent.com/57008159/211752402-a005e7ea-7769-4b05-8d60-8d31bc5229d0.png)

**Comment by andrewkozlik** [comment]
How about putting the account name at the top? It makes it more descriptive:

![image](https://user-images.githubusercontent.com/42678794/211772457-bdca7c82-ec1a-4eea-bb95-64b8c73ee6dc.png) or ![image](https://user-images.githubusercontent.com/42678794/211778815-38006119-a16a-4b87-b149-f7e26f2e6220.png)

> I think that the user should be able to see the whole address, no matter where he sends his money.

Actually AFAIK the largest addresses are 4 lines, except for Monero, which have six lines. So there should be no need for scrolling as long as the whole description takes at most 2 lines, which it will if we merge it with the "To:".

**Comment by Hannsek** [comment]
The only thing that I have concern about is that it will disturb the "classic" design while adding it at the end of the address won't disturb it. But it would be strange to have only the name of the account on the second screen (with taproot addresses). Let's put it in front of addresses, but on the new line.
<img width="653" alt="image" src="https://user-images.githubusercontent.com/57008159/211787155-d2193635-6007-46ab-ad31-f8e7a7d93944.png">

**Comment by Hannsek** [comment]
Related to https://github.com/satoshilabs/trezor-firmware/issues/93 and https://github.com/trezor/trezor-firmware/issues/2151.

**Comment by Hannsek** [comment]
https://github.com/trezor/trezor-firmware/issues/2680 related

**Comment by Hannsek** [comment]
Done in https://github.com/trezor/trezor-firmware/pull/2925
