### ISSUE TITLE
Revise path warning

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#2161]
When a non-standard BIP32 path is used for a particular coin and script type Trezor shows a warning. This usually pops up at the user at the beginning of the workflow and doesn't say much to someone who isn't expecting it. Also, T1 doesn't show the actual path. We should revise the wording and content of the dialog. Suggestions:
1. "Path m/86'/0'/0'/0/0 does not match the selected coin and script type. Continue?"
2. "Unknown path m/86'/0'/0'/0/0 for the selected coin and script type. Continue?"

We should also investigate to make sure the wording makes sense everywhere the dialog is used. For example in some altcoins it might be more like "does not match the selected network".

<img src="https://user-images.githubusercontent.com/42678794/157211144-02278eb6-f0b2-40fc-86a1-7da4a6b4539a.png" width="256"/> ![image](https://user-images.githubusercontent.com/42678794/157211212-15abbcc8-9559-409c-ac21-4bcfd61ef1e5.png)

**Comment by matejcik** [comment]
I would use "account" or "account type" in place of "script type", because that seems more legible to the end user.

Perhaps something like "wrong address path for selected account" covers Bitcoin and altcoin usecases equally?

**Comment by pedromtcosta** [comment]
I'm sorry if this is not the right place to ask, but isn't `86' /0' /0' /0 /0` a correct path for taproot?

**Comment by andrewkozlik** [comment]
> I'm sorry if this is not the right place to ask, but isn't `86' /0' /0' /0 /0` a correct path for taproot?

It is correct for Taproot, but it wouldn't be correct if the specified script type was legacy or SegWit v0 for example.

**Comment by matejcik** [comment]
@Hannsek I believe we have some designs ready for this, no?
i would love to get this done if so

**Comment by Hannsek** [comment]
We have, I'll post them here.

**Comment by Hannsek** [comment]
Here it is: <img width="278" alt="image" src="https://user-images.githubusercontent.com/57008159/232433604-3068cb8d-823c-45dd-bbe1-d6a9184f7a31.png">

**Comment by Hannsek** [comment]
![image](https://github.com/trezor/trezor-firmware/assets/57008159/f86a44a4-9875-4f48-9863-ae03893d0124)
Updated screen.

**Comment by matejcik** [comment]
(Please remove the exclamation mark from "account!". Nowhere else we shout at the user, and there is already a "!" in the icon.)

**Comment by Hannsek** [comment]
Isn't this done already? @mmilata
