### ISSUE TITLE
Upgrade to isort 5

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#2173]
https://pycqa.github.io/isort/docs/major_releases/introducing_isort_5.html
https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0.html

It might be possible to use one of the new isort profiles instead of our custom configuration.

**Comment by AdarshRawat1** [comment]
Can I work on this issue?

**Comment by matejcik** [comment]
please go ahead!

**Comment by AdarshRawat1** [comment]
Could you provide some direction on where to start?

**Comment by matejcik** [comment]
I would start by upgrading isort in poetry, removing the current isort config completely (in setup.cfg i think?) and replacing it by a profile. I didn't look into which profiles are available, but I vaguely remember that there's a `black` based one, so that's where I would start.

then I'd try to run the `make pystyle` task and see what changes show up. the ideal result is no changes, in which case you're basically done.

what might happen is that the new isort will not run at all, in which case you'll need to modify the invocation (in top-level makefile and in python/Makefile) so that it works again

**Comment by AdarshRawat1** [comment]
Please guide me on how I can run the `make pystyle` task.

**Comment by AdarshRawat1** [comment]
> This _looks like_ windows has a problem with all our files specified with forward slashes, so there's a good chance this won't work on Windows at all. If you're willing to go the extra mile, try to do it in WSL.

Noted ! Will do it in WSL.Thanks.

**Comment by matejcik** [comment]
something is wrong with your setup because no arguments are passed to isort/black

first of all you should be using `poetry` (see the last section [here](https://docs.trezor.io/trezor-firmware/core/build/index.html#poetry))

second, the makefile `PY_FILES` variable is empty
try running this command, which fills it:
`find . -type f -name '*.py'   | sed 'sO^\./OO' | grep -f ./tools/style.py.include | grep -v -f ./tools/style.py.exclude`

**Comment by AdarshRawat1** [comment]
@matejcik I executed this command after following all your guidance and resources.
![image](https://user-images.githubusercontent.com/100958893/226417887-b9d35dc3-d7e9-48e7-aebf-eaa12231b166.png)

After this I tested if other changes are remaining - 
1.
![image](https://user-images.githubusercontent.com/100958893/226418013-84842d90-38cb-4776-93d4-6f517c369f3c.png)

2.
![image](https://user-images.githubusercontent.com/100958893/226418238-081e565f-1c3e-4470-aec9-cf2aa76752b1.png)

Please verify !

**Comment by AdarshRawat1** [comment]
I think we need to update `pyproject.toml` as well (under the style section).
@matejcik your suggestions?

**Comment by matejcik** [comment]
fixed in https://github.com/trezor/trezor-firmware/pull/3219
