### ISSUE TITLE
Support Algorand Blockchain

### ISSUE THREAD

**Issue by void9090** [trezor/trezor-firmware#2176]
Now that the Trezor Suite application is done we can expect support for new coins.

Are you going to add support for Algorand, please?
Algorand is currently number 29 in the coinmarketcap and according to https://github.com/trezor/trezor-firmware/issues/2145#issuecomment-1053571698 you might want to consider adding Algorand.

Thank you.

**Comment by mdhz** [comment]
SOL is above that in ranking and I had requested it almost a year ago and it's still not implemented.

**Comment by hynek-jina** [comment]
@void9090 
We do not plan to add this coin anytime soon. If the situation changes, we will reopen the issue.
