### ISSUE TITLE
License is missing for crypto/chacha20poly1305

### ISSUE THREAD

**Issue by yfdyh000** [trezor/trezor-firmware#2179]
The MIT license does not exist in the header of any files. A separate LICENSE file is better.
The upstream: https://github.com/wg/c20p1305/blob/master/LICENSE
At least one contributor: https://github.com/trezor/trezor-crypto/pull/155

**Comment by prusnak** [comment]
Fixed in d2044d29b6c018aba6ceb7dfa9f4dea5b26a41d6
