### ISSUE TITLE
add hnt coin and helium blockchain

### ISSUE THREAD

**Issue by naminic** [trezor/trezor-firmware#2206]
please add hnt coin and the blockchain as it is an open source project and helium team are agile

**Comment by sime** [comment]
@naminic Thanks for the suggestion. We will track this internally, currently we are only shortlisting new coins to support that are in the top 20 in terms of market capitalization.

**Comment by naminic** [comment]
hnt is growing so fast and its popular and as it is open source it is easy to integerate
