### ISSUE TITLE
SLIP39 Recovery: allow user to fix incorrect word

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#221]
Child of #269 
In recovery, if the checksum fails, we could improve the UX, so it does not fail completely. Instead let's offer users, which word was wrong, which they can then fix.

**Comment by matejcik** [comment]
how do we know which word was wrong? :)

**Comment by tsusanka** [comment]
There is an autocorrection code:

> Implementations should not implement correction beyond potentially suggesting to the user where in the mnemonic an error might be found, without suggesting the correction to make.

**Comment by matejcik** [comment]
ooooh this should apply to SLIP-39 only

**Comment by ZdenekSL** [comment]
We need the UX part.

**Comment by ZdenekSL** [comment]
@tsusanka Please check if this is not duplicate.

**Comment by tsusanka** [comment]
The best way to approach this is probably to inform the user that 14th word (e.g.) is most likely the wrong one and offer the user to fix it.

However, it's important to note, that many users probably won't make a mistake in the word, rather skip one or write some twice etc. which this won't solve.

**Comment by tsusanka** [comment]
UX prefers not to do this unless there is a strong data background we should implement this.

Moving to backlog.

**Comment by ZdenekSL** [comment]
Closed after discussion
