### ISSUE TITLE
Wiping bootloader produces USB error when device disconnects - both T1 and TT

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2221]
**Describe the bug**
`trezorctl device wipe --bootloader` produces a USB error when device is being disconnected - mostly `usb1.USBErrorNoDevice: LIBUSB_ERROR_NO_DEVICE [-4]`, but sometimes other `LIBUSB_ERROR`

Otherwise, the whole wiping seems to be successful

**Firmware version and revision**
 - Trezorctl version `0.13.0` on `Windows`, current `master` on `Nixos`

**Desktop setup**
- happens both on latest company `Nixos` and `Windows11`

**To Reproduce**
- have any Trezor (TT or T1) connected in a bootloader mode
- `trezorctl device wipe --bootloader`
- seeing an error-trace ending with `usb1.USBErrorNoDevice:...`

**Comment by matejcik** [comment]
fixed in #2904
