### ISSUE TITLE
Allow for non-deterministic wallets

### ISSUE THREAD

**Issue by abvgdeyoj** [trezor/trezor-firmware#2224]

**Comment by matejcik** [comment]
would you mind expanding on this just a little bit?

**Comment by abvgdeyoj** [comment]
@matejcik Allow for usage/creation of wallets not based on the seed, but either on hardware RNG or imported.
This requires storage, but storage for resident secrets is a separate issue.

**Comment by prusnak** [comment]
This is out of scope for the Trezor project. All keys have to be recoverable from seed.
