### ISSUE TITLE
Logo for Kraken U2F

### ISSUE THREAD

**Issue by Midar** [trezor/trezor-firmware#2229]
Kraken supports U2F now. I guess it's a fair assumption that many Trezor users are also Kraken users and it would be nice to add a Kraken logo for U2F.

**Comment by prusnak** [comment]
Fixed by https://github.com/trezor/trezor-firmware/pull/2309

**Comment by bosomt** [comment]
**QA OK**

tested with `trezor-fw-regular-2.5.2-dff5bdce.bin`
