### ISSUE TITLE
python-trezor: more intelligent zcash v4 support in tx_api

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#223]
**up-to-date summary**:

users are running into problems when signing Zcash v4, because they're incorrectly setting `overwintered` and `group_id` flags. python-trezor should probably know this and stop them.

(original summary below)

-----

two sub-issues:
1. blockbook fields `fOverwintered` and friends got renamed, we need to fix that
2. for v4 we need more extra_data. i'm honestly considering counting raw tx bytes and just stuffing the whole suffix into extra_data

**Comment by ZdenekSL** [comment]
Wont be done
