### ISSUE TITLE
Extending PiTrezor for XRP and ADA

### ISSUE THREAD

**Issue by stn021** [trezor/trezor-firmware#2236]
In the sources for PiTrezor there are subroutines for XRP and ADA, also for XMR.
The sources for the Trezor-Suite are also in this repository.

There have been occasional request for support of XRP, but the answer was, that this would only be possible if in the future a "Model-T"-Version of PiTrezor would be created. That apparently is not so easy, due to for example the fact that the Model T uses a touchscreen.

I was wondering, if it might be possible to integrate the code for XRP and ADA and maybe even XMR into the existing PiTrezor. Also I would think that minimal changes (or even none at all) could be made to the Trezor-Suite, so that it does not say "Model T only" when you want to activate XRP.

**Comment by prusnak** [comment]
This is not possible. PiTrezor is based on Legacy code which runs on Model One and there is no plan to integrate this functionality into that codebase. Maybe if PiTrezor was based on Core code, this would be possible, but that's up to PiTrezor maintainer to decide whether they want to do this.
