### ISSUE TITLE
Support TRON (TRX)  blockchain

### ISSUE THREAD

**Issue by sunflower-sun** [trezor/trezor-firmware#2242]
Please add support for [TRON](https://tron.network/) tokens which based on TRC20 standard. TRON blockchain has a large community of users and developers. It would be fantastic if Trezor supports TRON tokens. Thanks a lot.

Some of the most common TRON tokens are:
* [TRX](https://tron.network/trx?lng=en)
* [BTT](https://bt.io/)
* [USDT](https://tron.network/usdt)

**Comment by hynek-jina** [comment]
Thank you for your contribution. We will note your request, however we do not plan to add any more tokens at this time.
