### ISSUE TITLE
Implement Trezor R UI

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#2246]
This parallels #1922 

UI designs are TBD so this might get deferred a couple times.

Some basic steps, prioritized by feature that are required for Bitcoin only firmware:

(PRs below are depending on each other in the top-to-bottom way)

- [x] Emulator up and running #2230 
- [ ] Homescreen  #2238 
- [ ] UI tests  #2252 
- [ ] PIN entry
  - [ ] #2233
  - [x] #2318 
  - [x] #2319
- [ ] Seed setup #2310 
- [ ] Seed backup #2264
- [ ] Seed recovery #2265 #2268
- [ ] Passphrase entry #2267
- [ ] Basic UI designs (confirm_action)
- [ ] Bitcoin signing flow
- [ ] Altcoin special screens

**Comment by mdhz** [comment]
What's this Trezor R?
Is it a new upcoming hardware model?

**Comment by prusnak** [comment]
@mdhz Correct, but it won't be available any time soon.

**Comment by Hannsek** [comment]
T2B1 design tracked in milestone https://github.com/trezor/trezor-firmware/milestone/38
