### ISSUE TITLE
Remove red alert for Wipe code

### ISSUE THREAD

**Issue by europound** [trezor/trezor-firmware#2247]
_Context: [Wipe code](https://wiki.trezor.io/User_manual:Wipe_code)_

- remove red alert after wipe code entered.
- should not be this obvious and harsh

**Wipe code quietly erases seed**
- returns back to the main screen as if pin was entered correctly
- → plausible deniability

**Comment by prusnak** [comment]
This has been discussed internally and we want to keep the warning.

**Comment by europound** [comment]
> This has been discussed internally and we want to keep the warning.

why?

**Comment by prusnak** [comment]
Duplicate of https://github.com/trezor/trezor-firmware/issues/2055
