### ISSUE TITLE
Differenciate HEADERTOOL error messages

### ISSUE THREAD

**Issue by TychoVrahe** [trezor/trezor-firmware#2255]
Would be useful if headertool gave specific reason why it failed to recognize image type.

Right now, it produces general "Unrecognized image type" error.

For example, information that the fail is due to non-matching code length is something that would provide developer valuable feedback.

**Comment by matejcik** [comment]
This is unfortunately more difficult than it is worth, because Construct reports errors pretty much in the format of "the format did not match the declaration".
