### ISSUE TITLE
Model R font files

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#2269]
* [PixelOperatorMono8.ttf.gz](https://github.com/trezor/trezor-firmware/files/9019525/PixelOperatorMono8.ttf.gz) Source: https://www.dafont.com/pixel-operator.font
* [unifont-14.0.04.otf.gz](https://github.com/trezor/trezor-firmware/files/9001048/unifont-14.0.04.otf.gz) Source: https://unifoundry.com/unifont/
* [unifont-14.0.04-bold.otf.gz](https://github.com/trezor/trezor-firmware/files/9000916/unifont-14.0.04-bold.otf.gz) Source: Custom made bold variant of Unifont (v14.0.04), with enough glyphs to fit Trezor use cases. The file is to be committed to this repository under similar [license](https://unifoundry.com/LICENSE.txt) as the source.

`PixelOperatorMono8.ttf` is to be used on headings and buttons. And `unifont.ttf` for everything in between.

**Comment by grdddj** [comment]
Done in [19aec90](https://github.com/trezor/trezor-firmware/pull/2277/commits/19aec907defd874101b428cc0046436e6e16c46c) and [e428d51](https://github.com/trezor/trezor-firmware/pull/2277/commits/e428d51a3920cdfd04535a1480d36c0eaca45deb) as a part of https://github.com/trezor/trezor-firmware/pull/2277.

Things are not ideal yet, the bigger fonts broke some layouts
