### ISSUE TITLE
Add type annotations using MyPy

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#227]
http://mypy-lang.org/

See https://mypy.readthedocs.io/en/latest/python2.html for Py2 syntax.

**Comment by matejcik** [comment]
let's track mypy typing for core in this as well?

**Comment by prusnak** [comment]
Current progress is in the [`jpochyla/static_typing`](https://github.com/trezor/trezor-firmware/tree/jpochyla/static_typing) branch

**Comment by jpochyla** [comment]
Superseded by #489
