### ISSUE TITLE
Update Connect tests, account for its move to Suite monorepo

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2295]
`Connect` tests are being moved into Suite monorepo.

We should account for this in our way of running them - https://github.com/trezor/trezor-firmware/blob/master/tests/connect_tests/connect_tests.sh

**Comment by sime** [comment]
Could it (or should it?) potentially support both?

Since Connect v8 will be support for some time.

**Comment by grdddj** [comment]
> Could it (or should it?) potentially support both?
> 
> Since Connect v8 will be support for some time.

Not sure at all. I am not knowledgeable enough about `Connect`, I just heard it moves to another place, so our `Connect` tests would no longer be updated

**Comment by sime** [comment]
@mroz22 @szymonlesisz Thoughts on how to maintain Connect tests in firmware?

**Comment by grdddj** [comment]
Already done, `Connect` tests are currently fine in `master`
