### ISSUE TITLE
Error screen for PIN creation failure

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#2318]
**Design:** 
![emu00000000](https://user-images.githubusercontent.com/216917/171420159-465d9818-60ce-490d-aa1f-de69d56ab9a5.png)

Similar to wrong pin when attempting an unlock.

![emu00000000](https://user-images.githubusercontent.com/216917/171421115-676d087e-d2de-4c56-807d-8c4f712b7f29.png)

**Spec:** 
When establishing a PIN, a mismatched PIN will prompt the user about the PIN entry failure. Cancelling will return the user to the homescreen.

**Comment by grdddj** [comment]
In [b476fc7](https://github.com/trezor/trezor-firmware/pull/2277/commits/b476fc702381f36de0cd1372d70a9f41053b5228) I have added the "show popup" functionality for `model R`, matching the current `model T` popup logic.

It is just a popup that will be on the screen for 3 seconds and then disappear, leaving the start of the PIN dialogue there.

> Cancelling will return the user to the homescreen.

Do we really want this? The behavior of the `model T` is as described above. Users can cancel during the PIN creation

**Comment by sime** [comment]
> > Cancelling will return the user to the homescreen.
> 
> Do we really want this? The behavior of the `model T` is as described above. Users can cancel during the PIN creation

Can't fault the existing cancel behaviour. You can ignore this.
