### ISSUE TITLE
Random cursor position on PIN entry

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#2319]
Upon entry of the first PIN digit, [randomly move the cursor](https://satoshilabs.slack.com/archives/CL1D61PQF/p1653899837844919?thread_ts=1653899229.314769&cid=CL1D61PQF) to another digit.

The digit of 1-9 order will be maintained.

Thus making it difficult to observe the actual digits being entered by an attacker.

**Comment by grdddj** [comment]
Done in [d4c2acd](https://github.com/trezor/trezor-firmware/pull/2277/commits/d4c2acd092d1d8265f4419b476cd5d47817b7bfb)
