### ISSUE TITLE
Add ButtonRequest to Shamir where needed

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#232]
We should first design the "protocol" (what messages are exchanged) for the SLIP-39 integration in Wallet. Since almost everything is done on the device, it should be quite simple. So far, in the [tsusanka/slip39 branch](https://github.com/trezor/trezor-firmware/commit/f0bd96b369c53a114fd77454f235fccffe46b2a3#diff-b00d8fe315e1298939ff19a0ec1d3ddeR194) there is just a simple bool in ResetDevice.

- [x] Is it all we need?
- [ ] Add ButtonRequest messages or similar for every screen on Trezor, so we can guide the user properly through the process.

This can be done in paralel with https://github.com/trezor/trezor-firmware/issues/59

**Comment by prusnak** [comment]
We need also shamir flag in the RecoveryDevice, no?

**Comment by prusnak** [comment]
I guess this is resolved now.

**Comment by tsusanka** [comment]
Well to some extent. This is not yet done:

> Add ButtonRequest messages or similar for every screen on Trezor, so we can guide the user properly through the process.

But it's a minor issue I guess.

**Comment by prusnak** [comment]
Reopening then

**Comment by ZdenekSL** [comment]
Decided that we are going to do this.

**Comment by tsusanka** [comment]
Seems like #35 is a prerequisite.

**Comment by tsusanka** [comment]
Related to #530

**Comment by ZdenekSL** [comment]
Closed after discussion

**Comment by prusnak** [comment]
We'll deal with that when solving bigger task at https://github.com/trezor/trezor-firmware/issues/35
