### ISSUE TITLE
Model R: Banners

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#2331]
## Design
[Figma](https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=1830%3A11937)

![Status](https://user-images.githubusercontent.com/216917/172602825-3ec2da17-cf2a-4f0a-a315-6abe2a1e1012.png)

### Font
[Pixel Operator 8](https://github.com/trezor/trezor-firmware/issues/2269)
 
## User Story
Given I setup my Trezor
When I skip the backup
Then I should see 'BACKUP NEEDED'

**Comment by grdddj** [comment]
Done in [1df6093](https://github.com/trezor/trezor-firmware/pull/2277/commits/1df60935e9965cea5192f537f917916344ddd781) - adding the warning icons in top corners and changing the text to monospace white

**Comment by sime** [comment]
@grdddj Get ready for some pixel pushing.

* Banner is 4px from the top, it needs to be **2px**.
* Top right icon is clipped by one pixel, it's showing 10x11 when the icon is actually **11x11**.
* Banner text is not centred.
* Word spacing needs to be **9px**.

Current screenshot for reference.

![emu00000000](https://user-images.githubusercontent.com/216917/180727301-98c234f1-e9f0-46b9-8a3d-52d5f5e61703.png)

**Comment by grdddj** [comment]
In [2ffed0b](https://github.com/trezor/trezor-firmware/pull/2277/commits/2ffed0b22ff7566996a4da52c5214e730154eb83):
- moving banner `2px` to the top
- moving the right icon `1px` to the left
- helping the centering text by `removing !` from the text (users in survey were not happy about it and warning icons already do the job)

About the word spacing, how many it is right now? I could look into how we render a space

![image](https://user-images.githubusercontent.com/42543243/180757382-6e39feae-3d33-4ddf-a2be-089f78b1c1df.png)

**Comment by grdddj** [comment]
> Word spacing needs to be 9px.

It looks like the `Unifont` has it **8px** and `Mono` has **10px**

**Comment by sime** [comment]
> * moving the right icon `1px` to the left

I'm using this tool for [image comparison](https://online-image-comparison.com/), and the right icon looks like it shift 2px to the left.
![Screenshot 2022-07-27 at 15 32 06](https://user-images.githubusercontent.com/216917/181259733-52774b47-4407-4e5c-9c63-52474d732e7e.png)

Reference image

![emu00000001](https://user-images.githubusercontent.com/216917/181259776-a658d56b-092b-4b36-8927-ef9ebbcec291.png)

**Comment by grdddj** [comment]
> It looks like the `Unifont` has it **8px** and `Mono` has **10px**

Unified to **9px** for both fonts in [a9627ab](https://github.com/trezor/trezor-firmware/pull/2277/commits/a9627ab266d9b0f6c1cb2496ed8f60dc2a69f37b)

**Comment by grdddj** [comment]
> > * moving the right icon `1px` to the left
> 
> I'm using this tool for [image comparison](https://online-image-comparison.com/), and the right icon looks like it shift 2px to the left.

This is because of a known limitation of our icon creation/rendering. I have an issue for that - https://github.com/trezor/trezor-firmware/issues/2416.

It is not a show-stopper, we can make an easy workaround for it - just creating a second version of the icon that will be rendered in the right top. However, it would be nice to address the limitations.

BTW, nice comparison tool, thanks for sharing :)

**Comment by sime** [comment]
> > > * moving the right icon `1px` to the left
> > 
> > 
> > I'm using this tool for [image comparison](https://online-image-comparison.com/), and the right icon looks like it shift 2px to the left.
> 
> This is because of a known limitation of our icon creation/rendering. I have an issue for that - #2416.
> 
> It is not a show-stopper, we can make an easy workaround for it - just creating a second version of the icon that will be rendered in the right top. However, it would be nice to address the limitations.

Would it work if the banner icon can be globally 12x11?

**Comment by grdddj** [comment]
> Would it work if the banner icon can be globally 12x11?

If its width would be `12`, then yes, it would help us. But how we could add one pixel to the width in this symetric shape?

**Comment by sime** [comment]
From a raster format POV it's trivial. Pad the image with a column of empty pixels.
![Screenshot 2022-07-28 at 10 33 58](https://user-images.githubusercontent.com/216917/181460517-c14ee9d1-9b07-440f-b163-074af7df5098.png)

**Comment by grdddj** [comment]
> From a raster format POV it's trivial. Pad the image with a column of empty pixels

I actually need to do it already for this icon, as we cannot work with `11x11`, so I have it `12x12` with empty bottom row and right column.

The issue is that this is suitable for the `left corner` - in the `right corner`, we would need empty left column to show it properly "cornered"

**Comment by grdddj** [comment]
Special icon for right corner created and used in [8bf08d9](https://github.com/trezor/trezor-firmware/pull/2277/commits/8bf08d94ff9d6bab693ce0359eb5a8c04f9adbbc)
