### ISSUE TITLE
Model R: Remove backup cancel CTA

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#2337]
## Design
|![emu00000000](https://user-images.githubusercontent.com/216917/173785085-cb0e40d4-dd80-42ed-a558-32ade9de6d97.png)|![emu00000000](https://user-images.githubusercontent.com/216917/173790114-e1289d69-99e2-46ae-93a8-fda3a03589ec.png)|![emu00000001](https://user-images.githubusercontent.com/216917/173785092-7d306e8b-dcd9-4e91-b5d1-6d44f5a8d74a.png)|

## Spec
As a Trezor User
I want to backup my seed phrase
So that I can recover my coins

Given I have started the backup flow
When I look at my Trezor
Then I should see 'Never make a digital copy of your recovery...'
And I should see 'I UNDERSTAND'
And I should not see 'Cancel'

Given I'm backing up my seed phrase
When I fail to verify the backup
Then I should see 'That is the wrong word. Please check again'
And I should see a 'CHECK AGAIN' button

Given I have started the backup process
When I physically disconnect the Trezor
And I reconnect the Trezor
Then I should see 'BACKUP FAILED'

## Error
When pressing cancel:
```
1655230943283371 trezor.wire DEBUG 0:0 expect: ()
1655230980932290 trezor.loop DEBUG ui.Result: <CANCELLED>
1655230980932490 trezor.loop DEBUG finish: <generator object '__iter__' at 14d922520>
1655230980932686 trezor.loop ERROR exception:
Traceback (most recent call last):
  File "trezor/loop.py", line 186, in _step
  File "apps/management/backup_device.py", line 29, in backup_device
  File "apps/management/reset_device/__init__.py", line 214, in backup_seed
  File "apps/management/reset_device/layout.py", line 125, in bip39_show_and_confirm_mnemonic
  File "apps/management/reset_device/layout.py", line 108, in show_backup_warning
  File "trezor/ui/layouts/tr/__init__.py", line 186, in confirm_action
  File "trezor/ui/layouts/tr/__init__.py", line 145, in raise_if_cancelled
ActionCancelled:
1655230980932786 trezor.workflow DEBUG close: <generator object 'backup_device' at 14d8f8860>
1655230980932831 trezor.loop DEBUG spawn new task: <generator object 'homescreen' at 14d932840>
1655230980932872 trezor.workflow DEBUG start default: <generator object 'homescreen' at 14d932840>
1655230980933020 trezor.wire DEBUG cancelled: Cancelled
1655230980933066 trezor.wire DEBUG 0:0 write: Failure
```

**Comment by grdddj** [comment]
Done in [d570e9b](https://github.com/trezor/trezor-firmware/pull/2277/commits/d570e9ba94d1708d115b43591de004caf7131e26) and [99e5952](https://github.com/trezor/trezor-firmware/pull/2277/commits/99e5952671666287b6c05da741bc4fa6b0345fb0) as a part of https://github.com/trezor/trezor-firmware/pull/2277

**Comment by sime** [comment]
**QA NOK**

> Given I have started the backup process
> When I physically disconnect the Trezor
> And I reconnect the Trezor
> Then I should see 'BACKUP FAILED'

This acceptance criteria fails. Both on device and emulator.

**Comment by sime** [comment]
> **QA NOK**
> 
> > Given I have started the backup process
> > When I physically disconnect the Trezor
> > And I reconnect the Trezor
> > Then I should see 'BACKUP FAILED'
> 
> This acceptance criteria fails. Both on device and emulator.
> 
> Edit: I see the trezor.io/start default screen. Like the seed hasn't persisted.

**QA OK**

Above only occurs with `trezorctl device setup`. A more accurate test case is `trezorctl device setup -s` followed by `trezorctl device backup`.
