### ISSUE TITLE
Adjust middle button behavior on Model R

### ISSUE THREAD

**Issue by TychoVrahe** [trezor/trezor-firmware#2346]
Currently the detection of middle click is failing sometimes, add filter/delay to eliminate errors and improve UX

**Comment by hynek-jina** [comment]
Waiting on UX research (expected on 18th of July)

**Comment by TychoVrahe** [comment]
After research, we will be moving on with two buttons. Research done here: https://github.com/trezor/trezor-firmware/tree/tychovrahe/double_btn

**Comment by TychoVrahe** [comment]
After research, we will be moving on with two buttons. Work done on this is here: https://github.com/trezor/trezor-firmware/tree/tychovrahe/double_btn
