### ISSUE TITLE
Prepare a system to embed bootloader version according to model type in core

### ISSUE THREAD

**Issue by TychoVrahe** [trezor/trezor-firmware#2351]
Currently we only have a bootloader binary for model T in Core source. We will need to design a way to do it for additional models. Obviously a solution like bootloader_T.bin and bootloader_R.bin is possible, but maybe there might be a better way to do it? something that will not bloat the repo over time with binaries, like pulling the bootloader binary from CI during build or something?

**Comment by prusnak** [comment]
> bootloader_T.bin and bootloader_R.bin is possible

+1

The binaries are really small, there is no need to over-optimize right now.

**Comment by matejcik** [comment]
given that we have predefined internal names, the solution is now clear:
`bootloader_T2T1.bin`
`bootloader_T2B1.bin`
