### ISSUE TITLE
Add display rotation to Features

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#236]
Let's return what rotation is used in Features. It might be useful for the Wallet settings to display what is currently used

**Comment by prusnak** [comment]
I would like to see more reasoning why this is needed. Otherwise I see this just as a nice to have feature.

**Comment by tsusanka** [comment]
Zorwy wanted to display, which setting is currently used. In other words highlight one of those buttons:

![photo6041744458678120268](https://user-images.githubusercontent.com/1835345/59113384-2bacbb80-8945-11e9-8b4f-80d00937b6a3.jpg)

There is no other way to find out this, is there?

**Comment by prusnak** [comment]
This adds unnecessary complexity. We don't show currently set homescreen in the homescreen selector either. Just show buttons without the highlight.

**Comment by tsusanka** [comment]
Ok. Cc @TomasZorvan
