### ISSUE TITLE
trezorctl fails with click 7.x

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#2364]
While fixing #1702, I used a keyword argument that is not supported on 7.x

The fix is instead of using `package_name`, we supply the `version` directly.

**Comment by matejcik** [comment]
QA instructions:
downgrade Click to 7.x via `pip install "click<8"`
try using `trezorctl`
upgrade Click to 8.0.x via `pip install "click>=8;<8.1"
try using `trezorctl`
upgrade Click to newest via `pip install --upgrade click`
try using `trezorctl`

**Comment by bosomt** [comment]
**QA OK**

all 3 times trezorctl works as expected
