### ISSUE TITLE
Model R: Progress spinner

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#2368]
**Design:** [Figma](https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=2441%3A7780)

Exported 64x64px transparent sprites (let me know if a background is preferred).

[progress_indicator.zip](https://github.com/trezor/trezor-firmware/files/9040371/progress_indicator.zip)

**Spec:** [Notion](https://www.notion.so/satoshilabs/TR-Sprite-of-loading-animation-e06cf2d45cc14a7ca45be928fe8c84b2)

Replace the currently Model T scaled loader.

**Comment by Hannsek** [comment]
Newer version here: https://github.com/trezor/trezor-firmware/issues/2622
