### ISSUE TITLE
Display rotation is broken on master

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#237]
On current master, if the `trezorctl set-display-rotation east` is called, the screen is rotated, but the buttons are clickable only at the older positions.

Although I didn't git-bisect I suspect the new UI is responsible.

**Comment by tsusanka** [comment]
@jpochyla could you look at this?

**Comment by jpochyla** [comment]
Sure!

**Comment by jpochyla** [comment]
Fixed in 4162266
