### ISSUE TITLE
Please support tokens of TRON network

### ISSUE THREAD

**Issue by L-Reid** [trezor/trezor-firmware#2378]
Please add support TRX and USDT(TRC20) of TRON blockchain. TRON is a top blockchain in the industry with a huge number of users. there are many applications based on it. If Trezor can support TRON, it will  be a great thing for all users. Thanks a lot.

**Comment by hynek-jina** [comment]
Thank you @L-Reid for you input.
We are and we want to remain a Bitcoin-first company. We have a lot of things on the roadmap directly related to Bitcoin that need to be implemented and released first, so we can not commit to a timeframe on this issue.
