### ISSUE TITLE
Model R: Introduce Cancel/'X' icon

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#2389]
Design: [Figma](https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=1830%3A10214)

![Image](https://user-images.githubusercontent.com/216917/179194304-deb143ae-e5e7-416a-9af9-8c5bba43c5b0.png)

Example location: Hold to wipe

**Comment by grdddj** [comment]
Support for icons as buttons added in [cfc9e2e](https://github.com/trezor/trezor-firmware/pull/2277/commits/cfc9e2e68f4ba38c5fd67fec0d7f383d5f5bea9b)

It currently includes these:
- small 8*8 icon with an outline/border ("x")
- bigger icon up to 12*12 without an outline ("<", ">")
- "arms" on the left and right of the middle button
- arrow-buttons with customizable width for scrolling the content up and down

**Comment by sime** [comment]
Borderless `X` icon is needed.

No actual screens are using a 'bordered' `X` icon.

**Comment by sime** [comment]
Additionally, remove borders around these buttons, and select needs arms.

![emu00000000](https://user-images.githubusercontent.com/216917/181525183-a4cdeb2a-553a-49f9-8de5-79f93ecb5cb2.png)![emu00000001](https://user-images.githubusercontent.com/216917/181525189-1e5929ff-efe9-4098-99fd-66478c811318.png)

**Comment by grdddj** [comment]
Done in [c163b03](https://github.com/trezor/trezor-firmware/pull/2277/commits/c163b033eea86620b4683248eb0a34db012109d8) and [b185fd0](https://github.com/trezor/trezor-firmware/pull/2277/commits/b185fd0f296ca9d1480b4ee4c09453cf3880b6da)
