### ISSUE TITLE
Thousand amount separator

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-firmware#2394]
With the use of `sat` units, there was a need to implement thousand separators for amount in Trezor Suite.
https://github.com/trezor/trezor-suite/issues/5545

The user needs to see the amount in the Suite and on the Trezor device in the same format for control when sending a transaction.

Most required is `en-us` formatting (like i.e. `123,456.78`) but more general solution would be even better for the future.

## Acceptance criteria
Given I view my coins in sats
When I prepare a transaction for 4000 sats
And I press Review & Send
Then I should see 'Confirm sending 4,000 sat' on the Trezor

### Model 1
Given I see 'Confirm sending 4,000 sat'
When I tap 'Confirm'
Then I should see 'Really send 4,153 sat'

### Model T
Given I see 'Confirm sending 4,000 sat'
When I tap 'Confirm'
Then I should see 'Total amount: 4,153 sat'

**Comment by sime** [comment]
Having a hardcoded locale scheme for a thousand separator when sats are used should be trivial.

We want to avoid locale's that [support spaces](https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html). Then a single scheme can cover the majority of cases.

@matejcik We would like to avoid spaces for security POV?

**Comment by hynek-jina** [comment]
Then we can go simply with `,` thousand separator which is currently in Suite as well.

**Comment by bosomt** [comment]
**QA OK**

TT OK

**Info:**
 - Suite version: desktop 22.8.1 (503b472935dec8a9c07aac5eef5ba43f86780a38)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
Maybe we can consider to adding this separator to Trezor Suite too ?
It would look clearer.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/31506317/183018558-644ca99f-0558-47a8-aef6-c1e8940ae9a3.png">

**Comment by hynek-jina** [comment]
@bosomt 
It's almost there: https://github.com/trezor/trezor-suite/issues/5545
