### ISSUE TITLE
T2B1 research: Animate PIN digit shuffling 

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#2395]
Related to https://github.com/trezor/trezor-firmware/issues/2358

User Research shows users are confused after selecting a digit, why is the 'PIN keyboard' shuffled.

Investigate the viability of animating of the digits progressing as they are shuffled. 

![P_20220720_183329](https://user-images.githubusercontent.com/216917/180036033-a72a561a-fefb-4257-8268-062144c991ec.jpg)

**Comment by Hannsek** [comment]
We don't have design capacity for this right now. :(
