### ISSUE TITLE
Model R: bigger fonts for PIN and other input methods

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2399]
The middle character in choice should be `64` font size, the side ones `32`.

It might eat a lot of flash space, export just the necessary characters, or try to somehow reuse already existing fonts (sizes `8` and `16` - maybe just "multiplying" them by four)

![image](https://user-images.githubusercontent.com/42543243/180743447-7f723b01-6682-4d53-ab2b-17a5307c4ff4.png)

**Comment by matejcik** [comment]
> somehow reuse already existing fonts (sizes `8` and `16` - maybe just "multiplying" them by four)

this is the way to go.

**Comment by grdddj** [comment]
Magnification supported in [a4b8248](https://github.com/trezor/trezor-firmware/pull/2277/commits/a4b82488f9833fee26af02ba70b76383c7fa8c8e) and used in [85fc691](https://github.com/trezor/trezor-firmware/pull/2277/commits/85fc6910b3a9b50a69dc18eaab2c6f43de7ff668)

I am very interested in how much flash space has the transformation logic eaten, I have not yet looked.

Couple letters still have some small inconsistencies, for example
![image](https://user-images.githubusercontent.com/42543243/181448773-e7c826dc-56d9-426e-bb69-01619599f703.png)
![image](https://user-images.githubusercontent.com/42543243/181448889-05317a8f-06e3-4e66-85ea-a82e20e01db2.png)

**Comment by grdddj** [comment]
> I am very interested in how much flash space has the transformation logic eaten, I have not yet looked.

Seems it did not make a big difference, around `2kb`, which is negligible compared to including all those big fonts.

**Comment by grdddj** [comment]
As agreed with @matejcik, the magnification could be put directly into already existing rendering logic
