### ISSUE TITLE
T2B1: improve one-time screens

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2400]
One-time screens that just display text (no buttons) are being reused from model `T`. It means there are very big icons and the title sometimes cannot fit the screen - "Passphrase entry", "Signing transaction".

![image](https://user-images.githubusercontent.com/42543243/180740974-229600a0-6975-4144-a442-24c53c16c3ee.png)
![image](https://user-images.githubusercontent.com/42543243/180742134-b79e7d10-2533-4f05-9e2b-6295d0dbe030.png)

Do something fitting for model R.

**Comment by sime** [comment]
Figma design: https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=2441%3A7786

**Comment by grdddj** [comment]
Simple screens without buttons and time-out windows implemented in [5468a94](https://github.com/trezor/trezor-firmware/pull/2610/commits/5468a94c5f6d8059ce4e8bb121780d7b710d7990)

**Comment by grdddj** [comment]
Done as a part of https://github.com/trezor/trezor-firmware/pull/2610
