### ISSUE TITLE
T2B1: support buttons with both icons and text

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2403]
There are some use-cases when we want to have both icon and text in one button:
- :success_tick: + "CONFIRM"
- :back_arrow: + "BACK"
- :hold_icon: + "CONFIRM" - as a succinct way for "HOLD TO CONFIRM"

![image](https://user-images.githubusercontent.com/42543243/180742726-e0c9b33f-9389-4539-9e54-74328dad9484.png)
![image](https://user-images.githubusercontent.com/42543243/180742777-e5faa121-e2c9-460f-a2cb-bef005c150a1.png)

**Comment by grdddj** [comment]
Is this still relevant, or we do not use these icon+text buttons anywhere anymore? @Hannsek

**Comment by Hannsek** [comment]
We are not using this with buttons, however we use it in "keyboards", but that is something different. I am closing it now.
