### ISSUE TITLE
Model R: Adjust PIN entry for longer prompts and show subpromt

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2405]
Sometimes in `PIN` entry the prompt text is long that it cannot be reliably displayed in the center/side.

We should consider showing this prompt at the top. Also, the subpromt (`You have 15 attempts left`) is not shown anywhere yet.

![image](https://user-images.githubusercontent.com/42543243/180741293-8084fa5a-0655-4238-b459-54b05b63b758.png)
![image](https://user-images.githubusercontent.com/42543243/180741319-8ab83cbd-3a8e-4ffc-9ac9-957c1fd3b2a3.png)

**Comment by sime** [comment]
Grooming the backlog. Closing as we will tackle this eventually.
