### ISSUE TITLE
Model R: content is sometimes colliding with buttons

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2406]
Probably make there a small empty region between content and buttons - to also allow for letters like `p` or `y` that have some parts lower than others.

![image](https://user-images.githubusercontent.com/42543243/180743835-3e1f34f1-8a50-4c55-b735-6346d2d3a1f4.png)
![image](https://user-images.githubusercontent.com/42543243/180744010-41424cfa-9b52-4bf5-956a-2444d340c746.png)

**Comment by grdddj** [comment]
@sime Please confirm the line height. They seem off.

**Comment by sime** [comment]
Grooming the backlog. Closing as we will tackle this eventually.
