### ISSUE TITLE
Model R: Bitcoin signing flow design

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2407]
Implement all the BTC signing screens according to `Figma` design.

![image](https://user-images.githubusercontent.com/42543243/180747188-26deb6b0-91b6-4b69-8710-bcec607dbd76.png)
![image](https://user-images.githubusercontent.com/42543243/180747218-54acbdc5-530b-4a7f-8f7f-8acd593af298.png)
![image](https://user-images.githubusercontent.com/42543243/180747259-e8e6305d-6963-4384-876a-b2c187103798.png)

**Comment by grdddj** [comment]
The first part is roughly done in [ae5960e](https://github.com/trezor/trezor-firmware/pull/2277/commits/ae5960e7858337a48b23d10b5b2f5e1991ac2a8b) - without much pixel-play and some details (for example the down arrow next the address is missing)

![image](https://user-images.githubusercontent.com/42543243/182347613-8dc43256-a76d-4a96-9c24-7c00b1ffa584.png)
![image](https://user-images.githubusercontent.com/42543243/182347675-5280ac07-3611-4612-a597-465a846764cc.png)

I am omitting the middle screen completely, as it does not make sense to show the fee and total (plus the fee-rate possibly) for each output - that will be part of the final transaction confirmation - to be done.

Currently pressing `X` from the summary goes to the previous page, we want to probably make it cancel the whole signing flow (that can be currently done by pressing `X` at the first screen).

Other considerations:
- Figma shows this flow in different versions, so some final design would need to be made
- We might include the horizontal scrollbar at the top (as is in some Figma designs) and/or consistent title on all screens (like `SEND`)

To be done:
- final transaction screen showing the total amount, fee and fee-rate
  - it can theoretically look something like the middle screen above, but with extra space for fee-rate

**Comment by grdddj** [comment]
> Tried to run the UI on commit https://github.com/trezor/trezor-firmware/commit/ec8dd5800b4b5589efaed2282a3ff2bb830c05f7
It crashed the emulator.

Good catch. The issue was the length of the address - I allocated just 50 characters on it, and `taproot` addresses have 62 characters :) 

Fixed in [3e4d83d](https://github.com/trezor/trezor-firmware/pull/2277/commits/3e4d83d8e4827d18e06c40d0c649dd4b2f908ab2) - allocating 80 characters.

However, for `taproot` address, the last two characters are not very nice right now, colliding with the left button. Something will need to be done with it - some truncating, splitting it into two pages or displaying the characters more densely in the middle rows, so that more fit in 5 rows.

![image](https://user-images.githubusercontent.com/42543243/182769519-b3febdb3-d800-44f2-9b01-bfc438222f1a.png)

**Comment by sime** [comment]
We will need multiple pages for sure. As other coins have longer addresses.

**Comment by grdddj** [comment]
> We will need multiple pages for sure. As other coins have longer addresses.

Paginated flow pages supported in [28071d8](https://github.com/trezor/trezor-firmware/pull/2277/commits/28071d8252e5541fba845aa9544af3c1c399be4a)

![image](https://user-images.githubusercontent.com/42543243/183297543-8bb38f62-bd09-4271-a396-92cb6c3e6b88.png)
![image](https://user-images.githubusercontent.com/42543243/183297551-8c66cb28-6f75-4eac-b7aa-c09c131afb05.png)
