### ISSUE TITLE
Model R: altcoin signing flow design

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2408]
Implement all the altcoin signing screens according to `Figma` design.

![image](https://user-images.githubusercontent.com/42543243/180747188-26deb6b0-91b6-4b69-8710-bcec607dbd76.png)
![image](https://user-images.githubusercontent.com/42543243/180747218-54acbdc5-530b-4a7f-8f7f-8acd593af298.png)
![image](https://user-images.githubusercontent.com/42543243/180747259-e8e6305d-6963-4384-876a-b2c187103798.png)

**Comment by sime** [comment]
Grooming the backlog. Closing as we will tackle this eventually.
