### ISSUE TITLE
Model R: experimental mode header collides with warning icons

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2411]
We might not show the icons in this case

![image](https://user-images.githubusercontent.com/42543243/180750843-ec88b02f-e520-446b-b68a-7653cae8abb0.png)

**Comment by sime** [comment]
When does this occur? Simpler approach drop the vowels: `EXPRMTL MODE`

**Comment by grdddj** [comment]
> When does this occur? Simpler approach drop the vowels: `EXPRMTL MODE`

Occurs when users set an `experimental mode` - for having access to some features that are "not-yet-completely-verified". Seems like currently we are using it only for `reboot_to_bootloader` functionality.

Not sure if users would be happy with `EXPRMTL MODE`. I would prefer just `EXPERIMENTAL`, or not showing the icons (which we can do for any longer-than-fitting text)

**Comment by matejcik** [comment]
"Experimental mode" is for developers only so no need to be too user friendly. Removal of wovels sounds fine.

**Comment by grdddj** [comment]
> "Experimental mode" is for developers only so no need to be too user friendly. Removal of wovels sounds fine.

Done in [2d797f4](https://github.com/trezor/trezor-firmware/pull/2277/commits/2d797f4d04aef39581b633c6eb67a3550118591d)

![image](https://user-images.githubusercontent.com/42543243/180764173-ba94498d-abe5-41d0-a24b-7a8439e04c3c.png)
