### ISSUE TITLE
Model R: On device tutorial 

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#2428]
## Design
[Figma](https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=3354%3A11195) 

## Spec 
Inspired by [user research](https://www.notion.so/satoshilabs/Trezor-R-Firmware-prototype-round-2-9542844383eb486aa116c646f7347ac6)

### User Story
As a Trezor user
I want to know the base navigation functions
So that I use my device in confidence

### Acceptance criteria
Given I installed firmware on my Trezor
And my screen says "Go to trezor.io/start"
When I press 'Create new wallet' in Trezor Suite
And I press 'Standard seed backup'
Then I should see 'Hello Welcome to your Trezor' on device

Given I installed firmware on my Trezor
And my screen says "Go to trezor.io/start"
When I press 'Recover wallet' in Trezor Suite
And I press 'Start recovery'
Then I should see 'Hello Welcome to your Trezor' on device

Given I see 'Success' (last screen)
When I press Start
Then I should see 'Do you want to create a new wallet' or 'Do you really want to recover a wallet'

**Comment by grdddj** [comment]
Done in [7c88084](https://github.com/trezor/trezor-firmware/pull/2277/commits/7c8808418b48e05161fd2533689856d09a4fc6bd)
