### ISSUE TITLE
Deletion of ellipsis in backup creation screen on Model R

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2437]
Users are confused when one of the word with three dots (ellipsis) in backup creation appeared.

**proposed changes**

- [ ] delete the ellipsis
<img width="264" alt="imagetrseed" src="https://user-images.githubusercontent.com/57008159/182792564-a10b4b9d-52a6-46d2-82e2-990a76728544.png">

**Comment by grdddj** [comment]
Done in [017d3f0](https://github.com/trezor/trezor-firmware/pull/2277/commits/017d3f0160b4b194289146196644360aaf137476)
