### ISSUE TITLE
Model R: decide if/where/how to use scrollbars

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2441]
We have the ability to show "scrollbars" signaling to the user their current position inside some flow (long paginated paragraphs, BTC signing, tutorial etc.)

Currently, these scrollbars are shown only in the generic "confirmation" layout being used for all the questions and confirmations, in the form of small dots in the center of the very right:
![image](https://user-images.githubusercontent.com/42543243/183257914-3d16219e-dacd-4459-a2d4-b46b931a569a.png)

In Figma, I found them loosely designed as a part of a common flow like this:
![image](https://user-images.githubusercontent.com/42543243/183258148-4533ecc5-c98c-42c0-8e49-2e510ff1162b.png)

Things to decide on in this regard:
- in which cases to use them
- where to position them - right top horizontally, right side vertically, etc.
  - in top right it can be colliding with a title, so we need to make sure the titles do not get so long when using scrollbar
  - on the very right side it decreases the overall text area
  - (the dot itself is `4x4px`, and with `2px` padding around it occupies `8px` in one direction and roughly `(N+1)*4px` in the other direction )
- how to handle it in possibly veeeery long pagination, like some ETH contract with 100 pages

**Comment by Hannsek** [comment]
Solved with https://github.com/trezor/trezor-firmware/issues/2630.
