### ISSUE TITLE
Fee rate not displayed when replacing transaction

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#2442]
**Describe the bug**
#1294 implements fee rate for "sign transaction" flow.
Fee rate should probably be displayed on "modify fee" screen as well.

screenshots:
https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/2826526641/artifacts/test_ui_report/passed/TT_bitcoin-test_signtx_replacement.py::test_p2tr_fee_bump.html

**Comment by sime** [comment]
We have the space to include the fee rate?

Concept: https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=3539%3A10964

**Comment by matejcik** [comment]
this design is for the "total for transaction" screen, not for "modify fee" when replacing. screenshots: https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/2930791419/artifacts/test_ui_report/passed/TT_bitcoin-test_signtx_replacement.py::test_p2pkh_fee_bump.html
relevant screen copied so it doesn't expire again:
![image](https://user-images.githubusercontent.com/596073/186647139-9afd6acf-772b-4923-9d6e-d4e91057b61e.png)

with that said, the same concept should work here -- the screen fits exactly _one_ additional line, so if the fee rate does not have a heading of its own, it will work fine

**Comment by grdddj** [comment]
`QA` testing instructions:
- modify fee/replace transaction in `Suite` (or anywhere else) and check whether the `Modify fee` screen shows a fee rate in brackets below transaction fee - for example `(66.4 sat/vB)`

![image](https://user-images.githubusercontent.com/42543243/187422323-41ce3d3f-1d2f-43d6-9b36-8e94876bc0af.png)

**Comment by grdddj** [comment]
We might consider doing it also for `legacy`, the fee-rate is not shown there when replacing.

There is also one free row left, where we could fit it. Question is whether it is worth the effort...

![image](https://user-images.githubusercontent.com/42543243/187440941-0e481ade-f623-45e1-8d7e-ba30788460d9.png)

**Comment by matejcik** [comment]
this issue is also tagged legacy so I believe that applies, yes

**Comment by grdddj** [comment]
> this issue is also tagged legacy so I believe that applies, yes

Done in https://github.com/trezor/trezor-firmware/pull/2481

**Comment by STew790** [comment]
**QA OK**

Trezor T:
![image](https://user-images.githubusercontent.com/48477147/191280066-81939b0a-d285-4a24-8481-18e69e292194.png)
Trezor One:
![image](https://user-images.githubusercontent.com/48477147/191282452-95abfe84-3f22-43f7-8229-f54205985062.png)


**Info:**
 - Suite version: web 22.9.2 (cfeba9a3533ec7f4a5d4f31da4ac8c8b768547ed)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 4bed278e80d23077676128eba8cb2478fcd31120)
 - Device: model 1 1.11.3 Universal (revision 4bed278e80d23077676128eba8cb2478fcd31120)
 - Transport: bridge 2.0.32
