### ISSUE TITLE
The Monero website states that hardware wallets must be updated by Aug-14 to continue to have access to Monero.  Where is this required update at?

### ISSUE THREAD

**Issue by uj** [trezor/trezor-firmware#2452]
The Monero website states that hardware wallets must be updated by Aug-14 to continue to have access to Monero.  Where is this required update at?  I assume that our Monero funds are inaccessible without a hardware update?

**Comment by prusnak** [comment]
Firmware update for Trezor Model T will be released later today via the Trezor Suite update 22.8.x.
