### ISSUE TITLE
The mcudev dev kit: blank screen? but works...

### ISSUE THREAD

**Issue by sebek0F9** [trezor/trezor-firmware#2464]
going through the instructions by mcudev (seems old, 2018).
he mentioned to use trezor-core, but the repo is read-only now. so i cloned trezor-firmware and went into the core directory, and worked from there.

i built openocd from source, and st-link from source.
i handled the udev rules by hand (all is good here)

after some trial and error, i managed to install dependencies. finally, I was able to use the command below:
pipenv run make clean vendor build_boardloader build_bootloader build_firmware flash openocd_reset STLINK_VER=v2-1 **OPTIMIZE=-Og**
 (but i **couldn't do it with optimize=-Og:**....this is the last part that errored).

/trezor/arm-toolchains/arm-gnu-toolchain-11.3.rel1-aarch64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld: build/boardloader/boardloader.elf section `.text' will not fit in region `FLASH'
/trezor/arm-toolchains/arm-gnu-toolchain-11.3.rel1-aarch64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld: section .capabilities LMA [000000000800bf00,000000000800bf1d] overlaps section .text LMA [00000000080001ac,000000000800c2c7]
/trezor/arm-toolchains/arm-gnu-toolchain-11.3.rel1-aarch64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 3728 bytes
collect2: error: ld returned 1 exit status
scons: *** [build/boardloader/boardloader.elf] Error 1
make: *** [Makefile:141: build_boardloader] Error 2

without optimize, it worked ( i think? here are the last parts when it flashed)

dd if=build/firmware/firmware.bin of=build/firmware/firmware.bin.p1 skip=0 bs=128k count=6
6+0 records in
6+0 records out
786432 bytes (786 kB, 768 KiB) copied, 0.00540997 s, 145 MB/s
openocd -f interface/stlink.cfg -c "transport select hla_swd" -f target/stm32f4x.cfg -c "init; reset halt; flash write_image erase build/boardloader/boardloader.bin 0x08000000; exit"
Open On-Chip Debugger 0.11.0+dev-00808-g9cd714cd1 (2022-08-18-19:34)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : clock speed 2000 kHz
Info : STLINK V2J39M27 (API v2) VID:PID 0483:3752
Info : Target voltage: 2.880562
Info : [stm32f4x.cpu] Cortex-M4 r0p1 processor detected
Info : [stm32f4x.cpu] target has 6 breakpoints, 4 watchpoints
Info : starting gdb server for stm32f4x.cpu on 3333
Info : Listening on port 3333 for gdb connections
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x08005048 msp: 0x10010000
Info : device id = 0x20036419
Info : flash size = 2048 kbytes
Info : Dual Bank 2048 kiB STM32F42x/43x/469/479 found
openocd -f interface/stlink.cfg -c "transport select hla_swd" -f target/stm32f4x.cfg -c "init; reset halt; flash write_image erase build/bootloader/bootloader.bin 0x08020000; exit"
Open On-Chip Debugger 0.11.0+dev-00808-g9cd714cd1 (2022-08-18-19:34)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : clock speed 2000 kHz
Info : STLINK V2J39M27 (API v2) VID:PID 0483:3752
Info : Target voltage: 2.883373
Info : [stm32f4x.cpu] Cortex-M4 r0p1 processor detected
Info : [stm32f4x.cpu] target has 6 breakpoints, 4 watchpoints
Info : starting gdb server for stm32f4x.cpu on 3333
Info : Listening on port 3333 for gdb connections
target halted due to breakpoint, current mode: Thread 
xPSR: 0x61000000 pc: 0x20000044 msp: 0x10010000
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x08005048 msp: 0x10010000
Info : device id = 0x20036419
Info : flash size = 2048 kbytes
Info : Dual Bank 2048 kiB STM32F42x/43x/469/479 found
openocd -f interface/stlink.cfg -c "transport select hla_swd" -f target/stm32f4x.cfg -c "init; reset halt; flash write_image erase build/firmware/firmware.bin.p1 0x08040000; flash write_image erase build/firmware/firmware.bin.p2 0x08120000; exit"
Open On-Chip Debugger 0.11.0+dev-00808-g9cd714cd1 (2022-08-18-19:34)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : clock speed 2000 kHz
Info : STLINK V2J39M27 (API v2) VID:PID 0483:3752
Info : Target voltage: 2.883373
Info : [stm32f4x.cpu] Cortex-M4 r0p1 processor detected
Info : [stm32f4x.cpu] target has 6 breakpoints, 4 watchpoints
Info : starting gdb server for stm32f4x.cpu on 3333
Info : Listening on port 3333 for gdb connections
target halted due to breakpoint, current mode: Thread 
xPSR: 0x61000000 pc: 0x20000044 msp: 0x10010000
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x08005048 msp: 0x10010000
Info : device id = 0x20036419
Info : flash size = 2048 kbytes
Info : Dual Bank 2048 kiB STM32F42x/43x/469/479 found
openocd -f interface/stlink.cfg -c "transport select hla_swd" -f target/stm32f4x.cfg -c "init; reset; exit"
Open On-Chip Debugger 0.11.0+dev-00808-g9cd714cd1 (2022-08-18-19:34)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : clock speed 2000 kHz
Info : STLINK V2J39M27 (API v2) VID:PID 0483:3752
Info : Target voltage: 2.884778
Info : [stm32f4x.cpu] Cortex-M4 r0p1 processor detected
Info : [stm32f4x.cpu] target has 6 breakpoints, 4 watchpoints
Info : starting gdb server for stm32f4x.cpu on 3333
Info : Listening on port 3333 for gdb connections
target halted due to breakpoint, current mode: Thread 
xPSR: 0x61000000 pc: 0x20000044 msp: 0x10010000
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz

after this the kit restarted, and the external touch screen lit up, but i don't see anything on the screen. if i touch the screen it responds, it dims, lights up, and lsusb shows generic trezor.
if i pop in an sd card, the external touch screen restarts. still nothing.
all i see is the backlight.....
on mcudev's website, step 13, ./trezorctl wipe_device works but it is waiting for me to confirm. i try to touch the screen in some random areas but im guessing i should be seeing a step-by-step instruction here. 

what am i doing wrong. please help.

**Comment by sebek0F9** [comment]
Sorry for the code label, let me add some detail.

I’m using the newer gcc-11, gcc-arm-none-eabihf. The tutorial uses  gcc-7? 

wipe_device and “make gdb_boardloader” complained about a missing libpython3.8.so.1. No problem, I used pyenv. (An awesome tool for managing python versions and virtualenvs).

**Comment by prusnak** [comment]
Yes, try that please

**Comment by sebek0F9** [comment]
Hey. Unfortunately, it didn’t work. I removed the built in LCD and SRAM. pretty sure I didn’t bridge any pins. Actually now without the SRAM, I can’t see “Generic SATOSHILABS trezor” when I do lsusb. Only the st-link.

did a fresh clone of the repo also and rebuild. Installed dependencies one at a time on each fail, 
via “pipenv install” in the core directory: click, trezor[ethereum,hidapi] (for trezorlib),  mako, munch. 

saw something new this time, that the compile asked for rust/cargo nightly build for -Z option. 

The result is the same except for lsusb output. The touchscreen light is on, it reacts to touch, but it’s just white. It resets when I pop in a blank card.

**Comment by sebek0F9** [comment]
Hm, I can see it in lsusb now.

**Comment by sebek0F9** [comment]
Has the 

PE11 and PC5 , and PB10 are still considered unpopulated right?

I connected all pins shown on the spreadsheet : for the display, touch screen, and micro SD socket .(except  SD_ON / PC0, the waveshare board doesn’t have this pin)

forgive me being novice, trying to be as detailed as possible. Thanks for reading

**Comment by sebek0F9** [comment]
Ok, I tried using an altinstall of python3.8 systemwide without pyenv . 

 I still have the white screen, but, I seem to have more access to gdb / debugging. It no longer says read-only for the breakpoints, but on a Couple of those commands listed in the tutorial, it says “program is not running”. The LED was yellow this time instead of flashing red/green

**Comment by sebek0F9** [comment]
Just updating my fails :(

I tried using another OS (Armbian)
I tried gcc arm eabi and also eabihf

tried it without pipenv 
Tried as root

It would be awesome to have pure cli tools, because the device is definitely registered and I can get into boot loader (I also tried the firmware update, which just gave me an unresponsive screen that time. )

When I try device reset I must continue on the touch screen , sadface.

The optimize -Og always shows overflowed FLASH each time

**Comment by sebek0F9** [comment]
I must be doing something obviously wrong. Very frustrating, anyway, I can’t think of anything else to try for now. 

Thanks anyway. I noticed a commit for core/rust, I was wishing it was for this.

**Comment by sebek0F9** [comment]
Some updates: 

Im trying without pipenv now at all, and only using pip3.9 as user. I found out that in the virtualenv, Trezorlib is using 0.9.3, and unless the Debian PAckage installed, I will get a build error of “cosi from trezorlib not found” from headertool.py. the trezor source code I found a file it says 0.13.4, so I think I should ditch pipenv and ideally any apt/Debian packages, only using pip.

That’s all for now. I’ll update

**Comment by sebek0F9** [comment]
I just noticed upon inspecting the touch screen module.

before I say what…..
i specifically requested from that guy on eBay, selling the ER-TFTM028-4 module for the 8080 8-Bit configuration at 3.3V, as per the instructions.

I am annoyed to find out that upon

**Comment by sebek0F9** [comment]
This is the capacitive touch panel manual. https://www.buydisplay.com/download/manual/ER-TFTM028-4_Datasheet.pdf

I checked section 4.3, page 13 for interface configurations. (J pin bridges/or shorts, and 0-ohm resistor / or open pad)

here’s a picture of mine. I specifically requested and selected for the 8080, 8-bit, 3.3V. Correct me if I’m wrong, but this looks like 4-wire spi accoeding to the data sheet. 

I’m upset.

![0FC107A5-1DA7-4B09-BF50-5D42A66B6E9C](https://user-images.githubusercontent.com/109636390/188032487-9fa9e4f0-f07e-4970-bd27-90454f548c6e.jpeg)

**Comment by invd** [comment]
I've had a brief look at the linked datasheet and compared it to your image of the board. It indeed looks like you have bought a compatible basic model (capacitive touchpad with internal controller via i2c on CON3, flex cable connector CON1 unpopulated) but that is set up for the wrong display communication mode and voltage.

To me, this is a plausible explanation why the prototype device reacts to touch screen events but fails to displays something meaningful on the TFT screen. So yes, this could be your problem.

If you are experienced with SMD soldering, I think you should be able to reconfigure the 0 ohm resistors and solder bridges to bring the display into the required parallel mode variant and select 3.3V operation.

Based on mcudev's PCB pictures and the datasheet descriptions, the resistors on R1-R10 shouldn't be a problem (upper right yellow arrow in your image) but please re-check that yourself.

Alternatively, ordering a second, correctly configured board may be worth it to avoid spending more time on the hardware debugging if you're concerned that the display has been damaged somehow already.

**Comment by invd** [comment]
As a quick side note: the Trezor T firmware is growing more and more towards the flash limits during development (see efforts like https://github.com/trezor/trezor-firmware/pull/2327) so it looks plausible to me that when mcudev's TREZOR Model T Dev Kit guide was written, the `-Og` optimization mode that optimizes for debug instead of performance or size still resulted in a working firmware, but that this has changed over the years.

Leaving out `OPTIMIZE=-Og` should make the compilation default to a more firmware-size-optimized `-Os`, which is probably what you want unless you're tracking down specific bugs.

Generally, I recommend being very careful around which firmware variant you flash since uploading and running the wrong firmware once will permanently lock the hardware debug capabilities.

**Comment by sebek0F9** [comment]
Thank you for responding. 

I’d be afraid to order from that seller again, i think they would send me the wrong configuration again despite my request.

I’ll try to change the configuration, I think I can do it, I’ve had some practice. 

I compiled several times and noticed the -0s flag in the terminal. Also saw production=0 many times. I don’t know if I’ve ever made a mistake, though. Maybe out of all those times, production was =1? 

how can I test and check if my debug capabilities are locked or not?

It’s locked permanently? Can’t unlock by reflashing, or openocd unlock? Or factory default firmware/files?

**Comment by invd** [comment]
@sebek0F9 I recommend re-reading the "Warning" and "Hardware - Questions" sections on https://mcudev.github.io/trezor-model-t-dev-kit/ which describe this.

> It’s locked permanently?

Yes, the goal of the normal production firmware is to disable any kind of debug access with no intended method of re-enabling it ever again.

**Comment by sebek0F9** [comment]
Hey, I made progress. I changed the display configuration by soldering the correct jumpers. I saw the trezor screen!  But only on one power up!!! 
I couldn’t tap past the unsafe firmware screen. Back to the white screen.

Also, the backlight looks a lot better.
Thank you for your responses, I appreciate it. I’ll keep trying.

**Comment by sebek0F9** [comment]
![Uploading 7541A3ED-79FE-4AC3-97C0-AAA55D0EBBDC.jpeg…]()

**Comment by sebek0F9** [comment]
I 
![77B19146-BB57-4DB3-BCA5-4B71ECF758AF](https://user-images.githubusercontent.com/109636390/188255079-60af5c2c-a1ef-4e65-8b63-711ad29db981.jpeg)

**Comment by matejcik** [comment]
Hello, unfortunately this is not a tech support forum for debugging custom dev kits :(
Trezor subreddit or Trezor Forum might be more appropriate, although also less likely to attract an audience technical enough to help.

I am closing the issue, feel free to continue to talk here, but in terms of planning this is something we will not be taking into consideration.

**Comment by sebek0F9** [comment]
Then why is the dev kit in the hardware docs? 

Okay then, bye

**Comment by sebek0F9** [comment]
I bought another one and it works now. I configured 3.3V jumper and J1-J8 before connecting anything . 

Damn that seller with his contradicting info. Thanks to those who helped me with feedback .
