### ISSUE TITLE
Ed25519 OpenSSH FIDO key setup fails

### ISSUE THREAD

**Issue by memoryhash** [trezor/trezor-firmware#2474]
**Describe the bug**
I am trying to setup FIDO for OpenSSH with my Trezor Model T, and cannot setup an ```ed25519-sk``` SSH key. It seems that infrastructure for Ed25519 is present in the firmware, so this looks like a bug. I am able to setup an ```ecdsa-sk``` SSH key just fine.

**Firmware version and revision**
Universal 2.5.2

**Desktop setup**
- OS: Windows 11 Enterprise (22000.856)
- OpenSSH:  ```ssh -V``` prints ```OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3``` (64 bit)

**To Reproduce**
Steps to reproduce the behaviour:
1. Install latest OpenSSH for Windows from [here](https://github.com/PowerShell/Win32-OpenSSH/releases/latest)
2. Add ```C:\Program Files\OpenSSH``` to the front of system PATH (verify with ```ssh -V```)
3. Open Windows Terminal and type ```ssh-keygen -t ed25519-sk```
4. Follow steps on screen. OK -> OK -> press tick on Trezor
5. Observe ```Key enrollment failed: invalid format```

**Expected behavior**
Being able to generate an ```ed25519-sk``` SSH key.

**Comment by andrewkozlik** [comment]
This is issue is not related to Trezor. OpenSSH uses libfido2 and in order for that library to work with ed25519 you need to link against OpenSSL not LibreSSL. This is a known issue in libfido2 https://github.com/Yubico/libfido2/issues/144. This [comment](https://github.com/Yubico/libfido2/issues/144#issuecomment-593838274) in the issue explains why.
