### ISSUE TITLE
Broken Links in docs firmware repository

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#2477]
Please see https://www.notion.so/satoshilabs/Broken-Links-docs-FIRMWARE-7fd9e24c7c7a422db16eef6a859de0b4
There are multiple broken links in https://docs.trezor.io/trezor-firmware/ that i found.
It's beyond my skill to fix all in `docs` section.

**Comment by mmilata** [comment]
We could add https://github.com/Michael-F-Bryan/mdbook-linkcheck to CI checks, but we'd have to deal with false positives somehow. Or maybe just render the docs to html and check it with `wget`?

**Comment by bosomt** [comment]
**QA OK** 🎉
