### ISSUE TITLE
Display only `sat` instead of `sat BTC`

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-firmware#2487]
> How about we leave only "sat" for Bitcoin and "sat [coin]" for all the others?

_Originally posted by @tsusanka in https://github.com/trezor/trezor-firmware/issues/1369#issuecomment-763822533_

**Comment by STew790** [comment]
**QA OK**
Both T1 and TT are correctly showing only `sat` when sending BTC with this unit selected.

**Info:**
 - Suite version: web 22.9.2 (cfeba9a3533ec7f4a5d4f31da4ac8c8b768547ed)
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
- OS: Linux x86_64
- Screen: 1920x1080
- Device: model T 2.5.3 Universal (revision https://github.com/trezor/trezor-firmware/commit/4bed278e80d23077676128eba8cb2478fcd31120)
- Device: model 1 1.11.3 Universal (revision https://github.com/trezor/trezor-firmware/commit/4bed278e80d23077676128eba8cb2478fcd31120)
- Transport: bridge 2.0.32
