### ISSUE TITLE
enter fake decoy words when recovering TREZOR MINI

### ISSUE THREAD

**Issue by europound** [trezor/trezor-firmware#2491]
**Design:** [Figma](TODO)
random entrance of seed words is not enough for brute force crackers
add:
type in fake decoy word from wordlist generated by trezor mini
let's say for each true seed word add randomly extra 5 words or so
so 24 seed phrase + 24*5 fake words
randomize sequence
feature for trezor mini

**Comment by matejcik** [comment]
just use advanced recovery
