### ISSUE TITLE
25th word passphrase on trezor mini

### ISSUE THREAD

**Issue by europound** [trezor/trezor-firmware#2495]
**Design:** [Figma](TODO)

attach a pin to a 25th word just like on ledger

for now you cannot enter 25th word without a computer

**Spec:** [Notion](TODO)

**Comment by prusnak** [comment]
We don't like this feature and such won't be implemented. Also this is a GitHub repository for Trezor, not for its counterfeit clones.

**Comment by europound** [comment]
what? do you think it is better to type in 25th word? not!
