### ISSUE TITLE
Rust UI: homescreen, lockscreen

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-firmware#2498]

**Comment by TychoVrahe** [comment]
QA: please try uploading few (dozens) randomly found 240x240 jpegs and report any that does not work, crashes the FW or does something else unexpected

**Comment by Hannsek** [comment]
@TychoVrahe What is the biggest possible size of the image? 13kB?

**Comment by TychoVrahe** [comment]
16kB

**Comment by TychoVrahe** [comment]
16kB
