### ISSUE TITLE
TT redesign: special screens for altcoins

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-firmware#2500]
most altcoin functionality is covered by `confirm_text` / `confirm_blob` / `confirm_properties`.

However, there are several custom screens:
* `confirm_total_ethereum` -> should be converted to a sequence of "confirm fee" -> "confirm fee" -> "confirm total" or something along these lines
* `confirm_total_ripple` -> should be removed in favor of "confirm output" -> "confirm fee" -> "confirm total"
* `confirm_transfer_binance` -> should be converted to `confirm_properties` for inputs, `confirm_output` for outputs. Unfortunately there doesn't seem to be a sensible way to show total, so some sort of "really confirm? (hold)" with no further info is probably the way to go.
* `confirm_decred_sstx_submission` -> figure something out? probably a `confirm_properties`?

**Comment by grdddj** [comment]
Below are the custom screens in their current look.

To make sure, the goal here is to make it look exactly the same, or just "somehow make it work"?

![image](https://user-images.githubusercontent.com/42543243/189884974-dbfe21c7-fd3e-4d6d-80eb-abf17a6f52aa.png)
![image](https://user-images.githubusercontent.com/42543243/189885314-17aa4076-bf05-46c9-878e-8d991831c02a.png)
![image](https://user-images.githubusercontent.com/42543243/189885031-e92583c6-6325-40e6-b132-90d112b939e8.png)
![image](https://user-images.githubusercontent.com/42543243/189885058-dc2eb261-5d7d-4470-a096-fa9df5554462.png)
![image](https://user-images.githubusercontent.com/42543243/189885010-09f78cb1-84b3-42d6-910a-71eaf3b2b90b.png)

**Comment by grdddj** [comment]
Done in https://github.com/trezor/trezor-firmware/pull/2545
