### ISSUE TITLE
FIDO2 with invity.io logo

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2528]
"can we put a PNG invity logo in there?"

![image](https://user-images.githubusercontent.com/57008159/192571127-e0ecbb5a-5d9a-476d-8ecc-a3741690179f.png)

related: https://github.com/trezor/trezor-firmware/pull/1529

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.10.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision e7ff43272ccae49fe4b1dcf198ed51c82d7c1472)
 - Transport: bridge 2.0.31
