### ISSUE TITLE
Is it possible to disable user confirm for each transaction sign?

### ISSUE THREAD

**Issue by vlddm** [trezor/trezor-firmware#253]
Need to send a lot of transactions, would be nice to have an option to disable user confirmation for some time or for few whitelisted addresses. 
Can it be done without patching firmware?
If no, where is the best place in code to patch?
Thx

**Comment by tsusanka** [comment]
This is currently not supported and we do not plan to.

-----

You can patch the firmware yourself, but be advised that your build won't be signed by us and therefore the device will get wiped in case you upload your own firmware. You'd have to enter the seed again.

> If no, where is the best place in code to patch?

Probably here and maybe few other places:
- https://github.com/trezor/trezor-firmware/blob/master/core/src/apps/wallet/sign_tx/signing.py#L109
- https://github.com/trezor/trezor-firmware/blob/master/core/src/apps/wallet/sign_tx/signing.py#L208 
- https://github.com/trezor/trezor-firmware/blob/master/core/src/apps/wallet/sign_tx/signing.py#L170

-----

Please be careful.
