### ISSUE TITLE
FIDO layouts

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-firmware#2532]

**Comment by bosomt** [comment]
**QA OK**

Works as expected /tested on Google and GitHub account/
Noted one thing, that register / authenticate message and web log/name is not properly aligned but its probably expected /it matches screenshots from PR/

<img width="362" alt="image" src="https://user-images.githubusercontent.com/31506317/207592295-af1b5512-1c67-4745-a538-05afa03140da.png">

<img width="347" alt="image" src="https://user-images.githubusercontent.com/31506317/207592340-da8859bf-6a0d-4dcc-8327-a978d5efa9c3.png">


**Info:**
 - Suite version: desktop 22.12.1 (ddaacdb2245d7a909b3d2abfe918cff34d2e1609)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision ff35c77bad82c7acac1df6245940ebe0d6454642)
 - Transport: bridge 2.0.32

**Comment by Hannsek** [comment]
@mmilata Did you fix the layout? (https://satoshilabs.slack.com/archives/C02BY51RD8R/p1669232972198689)

**Comment by mmilata** [comment]
No

**Comment by Hannsek** [comment]
Then please fix the layout.
