### ISSUE TITLE
Add trezorctl command for screen capture

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2547]
To make screenshotting/UI visual testing easier, it is worth creating a `trezorctl` command that tells `Trezor` to save screenshots into a specified directory

**Comment by prusnak** [comment]
Is that for emulator only?

**Comment by grdddj** [comment]
> Is that for emulator only?

I think so. It would be really nice if it worked with hardware device in `debug` mode, but I do not think it does - it would need to send the data through `USB` and something would need to save it on the host. I will however try

**Comment by grdddj** [comment]
Done in https://github.com/trezor/trezor-firmware/pull/2548
