### ISSUE TITLE
Analyze moving all micropython code into Rust

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2550]
As `micropython` environment takes almost `200 kb` of flash space (which is very scarce to us), it might be a possibility to save this space by replacing all the `micropython` code with `Rust`.

It can be a next logical step after we will have a stable and reliable `UI` in `Rust` (together with boot sequence in `Rust` and other things like this).

Some quick starting notes:

General:
- there is circa `32_000` single-lines-of-code in `core/src` (excluding docstrings and empty lines) - according to https://pypi.org/project/pygount/
- https://pypi.org/project/python-rs/ seems to be quite handy for quick-and-dirty python-to-rust syntax migration
  - just running `pyrs src` will create a `src-pyrs` dir with all the `.py` files from `src` transformed to `.rs`
  - most if not all of these files would need manual treatment to compile/work well, but is a nice option to quicken the migration process

Pros:
- we would save a lot of flash space accounting for `micropython` env right now (and some of the currently needed `micropython` bindings in `C` )
- we would have absolute control over the code (not being limited by `micropython` internals) - for example ability to inline functions etc.
- the type-safety of `Rust` could find/eliminate some hidden bugs (we would not need to use `pyright`, `flake`, `pylint` etc. - `Rust` compiler should take care of everything (with the help of `clippy`))

Cons:
- it would probably take a lot of time - weeks/months - to complete the whole rewrite, and testing it properly
- it could be then harder to contribute for external contributors (likes of `Cardano`), who can now quite easily add/change features in `python` style, they would need to switch to `Rust`
- very low-level crypto operations like in `Monero` could be hard to do
- it might not even work for some unexpected technical reason

Other considerations:
- we would need much better `Rust` string handling than we currently have
- `Rust` exception handling works differently than the `python` ones
- would we be still alright with `no-std` `Rust` - and couldn't we even use the "full"-one, when we would have more flash space?
- it would probably not be possible to run the code from the source (real-time `micropython` interpretation)
- as `gdb` does not work with `micropython`, it could give us more debugging capabilities

Possible next steps:
- trying to create some `MVP` - with the basic event loop and some `Hello world` application doing some small calculation and layout interaction

**Comment by hynek-jina** [comment]
It's a bigger project.. Let's plan that first..
