### ISSUE TITLE
each icon (for IconDialog) takes 0.5K of flash, we need to either figure out how to represent three-color image more efficiently than 16bpp, or draw them procedurally

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#2558]

**Comment by prusnak** [comment]
> three-color image

Which images are these?

**Comment by matejcik** [comment]
![image](https://user-images.githubusercontent.com/596073/195597907-ac79b038-ac00-4806-8f06-56099009e295.png)

black background + yellow triangle + white excl mark + alpha-blends on borders
to save space, we need to compose "4bpp triangle" + "4bpp excl mark" (as opposed to rgb565 of the whole thing)

**Comment by prusnak** [comment]
I think we could create a function that takes a list of tuples with icon data and combines these together?

Something like:

```
combine_icons(x, y, w, h, background_color, icons)
```

where icons is a list of tuples: `(icon_x, icon_y, icon_data, render_color)`

**Comment by matejcik** [comment]
yes, that is probably the solution. we could not do this before however, because before #2471 we did not have the capability to blend icons over one another

**Comment by prusnak** [comment]
> we did not have the capability to blend icons over one another

I meant the software blending. The `combine_and_render_icons` functions would go over pixels and compute each pixel color.

``` python
for yy in range (h):
   for xx in range(w):
      color = 0
      for icon in icons:
         c = compute_icon_color(icon, xx, yy)
         color += c
      color /= len(icons)
      push_pixel_data_to_display(color)
```
