### ISSUE TITLE
Add Proton mail profile to Trezor firmware

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#2560]
Recently Proton enabled two-factor authentication keys (2FA keys) login and Trezor works as expected.
So we can add U2F definition to our firmware.

https://proton.me/blog/security-keys

<img width="281" alt="image" src="https://user-images.githubusercontent.com/31506317/195783312-efbec5a8-9fc3-41f6-b15d-618fd8ce51bd.png">

**Comment by prusnak** [comment]
JFYI

```
>> hashlib.sha256(b"proton.me").hexdigest()
'a259c2b50d785080f8be7f17caf8156c8d18f47edbaf518fa6f59f29cd28f15c'
```

**Comment by prusnak** [comment]
PR in https://github.com/trezor/trezor-firmware/pull/2563

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.10.2 (4fecea60b5c0f2777708c67640375a753bd49234)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.10.2 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 498422ce5db85a9a279f6e8c8fce659cd12ea679)
 - Transport: bridge 2.0.31
