### ISSUE TITLE
Loader draws over homescreen when accessing wallet - TT UI2

### ISSUE THREAD

**Issue by TychoVrahe** [trezor/trezor-firmware#2574]
When wallet is accessed and the `get_seed` function draws a loader, it does it on top of homescreen causing ugly looking mess.

Probably the display should be cleared first? 

Observing this on TT UI2. 

To reproduce just init the device and access standard wallet.

**Comment by bosomt** [comment]
**QA OK**

 - Device: model T 2.5.4 Universal (revision 305b7fe84d802db7f0826d07a222a886f73732f0)
