### ISSUE TITLE
Trezor R PIN selection screen shuffling

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2599]
Edit the behaviour of shuffling the numbers on PIN selection screen for model R.

Stay on selected number and shuffle every other numbers.

**Comment by grdddj** [comment]
Done in https://github.com/trezor/trezor-firmware/commit/a8cb21e349969fd5e07a7f5bc95b64221ebd1564

![image](https://user-images.githubusercontent.com/42543243/199941523-add66b8b-1bde-424e-9fa6-b84d46b62333.png)
