### ISSUE TITLE
Shamir backup firmware error during backup

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#260]
Empty Trezor with 2.1.2

Do you want to create Shamir wallet ? 
Create.
Skip backup:

Failed to create wallet
And after you reconnect device:
Reading of accounts failed.
Error details: Firmware error

See screenshot:
![shamir](https://user-images.githubusercontent.com/31506317/60075157-f960d380-9724-11e9-8093-7eebbdc27638.png)

**Comment by tsusanka** [comment]
This is on wallet side, but I'll communicate it with zorwy.

**Comment by tsusanka** [comment]
Fixed in https://github.com/trezor/trezor-firmware/commit/10e5ec61359ac7f91464d8a07db94498a111a9d7
