### ISSUE TITLE
TR design

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2601]
Tasks that are required for Bitcoin only firmware have priority.

- [ ] Bootloader https://github.com/trezor/trezor-firmware/issues/2605
- [ ] Onboarding
     - [ ] Tutorial #2620
     - [ ] Seed backup
     - [ ] Pin
- [ ] Recovery
     - [ ] # of words
     - [ ] Word entry
- [ ] Initialized
     - [ ] Homescreens
     - [ ]  Generic screens
- [ ] Send & Receive
- [ ] Loading screen https://github.com/trezor/trezor-firmware/issues/2622

**Comment by hynek-jina** [comment]
We will try to use milestone instead of this epic:
https://github.com/trezor/trezor-firmware/milestone/38
