### ISSUE TITLE
T2B1 design - bootloader

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2605]
Design: https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=3790%3A11545

<img width="540" alt="image" src="https://user-images.githubusercontent.com/57008159/203309111-0cb89413-3871-466f-8b70-e16911b09a6a.png">

<img width="729" alt="image" src="https://user-images.githubusercontent.com/57008159/203310452-d0431b69-9f2c-41dc-bae9-6d680c78ba66.png">

FW-less:
<img width="589" alt="image" src="https://user-images.githubusercontent.com/57008159/203311999-d011f034-dc8b-4729-85ec-27a2a4c5246b.png">

**Comment by TychoVrahe** [comment]
Some feedback:
from firmware perspective, it would be beneficial to have the same flow as in model T - keeps things nicely united, less error prone and easier to maintain. This means either removing the initial bootloader warning on TR or adding it in TT, and then have screen with enter menu/ install fw actions like this:
![20221111_151818](https://user-images.githubusercontent.com/37884576/203006326-205064eb-e553-4a6d-8636-7633429003e1.jpg)
(this would also require addition icon design for exit menu item)

Confirming menu actions: we dont use hold to confirm on TT, no need to do it here (its unnecessary complication). Reboot action does not have to be confirmed at all.

See comparison of progress bar/spinner. The spinner is nice and the transition in success screen is smooth, but the beginning with no circle around the icon is weird.
![20221111_153715](https://user-images.githubusercontent.com/37884576/203008199-27602dae-4cb6-415f-803f-7ed0c8ffd1dd.jpg)
![20221111_153907](https://user-images.githubusercontent.com/37884576/203008316-bad2422b-84c5-4a49-885b-4091cda1dc09.jpg)

The mono font is problematic at some screens, see (mainly the phrase 'UNSAFE, DO NOT USE!' doesn't fit one line:
![font2](https://user-images.githubusercontent.com/37884576/203009494-1805b8e5-bffa-415e-92d0-0e1b0a693d55.jpg)
![font1](https://user-images.githubusercontent.com/37884576/203009497-3bdf0198-084c-4971-a04c-c341ad89d696.jpg)

**Comment by Hannsek** [comment]
Noted, new design in progress.

**Comment by Hannsek** [comment]
Design in original comment updated.
@TychoVrahe Please do two versions of bootloader with different types of font (mono, normal) so that we can compare them.

**Comment by Hannsek** [comment]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/57008159/207308652-be784189-3469-4757-aa29-4209b76e4157.png">

**Comment by Hannsek** [comment]
Two icons of _trash_ and _exit_ uploaded:
![trash](https://user-images.githubusercontent.com/57008159/207621759-97a7c875-ec86-4ba8-bfd0-62accd2afc2b.png)
![Union](https://user-images.githubusercontent.com/57008159/207621762-9f45b033-7591-4f57-9429-789705864cc9.png)

**Comment by Hannsek** [comment]
rsod screens + wipe code screen: 
<img width="628" alt="image" src="https://user-images.githubusercontent.com/57008159/219066248-c3d165ea-a2e8-4f57-b597-103cac7352dc.png">
<img width="208" alt="image" src="https://user-images.githubusercontent.com/57008159/219066352-72f5542d-5718-4f4b-9041-2c8c60c727b9.png">
