### ISSUE TITLE
Unify all the screens being shown in TT and TR

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2609]
In the new `model R` design, we want to show some new information (new dialogs, new screens) that are not existing in  `model T` (in the old `UI` nor in the redesigned `UI2`).

Examples:
- `PIN will be used to access this device.It should contain at least 6 digits.`
- `Write all words in order on recovery seed card. Do NOT make digital copies.`

It would be better if all the models would show the very same information.

Benefits:
- not having to branch the "core" logic - we could reuse all the  "non-UI" code and just the displaying itself would be model-specific
- having all the strings at one place, easy to update
- all the models would send the same `button requests` (important for `Suite` and tests)

This would probably increase its importance when `T3` comes - the more models we have, the more chaos would be caused by differences in what they show and multiple places to update it all.

With the `TT redesign` release in January, we should probably agree quite soon and possibly incorporate all these things from `TR` into `TT redesign` as well - otherwise then `TR` release would mean changes for `TT`.

**Comment by Hannsek** [comment]
No need for issue. We will be looking at that continuously.
