### ISSUE TITLE
Set the threshold screen - redrawing error

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-firmware#261]
TT 2.1.2, 1ec5d091
https://mytrezor.corp.sldev.cz/feature/shamir-backup/development/
Set the threshold screen

Steps to reproduce:
- navigate through the Shamir backup process until you reach the set the threshold screen
- set the threshold over 10
- set the threshold lower than 10

Expected:
The screen is redrawn correctly and does not show any graphical errors.

Actual:
A graphical error is displayed, see the screenshot below.
![image](https://user-images.githubusercontent.com/10185314/60080753-cf151300-9730-11e9-994b-162b403dcadf.png)

**Comment by andrewkozlik** [comment]
Same bug appears in _Set number of shares_ screen. Also note the redrawing bug in the words "sharess" and "locationss".

**Comment by jpochyla** [comment]
Fixed in 4d0fe4d06404ffa9a3f47ac4eb22ed898a85703e
