### ISSUE TITLE
T2B1 design - Tutorial

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2620]

**Comment by Hannsek** [comment]
![image](https://user-images.githubusercontent.com/57008159/200583684-71847582-d7f8-4429-8286-78d90f31c458.png)

**Comment by Hannsek** [comment]
063 - dot-arrow missing
067 - change the copy to _Tutorial finished._
![image](https://user-images.githubusercontent.com/57008159/201596853-c96e3ee3-9958-4d85-8746-023f6a154bd1.png)

**Comment by Hannsek** [comment]
Change `got it` to `continue`.

**Comment by grdddj** [comment]
A proposal:
- do not show tutorial when doing backup/recovery
- show it when the device is uninitialized and is connected to the computer
