### ISSUE TITLE
T2B1 design - PIN, wipecode

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2636]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/57008159/208422235-f76e9880-d36f-40db-a16a-c1222236c5f3.png">

`15 tries left` will not be visible when setting up the PIN.
It will show up after the first unsuccessful attempt.

**Comment by grdddj** [comment]
Nice, I like that we are showing the prompt and trials left in the missing header - I currently have a screen before showing this info.

With the `CHECK PIN: please re-enter`, that might not be necessary right now, as the prompt will say `Re-enter PIN`.

Just to make sure, I am starting the numbers from 0.

Note to myself - I need to update the `eye` icon, I have the old version

**Comment by Hannsek** [comment]
`CHECK PIN: please re-enter` is mandatory from the user POV.

Starting the numbers from 0 is fine.

**Comment by grdddj** [comment]
Current state of the PIN setting after [73458cb](https://github.com/trezor/trezor-firmware/pull/2610/commits/73458cb407314f8994bca5b3722babf1e0019980):

![image](https://user-images.githubusercontent.com/42543243/201721118-3c52ac5c-5076-457d-bbbc-dceaec2690fc.png)

**Comment by Hannsek** [comment]
114, 115 - copy is bold, missing "PIN" in copy -> _Please re-enter PIN to confirm_

**Comment by Hannsek** [comment]
Changed copy on PIN screen: 
<img width="284" alt="image" src="https://user-images.githubusercontent.com/57008159/224004815-e6037bb9-8ff3-4a9a-a078-6019f3c5c118.png">
It should be at least 4 digits long --> PIN should be 4-50 digits long.

**Comment by grdddj** [comment]
Currently looks like this:

![image](https://user-images.githubusercontent.com/42543243/224048051-e6440541-f345-43fb-ad35-54bd83a60bc3.png)

Is it alright, or do we want to make it pixel-perfect with Figma?

**Comment by Hannsek** [comment]
The letters seems off. Also the positioning of the paragraphs is weird. Can we make it like this?
<img width="186" alt="image" src="https://user-images.githubusercontent.com/57008159/224062438-fe9d5618-5748-404d-a0d0-66fa9b550cc5.png">

**Comment by grdddj** [comment]
I could do this with minimal changes:

![image](https://user-images.githubusercontent.com/42543243/224078569-d8c65b73-e1af-4969-9885-84cca9129a42.png)

It currently uses the general way of rendering text, but we should be able to create a specific, "hard-coded" version just for this flow. Will try it

**Comment by Hannsek** [comment]
We should get rid of the first two arrows.
