### ISSUE TITLE
Drop Trezor 1 UI from trezor-core

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#2639]
There is no reason to keep it because T1 and TR can use the same UI code.

**Comment by matejcik** [comment]
I didn't notice that there's still `model_t1` on the Rust side of things. that should be dropped too.

**Comment by grdddj** [comment]
It could be useful here - I have a commit for deleting `T1` completely in my `TR` branch - https://github.com/trezor/trezor-firmware/pull/2610/commits/e891734feba0e4dae8bd07d76eff150658f6d62b
