### ISSUE TITLE
Touch screen chip/driver alternative for FT6206/6236

### ISSUE THREAD

**Issue by sebek0F9** [trezor/trezor-firmware#2647]
The docs say that Driver IC: FT6236 or FT6206 is the one used in the Trezor T for the CTP.

The GT911 chip seems to be easier and cheaper to find, I’m wondering if that will work with the LCD.
(The lcd being the same: either ST7789V, GC9307, or ILI9341V).

**Comment by prusnak** [comment]
Please try it and let us now. Thank you!

**Comment by sebek0F9** [comment]
I ended up getting the module. It works now. I will post results if I test the GT911 in the future.
