### ISSUE TITLE
TT bootloader - screen copy change

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2650]
Change of copy in these three screens in TT bootloader:
![image](https://user-images.githubusercontent.com/57008159/203270045-06338845-8022-4f1a-ab95-725b0a82b3e0.png)
(Reboot, Factory reset -> Reboot Trezor, Wipe Trezor)
![image](https://user-images.githubusercontent.com/57008159/203270333-aee96f3f-cf61-42d8-b652-f7d75486f9c3.png)
(Wiping device -> Wiping Trezor)
![image](https://user-images.githubusercontent.com/57008159/203270296-2900a767-9527-413b-a9ce-3749d9ef061c.png)
(Device wiped successfully. -> Trezor wiped successfully.)

**Comment by TychoVrahe** [comment]
doing this in https://github.com/trezor/trezor-firmware/pull/2306
