### ISSUE TITLE
T2B1 design - Receive

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2652]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/57008159/208422826-f5fedbbb-7b2e-4a98-9870-db7c832d0820.png">

**Comment by grdddj** [comment]
Done in [7926b02](https://github.com/trezor/trezor-firmware/pull/2610/commits/7926b02a44ef99ff97b4242cae9cf3c1c244ec05)

As we discussed, `xpubs` in case of multisig address are currently not supported

**Comment by Hannsek** [comment]
<img width="226" alt="image" src="https://user-images.githubusercontent.com/57008159/215475626-72eb1966-eed1-448f-ac23-d7c71a78fd6c.png">

@grdddj add header with currently used wallet

**Comment by Hannsek** [comment]
<img width="816" alt="image" src="https://user-images.githubusercontent.com/57008159/218023103-25dc996f-e818-4d55-9642-78d67f775f3a.png">

**Comment by Hannsek** [comment]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/57008159/228555271-39d803fb-25b4-47ec-9a30-ec046194721c.png">
Please change _trezor.io/support_ to bold.

**Comment by grdddj** [comment]
> Please change _trezor.io/support_ to bold. 

Done in [c2c9156](https://github.com/trezor/trezor-firmware/pull/2610/commits/c2c9156ad06435d2dacbe6ab018dc95758733f55)

**Comment by Hannsek** [comment]
In case of multisig -> put this as an header: 
![image](https://github.com/trezor/trezor-firmware/assets/57008159/1deaf6b3-7755-459e-ba0a-fdd2c8b86654)
