### ISSUE TITLE
TT UI2 scrollbar

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2656]
![image](https://user-images.githubusercontent.com/57008159/203555047-d1f9dd34-5b0e-4c26-b21f-74002808c635.png)

Max 7 visible dots. Max 5 big dots at the ends, otherwise 3 big dots.

big - 100 %, middle - 50 %, small - 25%

Figma: https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=1126%3A237&t=1RfM47z4HRCL9v6P-0

**Comment by bosomt** [comment]
**QA OK**

scrollbar works/looks like expected.

Noted that text at last page is centered in middle of the screen, not sure if its expected or not.
I can create follow up issue if not expected.

![Image](https://user-images.githubusercontent.com/31506317/207392535-885185b2-4548-4567-ba25-a7ed21f40c17.png)

**Info:**
 - Suite version: desktop 22.12.1 (ddaacdb2245d7a909b3d2abfe918cff34d2e1609)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision ff35c77bad82c7acac1df6245940ebe0d6454642)
 - Transport: bridge 2.0.32

**Comment by Hannsek** [comment]
Are the two dots on the edges smaller than the 3 dots in the middle?

**Comment by Hannsek** [comment]
Have you tried more than 5 pages? Did you see smaller dots?

**Comment by bosomt** [comment]
@Hannsek as soon i had more than 5 pages i see that size was changing as i scrolled
