### ISSUE TITLE
T2B1 design - Send

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2664]
![image](https://user-images.githubusercontent.com/57008159/204524951-2cc6b986-a3e8-4c6b-b0bb-c62524dc0c10.png)

**Comment by Hannsek** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/57008159/208422667-d8bb033d-c72a-41df-9066-5317f4bbd0da.png">

**Comment by grdddj** [comment]
Without the final "Transaction Signed" `Popup` done in [44490e6](https://github.com/trezor/trezor-firmware/pull/2610/commits/44490e64bcb6d7592dd6853c35a943fcfff8b97d)

![image](https://user-images.githubusercontent.com/42543243/210178330-fe35b9c9-b57a-41a4-806e-f7937876358d.png)

**Comment by matejcik** [comment]
"Recipient #1" ends with a "Confirm", but then the "Amount #1" allows going back?
that seems weird. if we do allow going back (reasonable), then at least the verb should not be "confirm" because at that point it's not really confirmed

**Comment by Hannsek** [comment]
There was a discussion about that and according to them this is the best wording…

**Comment by Hannsek** [comment]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/57008159/215475969-f2a01c7a-e353-4c16-acf7-cf0410716e17.png">

Here is slightly bigger `i` sign than in receive flow. (See figma https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=5437%3A36557&t=Iu3ljOwwRQscCic4-4)

Different button on `recipient` tab - `Continue` instead of `Confirm`

**Comment by Hannsek** [comment]
<img width="209" alt="image" src="https://user-images.githubusercontent.com/57008159/220276600-7f6ceac6-7e93-474a-aa3e-a48a3f290755.png">
