### ISSUE TITLE
No USB Connection error

### ISSUE THREAD

**Issue by Janaka-Steph** [trezor/trezor-firmware#2676]
Firmware: 2.5.3

I just bought a Model T, and I use it on a Macbook M1. M1 don't have USB A ports anymore. However you only provide a USB A to USB C cable. You sell your product at €262.80 and you can't provide a USB C to USB C cable?! Seriously?
Anyway, I found a Trezor usb c to usb c cable which was provided on Model T before, so I use that cable, and I get "No USB Connection" error.

**Comment by prusnak** [comment]
This is not a support channel, however I suggest trying a different USB cable.

If that does not help, feel free to reach our user agents at http://trezor.io/support
