### ISSUE TITLE
Delete unused components from micropython UI - Popup, Loader, Pageable...

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2686]
`core/src/trezor/ui/loader.py` and `core/src/trezor/ui/popup.py` contain UI components that are not used anymore (because of moving UI to `Rust`). Also `core/src/trezor/ui/components/common/confirm.py` has unused `Pageable` class.

Still having them in codebase is just increasing the binary size.

**Comment by grdddj** [comment]
Turns out the `Loader` is still being used via `LoadingAnimation` in https://github.com/trezor/trezor-firmware/blob/550e2a79512b75f09e57878baaa52bb5310aefbe/core/src/apps/management/reset_device/__init__.py#L26-L28

@mmilata Did we miss this when moving into `Rust` loaders, or is this intentional?

**Comment by mmilata** [comment]
You're right, I have missed it. Will move it to rust side.

**Comment by grdddj** [comment]
Thanks, I have tagged you (and this issue) in https://github.com/trezor/trezor-firmware/pull/2688, as after we remove `Loader`, there will be more removing to be done
