### ISSUE TITLE
[Epic] Shamir 2.0

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-firmware#269]
Parent issue to all Shamir 2.0 related tasks

Child tasks:
Shamir Persistence #270 
Bonus tip about T9 keyboard #271 
Cardano support with Shamir #272 
Refactoring crypto.slip39.API #273 
Refactoring storage.py #274 
Refactoring mnemonic/__init__.py #275 
Support troubleshooter for Shamir #277 
A complete dry run of all Shamir shares #276
SLIP39 Recovery: do not hard fail when an incorrect word was entered #221 
Inform user why the recovery failed #279

**Comment by tsusanka** [comment]
Maybe we should do https://github.com/trezor/trezor-firmware/issues/221 as well

**Comment by tsusanka** [comment]
And https://github.com/trezor/trezor-firmware/issues/279 .

**Comment by ZdenekSL** [comment]
Added those two as child issues.
