### ISSUE TITLE
T2B1 design - passphrase entry

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2696]
<img width="289" alt="image" src="https://user-images.githubusercontent.com/57008159/210507221-2825fc18-8409-4065-ac31-e4239168a219.png">
<img width="341" alt="image" src="https://user-images.githubusercontent.com/57008159/208424304-e05fbe3d-9939-4d00-a3b2-ea4411932d86.png">

<img width="495" alt="image" src="https://user-images.githubusercontent.com/57008159/208423693-1e196bfd-1f97-40fb-9b17-e30d5524512d.png">

**Comment by Hannsek** [comment]
<img width="198" alt="image" src="https://user-images.githubusercontent.com/57008159/210969904-c10ec355-a204-4a6f-92b4-00d0ef4e6270.png">

**Comment by Hannsek** [comment]
<img width="219" alt="image" src="https://user-images.githubusercontent.com/57008159/214292459-22cc5192-5cf6-4035-841c-8a89f5ffe053.png">

**Comment by Hannsek** [comment]
missing `*`, `#`

+ change middle button from `confirm` to `select` when on `SHOW`

+ when the first character is space, `x cancel` do not change to `<- delete`

**Comment by Hannsek** [comment]
![IMG_8248](https://user-images.githubusercontent.com/57008159/228556195-c2b698fe-30fc-439f-9d9a-34408e28355f.png)
header not displaying last `E` properly.

**Comment by grdddj** [comment]
> ![IMG_8248](https://user-images.githubusercontent.com/57008159/228556195-c2b698fe-30fc-439f-9d9a-34408e28355f.png) header not displaying last `E` properly.

Good catch, there is an "invisible" scrollbar at the right side. Fixed in [0098290](https://github.com/trezor/trezor-firmware/pull/2610/commits/0098290dcda3d5f9f06a0316c3c1c8a4f708669f)
