### ISSUE TITLE
UI2: tos - copy change

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2709]
Change copy for these kind of screens: 
![image](https://user-images.githubusercontent.com/57008159/210511366-215a0464-fe19-4c61-b6ab-937c7abee92b.png)

**Delete the initial question.**
**Change heading**
**Change buttons**
![image](https://user-images.githubusercontent.com/57008159/210513927-d68382a7-e474-47c7-8508-153b2fe3dd35.png)

https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=6015%3A45701&t=gdClSu39z7PYeyy2-4

**Comment by matejcik** [comment]
the current screen reads "Shamir Backup" if shamir is in use.
do we completely drop that info?
![image](https://user-images.githubusercontent.com/596073/212114538-32f353d4-ea17-48bb-9b3c-18705981e3b9.png)
![image](https://user-images.githubusercontent.com/596073/212114606-f3c786b0-d615-401b-b479-1db2a80aa152.png)

**Comment by Hannsek** [comment]
Good point, we can put it into the brackets on the new line of header: 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/57008159/212247910-6ec44c6f-7bcd-41fb-a1a3-806dda404ddb.png">

**Comment by matejcik** [comment]
I would prefer not having multiline title, if we can at all avoid it. the layouts implicitly assume that the header is one line.
but @mmilata has a better idea about how disruptive that would be?

**Comment by mmilata** [comment]
Not massively disruptive I think. We'd have to implement multiline Label<>s and then be careful not to have multiline label that changes content at runtime to something with different number of lines (titles can't be changed after constructor but labels can).

**Comment by matejcik** [comment]
I did something that touches the possibility of multiline labels in the FIDO PR. Don't recall if I assume that it must be one line, or whether it depends on the preconfigured label height.

**Comment by TychoVrahe** [comment]
we also have the marquee now, might be worth considering
