### ISSUE TITLE
Bonus tip about T9 keyboard

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-firmware#271]
Add infobox about T9 keyboard.
Add header option into infobox.

**Comment by tsusanka** [comment]
Let's do this. But choose the wording carefully, example: "one by one, but you can speed it up by tapping each button only once (T9 keyboard)". This focues on why and not on what.

**Comment by ZdenekSL** [comment]
The text will be decided based on user testing. Matěj is responsible for handling this part, we need just to prepare the header and spacing.

**Comment by ZdenekSL** [comment]
Text You can type the letters one by one or use it like a predictive T9 keyboard.

**Comment by ZdenekSL** [comment]
Won't be done after discussion

**Comment by tsusanka** [comment]
Removed in https://github.com/trezor/trezor-firmware/commit/cefb1cf4fd9f870da308704565d1ed61461b2c5e#diff-65fbfc4127aa71804b069d407a26dd9fL191
