### ISSUE TITLE
Refactoring crypto.slip39.API

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-firmware#273]
Child of #269 
Refactor crypto.slip39 API

**Comment by tsusanka** [comment]
Let's also remove the default values (for example for the iteration exponent). We are forgetting to pass it from the storage then, see https://github.com/trezor/trezor-firmware/pull/428#discussion_r317668410.

**Comment by tsusanka** [comment]
Merged into `iss442-supershamir-refactor`.
