### ISSUE TITLE
T2B1: debug screen with fonts

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2730]
Create a debug screen with all fonts that we have on the device so that we know how they look on the device.

Put it at the beginning of the tutorial flow.

**Comment by grdddj** [comment]
Done in a special branch - https://github.com/trezor/trezor-firmware/tree/grdddj/R_debug_font_screen

**Comment by Hannsek** [comment]
Do we need review on this?

**Comment by grdddj** [comment]
Probably not, it is not a part of the "main" branch, just a one-time thing for you
