### ISSUE TITLE
UI2 - not cleaning passphrase row properly (for a dollar sign)

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2734]
By a coincidence, I have found out that the dollar sign `$` seems to have a bigger height than any other symbols available in `passphrase`.

It causes one upper pixel of dollar sign to be outside of the area belonging to the passphrase row. When deleting the passphrase, these pixels still stay there:

![image](https://user-images.githubusercontent.com/42543243/211865853-37e21a37-3e47-453a-8f55-5a4343f5f092.png)

![image](https://user-images.githubusercontent.com/42543243/211865799-a0b36199-150d-4e05-abf4-79cfc529cfcd.png)

It is a very unique situation, maybe not even worth fixing, but we might want to know about this

**Comment by matejcik** [comment]
i believe this is an instance of #2657

**Comment by mmilata** [comment]
note to self: @grdddj has click test for this in the R branch, perhaps cherry-pick it when this is fixed
