### ISSUE TITLE
UI2: `show_share_words` should accept list of `share_words` in Rust instead of a chunked string

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#2740]
T2B1 got this right: the list `share_words` should be passed into Rust to make the chunks as appropriate.
T2T1 UI2 should do the same thing.

**Comment by obrusvit** [comment]
I accidentally fixed this in https://github.com/trezor/trezor-firmware/pull/4322 

By introducing `show_share_words` in `trait UiFeaturesFirmware`, I needed a way how to pass the words as `Vec<TString, 33>`. The straightforward way was to pass the list to rust directly.
