### ISSUE TITLE
Refactoring mnemonic/__init__.py

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-firmware#275]
Child of #269 
Refactor mnemonic/__init__.py

**Comment by tsusanka** [comment]
Let's do this on top of #331

**Comment by tsusanka** [comment]
I'm gonna do this one, on top of #331, if that's fine.

**Comment by tsusanka** [comment]
Implemented in tsusanka/iss275-mnemonic-refactor

**Comment by tsusanka** [comment]
Merged to master.
