### ISSUE TITLE
T2B1 design - arrows

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2760]
Dotted arrows at the bottom and top of the page when the text is too long for one screen:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/57008159/213656898-7234ce26-a368-4ba2-a41b-2f9dda5eb2e1.png">

**Comment by Hannsek** [comment]
<img width="403" alt="image" src="https://user-images.githubusercontent.com/57008159/214599264-bd532cb8-4aa4-433b-a6ff-dca17a410662.png">

**Comment by grdddj** [comment]
Done in [b0ea008](https://github.com/trezor/trezor-firmware/pull/2610/commits/b0ea008c2e71b629500baf8d6b01d4cacf31d683) as part of https://github.com/trezor/trezor-firmware/pull/2610
