### ISSUE TITLE
T2B1 design - center text on buttons

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2767]
Text on buttons is sometimes not centered (±1px). It is probably because of different width of individual letters.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/57008159/214523398-aa9dc6ee-9508-4a08-abe1-7fe4e88d9e30.png">

<img width="522" alt="image" src="https://user-images.githubusercontent.com/57008159/214523466-05ccd20b-9498-42d1-9c47-84f8366cc6b0.png">

**Comment by grdddj** [comment]
Done in [2658dea](https://github.com/trezor/trezor-firmware/pull/2610/commits/2658dead89e3db84ee55226ffd2302554fc7ac3d)
