### ISSUE TITLE
Seed partially leaked in Invalid Mnemonic checksum error 

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-firmware#278]
fw version core-2019-07-bc3a4a

Steps-to-reproduce (i will need to verify it once more):

1. Do Shamir Recovery
2. Enter a share incorrectly (i guess)

<img width="881" alt="Screenshot 2019-06-27 at 12 53 11" src="https://user-images.githubusercontent.com/31442634/60261352-f52ae680-98db-11e9-8602-55d7535c45d5.png">

**Comment by tsusanka** [comment]
Fixed in https://github.com/trezor/trezor-firmware/commit/c205acd3e186787c789fb1b3fdce0bfe35f08969 . Please test again and close if it seems fixed. (I'll send firmware soon)

**Comment by pankrats** [comment]
now, in version a5d7f2, it is fixed. looks good:
![Screenshot_20190627_155007](https://user-images.githubusercontent.com/31442634/60274125-d0446c80-98f7-11e9-9ae7-484a291376f1.png)
