### ISSUE TITLE
T2B1 design - device name

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2780]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/57008159/216049810-806c8b45-b1de-4595-b7af-b0af9573f4fc.png">

**Comment by grdddj** [comment]
Done in [ca9fc27](https://github.com/trezor/trezor-firmware/pull/2610/commits/ca9fc27585abfc9269a5d3c7f2ac4eb547acbe4d)
