### ISSUE TITLE
T2B1 design - multisig receive

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2785]
related: #2652

<img width="604" alt="image" src="https://user-images.githubusercontent.com/57008159/216592720-2b53db01-1966-45e9-929a-2b1c1f50586b.png">

marquee in the header: `MULTISIG XPUB #1 (YOURS)`, `MULTISIG XPUB #2 (COSIGNER)`

**Comment by grdddj** [comment]
Done in [0acf940](https://github.com/trezor/trezor-firmware/pull/2610/commits/0acf94099aebaaa53152c971628794aba792b034)

**Comment by Hannsek** [comment]
https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9?node-id=6573:50981#366442002

Show more -> view full

**Comment by grdddj** [comment]
> Show more -> view full

Changed in [b5c9195](https://github.com/trezor/trezor-firmware/pull/2610/commits/b5c9195abb5569432178893c1baacaa44535fb70)
