### ISSUE TITLE
Separate JPEG decoder into its own crate

### ISSUE THREAD

**Issue by mmilata** [trezor/trezor-firmware#2787]
Let's call it `trezor-tjpgdec` maybe?

cc @TychoVrahe

**Comment by TychoVrahe** [comment]
Some things that need to be resolved:
- our specific in/out functions need to be separated
- Rect which i originally replaced by our struct from geometry needs to be reverted to something independent 
- figure out how to do configuration like output format
- at least some basic docs
- decide if we want to include the missing features from original lib: table clip, fastdecode=1
- remove optimization attributes, optimize on crate level

**Comment by mmilata** [comment]
This article uses similar allocator as we do: https://matklad.github.io/2022/10/06/hard-mode-rust.html
