### ISSUE TITLE
T2B1 - screen freeze after wipe code entered

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2788]
Screen freeze on `processing` screen after wipe code entered.

After replugging the device is wiped.

On emulator, there is no freeze but there is old screen (from model T maybe?) with text too big to fit onto the screen.

**Comment by grdddj** [comment]
Trying it on the current `TR` branch on hardware, there is already no freeze, but this screen:

```
             X
    WIPE CODE ENTERED

       PLEASE VISIT
     TREZOR.IO/RSOD
```

**Comment by Hannsek** [comment]
So can we close this?

**Comment by grdddj** [comment]
I believe so, looks like the error screen got added outside of TR PR
