### ISSUE TITLE
Inform user why the recovery failed

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#279]
Child of #269 
Currently, we only throw out an error "Mnemonic is not valid" if the recovery/dry run fails. We should:

- <s>tell the user if the checksum of the currently entered mnemonic was wrong</s> tracked in see https://github.com/trezor/trezor-firmware/issues/221
- <s>tell the user if this mnemonic was already entered (ideally as soon as they they enter the fourth word?)</s> tracked in #293
- <s>tell the user if this mnemonic is part of another seed (different identifier)</s> tracked in #305

**Comment by ZdenekSL** [comment]
@tsusanka Please update the specification.

**Comment by tsusanka** [comment]
I've moved those three points to a seperate issues: #221, #293 and #305.
