### ISSUE TITLE
Add Firmware Pull requests to Firmware project automation

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-firmware#2791]
- [x] Add all new PR into project: https://github.com/orgs/trezor/projects/60
- [x] Remove previous automation to https://github.com/trezor/trezor-firmware/projects/2

**Comment by Hannsek** [comment]
Can the creator of the PR be automatically assigned to that PR?
Can the status of the pr be automatically set to "Needs review"?

**Comment by hynek-jina** [comment]
@Hannsek I'm closing this one.. please create a followup issue if needed.
