### ISSUE TITLE
Drop coins support for T2B1

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2793]
Drop support for all coins bellow in FW for T2B1.

![image](https://user-images.githubusercontent.com/57008159/216991130-9f534d9d-8ce3-4c24-ac77-c44169165c8a.png)

**Comment by tomasklim** [comment]
Take in mind `Capability_Bitcoin_like` complication

**Comment by ibz** [comment]
NB: since T3T1 coin support is the same as T2B1 for now (see #3781) - this will also apply to T3T1!
