### ISSUE TITLE
Create new message for Tutorial flow

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2795]
Now only for model T2B1.

**Comment by grdddj** [comment]
Done in [4f4b89c](https://github.com/trezor/trezor-firmware/pull/2610/commits/4f4b89c2e8e6df68635d5476025a78558debf1e8)
- we could certainly do some improvements, for example do not even including this file for TT, or throwing an error in `trezorctl` / `firmware` when trying to call it on TT
