### ISSUE TITLE
Implement Binance Coin

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#28]
- [x] protobuf definitions
- [x] get_address
- [x] hashing/signing functions 
- [x] serialization functions
- [x] layouts
- [x] CLI support
- [x] input validation
- [x] unit tests (in progress)
- [x] device tests
- [x] revisit layouts
- [x] add useful info to readme
- [x] refactor device tests to use input flow (was already done)

~~[ ] refactor serialization~~ - moved to #188 
~~[ ] tests for transactions with multiple msgs~~ - not supported based on documentation

**Comment by ZdenekSL** [comment]
Merged to master

**Comment by prusnak** [comment]
Merged via https://github.com/trezor/trezor-firmware/commit/90b91a7fb55bc8059b752874a04d8b8c29b223fb
