### ISSUE TITLE
Cannot install unsigned fw on T1

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2801]
`trezorctl firmware_update -f "./trezor.bin"` gives multiple errors

it, however, can be installed with `trezorctl firmware_update -f "./trezor.bin" -s`

**Comment by matejcik** [comment]
please provide the errors :)

**Comment by Hannsek** [comment]
`trezorlib.firmware.util.Unsigned`

@matejcik: bug: refuses to install unsigned firmware where it should instead prompt
