### ISSUE TITLE
Transaction broadcast fails with mandatory-script-verify-flag-failed

### ISSUE THREAD

**Issue by winter-tiger** [trezor/trezor-firmware#2819]
**Describe the bug**
I created a transaction JSON using the `build_tx.py` tool and signed it using a Trezor Model T.
Coinb.in fails to broadcast the transaction with the following error:

> mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element) (code 16)

**To Reproduce**
Using the `build_tx.py` tool from [commit](https://github.com/trezor/trezor-firmware/tree/e4661e8f051e5cf19730ba0a6bd35edc826a3d50):

```
% trezor-firmware/python % python3 tools/build_tx.py
Coin name [Bitcoin]: 
Blockbook server [btc1.trezor.io]: 

Previous output to spend (txid:vout) []: 437592982721b68ccceee8c9f89fecc92d4c9856c6b1d53a567aaffb0624e80d:2
From address: 3BPM9UktK9JeyA4c91TgkKWwZe9aYohrFH
Input amount: 43965
BIP-32 path to derive the key: m/49'/0'/0'/0/22
Script type: SPENDP2SHWITNESS
Sequence Number to use (RBF opt-in enabled by default) [4294967293]: 

Output address (for non-change output) []: 3Jj9d8xx6Q9Hfe3sotUR3nPfFYmJQLMsF1
Amount to spend (satoshis): 43465 

Output address (for non-change output) []: 
BIP-32 path (for change output) []: 
Transaction version [2]: 
Transaction locktime [0]: 
```

Produces the following JSON output:

```
{
  "coin_name": "Bitcoin",
  "details": {
    "lock_time": 0,
    "version": 2
  },
  "inputs": [
    {
      "address_n": [
        2147483697,
        2147483648,
        2147483648,
        0,
        22
      ],
      "amount": 43965,
      "coinjoin_flags": 0,
      "prev_hash": "437592982721b68ccceee8c9f89fecc92d4c9856c6b1d53a567aaffb0624e80d",
      "prev_index": 2,
      "script_type": "SPENDP2SHWITNESS",
      "sequence": 4294967293
    }
  ],
  "outputs": [
    {
      "address": "3Jj9d8xx6Q9Hfe3sotUR3nPfFYmJQLMsF1",
      "amount": 43465,
      "script_type": "PAYTOADDRESS"
    }
  ],
  "prev_txes": {
    "437592982721b68ccceee8c9f89fecc92d4c9856c6b1d53a567aaffb0624e80d": {
      "bin_outputs": [
        {
          "amount": 5500,
          "script_pubkey": "6a4c5058325b5e3dcc673273ad5db48a45eb7a21268746c5a973466ac242f7d8f11b9616032a148b00ab5baa87a15f1b87e5157bc9569606f8a874eb55e6bf0ae517219a05f0000bd81c0023000bd71b009c29"
        },
        {
          "amount": 43965,
          "script_pubkey": "a914f717847b4b9b32fe17c060b176ee81f4057036be87"
        },
        {
          "amount": 43965,
          "script_pubkey": "a9146a59d12d8c6cb19102e0b20510ad0dfc613b3dfb87"
        },
        {
          "amount": 12036243,
          "script_pubkey": "76a9144397615609ebb13c36847a6ca710b386ccfd4e1a88ac"
        }
      ],
      "inputs": [
        {
          "coinjoin_flags": 0,
          "prev_hash": "9466d303be55f7ad5450fa1b424eb7dfd12f0850a77bbdbd5b8626919e18db4b",
          "prev_index": 3,
          "script_sig": "47304402200ab463d522257c9b2d87c3ee670c1896c41e803f5a9f2bb1537c6d1261bfce8e022052146aa073c8c36855f96c9c3251f2011d4e5e3ef61f798402e550afad8f28e001210355459a64f40fdee501f55f3c4b778caf1d4c9d26fe8d3873df4d6e463495f4ae",
          "script_type": "SPENDADDRESS",
          "sequence": 4294967293
        }
      ],
      "lock_time": 0,
      "version": 1
    }
  }
}
```

I then sign the JSON transaction:

```
% trezorctl btc sign-tx trezor_tx.json
```

which produces the signed transaction:

```
020000000001010de82406fbaf7a563ad5b1c656984c2dc9ec9ff8c9e8eecc8cb62127989275430200000017160014425256f1435931e59d178859f56d32a6f77e9639fdffffff01c9a900000000000017a914bae165d66f9dfb6f59341cf2e841c085deef878487024730440220012ea3d6f424d4f6b3a134630c016757affa837afd2b9a07986d4a9a0d1a5a1302201184e9afbe02b2459b31b11d9d281ccc8569c21863d3e2d6a1ff462c1793064e012103bc4577c9dcf949c729d81d514d379e5ce730f2896909c7803b21559188789f6d00000000
```

Attempting to broadcast the signed transaction using [Coinb.in](https://coinb.in/#broadcast) shows the following error:

> mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element) (code 16)

**Firmware version and revision**
Describe firmware version and revision you are using when encountering the bug.
Trezor Model T with firmware version 2.5.3 and emulator

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: N/A
 - OS: macOS
 - Browser: Firefox 
 - Version 109.01

**Expected behavior**
I expect Coinb.in to not complain about mandatory-script-verify-flag-failed and broadcast the transaction.

**Screenshots**
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/1248500/218633532-bd35a756-2d3e-4532-b889-6610c2c9788f.png">

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/1248500/218633556-516cf5a8-2981-4a19-a778-f402ae04f095.png">

**Additional context**
To sign using the emulator I patched the emulator firmware by [commenting this check](https://github.com/trezor/trezor-firmware/blob/e4661e8f051e5cf19730ba0a6bd35edc826a3d50/core/src/apps/bitcoin/sign_tx/bitcoin.py#L268
) to forcibly sign the transaction.

**Comment by matejcik** [comment]
This would typically indicate that the transaction is signed by someone who doesn't own the funds.

This is suspicious in particular:

> To sign using the emulator I patched the emulator firmware by [commenting this check](https://github.com/trezor/trezor-firmware/blob/e4661e8f051e5cf19730ba0a6bd35edc826a3d50/core/src/apps/bitcoin/sign_tx/bitcoin.py#L268) to forcibly sign the transaction.

That check verifies that you are using the correct key. If you had to comment it out, it means that you're trying to spend "someone else's" coins.

Please clarify where the problematic transaction came from: is it a Trezor with official SatoshiLabs firmware loaded with the correct seed for address `3BPM9UktK9JeyA4c91TgkKWwZe9aYohrFH`? Or is it the emulator?

**Comment by winter-tiger** [comment]
Thank you for your quick response!

The problematic transaction was generated using the `build_tx.py` tool in this repository.
I am signing and broadcasting the transaction using two approaches:
- Patched Trezor emulator with random seed and patched to generate a signed transaction: used for dev testing only.
- Physical Trezor with the correct seed authorized to spend the utxos.
In both cases the broadcast tool Coinb.in tool raises the same error.
This error is expected for the first case above but not for the second case.
I hope this is more clear.

**Comment by matejcik** [comment]
the transaction that you posted has a signature by public key `03bc4577c9dcf949c729d81d514d379e5ce730f2896909c7803b21559188789f6d` which yields address `3JNH6miNDAtjaEGTUpUj2N49hpCdZDR9tD`

but the right public key for address `3BPM9UktK9JeyA4c91TgkKWwZe9aYohrFH` which is the owner of the funds is `03f7fa8f9261c52883ed137895b8fd03d50efffb832145614a281346f1d89a1726`

did you post the tx hex produced by the emulator or by the correct Trezor?

**Comment by winter-tiger** [comment]
Thank you for your patience. I had the Trezor physical device sign the transaction which is provided below. It turned out that the wrong spend path was used to sign the transaction which you could deduce. I'm puzzled as to why the firmware complained about signing the transaction while the physical device signed the invalid transaction. I know the physical Trezor is running an old firmware version (I don't know which one exactly). Is this a bug that was fixed at some point?


```
02000000000101502096a4b1af2f6756a00179d97d212fd118d17a3d1ae435a0388d0522512738010000001716001447a00c929aedda6a203bb834173c9d2e257b3c3ffdffffff014f9a02000000000017a914bae165d66f9dfb6f59341cf2e841c085deef8784870248304502210082ab7ad34dcca00e9b14a2916dd8a74dbd9b53db6c16b57450dbd6db420cfb2002201c0d87df22348fa42bad40d72f04519c2e78d4c515483d7dca374cd73b93ea04012102178d08f4089e99e32b79594f26331866c6dcc0d6b6bbcb759d9eafc046f54d7c00000000
```

**Comment by matejcik** [comment]
> I know the physical Trezor is running an old firmware version (I don't know which one exactly).

I wonder why you wrote "Trezor Model T with firmware version 2.5.3" then? It would be super nice to know that your firmware is outdated from the start. Speaking of, updating to latest firmware is a great debugging step when looking for problems.

And yes, the "does the signed input actually belong to the wallet" check was introduced in version 2.5.1.

**Comment by winter-tiger** [comment]
Thank you for your quick response and I sincerely apologize for the confusion. 

> "Trezor Model T with firmware version 2.5.3"
I meant to say this is for the emulator that I'm running.

Unfortunately, I don't have access to my customer's physical device so I was unable to retrieve the physical device firmware version and I incorrectly assumed it was updated.

Thank you for providing such a fast resolution to this matter.
Your team sets an example for customer support!
