### ISSUE TITLE
Confusing text "Never make a copy of digital shares..." when creating Single backup

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-firmware#282]
Reported by Oliver

Steps to reproduce:
1. An empty device, select Create a New Wallet -> Create with Single Backup
2.  In the new wallet click on Create a backup in 3 minutes

On the device you will see:
![photo_2019-06-27_16-45-58](https://user-images.githubusercontent.com/31442634/60276015-1949f000-98fb-11e9-831a-ddf0a6559a26.jpg)

But  instead you will see **only one seed displayed** (not shares), so the text is confusing.

**Comment by tsusanka** [comment]
@bentonoliver so the text should be "Never make a digital copy of your recovery seed and never upload them online!" for BIP-39?

**Comment by bentonoliver** [comment]
> @bentonoliver so the text should be "Never make a digital copy of your recovery seed and never upload it online!" for BIP-39?

Yes.

Also, fix the header by changing "Backup" to "Back up".

**Comment by tsusanka** [comment]
Fixed in f78e75bc38071e2c650cb0a7526cf529d923bffc.
