### ISSUE TITLE
UI2: Welcome screens (uninitialized)

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2823]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/57008159/220272824-0bda627a-59a8-4a7f-be8c-087b3d6bc2e8.png">
[Archive.zip](https://github.com/trezor/trezor-firmware/files/10906716/Archive.zip)

**Comment by Hannsek** [comment]
@matejcik The last screen is meant to be there as a homescreen between fw installation and the end of an onboarding process. 

Having there some link like `trezor.io/start` does not make much sense in this situation as you already have Suite installed.

**Comment by matejcik** [comment]
again:

> The last screen is meant to be there as a homescreen between fw installation and the end of an onboarding process.

This does not match the idea that this screen communicates (from fw point of view at least) something like "please wait until your Trezor is fully started up".
Maybe we don't need that in the "not set up" case though?

> Having there some link like trezor.io/start does not make much sense in this situation as you already have Suite installed.

the user _can_ end up in a situation where they have FW installed, but didn't finish the setup, e.g.: fw installed on work PC, continuing at home; or continuing the next morning and forgetting everything

**Comment by Hannsek** [comment]
https://github.com/trezor/trezor-firmware/issues/2825#issuecomment-1450179615
