### ISSUE TITLE
UI2: Welcome screens (initialized)

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2825]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/57008159/220160057-91c40b1b-48fb-498a-818f-b6bd2d25b1f0.png">

The second screen will be visible for app. 1,5 s.

Default name of the device is `Trezor Model T`

The first logo comes from the bootloader.
[locks.zip](https://github.com/trezor/trezor-firmware/files/10791600/locks.zip)

**Comment by grdddj** [comment]
TODO: there is a need to get pixelated icon

**Comment by Hannsek** [comment]
Please move the lock up so that it will be positioned 48 px from the top of the screen
