### ISSUE TITLE
The bootloader version is 1.8.0. How do I update the custom firmware?

### ISSUE THREAD

**Issue by webees** [trezor/trezor-firmware#284]
After updating the custom firmware, the error: unofficial firmware detected.
I want to plug the trezor one on a small server for automated signing, so the button operation is removed from the source code. This is my source code：https://github.com/webees/trezor-mcu

Can I buy a new one to solve the problem?

**Comment by prusnak** [comment]
This is not an error, just a warning. This warning cannot be turned off.

Compile your firmware with the following lines removed and it will work:
https://github.com/webees/trezor-mcu/blob/892ce17f96ec38a3e66432910257c4056433bd12/startup.s#L22-L30
