### ISSUE TITLE
UI2: style update

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2849]
**Design:** https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=6990%3A51701&t=GE04kwfXWS6BZWAD-4

**Spec:**

- [ ] layout
 - margins will be now 6px from the edge
 - spaces between texts - 0px 
![image](https://user-images.githubusercontent.com/57008159/221588345-6d0093b1-c63e-4105-a0cf-52bc155cedd6.png)
 - spaces between "sections" - 6px
 - text centered within sections
![image](https://user-images.githubusercontent.com/57008159/221588485-525273d6-ab38-442a-957d-075c95bf09b6.png)
 - dynamic width for content 
![image](https://user-images.githubusercontent.com/57008159/221588592-50d833d0-22cb-46ac-9ab8-28da3ae18ab5.png)
 - dynamic height for headers with/without icon: with: 228x44, without: 228x20
![image](https://user-images.githubusercontent.com/57008159/221588680-9b87e663-9682-46af-9a9c-af2f412ef7fb.png)

- [ ] buttons
 - 2 buttons area: 228x50 & 228x100
![image](https://user-images.githubusercontent.com/57008159/221589458-1371c14b-7e25-453f-98cb-ed5ba0eef396.png)
![image](https://user-images.githubusercontent.com/57008159/221591267-fdda94a8-cfa1-408e-957c-498552796301.png)
 - small button: 56x50 
![image](https://user-images.githubusercontent.com/57008159/221591548-9c6c5418-f23c-4216-b054-e6b5c605c00f.png)
 - big button: 166x50 
![image](https://user-images.githubusercontent.com/57008159/221591646-e6b562ed-59ca-4d6c-a401-fe7973beb65d.png)
 - upper button: 228x44
![image](https://user-images.githubusercontent.com/57008159/221591761-8a6e6805-579f-49fd-b656-f2e99f007206.png) 
 - single button: 228x50
![image](https://user-images.githubusercontent.com/57008159/221591987-c05bdd63-7f2e-406c-96da-901daa91b491.png)
 - middle sized button: 111x50
![image](https://user-images.githubusercontent.com/57008159/221592328-6ad4edb7-6edc-4348-8dd8-72eabf3c3c67.png)

- [ ] pagination
 - ![image](https://user-images.githubusercontent.com/57008159/221592971-2e364f06-e594-4d70-b704-661dc2b1d051.png)

- [ ] keyboard
 - ![image](https://user-images.githubusercontent.com/57008159/221593212-a231a5c9-3596-4ada-8b9e-5629267af2fd.png)

- [ ] notifications: 228x36 
![image](https://user-images.githubusercontent.com/57008159/221593904-972a5140-e51e-4c66-96c3-55389fe2f83b.png)

- [ ] colours: https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=6837%3A52769&t=GE04kwfXWS6BZWAD-4
- [ ] fonts: https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=6990%3A52090&t=GE04kwfXWS6BZWAD-4
 - Headlines and buttons: 
![image](https://user-images.githubusercontent.com/57008159/221594361-049369d9-1050-4fd5-86cd-1a060ca07552.png)
 - Subheadline: 
![image](https://user-images.githubusercontent.com/57008159/221594438-2b88925e-e77b-4822-83a4-18555a1ba5f8.png)
 - Body: 
![image](https://user-images.githubusercontent.com/57008159/221594542-8f23e629-a1b4-4d83-a8e3-68013e41e439.png)
 - Mono: 
![image](https://user-images.githubusercontent.com/57008159/221594623-1bdffc71-75ef-4102-be30-0b44f1f09d04.png)

- [ ] icons: https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=6990%3A52122&t=GE04kwfXWS6BZWAD-4

**Comment by mmilata** [comment]
Also: https://github.com/trezor/trezor-firmware/pull/2843#issuecomment-1453056584

**Comment by Hannsek** [comment]
Also, the "intensity" homescreen blurring has been edited.  See: https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=7079%3A54925&t=mB1OgFwgcx9jG4K2-4
