### ISSUE TITLE
allow Model T initialization without computer

### ISSUE THREAD

**Issue by chaserene** [trezor/trezor-firmware#2862]
if I'm not mistaken, a Model T with a firmware installed doesn't need to depend on a computer to be initialized. just like when using a [wipe code](https://trezor.io/learn/a/create-wipe-code-to-erase-device), the only thing the USB connection is needed for is power.

what do you think about allowing uninitialized Model Ts that have a firmware and are connected to a no-data USB port (e.g. a power bank) to be initialized solely through the touchscreen? this way the only time that the Trezor's screen displays mnemonic words and when the user needs to create/access their physical backup could happen in an environment that is free from any other computer, on or offline, reducing the chance for surveillance.

**Comment by Hannsek** [comment]
Hi @chaserene, we have this on our roadmap, however, I cannot tell you when exactly this would be possible to use.
