### ISSUE TITLE
Small Taproot QR code on T1

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#2863]
The Taproot QR code in `GetAddress` on T1 is very small. Can we make it bigger? The problem is that the code is 33x33 pixels, whereas the available area is 64x64. We could double the size and then shave off one line of pixels on each side (top, bottom, left, right). Or increase the area to, say, 74x64 and shave off only one row of pixels on the top and bottom.

Before:
![image](https://user-images.githubusercontent.com/42678794/223082526-e7591d1a-5e15-4523-9364-278932fe70bb.png)

After 1:
![image](https://user-images.githubusercontent.com/42678794/223084836-e3b2540f-5c21-4b39-ac98-e41581adb595.png)

After 2:
![image](https://user-images.githubusercontent.com/42678794/223086375-34bc53d8-842a-402d-8ad5-8960fa5bc77c.png)

The same problem might also be present for P2WSH, i.e. SegWit v0 multisig.

**Comment by Hannsek** [comment]
There were discussions about this here https://github.com/trezor/trezor-firmware/issues/2638 and https://github.com/trezor/trezor-firmware/issues/2190.

I believe it is the same issue, no?

**Comment by matejcik** [comment]
yeah, we tried the cutoff but apparently there have been problems with scannability.

**Comment by prusnak** [comment]
Maybe we should drop the QR code from T1 completely?

I think it's a gimmick and no one uses it, since it is unusable (unlike TT where QR code is much bigger).

**Comment by prusnak** [comment]
> Most of the users can scan it comfortably.

Even the smallest Taproot one?

**Comment by Hannsek** [comment]
Yes, but it depends on the cameras.
