### ISSUE TITLE
Recovery: Backspace button is too small

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#288]
Many consider the backspace button way too small and difficult to press.

Reported by @andrewkozlik

**Comment by mmahut** [comment]
I second this, while in recovery I wanted to hit the backspace button while confirmed the bad word. #286 would fix this for my use case too, therefore I think one of these should make it in.

**Comment by tsusanka** [comment]
I think this looks quite alright. We should consider doing this for BIP-39 as well, I'll check out what is the widest word there.

![emu00000001](https://user-images.githubusercontent.com/1835345/60509166-934bf180-9ccc-11e9-94e9-2fc24641bf3f.png)

![emu00000000](https://user-images.githubusercontent.com/1835345/60509165-934bf180-9ccc-11e9-939f-441242ced3d5.png) ![emu00000002](https://user-images.githubusercontent.com/1835345/60509167-934bf180-9ccc-11e9-90bb-161d4108159d.png)

(downtown is one of the widest words)

**Comment by prusnak** [comment]
Can you please try the word "remember"?

**Comment by tsusanka** [comment]
The fifth of November! And also mountain, which is quite large.

![emu00000000](https://user-images.githubusercontent.com/1835345/60510544-ebd0be00-9ccf-11e9-8844-f6d975dabf52.png) ![emu00000001](https://user-images.githubusercontent.com/1835345/60510545-ebd0be00-9ccf-11e9-9061-d76ab5458711.png)

**Comment by prusnak** [comment]
Looks great! Let's investigate this for BIP39 as you suggest.

**Comment by andrewkozlik** [comment]
FYI, the widest word using the Trezor normal font is "downtown" (93 pixels) for SLIP-0039 and "mushroom" (95 pixels) for BIP-0039. But now I realized that we are using the monospace font for the word, So it makes no difference :-D. All eight-letter words are 96 pixels.

**Comment by tsusanka** [comment]
For BIP-39:

![xemu00000000](https://user-images.githubusercontent.com/1835345/60512033-ccd42b00-9cd3-11e9-8c90-573814097ae7.png) ![xemu00000001](https://user-images.githubusercontent.com/1835345/60512034-ccd42b00-9cd3-11e9-9877-0c1cc89d3a79.png)
![xemu00000002](https://user-images.githubusercontent.com/1835345/60512035-ccd42b00-9cd3-11e9-9858-f9ce22043e74.png) ![xemu00000003](https://user-images.githubusercontent.com/1835345/60512052-d78ec000-9cd3-11e9-8301-c39cc038718c.png)

It's all good. I'm also considering moving it one more pixel to the left (but you can barely see it):

![emu00000000](https://user-images.githubusercontent.com/1835345/60512079-eecdad80-9cd3-11e9-885f-f9cd9782a624.png)

**Comment by tsusanka** [comment]
I'm also considering moving it one more pixel to the left (but you can barely see it):

![emu00000000](https://user-images.githubusercontent.com/1835345/60512079-eecdad80-9cd3-11e9-885f-f9cd9782a624.png)

**Comment by tsusanka** [comment]
PR in https://github.com/trezor/trezor-firmware/pull/302
