### ISSUE TITLE
Add trezor color into device during assembling (T2B1)

### ISSUE THREAD

**Issue by TychoVrahe** [trezor/trezor-firmware#2885]
We need to differentiate colors of produced device. We need to add a color flag somewhere during production.
 
One way that comes to mind is to use OTP memory which would be programmed dur8ng device testing

**Comment by prusnak** [comment]
Btw, OTP usage is documented here - https://github.com/trezor/trezor-firmware/blob/master/docs/core/misc/memory.md#otp

What is not explicitly documented in this file is the format of block 0.

This is mentioned here: https://github.com/trezor/trezor-firmware/blob/67f3af619ab7e91bf980e5fdec5949c5824ad049/core/embed/prodtest/main.c#L386

So all Trezors Model T manufactured today will contain `TREZOR2-230315` in OTP block 0.

It is trivial to extend this string identifier to something that makes sense. Each block has 32 bytes, so there is plenty of space to use for this.
