### ISSUE TITLE
Bootloader UI: bottom bar

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2910]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/57008159/227907254-a12da7a7-c6b2-4c6c-827a-699430dde398.png">

https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=7657%3A55243&t=Mmm1eRg2tu68cdMZ-4

**Comment by Hannsek** [comment]
Please change these screens as well:
<img width="297" alt="image" src="https://user-images.githubusercontent.com/57008159/227909928-51c539da-5f76-40cc-b4f5-f90ea2dd068e.png">

<img width="163" alt="image" src="https://user-images.githubusercontent.com/57008159/227909991-2444d993-c4e5-401e-8ab8-8ed7391c0979.png">

**Comment by matejcik** [comment]
also changing the initial installation screen, hope that's ok
![image](https://user-images.githubusercontent.com/596073/228576330-9480ccac-6dd3-439e-8257-805f1abb7952.png)

**Comment by Hannsek** [comment]
Is this done on the top of master? Because I see smaller font than it should be. Otherwise ok.

**Comment by Hannsek** [comment]
Which colour did you choose for the thin line?

**Comment by matejcik** [comment]
> Is this done on the top of master? Because I see smaller font than it should be. Otherwise ok.

the font is smaller because it's the same one as the "RESTARTING". in bootloader we only have the normal non-bold font. I can put in that one.

> Which colour did you choose for the thin line?

some kind of gray, same as was the button color previously

**Comment by Hannsek** [comment]
Please use TT/Body (TT Hoves, Regular, 21)

**Comment by matejcik** [comment]
![image](https://user-images.githubusercontent.com/596073/228791250-d9d3b0d7-0b59-4ba6-b10e-64e61ee4e9b5.png)

**Comment by Hannsek** [comment]
The `restartinng in 3` looks like it is not centered between the line and the bottom of the screen.

**Comment by matejcik** [comment]
![emu1680274900-000](https://user-images.githubusercontent.com/596073/229157221-33fcb92e-ded8-41a6-b27a-7ab81bc3e957.png) ![emu1680274936-000](https://user-images.githubusercontent.com/596073/229157370-0d9463cf-9f28-4bc4-bcd3-82422ba709c4.png) ![emu1680275088-000](https://user-images.githubusercontent.com/596073/229157966-1784c66c-fb0a-40ee-a89c-7b0af8d8a432.png) ![image](https://user-images.githubusercontent.com/596073/229158045-7b724812-c66c-41ea-97ba-44b731f72e6f.png) ![image](https://user-images.githubusercontent.com/596073/229158080-560ee160-647d-489c-ba2f-eb46898468dc.png) ![image](https://user-images.githubusercontent.com/596073/229158119-12e35b5b-c147-49fb-b94d-f03f78c90a36.png) ![image](https://user-images.githubusercontent.com/596073/229158340-ee815ad5-be06-45a7-94d5-b026e6347b98.png)


In case of errors, I can tweak _some_ strings:
* I can globally change "FATAL ERROR" to "INTERNAL ERROR"
* I can always change contents of the middle line
* In case of "USB ERROR", I can also separately modify the title too.

please let me know what the wording should be. we still need to remove the full-stops at end of "installed successfully."



> The `restartinng in 3` looks like it is not centered

that's an artifact of the screenshot: the "virtual screen" does not extend all the way to the bottom edge of the screen cutout.
even if the real device is the same, it would be annoying to deal with it: we would need to make the black-background text move a couple pixels down to compensate, but leave alone all those with non-black background. I would prefer not doing that in the bootloader.

**Comment by matejcik** [comment]
> invalid firmware signature

there are actually several "reasons" for ignoring the firmware that I think is too much:

* Bootloader downgraded

keep this one but change to "Bootloader downgrade protection" ? current users will not see it anyway.

* invalid vendor header
* invalid vendor header signature
* invalid firmware header
* invalid firmware signature
* invalid firmware hash

=> all of those can be something like "firmware is corrupted", I have a hard time imagining a scenario where the distinction is important. In all cases the resolution steps are (1) try to reinstall firmware, several times, and (2) throw out the device and get a new one.

In the new-style user friendly error screens, I would like "FIRMWARE IS CORRUPTED" (or similar) to be the header, and the reason code be the smaller text. For now, "internal error" / "firmware corrupted" seems fine.

* unauthorized vendor keys 

This is a very special case that nobody will ever see, so i'd leave that alone, except maybe capitalize the first word

* wrong firmware model

This one seems relevant, although in theory it should be impossible to encounter.

**Comment by Hannsek** [comment]
<img width="174" alt="image" src="https://user-images.githubusercontent.com/57008159/229456623-339be9e8-64e9-4fd8-a090-22aa78e6932d.png">
Should start with big "I"
