### ISSUE TITLE
UI2: wallet backup fix padding

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2911]
Current implementation: 
![current](https://user-images.githubusercontent.com/57008159/227965683-386c29b8-addb-4d82-bc79-9534b37fa5cf.png)

Fixed screen: 
<img width="256" alt="image" src="https://user-images.githubusercontent.com/57008159/227966256-500780ba-920b-4251-8c33-d9a60903c9a7.png">

This fix should be done in every flow where users see seed words on the screen.

**Comment by FUHAR-GARG** [comment]
Hey 
Your github profile has always been a great source of help . While going through your page I found this issue and had tried my best so as to find the solution to the given problem . I think this Problem can be fixed using “"setfill('0') << setw()"” . 
Thank you for your attention . I will be grateful if I can contribute .

**Comment by matejcik** [comment]
@AdarshRawat1 please finish the isort PR first
