### ISSUE TITLE
T2B1: Some letters (not only in recovery flow) are not centered

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2917]
letters `i` and `l` are not centered

![IMG_8246](https://user-images.githubusercontent.com/57008159/228492571-a9f4978e-25fc-4e8f-a825-44a25516dd07.png)

**Comment by Hannsek** [comment]
On `Number of words` screen, numbers 12 and 18 are not centered either.

**Comment by grdddj** [comment]
Fixed in [a546c9d](https://github.com/trezor/trezor-firmware/pull/2610/commits/a546c9dba562aff76ef8d53f5245b838618a50d8) - there are some numbers/letters, which have a non-zero x-bearing, so they were not being properly centered. Accounting for this now
