### ISSUE TITLE
Recovery: warn the user if such share was already entered

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-firmware#293]
Child of #269 
It seems like an issue for me, if not, please, explain. 

Steps to reproduce:
1. Generate a Shamir backup, for example:
![image_2019-06-28_11-45-26](https://user-images.githubusercontent.com/31442634/60423105-bc498500-9bed-11e9-9f59-e8bd0d4cbbaa.png)
threshold 8/16 shares

2. Do a Shamir Recovery (20 words). 
3. Enter the same share several times (I entered the 1st share 3 times in a row), result: 

![photo_2019-07-01_10-50-43](https://user-images.githubusercontent.com/31442634/60423276-219d7600-9bee-11e9-8f55-9a862cf98d44.jpg)

**Comment by tsusanka** [comment]
We currently do not check, if the entered share was already entered or not. Let's discuss on standup if we need to push this into the freeze.

**Comment by ZdenekSL** [comment]
We can warn the user after the fourth word was entered.

**Comment by ciny** [comment]
I already implemented part of this as part of #276 , it is in ciny/shamir_dryrun branch. As with #276 work on this will be finished after #270 is done. I'll assign this to myself and implement it when persistence is done.

**Comment by ciny** [comment]
work on this has been moved to ciny/shamir_word_checks (together with #305 ) and it supports persistence. PR will be made after #270 is merged.

**Comment by ciny** [comment]
Code merged from ciny/shamir_word_checks branch to tsusanka/iss270-persistance, it will make it to master as part of #347

**Comment by tsusanka** [comment]
Merged to master.
