### ISSUE TITLE
Change text on the button

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2938]
While setting locktime, on the confirmation button, there is currently `NEXT`. 

Please change it to `CONFIRM`.
![IMG_8278](https://user-images.githubusercontent.com/57008159/230358936-49104c3b-4031-40c8-adf1-1f7de692012e.png)

the same thing for confirm fee screen in eth send flow
![IMG_8279](https://user-images.githubusercontent.com/57008159/230358900-22b9fdce-24f0-45b7-a292-7a7142db6e2b.png)

**Comment by mmilata** [comment]
Wanna get rid of NEXT everywhere? These screens would be affected: https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/4092339281/artifacts/test_ui_report/differing_screens.html

**Comment by Hannsek** [comment]
Probably yes. But not replace it with `confirm` everywhere.

For example here:

<img width="243" alt="image" src="https://user-images.githubusercontent.com/57008159/231151800-6733b399-60d5-4a08-8d8a-eb65e276eb91.png"> 

and here: 
<img width="237" alt="image" src="https://user-images.githubusercontent.com/57008159/231153752-1253ff00-95d9-4ad9-bfef-a005a6837834.png">


`Continue` would fit better here.




Also, how much complexity would be to add custom text in different flows?
E.g. here: 
<img width="238" alt="image" src="https://user-images.githubusercontent.com/57008159/231154142-f562481f-ac47-4006-b21f-e25fe04da955.png">

`Decrypt` instead of `Confirm`

**Comment by Hannsek** [comment]
Yes, it should. Something like this is feasable?

<img width="338" alt="image" src="https://user-images.githubusercontent.com/57008159/231203677-f8aea0ad-255a-4a87-97f8-49ea2f9026a2.png">



Also, this is how signing unknown token (not in eth definition) would look like?
<img width="157" alt="image" src="https://user-images.githubusercontent.com/57008159/231203881-17563640-8215-4ff1-8d9b-155ff2fec979.png">

**Comment by prusnak** [comment]
Does the locktime (YYYY-MM-DD HH:MM:SS)  fit on the display with the monospace font? If yes, it would be nice to change it.

**Comment by Hannsek** [comment]
It unfortunately won't fit by few pixels.
However, we can do something like this:
<img width="150" alt="image" src="https://user-images.githubusercontent.com/57008159/231206979-d7dd5c48-3a4e-4136-94d9-842b18e93687.png">
