### ISSUE TITLE
Create a Bootloader changelog, update the FW changelogs

### ISSUE THREAD

**Issue by bentonoliver** [trezor/trezor-firmware#294]
There's currently no BL changelog. It would be great to have one.

Ideally, update the information in both

- the [core firmware changelog](https://github.com/trezor/trezor-firmware/blob/master/core/ChangeLog) (missing altoghether)

- the [legacy firmware changelog](https://github.com/trezor/trezor-firmware/blob/master/legacy/firmware/ChangeLog) (missing some updates)

to include the information about bundled upgrades.

**Comment by prusnak** [comment]
Added in 324cb651c67cd2c77e8d459c9d6d327b73756c5b
