### ISSUE TITLE
Replace banner by normal header in recovery flow

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2947]
Replace banner by normal header in receive flow + align text to left according the design below:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/57008159/231137908-ecb03953-81a3-4589-9931-59669d1d0746.png">
<img width="121" alt="image" src="https://user-images.githubusercontent.com/57008159/231138576-d71756fb-9e15-4733-9769-7c2690415e31.png">

**Comment by mmilata** [comment]
I think this has been fixed by #3163. The current state matches Figma, which I assume is more up to date than this issue.
