### ISSUE TITLE
Coinjoin screens for T2B1

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2957]
**Design:** Ready below

**Comment by grdddj** [comment]
Draft without loader done in [e1252e9](https://github.com/trezor/trezor-firmware/pull/2610/commits/e1252e9ee9f9a2415f29a4e47d15b80ad34f1f1b):

![image](https://user-images.githubusercontent.com/42543243/231779469-eb990df1-170f-49fe-8662-1d425bbc1fa3.png)

**Comment by Hannsek** [comment]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/57008159/234241265-e90da69c-f01d-4c53-97b2-64b8b50ba8eb.png">

**Comment by Hannsek** [comment]
Is this done?

**Comment by grdddj** [comment]
> Is this done?

No, the loaders are missing there

**Comment by Hannsek** [comment]
Small changes: Font in header, wording

https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?type=design&node-id=8825-68716&t=kyXA4olzpDvXBNZr-4

**Comment by grdddj** [comment]
Merged in https://github.com/trezor/trezor-firmware/pull/3135
