### ISSUE TITLE
Device freezes after computer lock 

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-firmware#296]
browser: Chrome
OS X
communication protocol: Bridge/WebUSB

It happens with 2.1.2 ver 50f16366

Steps to reproduce:
1. Initialize your device and start "Create new wallet process" (it doesn't matter if you choose Shamir or Simple backup)
2. Lock your computer during the process.
3. Carry on with the process on Trezor device. 

Result: 
at some point, the device will freeze. 
![2019-07-01 14 41 13](https://user-images.githubusercontent.com/31442634/60437294-55889380-9c0e-11e9-9726-cb5ebe112012.jpg)
![2019-07-01 14 41 07](https://user-images.githubusercontent.com/31442634/60437297-55889380-9c0e-11e9-9aa0-3e4710a2e3ec.jpg)

It seems not that critical, as if you reload the web wallet the device becomes functional again. 

I will check the 2.1.1 fw version as well.

**Comment by pankrats** [comment]
With 2.1.1 the device screen just goes blank during the same use-case. 
So I guess it is not a regression. 
![2019-07-01 14 53 51](https://user-images.githubusercontent.com/31442634/60438044-0e030700-9c10-11e9-971e-05f655448328.jpg)

**Comment by ZdenekSL** [comment]
Closed after discussion. Wont be done.

**Comment by tsusanka** [comment]
Because this can't be fixed easily (and is probably more of a bridge issue).
