### ISSUE TITLE
Exclamation point is not centered inside the warning icon

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2980]
<img width="253" alt="image" src="https://user-images.githubusercontent.com/57008159/234051321-b78fe73f-6de5-4739-a15a-98d263cf6484.png">

**Comment by grdddj** [comment]
The distance from the boundary to the exclamation mark is currently 21px from left and 23px from right.

The best I could do is to make it 23 px from left and 21 from right (when manually increasing `BlendedImage.fg_offset` by one)

There might be some limitation of `BlendedImage`.

It is not a severe problem, so unless @TychoVrahe  or @mmilata have quick solutions, I propose not spending time on this (at least not now)
