### ISSUE TITLE
Coverage: num_pad.py

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#299]
The following file has 0% coverage:

* src/trezor/ui/num_pad.py

Is it used in the firmware? If yes, can we somehow test it?

**Comment by tsusanka** [comment]
It is currently not used. It was developed for Shamir backup to enter number of shares and threshold, but we've finally replaced it with the + - interface.

**Comment by prusnak** [comment]
Ah, OK. Let's delete this. In case we want it back, we'll find here: 3c40ab8d96cd0be42c16d3d4f413ff2608eb9f1f (the commit which deletes it).
