### ISSUE TITLE
How can i sign my custom firmware legacy

### ISSUE THREAD

**Issue by taherfattahi** [trezor/trezor-firmware#2998]
I build and compile all of the things from legacy firmware and now I have `trezor.bin` inside the firmware folder now how can I sign this firmware bin file?

**Comment by matejcik** [comment]
hello, this is an issue tracker, not a user support forum. Feel free to repost your question to the Trezor Forum at forum.trezor.io, or the official subreddit /r/Trezor, or the gitter chat trezor/community
