### ISSUE TITLE
Interested in customizing the bootloader and firmware

### ISSUE THREAD

**Issue by taherfattahi** [trezor/trezor-firmware#2999]
Hello, I'm interested in customizing the latest bootloader and firmware of Trezor from the git repository. Could you please guide me on how to sign the firmware to ensure it runs correctly? Additionally, will I be able to use Trezor suite with the customized firmware later on?

**Comment by matejcik** [comment]
hello, this is an issue tracker, not a user support forum. Feel free to repost your question to the Trezor Forum at forum.trezor.io, or the official subreddit /r/Trezor, or the gitter chat trezor/community
