### ISSUE TITLE
Bitcoin only firmware

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#3]

**Comment by tsusanka** [comment]
Let's not forget to add this to CI as a new stage.
At first, wallet won't offer this fw.

**Comment by prusnak** [comment]
Implemented for legacy in https://github.com/trezor/trezor-firmware/commit/236ca1ae830d3c0b7fd9755a1286141484e0b567 + https://github.com/trezor/trezor-firmware/commit/597b9fabd1f4c35c35bd24dbf588048ac5cd4cac

**Comment by prusnak** [comment]
https://github.com/trezor/trezor-firmware/issues/135 needs to be done for Trezor Model T first

**Comment by prusnak** [comment]
Depends on https://github.com/trezor/trezor-firmware/pull/421

**Comment by prusnak** [comment]
Implemented in https://github.com/trezor/trezor-firmware/pull/427 for TT

**Comment by prusnak** [comment]
PR https://github.com/trezor/trezor-firmware/pull/427 merged, Done! :tada:
