### ISSUE TITLE
MAGIC ERC-20 token support not working

### ISSUE THREAD

**Issue by mzolkiewski** [trezor/trezor-firmware#3001]
**Describe the bug**
A while back I opened a PR to add support for the [MAGIC](https://coinmarketcap.com/currencies/magic-token/) token on Arbitrum https://github.com/ethereum-lists/tokens/pull/704
The PR got merged and since then there have been multiple Trezor firmware updates but still token transfers are shown as UNKNOWN on the Trezor display.
Did I do something wrong in the PR? That was the first Arbitrum token added to token list so maybe that's the reason it's not working?

**Firmware version and revision**
2.6.0

**Desktop/smartphone setup (please complete the following information):**
Trezor Model T.

**To Reproduce**
1. Initialize a transfer of MAGIC token on Arbitrum.
2. Check Trezor display.

**Expected behavior**
Trezor display should show the MAGIC token name.

**Comment by matejcik** [comment]
```
$ trezorctl ethereum -a sign-tx \
   -n m/44h/60h/0h \
   --chain-id 42161 \
   --gas-limit 100 \
   --max-gas-fee 1000 \
   --max-priority-fee 1000 \
   --eip2718-type 2 \
   --nonce 1 \
   --token 0x539bdE0d7Dbd336b79148AA742883198BBF60342 \
   0x000000000000000000000000000000000000dEaD 1234567890000000000
```
  
![Screenshot from 2023-05-09 10-22-03](https://user-images.githubusercontent.com/596073/237040315-f6dca4ea-4498-4028-bbae-c4e1081cfea8.png)

---

can you provide _more detailed_ steps to reproduce?

**Comment by mzolkiewski** [comment]
Interesting. I just tried the command you provided and still got UNKNOWN on my physical trezor. Same for the people on my team. Can you try on a physical device?
FYI I had to do it without the `-a` option though because I got an error `No such option: -a`. Not sure what `-a` does?

**Comment by matejcik** [comment]
> FYI I had to do it without the `-a` option though because I got an error `No such option: -a`. Not sure what `-a` does?

that would be the reason. please update your trezorctl first

since 2.6.0 the definitions for tokens are downloaded from Trezor servers on demand, see https://docs.trezor.io/trezor-firmware/common/ethereum-definitions.html for details. you need to pass an option to trezorctl to enable this.
If you're using Trezor Connect, you need to make sure you are on v9. If you have your own integration, you will need to implement the definitions as documented on the above link.

**Comment by mzolkiewski** [comment]
I see, thank you for the explanation. I did update `trezorctl` and now I can see MAGIC on my display.
Now what about a more "real life" use case where we just want to send some MAGIC via Metamask? When I try that, it still says UNKNOWN. Am I to understand that Metamask needs to implement this on their end as per the link above?

Just so we're on the same page, here are the steps to reproduce the Metamask issue:
1. Connect your trezor to metamask
2. Go to https://arbiscan.io/token/0x539bde0d7dbd336b79148aa742883198bbf60342#writeProxyContract
3. Click `Connect to Web3` and connect trezor wallet via Metamask
4. Open the `transfer` method
5. Provide any recipient and amount and click `Write` - you will need some ETH and MAGIC to get through Metamask validation
6. Check trezor display - the token is shown as UNKNOWN

**Comment by Hannsek** [comment]
It is exactly as you say. MetaMask need to release the new version. Meanwhile, you can use other wallet, like Enkrypt.
