### ISSUE TITLE
T2B1: regenerate icons with odd height

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#3016]
In the past, there was a limitation that the icons need to have even height. Because of that, some icons have now an empty bottom row, to satisfy this limitation. We can regenerate those to make them odd-heighted

**Comment by Hannsek** [comment]
Is this done also for bootloader?

**Comment by grdddj** [comment]
> Is this done also for bootloader?

Bootloader is using the majority of icons from firmware, so it benefits from this as well.

There are some extra icons like these

![image](https://github.com/trezor/trezor-firmware/assets/42543243/2be18349-a17f-45b6-a1b8-ad3d0ba86236)

that I cannot find as `png` icons (in `core/assetrs/model_r`). These work fine however, so no necessary action there

**Comment by Hannsek** [comment]
Ok, eventually, we can put there pngs of these icons.
