### ISSUE TITLE
Support THORChain/RUNE

### ISSUE THREAD

**Issue by gasull** [trezor/trezor-firmware#3022]
**Design:** [Figma](TODO)

**Spec:** [Notion](TODO)

[THORChain](https://thorchain.org/) is the largest non-custodial multichain DEX.  It works on the layer 1s, without wrapping assets.  Its nodes bond the RUNE cryptocurrency to enter the network.

Please support THORChain/RUNE, as this is important for the non-custodial crypto ecosystem at large.

**Comment by gasull** [comment]
A better link to read about THORChain:

https://docs.thorchain.org/

**Comment by Hannsek** [comment]
We are not planning to support THORChain anytime soon. Therefore, I am closing this issue as not planned. We can reopen this if it become relevant.
