### ISSUE TITLE
Non-debug builds do not finish some layouts

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#3026]
I am observing a strange thing on both `TT` (on master) and `TR` (on its branch) when doing `non-debug-frozen-emulator-build`, e.g. `make build_unix_frozen` or `TREZOR_MODEL=R make build_unix_frozen`

The issue looks like this:
- after a command, e.g. `trezorctl device wipe`, the `UI` does not go back to the `homescreen` (the screen is frozen at the end of the loader), but there seems to be an "infinite loop" spawning new `Homescreen` objects (which is the case also right after spawning the emulator).

On `TR`, I am facing it even on the hardware device.

Everything is fine in a debug-build, so there is probably some difference coming from `if __debug__:`, but I was not able to find something relevant.
 
![image](https://github.com/trezor/trezor-firmware/assets/42543243/b0e6be81-0efd-4c74-9a63-10ea481198b7)

**Comment by matejcik** [comment]
this is what I get when running a non-debug build from master:
![image](https://github.com/trezor/trezor-firmware/assets/596073/3da8666f-b6dd-4356-b265-aee31272ffd2)
my guess is that this is related

**Comment by matejcik** [comment]
found the problem:
https://github.com/trezor/trezor-firmware/blob/master/core/src/trezor/ui/layouts/tt_v2/homescreen.py#L31-L38
looks like it got broken in some rebase because the comment "in __debug__ mode" indicates that there _used to be_ if debug around it

**Comment by Hannsek** [comment]
Seems related to [this](https://github.com/trezor/trezor-firmware/issues/2788).
