### ISSUE TITLE
Questions about Shamir usage

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#303]
- Is the keyboard layout easy to use?
- Does it bother you that the passphrase keyboard and Shamir recovery keyboard have different layouts?
- Should there be an infobox for T9?

**Comment by tsusanka** [comment]
Tutorial for testing:

- Let the users try out reset (initilization) with Shamir backup
- Do they understand they can backup now or delay the backup?
- Let the users go through the complete recovery process
- Make up and enter passphrase (so the user sees two different keyboards)
