### ISSUE TITLE
T2B1 - screen is stuck on the last screen of flow

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3032]
E. g. 
- when you confirm a send tx, the last screen of the flow is `signing tx` screen
<img width="227" alt="image" src="https://github.com/trezor/trezor-firmware/assets/57008159/8b68f2cd-56da-4f14-a5c8-77bc87652e65">

- when you confirm receive address, the screen is stuck on this screen: 
<img width="265" alt="image" src="https://github.com/trezor/trezor-firmware/assets/57008159/13b99966-6974-4117-af16-c637e439d0e2">

It gets unstuck when device receives some additional message.

**Comment by grdddj** [comment]
Isn't this a duplicate of (already solved) https://github.com/trezor/trezor-firmware/issues/3026?
