### ISSUE TITLE
Device name does not support diacritics and emojis

### ISSUE THREAD

**Issue by iBobik** [trezor/trezor-firmware#3034]
**Describe the bug**
After update to 2.6.0 my name on the Trezor was crippled.

**Firmware version and revision**
2.6.0

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor Suite
 - OS: macOS
 - Version 23.4.2

**To Reproduce**
1. Name your device to e.g. "T žščřěýáíéúů 😀"
2. See inverse `?` characters on the Trezor screen

**Expected behavior**
All UTF characters will be rendered properly

**Screenshots**

<img width="1092" alt="Snímek obrazovky 2023-05-24 v 14 00 15" src="https://github.com/trezor/trezor-firmware/assets/614232/dfbab20f-7db3-4b13-93ee-da41896e0029">

![IMG_5949](https://github.com/trezor/trezor-firmware/assets/614232/e47eece2-91fc-48dc-a68b-a0ea427c2e48)

**Comment by Hannsek** [comment]
Yeah, I have this in my mind for several month. We would eventually solve it in suite, where we wouldn’t allow diacritics and special characters.
I closed this issue as there is no way in near future we would implement this.

**Comment by Hannsek** [comment]
Added the [issue](https://github.com/trezor/trezor-suite/issues/8604) to Trezor Suite.
