### ISSUE TITLE
monero get-address returns DataError regardless of hardening

### ISSUE THREAD

**Issue by chaserene** [trezor/trezor-firmware#3036]
**Describe the bug**
trezorctl's `monero get-address` command returns a DataError, complaining about a non-hardened path, even when the path is hardened all the way.

**Firmware version and revision**
2.6.0, universal

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: trezorctl 0.13.6 from the trezor PyPI library
 - OS: GNU/Linux

**To Reproduce**
1. run `trezorctl monero get-address --address m/44'/128'/0'/0'`
2. proceed on the device either with or without a passphrase
3. see the error: `Error: DataError: Non-hardened paths unsupported on Ed25519`

**Expected behavior**
I expect to get the 0th account's (in Monero account terms) 0th address.

another interesting thing is that a few versions ago (firmware 2.5.3, trezorctl 0.13.5) the working path format for this command was `m/44'/128'/x'` (x≤0), which doesn't conform to BIP32, but makes more sense since the current Monero address derivation scheme doesn't have a notion of external and internal key chains. now if you use such a path, trezorctl hangs indefinitely.

**Comment by prusnak** [comment]
My intuition tells me you are not quoting the variables in shell properly.

Does these two lines work as expected?

```
trezorctl monero get-address --address "m/44'/128'/0'/0'"
trezorctl monero get-address --address m/44h/128h/0h/0h
```

**Comment by matejcik** [comment]
> please show this requirement in the help article of the command

This is a property of your shell, not of trezorctl -- and the help text is not a place to explain how your shell works.

I agree that it would be nice to have some sort of documentation on trezorctl that summarizes these relatively common gotchas, but the help texts are not it.

**Comment by prusnak** [comment]
Added https://github.com/trezor/trezor-firmware/issues/3037 to handle the quoting issue.
