### ISSUE TITLE
Use m/44h/128h/0h instead of m/44'/128'/0' for hardened paths everywhere

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#3037]
People have trouble quoting paths in shell (see https://github.com/trezor/trezor-firmware/issues/3036 for an example). Using `h` instead of `'` helps with this.

**Comment by matejcik** [comment]
is it ok to change this in descriptors too? (it changes the checksum)

**Comment by prusnak** [comment]
> is it ok to change this in descriptors too? (it changes the checksum)

Yes, descriptors too, please
