### ISSUE TITLE
DEBUG_BUILD=1 problems for build_unix target

### ISSUE THREAD

**Issue by tylerdmace** [trezor/trezor-firmware#304]
```Bash
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find -lc
/usr/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
scons: *** [build/unix/micropython] Error 1
make: *** [Makefile:106: build_unix] Error 2
```

I see reference to this issue in the old `trezor-core` repo and it was closed as being a problem with Ubuntu. I, however, can confirm this issue exists for at least four distributions (clean installs) so I'm inclined to believe that there is a fix somewhere in `SConscript.unix` that resolves library paths better.

**Comment by matejcik** [comment]
the problem is that `-no-pie` isn't actually an option that exists in `ld`
we can switch to gcc's `--no-pie`, which maybe does what we want? but i don't know what it is that we want

@prusnak do you know why no-pie is there? if not, i'd drop the whole option. otherwise let's figure out if passing it to gcc instead of ld helps

**Comment by hiviah** [comment]
The `DEBUG_BUILD=1` works when you delete `-no-pie` from `SConscript.unix`. Also it seems that you need to enable one ifdef in `py/nlrx64.c` in `vendor/micropython`:

    --- a/py/nlrx64.c
    +++ b/py/nlrx64.c
    @@ -58,9 +58,9 @@ unsigned int nlr_push(nlr_buf_t *nlr) {
         #else
     
         __asm volatile (
    -    #if defined(__APPLE__) || defined(__MACH__)
    +    //#if defined(__APPLE__) || defined(__MACH__)
         "pop    %rbp                \n" // undo function's prelude
    -    #endif
    +    //#endif

Without the nlr patch the emulator segfaults.

**Comment by prusnak** [comment]
@tylerdmace What distros have you been trying? This works perfectly for distros I use (including the Debian which is used in the Dockerfile).

**Comment by hiviah** [comment]
For some reason, the nlr needs patch for debug build and must not have it without debug build (tried on Ubuntu 16.04 LTS so far)

**Comment by hiviah** [comment]
Seems that using `-Og` instead of `-O0` in gcc optimization flags makes the segfault go away without the need of nlr patch.

**Comment by tsusanka** [comment]
@hiviah is this issue still relevant?

**Comment by hiviah** [comment]
Apparently this still persists in the last three Ubuntu LTS (what I could test). Just invocation changed:

*  `make UNIX_PORT_OPTS="TREZOR_EMULATOR_DEBUGGABLE=1" build_unix`
*  `make UNIX_PORT_OPTS="TREZOR_EMULATOR_DEBUGGABLE=1" PYOPT=0 build_unix_frozen`

I'll fix it by changing the `-O0` to `-Og`. Worked well so far and even the gcc manual seems to suggest `-Og` should be preferred to `-O0` for debugging now.
