### ISSUE TITLE
Behaviour of the xpub displaying should be aligned with address displaying

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3047]
https://github.com/trezor/trezor-suite/issues/3454#issuecomment-1569917006

xpub qr code under `i` button, missing x -> xpub mismatch?

**Comment by Hannsek** [comment]
Probably related: https://github.com/trezor/trezor-firmware/issues/3043

**Comment by bosomt** [comment]
Checked it with latest version 23.6.1 that will be soon released and it does not show complete xpub address when address is too long.
problematic coins are:
Cardano Ada and Bitcoin taproot address.

**Model One** via confirm button you are navigated to rest of XPUB characters
**Model T** shows first part of xpub and rest is ignored so if you only check last charasters of XPUB it wont match when compared with Trezor Suite.

![image](https://github.com/trezor/trezor-firmware/assets/31506317/af67f2d8-edfb-4f8e-818e-2e37b86f083d)

**Comment by mmilata** [comment]
I can confirm the Cardano issue but not the taproot one. Can somebody please provide steps to make trezor display truncated taproot XPUB?

The old UI did not show QR code for XPUBs, I'll see if it can be added such that it's scanable.

**Comment by bosomt** [comment]
Checked it one more time /multiple accounts + testnet/ and Bitcoin taproot XPUB is displayed **correctly** /except prefix missing / sorry for confusion. 

```
tr([2c27fa4b/86'/0'/0']xpub6BvdKTJruDymKUqK7wm9q3NsieBnNzjeYEC6ik25wPLY5aR3A34TQhJtfnegRTZmWPbcaBbB1NphhnfiSz3EXmU4uKqkx9BaiCr9d8q5DSS/<0;1>/*)

vs

xpub6BvdKTJruDymKUqK7wm9q3NsieBnNzjeYEC6ik25wPLY5aR3A34TQhJtfnegRTZmWPbcaBbB1NphhnfiSz3EXmU4uKqkx9BaiCr9d8q5DSS

```
