### ISSUE TITLE
Recovery: warn user if they enter different identifier than expected

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#305]
Tell the user if this mnemonic is part of another seed (different identifier) right after the second word.

Somewhat in conflict with #292

**Comment by tsusanka** [comment]
Let's do this instead of #269 .

Only display an error (asap) and add a button to try again.

**Comment by tsusanka** [comment]
Let's do this on top of #331

**Comment by ciny** [comment]
Code merged from ciny/shamir_word_checks branch to tsusanka/iss270-persistance

**Comment by tsusanka** [comment]
Merged to master.
