### ISSUE TITLE
CI tests sometimes miss UI report

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#3066]
Lately, it is quite common that some CI tests - be it `click` or `device` tests - do not have the `UI report` (`test_ui_report` directory) exported in the artifacts

https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/4422578927/artifacts/browse

**Comment by Hannsek** [comment]
It seems that the problem is only with `core device r tests` and this is happening with all jobs.

Or can it be related to pipeline #891615270?
