### ISSUE TITLE
Testing simple FIDO2 examples from python-fido2 module fails on Trezor model T.

### ISSUE THREAD

**Issue by ashleysommer** [trezor/trezor-firmware#3068]
**Describe the bug**
Creating a FIDO2 credential using the [FIDO2 python module reference hmac-secret example](https://github.com/Yubico/python-fido2/blob/main/examples/hmac_secret.py) fails with "Authenticator does not support ClientPin". 

The error is pretty easy to track down by stepping through the python-fido2 sourcecode. When [creating a new credential](https://github.com/Yubico/python-fido2/blob/54cee2216a065620b04d0a4d6c75ecb2b506feda/fido2/client.py#L549-L595) the client library [checks if it needs to ask for Pin Auth](https://github.com/Yubico/python-fido2/blob/54cee2216a065620b04d0a4d6c75ecb2b506feda/fido2/client.py#L531) from the device. To determine this, it checks [for if 'uv' is in ctap info options, and if `'uv==True'`](https://github.com/Yubico/python-fido2/blob/54cee2216a065620b04d0a4d6c75ecb2b506feda/fido2/client.py#L474). The Trezor model T [does advertise "uv=True"](https://github.com/trezor/trezor-firmware/blob/8d812ca36e1e04049b849f06af925b629cc6196b/core/src/apps/webauthn/fido2.py#L1904-L1914). On the very next line the fido2 library [attempts to initialize the ClientPin verification method](https://github.com/Yubico/python-fido2/blob/54cee2216a065620b04d0a4d6c75ecb2b506feda/fido2/client.py#L532) then [throws an exception](https://github.com/Yubico/python-fido2/blob/54cee2216a065620b04d0a4d6c75ecb2b506feda/fido2/ctap2/pin.py#L252) because "clientPin" is not in info.options.

Seems like when it comes to 'uv' and 'clientPin', you need both advertised or neither advertised.

**Firmware version and revision**
Testing on Trezor Model T Universal Firmware v2.6.0

**Desktop/smartphone setup (please complete the following information):**
 - Python3, python-fido2 module 

**To Reproduce**
1. Plug in Trezor model 2 and input your PIN to connect the device to the PC
2. Run the reference [hmac_secret.py](https://github.com/Yubico/python-fido2/blob/main/examples/hmac_secret.py) example file.
3. See error "Authenticator does not support ClientPin".

**Expected behavior**
Trezor T FIDO2 info should not advertise 'uv=True' in info.options if 'clientPin' is not in info.options.

**Additional context**
For transparency: I was sent a Trezor Model T free of charge from SatoshiLabs for the purposes of testing and [implementing FIDO2 hmac-secret support in a popular opensource application](https://github.com/keepassxreboot/keepassxc/discussions/9506).

**Comment by ashleysommer** [comment]
If I patch the python-fido2 library to ignore the advertised 'uv==True' and assume no UV, it works normally, asks for my pin on the screen, then creates and registers the credential correctly on the device.

But it fails again further on. When sending the hmac-secret salt for attestation the library needs access to the pin-protocol's shared secret (to encrypt the salt going over the wire). This causes the fido2 library to [attempt to initialize the ClientPin module again](https://github.com/Yubico/python-fido2/blob/54cee2216a065620b04d0a4d6c75ecb2b506feda/fido2/ctap2/extensions.py#L127-L128) that leads to the same "Authenticator does not support ClientPin" message.

Patching to ignore the "uv==true" info in this case does not work, because the `hmac-secret` requires clientPin support regardless.

Note, a lot of this is mentioned already under the "User Verification" heading in the  Trezor's [webauthn app README]( https://github.com/trezor/trezor-firmware/tree/master/core/src/apps/webauthn).

**Comment by prusnak** [comment]
> Seems like when it comes to 'uv' and 'clientPin', you need both advertised or neither advertised.

You suggest that Trezor code needs fixing, but isn't it the python-fido2 code that needs to be fixed?

**Comment by ashleysommer** [comment]
I did not mean to suggest the Trezor code needs changing. I was simply filling out the provided Github Issue template with my observations. It could well be the case that the python-fido2 library is acting incorrectly here.

From my perspective, I (perhaps incorrectly) believed the python-fido2 client code to be somewhat of a reference-implementation of a FIDO2 client that FIDO2 hardware is tested against, and it was surprising to me that the Trezor implementation does not work with it.

I am in the process of opening an issue on the python-fido2 Github issue tracker, to see if it is able to be fixed on their side.
