### ISSUE TITLE
TOS link not visible in Shamir backup wallet creation

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#3076]
For `TT`, when choosing (Super)Shamir backup, the wallet creation screen does not show `trezor.io/tos` link as it cannot fit the screen because of two-line title

Mentioned at https://github.com/trezor/trezor-firmware/pull/3074#issue-1756683383

![image](https://github.com/trezor/trezor-firmware/assets/42543243/ccb2827c-fd39-46ad-a821-318c6f69775a)

**Comment by Hannsek** [comment]
With new wording, `SHAMIR` should fit on one line. 
![image](https://github.com/trezor/trezor-firmware/assets/57008159/0d3c0c53-cc45-4096-981b-ad0604b6a9cc)

However, `SUPER SHAMIR` wouldn't fit on one line. Is it possible to have different vertical space between the "paragraphs"? 
![image](https://github.com/trezor/trezor-firmware/assets/57008159/cde25e36-7370-4793-98eb-5e360a4cbc0b)

**Comment by grdddj** [comment]
> With new wording, `SHAMIR` should fit on one line. ![image](https://user-images.githubusercontent.com/57008159/246651688-0d3c0c53-cc45-4096-981b-ad0604b6a9cc.png)

Right, we are currently hardcoding the line-break, we can just replace it by normal space

 
> However, `SUPER SHAMIR` wouldn't fit on one line. Is it possible to have different vertical space between the "paragraphs"? ![image](https://user-images.githubusercontent.com/57008159/246651654-cde25e36-7370-4793-98eb-5e360a4cbc0b.png)


I guess it will be possible to get rid of the vertical space when the label has two lines - we are currently putting `\r` at the end of the first paragraph to create the space

**Comment by prusnak** [comment]
I think we should drop "SUPER SHAMIR" and just use "SHAMIR" for this case as well. We don't use this wording anywhere in the product.

**Comment by grdddj** [comment]
> I think we should drop the word "SUPER| from "SUPER SHAMIR" and just use "SHAMIR" for this case as well. We don't use this wording anywhere else in the product.

That would make things easier, I am for it :)

**Comment by Hannsek** [comment]
Fair enough.
