### ISSUE TITLE
50th character in passphrase cannot be 'b'

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#3078]
**Describe the bug**
Keyboard is disabled for 50th character after the first tap

**Firmware version and revision**
2.6.0 Production

**To Reproduce**
1. Enter passphrase "1234567890" x4 then "123456789b" i.e. "1234567890123456789012345678901234567890123456789b"

**Expected behavior**
'b' can be entered

**Screenshots**
![P_20230614_190014](https://github.com/trezor/trezor-firmware/assets/216917/fa1db226-c3bb-4ec5-92ef-792a85d35962)
![P_20230614_190007](https://github.com/trezor/trezor-firmware/assets/216917/65d43301-5623-4f3b-a393-9c707851b84d)

**Additional context**
https://www.reddit.com/r/TREZOR/comments/1498be1/ive_encountered_a_problem_when_im_typing/

**Comment by Hannsek** [comment]
This is already fixed.
