### ISSUE TITLE
Adjust pin entry to look the same as passphrase entry

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3087]
https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/4488853768/artifacts/test_ui_report/passed/TR-click_tests-test_pin.py%3A%3Atest_pin_change.html

<img width="265" alt="image" src="https://github.com/trezor/trezor-firmware/assets/57008159/8175f125-5b3e-4649-96bb-54c3a8d5fdf8">
<img width="261" alt="image" src="https://github.com/trezor/trezor-firmware/assets/57008159/229ea9ec-dcd7-4cf6-9bde-0a8138bdb148">

Should be centered between the upper character line 
numbers/text) and the bottom button.

**Comment by Hannsek** [comment]
We can do either this or do it the same as passphrase input. i.e. header would be still present and actual pin entries would be below it.
<img width="241" alt="image" src="https://github.com/trezor/trezor-firmware/assets/57008159/966437cd-5d21-497d-81bc-3f0b9e94ba43">

**Comment by Hannsek** [comment]
The second option is probably better. What do you think @grdddj?

**Comment by grdddj** [comment]
> The second option is probably better. What do you think @grdddj?

I like this, so it will show `ENTER PIN/WIPECODE` all the time. The second line will be then a subprompt (`You have 15 tries left`) when PIN is empty, or asterisks when user already inputted something.

**Comment by grdddj** [comment]
> `You have 15 tries left` is visible only after the first unsuccessful try, no?
> 
> ![image](https://user-images.githubusercontent.com/57008159/246830607-6b92c263-978f-4585-ab6e-82d53f35bec9.png)

Right, not on the first try. We currently do not show the underscore when the PIN is empty, but will do it

**Comment by Hannsek** [comment]
I'd say to that one below, as the user wants to see the words. 
![image](https://github.com/trezor/trezor-firmware/assets/57008159/99d99001-ab17-470c-a0f0-73235807b453)

**Comment by grdddj** [comment]
Merged in https://github.com/trezor/trezor-firmware/pull/3135
