### ISSUE TITLE
Help me please Trezor One

### ISSUE THREAD

**Issue by sairex28** [trezor/trezor-firmware#309]
Good afternoon, I bought a trezor wallet, did everything on the video in YouTube, well, setting the wallet, after clicking on the update to the latest version, I hung up, I updated the page and after that I could not enter the wallet myself, what should I do? Can someone help me? What is the problem? Posted in those. Support is silent for more than 3 days ... Also on the computer can not find the driver Trezor interface.

**Comment by raymonddurk** [comment]
This isn't the appropriate forum for this. Wipe the device (assuming you have the seed backed up) and download the firmware again.

**Comment by sairex28** [comment]
I tried to reinstall, nothing helps ... I do not know where to write with my problem.

**Comment by sairex28** [comment]
I wrote "To continue connect Trezor", I insert it, but it does not see it or that I do not understand, I tried different cables already.

**Comment by prusnak** [comment]
=> https://trezor.io/support/
