### ISSUE TITLE
Request for Polkadot Ecosystem Support

### ISSUE THREAD

**Issue by etsraphael** [trezor/trezor-firmware#3092]
Hello Trezor Team,

I am writing as a member of the Polkadot community, as well as a potential future Trezor user. Polkadot is currently ranked 13th in the cryptocurrency market cap and has been demonstrating consistent growth since its inception in 2020. The platform is known for its solid team and promising features, making it one of the key players in the blockchain industry.

Despite this, I noticed that Trezor does not yet support the Polkadot ecosystem, which is a deterrent for me and likely many others in our community from choosing Trezor as our hardware wallet. Many of us have been using Ledger, but due to various reasons, the trust in that company has been eroding and we are actively seeking alternatives.

Given the market position and the reputation that Trezor holds, I believe adding support for the Polkadot ecosystem could be a strategic move that benefits both Trezor and its potential users. This will not only expand your customer base but also serve as a vote of confidence for the Polkadot community, reinforcing your position as a leader in the hardware wallet market.

I understand that adding support for a new blockchain is a significant undertaking, but I believe the potential benefits for Trezor and its users would make it worth considering.

I appreciate your time in considering this proposal, and I'm looking forward to seeing the Trezor ecosystem continue to grow.

**Comment by Hannsek** [comment]
Hello @etsraphael, thank you for bringing up this issue.

We appreciate your interest in expanding the blockchain/coins supported by our ecosystem. Currently, we are in the process of developing our roadmap to incorporate new assets into Trezor. Unfortunately, I cannot provide further details at this time. Rest assured that once our roadmap is finalized, we will create a dedicated issue on GitHub to address this matter. Therefore, I am closing this issue.

If you have any additional questions or concerns, please feel free to continue here.
