### ISSUE TITLE
combine script does not combine firmware properly

### ISSUE THREAD

**Issue by TychoVrahe** [trezor/trezor-firmware#3123]
TT firmwares are split into two discrete sections. When attempting to combine board+boot+firmware, combine script makes a binary, but does not account for the "hole" in flash that needs to be skipped.

**Comment by prusnak** [comment]
> When attempting to combine board+boot+firmware, combine script makes a binary, but does not account for the "hole" in flash that needs to be skipped.

That's correct. We never used the combine scripts to combine a firmware that was occupying the second section in the past (because the testing firmware was rather small).

**Comment by matejcik** [comment]
do we care? i.e., is there a usecase to combine with a full firmware?

i would be ok with "fixing" this by adding a size limit to the combine script

**Comment by TychoVrahe** [comment]
well i needed to combine a binary for purpose of emc testing and the testing firmware was not combined properly. while its easier for me to send one binary for flashing, i think we can also live with flashing combined board+bootloader and uploading the firmware via suite, but at least the error message would be nice so that we don't unknowingly produce binaries that dont work

**Comment by prusnak** [comment]
If there is a usecase and it seems there is, I vote for fixing the combine script. It shouldn't be much harder than just adding a size limit. If you already know the size limit, you should also know where to flash each part.
