### ISSUE TITLE
Differentiate changelog entries between core models

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#3159]
We should be able to produce changelog for T2T1 independent of changelog for T2B1, and not include T2B1-specific items for T2T1 and vice versa.

Probably as simple as creating a convention for changelog entries, e.g., `[T2B1] Changelog goes here` for model-specific?

**Comment by Hannsek** [comment]
@matejcik Do we need this to be done until the next (November) release?

**Comment by mmilata** [comment]
What needs to be done is documenting the convention. Generating the filtered changelogs is easy, if we want it I'll do it for the release.

**Comment by matejkriz** [comment]
We have links to the CHANGELOG file from Suite UI, so we just need the original file to keep exist so there are no broken links. 

Other question is what we want to present to the users and how and that is completely product question so @Hermez-cz please create an issue if needed or let's discuss possible options and priority...
