### ISSUE TITLE
Add colors information to trezor-common repo

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#3160]
There should be a json dict `common/models/colors.json` with the following structure:
```
{
  "T2B1": {
    0: "Black",
    1: "White"
  }
}
```
Mainly for Connect/Suite consumption but we might need this too.

additionally, we might want to add internal names mapping? `common/models/names.json`
```
{
  "T1B1": "Model One",
  "T2T1": "Model T",
  "T2B1": "Model R"
}
```
how about it @Hannsek ?

**Comment by prusnak** [comment]
This might be a single json where colors are a subkey?

**Comment by romanz** [comment]
Should https://github.com/trezor/trezor-firmware/blob/main/common/models.json be updated with TS7 colors?

CC: @MiroslavProchazka
