### ISSUE TITLE
Final word in recovery freezes when the computer is sleeping

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#3165]
**Describe the bug**
Entering the 12th or 24th word whilst a computer sleeps is frozen on the last screen

**Firmware version and revision**
2.6.0

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor Suite 23.7.2
 - OS: macOS ARM 13.4.1

**To Reproduce**
1. Empty Trezor
2. Recover
3. Choose 12 words
4. Sleep computer
5. Enter all seed

**Expected behavior**
Success screen

**Screenshots**

https://github.com/trezor/trezor-firmware/assets/216917/5a98027c-9556-4338-bfef-3256548c3d38

**Comment by Hannsek** [comment]
What about recovering on power bank? Trigger the recovery process on computer and then reconnect to powerbank?
