### ISSUE TITLE
T2B1 fido, u2f design

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3168]
https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Firmware?type=design&node-id=8825-68720&mode=design&t=LNvdUCDk0z9VwL5J-4

**Comment by Hannsek** [comment]
Edited in Figma. Waiting for copy approval form @b-irving.

**Comment by Hannsek** [comment]
@grdddj this is done?

**Comment by grdddj** [comment]
> @grdddj isn't this done already?

I think so - https://figma.grdddj.eu/flow/FIDO

We can close it then

**Comment by Hannsek** [comment]
Need change the error screen + change the numbering of the screens [here](https://figma.grdddj.eu/flow/FIDO).
