### ISSUE TITLE
Consider enabling flake8-bugbear

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#3179]
There are some exciting(tm) new changes in the 2023 style. Let's review and apply them.

While we're at it, consider [looking](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#flake8) at [bugbear](https://github.com/PyCQA/flake8-bugbear#list-of-warnings)

**Comment by matejcik** [comment]
black upgraded in #3570 

keeping open for bugbear

**Comment by prusnak** [comment]
> keeping open for bugbear

Maybe we should drop `flake8` and use `ruff` instead. Ruff also supports bugbear rules - see https://docs.astral.sh/ruff/rules/ - and it is blazingly fast.

**Comment by matejcik** [comment]
makes sense, closing in favor of #2820
