### ISSUE TITLE
Position of logo when loading to homescreen is different from actual homescreenlogo position

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3180]
I believe this can be solved by different homescree?

However there is an inconsistency in model name (text) It has different spacing when loading than on homescreen.

Video [here](https://satoshilabs.slack.com/archives/CL1D61PQF/p1690455778801759?thread_ts=1690454813.444529&cid=CL1D61PQF).

**Comment by Hannsek** [comment]
If it comes from firmware, it is fine, we have time. If from bootloader, we have to solve it in two weeks

**Comment by Hannsek** [comment]
This is done, right< @TychoVrahe

**Comment by TychoVrahe** [comment]
yes
