### ISSUE TITLE
Incorrect ShowDeviceTutorial response when cancelled 

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-firmware#3187]
**Describe the bug**
The `ShowDeviceTutorial` method responds with `success: true` when tutorial is canceled on device, which impacts Suite UI.

**Firmware version and revision**
2.6.1

**Expected behavior**
It responds with `success: false` when canceled on device

**Comment by grdddj** [comment]
Quick fix done in https://github.com/trezor/trezor-firmware/pull/3198 - @dahaca please check that this solves the problem in `Suite`
