### ISSUE TITLE
"Show all" instead of "view full" 

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3191]
Replace on both, TT and T2B1, `view full` with `show all`. E.g.

![image](https://github.com/trezor/trezor-firmware/assets/57008159/e05d4390-34ac-4f14-abf3-625d6581eef9)
![image](https://github.com/trezor/trezor-firmware/assets/57008159/dd0bdef4-0c94-4693-9735-31d8b1108edd)
![image](https://github.com/trezor/trezor-firmware/assets/57008159/18ac6311-6f32-4d25-a888-83a659d88b1b)

**Comment by grdddj** [comment]
Is it just highlighting the text in Figma, or do we want the text background to be yellow on TT?

**Comment by Hannsek** [comment]
It was highlighted in Figma. Replaced the screens.
