### ISSUE TITLE
Add bootloader emulator builds into CI

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#3193]
They are not being used very often, so it can happen that we break them without noticing - and then they do not work when we need them.

**Comment by TychoVrahe** [comment]
Specifically this about bootloader emulator builds. Regular bootloaders are already in CI.

**Comment by mmilata** [comment]
Is the bootloader emulator supposed to work for model T? I'm getting
> secret.c:25: undefined reference to `SECRET_AREA'

https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/4993757912

**Comment by TychoVrahe** [comment]
it is supposed to work. we should not be compiling secret.c for models without optiga
