### ISSUE TITLE
RippleGetAddress with path m/44'/1'/0'/0/0 throws Failure

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-firmware#321]
Testnets paths should be allowed for any coin

+ it would be nice to test it for every coin

**Comment by matejcik** [comment]
At the same time, we should make sure that adding testnet paths to all coins does _not_ allow `coin_name="Bitcoin"` to be signed with a testnet derivation path. Not sure if a similar issue can arise in other currencies.

**Comment by matejcik** [comment]
this is fixed in #959
