### ISSUE TITLE
Make the homescreen image fullscreen

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#322]
On model T we currently set the homepage screen as a tiny circle. Marketing mentioned it'd be nicer to have the screen all the way over the display. To be discussed.

**Comment by prusnak** [comment]
There is a good reason for that and that is visual identity + we can be sure that the label is always readable. Let's discuss that with UX.

**Comment by tsusanka** [comment]
Just to add, this was brought up by Vladimir from marketing (illustrator).

**Comment by ZdenekSL** [comment]
IMHO, its because you have the top part reserved for warnings and errors? 
![maxresdefault](https://user-images.githubusercontent.com/50332311/66842596-d5432f80-ef6b-11e9-8954-4a34fa7ddba7.jpg)

**Comment by ZdenekSL** [comment]
Closed after discussion with the product owner.

**Comment by tsusanka** [comment]
Reevaluated, we want do this.

**Comment by tsusanka** [comment]
Being done as part of the tt redesign.
