### ISSUE TITLE
Allow amounts denomination in Satoshi

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#324]
Currently, we show amounts in BTC. We should allow the denominations in satoshi, too.

Where should be the setting stored?

1) a setting of a device (stored in the device storage)
2) a setting of a software wallet (setting passed to the device in all messages showing amounts such as SignTx)

**Comment by slush0** [comment]
I prefer settings of the device (with change confirmed by the user). This could prevent some kinds of issues and potential attacks by host computer (like sudden change of denomination in signtx so user is accidentally sending 1000x more than he thinks).

**Comment by prusnak** [comment]
Issue in Trezor Suite - https://github.com/trezor/trezor-suite/issues/3004

**Comment by prusnak** [comment]
We've decided that we'll add the denomination attribute to SignTx and Trezor will show amounts according to this.
