### ISSUE TITLE
ETH fees units

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3246]
Please change ETH fees units in ETH send flow as follows:
![image](https://github.com/trezor/trezor-firmware/assets/57008159/ab25827b-8c64-40dd-be45-18d9abe7b51a)
![image](https://github.com/trezor/trezor-firmware/assets/57008159/de0fc492-6c07-49a1-a586-08bd3f0c4284)

Maximum fee: wei ETH -> ETH
Gas price: ETH -> Gwei

Add (if not already satisfied) priority fee key.

**Comment by Hannsek** [comment]
@grdddj please take a look, it should be low hanging.

**Comment by grdddj** [comment]
> @grdddj please take a look, it should be low hanging.

Right, PR done - https://github.com/trezor/trezor-firmware/pull/3414

It was quite easy to change, but I am not sure we want it like this --- please check the results/diffs
