### ISSUE TITLE
【trezorctl nem-get-address --help】The documentation description seems to be wrong.

### ISSUE THREAD

**Issue by webees** [trezor/trezor-firmware#325]
![image](https://user-images.githubusercontent.com/5155291/61099924-aada6580-a496-11e9-8bfd-7f41849020c4.png)

**Comment by tsusanka** [comment]
Are you pointing at the zeros? You are right, as [documented](https://github.com/trezor/trezor-firmware/blob/master/core/docs/coins/README.md) we allow both 44'/43'/a' and 44'/43'/a'/0'/0', but non-hardened paths are forbidden. We'll fix this.
