### ISSUE TITLE
Ethereum flow for TT

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3261]
It was [done only for T2B1,](https://github.com/trezor/trezor-firmware/pull/3188) please do it also for TT.

[Designs](https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Firmware?type=design&node-id=8833-74263&mode=design&t=92rdd2UmYU4OjVx0-4)

**Comment by Hannsek** [comment]
Already done. There is a problem in trezor-user-env

**Comment by grdddj** [comment]
> Already done. There is a problem in trezor-user-env

So that it is not hanging here - I think the issue in `tenv` was solved by re-enabling the builds. Could be closed IMO
