### ISSUE TITLE
Bake eth definitions into the next fw signing bundle

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3266]

**Comment by matejcik** [comment]
in terms of automation, it would be nice if `common/tools/release.sh` fetched the latest timestamp from https://github.com/trezor/definitions and put it in `released-definitions-timestamp.txt`

**Comment by mmilata** [comment]
I've added `cointool.py new-definitions` command in the private repo.

**Comment by Hannsek** [comment]
@mmilata can we close this?

**Comment by mmilata** [comment]
Yes, it's implemented in the private repo and is expected to be eventually merged into master. Let's reopen if more needs to be done.
