### ISSUE TITLE
"Account" key missing in altcoins receive flow

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3282]
T2B1 only?

<img width="263" alt="image" src="https://github.com/trezor/trezor-firmware/assets/57008159/d947a90a-b18d-49c9-9ff2-967df4e27b27">

**Comment by grdddj** [comment]
Currently `account` for altcoins like `bnb` is empty - I think there is no concept like "segwit" or "taproot" in these altcoins - what do you want to display there?

**Comment by matejcik** [comment]
"Account #1" ?

**Comment by Hannsek** [comment]
Ethereum #1, when it is on ETH#1 account?
XRP #1
and so on.
Does it make sense?

**Comment by grdddj** [comment]
> Ethereum #1, when it is on ETH#1 account? XRP #1 and so on. Does it make sense?

Right, so the name of the currency and ` #{num}`, that is alright
