### ISSUE TITLE
Preview of the wallpaper while setting up default homescreen

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3297]
new: ![image](https://github.com/trezor/trezor-firmware/assets/57008159/951b82b7-ff64-411b-8bd8-d116cbaf09dd)
old: ![image](https://github.com/trezor/trezor-firmware/assets/57008159/bd7d460f-9a71-40b2-b7e6-6feab8672863)

Both T2B1 and T2T1

**Comment by Hannsek** [comment]
Can someone please take it? @mmilata @grdddj

**Comment by grdddj** [comment]
> Can someone please take it? @mmilata @grdddj

Yeah, I will do it tomorrow
