### ISSUE TITLE
Non-fluent loaders

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3311]
**Describe the bug**
Buggy loaders, see video below.

**Firmware version and revision**
2.6.2 (debug and normal)

**Expected behavior**
A fluent loader.

https://github.com/trezor/trezor-firmware/assets/57008159/017f8723-b9ab-44bf-b21e-96c692510e7a

**Comment by mmilata** [comment]
Possibly related to #3296 which recently touched the loader code.
