### ISSUE TITLE
Delete "CONFIRM" button when no number is entered

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3319]
https://satoshilabs.slack.com/archives/CL1D61PQF/p1696251330393949

**Comment by Hannsek** [comment]
fixed in #3320 @grdddj ?

**Comment by grdddj** [comment]
> fixed in #3320 @grdddj ?

Nope, the `CONFIRM` button is still there, but when you click it, nothing happens

**Comment by Hannsek** [comment]
Yeah, than it is ok. I am closing this. Thanks
