### ISSUE TITLE
Send wire.ProcessError instead of ValueError where applicable

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#332]
I've noticed this in Ripple app mostly. For example [here](https://github.com/trezor/trezor-firmware/blob/96cdd886bcb37982d193f525d157a101720a7056/core/src/apps/ripple/serialize.py#L86) we should send ProcessError to the user, because it's not an error just some wrong input.

**Comment by prusnak** [comment]
Hint: don't put pointers to files in the master branch, they tend to become invalid soon
Hint2: if you are viewing the file in master (or any other branch), press `Y` on a keyboard and github will change the branch name in the URL to actual HEAD of the branch, which you can then use as a permalink

**Comment by tsusanka** [comment]
The Refined GitHub extension solves this, so I'm forgetting about it quite often. But you're right of course, fixed.

See:
![Screenshot from 2019-07-15 23-04-41](https://user-images.githubusercontent.com/1835345/61249220-046fb800-a755-11e9-86fd-d75067e63ef5.png)

**Comment by tsusanka** [comment]
Another example: providing invalid Bitcoin bech32 address (see https://github.com/satoshilabs/mytrezor/issues/818) raises Firmware error, but we should communicate to the user that the input is invalid.
