### ISSUE TITLE
Create special fw to display arbitrary text for testing purposes

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#333]
Similar to https://github.com/trezor/trezor-firmware/issues/235 UX/marketing would make use of firmware which would show arbitrary text (via the Text component) sent using trezorctl or some other simple interface.

**Comment by tsusanka** [comment]
We have encountered this with @andrewkozlik again, so I'm increasing priority.

**Comment by prusnak** [comment]
This is implemented in #713 so we just need to review the PR
