### ISSUE TITLE
Random passphrases using SLIP-0039 wordlist

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#335]
**Tasks**
1. Allow the user to generate a random passphrase on the Trezor T using words from the SLIP-0039 wordlist.
2. Allow the user to enter their passphrase using the SLIP-0039 predictive keyboard.

**Justification**
- Humans are not good at making random choices, such as generating a strong passphrase. It would therefore be useful to generate the passphrase using the hardware RNG in Trezor.
- Humans are better at remembering words rather than random sequences of symbols. However, words take long to enter. The SLIP-0039 predictive keyboard makes it possible to type for example six words in **30 touches** (4 keystrokes plus one confirmation per word). Six words is 60 bits of entropy, which is equivalent to about 13 random lowercase letters. Entering 13 lowercase letters requires **28 touches** on average on the Trezor T plus waiting when the next letter is on the same key as the previous letter. So the difficulty of entering the passphrase is approximately the same, but the word-based one is easier to remember.

**Questions**
We have to decide on how the user will access the predictive keyboard. Some possibilities are:
- Add the predictive keyboard to the list of keyboards which can be accessed by swiping over the normal passphrase keyboard. A disadvantage is that it might confuse users who are unaware of the feature.
- User will be explicitly asked prior to passphrase entry whether they want to enter the passphrase on the host, on the device or on the device using the SLIP-0039 predictive keyboard.
- There will be a configurable persistent setting to use the normal or the SLIP-0039 predictive keyboard.

**Comment by ZdenekSL** [comment]
Closed after discussion with PO
