### ISSUE TITLE
ETH send flow - contract address and token name

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3369]
current: 
![image](https://github.com/trezor/trezor-firmware/assets/57008159/1b36fa7e-af4d-4c5b-ac10-aeb5519bb77d)

new: 
<img width="477" alt="image" src="https://github.com/trezor/trezor-firmware/assets/57008159/452cb4e0-55dd-4fb0-8ceb-775716c2d82d">

![image](https://github.com/trezor/trezor-firmware/assets/57008159/dbfada52-eac0-4fde-a884-d0e85ac65773)
marquee in header

**Comment by matejcik** [comment]
what, why?
