### ISSUE TITLE
Implement screensaver for T2B1

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#3377]
For first iteration, we probably want to copy what T1 does, namely:

* when no PIN is set, show black screen after 10 minutes
* when PIN is set, lock and show black screen after autolock delay (10 min by default)

I believe we can implement this by (a) changing Lockscreen to render all black and (b) for T2B1 only, allow locking even when no PIN and not SD protect is there.

cc @Hannsek if this is really what we want

**Comment by sophiadapers88** [comment]
![image](https://github.com/trezor/trezor-firmware/assets/149452790/8f8fa89d-a556-4801-89c7-db9961ea2068)
My MM - Trezor skipping this step
