### ISSUE TITLE
Align send flow button request on T2B1 with TT

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3392]
![image](https://github.com/trezor/trezor-firmware/assets/57008159/36012c26-ef0f-4941-acee-57babef084e8)

Currently, when user clicks CONTINUE, it won't send button request to Suite.

**Comment by Hannsek** [comment]
@grdddj Can you please check the differences between TS3 and TT button requests on different flow? Cardano, btc, altcoins, …

**Comment by grdddj** [comment]
> @grdddj Can you please check the differences between TS3 and TT button requests on different flow? Cardano, btc, altcoins, …

Right, I have noticed at least `modify-amount` flow to be different - fixed as well in https://github.com/trezor/trezor-firmware/pull/3393

**Comment by Hannsek** [comment]
@grdddj is this done?

**Comment by grdddj** [comment]
> @grdddj is this done?

Will be done after merging https://github.com/trezor/trezor-firmware/pull/3393
