### ISSUE TITLE
update micropython dependency to latest stable

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#34]
1.10 points:

- [ ] Review mpconfig.h and figure out if we can disable some optional features.
- [ ] Can we enable `MICROPY_OPT_CACHE_MAP_LOOKUP_IN_BYTECODE`?
- [ ] Can we use newly-introduced `MP_STATIC_ASSERT` somewhere?
- [ ] Can we somehow benefit from pystack?
- [ ] our uctypes.sizeof patch probably no longer necessary - see micropython/micropython#3101 + micropython/micropython@2411f42
- [ ] remove SOF callback from the CDC code - see micropython/micropython@0f6f86c

1.11 points:
- [ ] ?

**Comment by jpochyla** [comment]
https://github.com/micropython/micropython/commit/fa07deda9f129c1992726d2a51c6eaac168247f0

**Comment by tsusanka** [comment]
Done by https://github.com/trezor/trezor-firmware/pull/789
