### ISSUE TITLE
Missing documentation on how to verify T2B1 

### ISSUE THREAD

**Issue by maaft** [trezor/trezor-firmware#3418]
In [docs](https://docs.trezor.io/trezor-firmware/common/reproducible-build.html) you can find instructions  how to verify self-build firmware for model T and model One.

How can this be done with the new Safe 3?

**Comment by matejcik** [comment]
the Safe 3 firmware is the same type and format as the TT so the exact same instructions apply.

the only change (which we do need to document) is that the path to the TS3 binary is `build/core-r/fimware/firmware.bin`, and similarly for the model T the path changes to `core-t`

**Comment by Giszmo** [comment]
It's `core-R` and `core-T` respectively.

**Comment by bosomt** [comment]
baybe we can consider adding instructions for macOS ?
Maybe command are need to be started in nix-shell ?
Results from my `macARM 15.0.1 (24A348)`

```
❯ bash build-docker.sh core/v2.8.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2563k  100 2563k    0     0  7760k      0 --:--:-- --:--:-- --:--:-- 7768k
usage: sha256sum [-bctwz] [files ...]
❯ cd build/core
cd: no such file or directory: build/core
❯ cd build
cd: no such file or directory: build
```

**Comment by Hannsek** [comment]
@bosomt feel free to go ahead 😄
