### ISSUE TITLE
Shamir : device tests

### ISSUE THREAD

**Issue by ciny** [trezor/trezor-firmware#342]
Child of #269 
Add/modify device tests for shamir workflows
- [x] reset happy path
- [x] recovery happy path
- [x] dry run happy path
- [x] exception paths
- [x] warnings (identifier mismatch, share already added, invalid share)
- [x] verify that bip39 tests still work as expected
- [ ] persistence (have you tried turning it off and on again?)
- [x] refactor to use inputflow in the tests (maybe a separate issue for this?)

**Comment by tsusanka** [comment]
I have moved the persistance tests to separe issue #370.
