### ISSUE TITLE
Add V Systems (VSYS) Support

### ISSUE THREAD

**Issue by SheldonYS** [trezor/trezor-firmware#344]
Hello! We are from V Systems (also known as VSYS) team. V SYSTEMS is a blockchain database cloud project that aims to create a brand new digital economy era. The project will deliver the world's first object-oriented general purpose distributed database, which is empowered to carry complex decentralized applications. We are now in the Top 30 of Coin Market Cap and currently looking forward for that trezor-firmware could support VSYS.

Web Page: https://www.v.systems/

For cryptographic, we used `Curve25519`, which developed by whispersystems, to generate key pairs. And also used `BLAKE2B256`, `KECCAK256` and `SHA256` hash function to convert public key to address. And using `Ed25519` to do signature. The approximate scale approaches to Cardano(ADA), but generation way is different. We have [Python SDK](https://github.com/virtualeconomy/pyvsystems) to boost up integration development. All the generation procedure can be found in [account.py](https://github.com/virtualeconomy/pyvsystems/blob/master/account.py). We will pick the code snippet from SDK and then integrate into trezor-firmware.

Frontend wallet: https://wallet.v.systems/ (will support Trezor)

Block Explorer: https://explorer.v.systems/

Documents: https://github.com/virtualeconomy/v-systems/wiki

**Comment by prusnak** [comment]
Seems OK. You can start working on code and provide a pull request.
