### ISSUE TITLE
Trezor One - QR code for BCH on Trezor device contains address in capitals

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-firmware#345]
fw version 1.8.1

similar to https://github.com/trezor/trezor-firmware/issues/191

![2019-07-18 10 23 28](https://user-images.githubusercontent.com/31442634/61441552-28deb680-a946-11e9-8046-a5f6d31ed979.jpg)
![2019-07-18 10 23 38](https://user-images.githubusercontent.com/31442634/61441553-28deb680-a946-11e9-8b14-68fcb8866e54.jpg)
![2019-07-18 10 23 44](https://user-images.githubusercontent.com/31442634/61441555-28deb680-a946-11e9-8459-e46aed2b737d.jpg)

**Comment by prusnak** [comment]
According to https://www.bitcoincash.org/spec/cashaddr.html

> Lower case is preferred for cashaddr, but uppercase is accepted. A mixture of lower case and uppercase must be rejected.
> Allowing for uppercase ensures that the address can be encoded efficiently in QR codes using the alphanumeric mode.

The uppercase here is by design to encode efficiently in QR code.

I changed the code of the new firmware to be consistent with this behaviour: 007f3aa6dea61ec9e8105fac2ed875f94e118050
