### ISSUE TITLE
Update Bootloader changelog for Trezor T on trezor.io/learn

### ISSUE THREAD

**Issue by CodeShakingSheep** [trezor/trezor-firmware#3473]
Released bootloader versions

- 2.1.1 - June 2023
- 2.1.2 - August 2023
- 2.1.3 - September 2023
- 2.1.4 - November 2023

for Trezor T are not mentioned on https://trezor.io/learn/a/bootloader-changelog in the version overview. Would love to see them added there.

**Comment by matejcik** [comment]
I have passed the report to the right people. Closing the issue here, as the firmware repo can't do anything about it, the `CHANGELOG.md` file in the repo is in order.

**Comment by CodeShakingSheep** [comment]
Thanks for your reply @matejcik. Where would have been the right place to address this? I couldn't find a repository for the website.

**Comment by Hannsek** [comment]
The best way is to use Trezor support.
