### ISSUE TITLE
[Model T] "Definition is outdated" error on one particular ETH contract address

### ISSUE THREAD

**Issue by the-emerald** [trezor/trezor-firmware#3499]
**Describe the bug**
Device returns "Definition is outdated" when attempting to call the contract `0x7b35Ce522CB72e4077BaeB96Cb923A5529764a00` on Ethereum Mainnet. This happened across two different Model Ts with two different devices running different OSes.

**Firmware version and revision**
2.6.4 Universal

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: MetaMask and Frame
 - OS: Windows, Mac and Linux
 - Browser Firefox and Chrome

**To Reproduce**
1. Create a transaction that calls `0x7b35Ce522CB72e4077BaeB96Cb923A5529764a00`. Any function will do.
2. Attempt to sign the transaction. Trezor will return "Definition is outdated".

**Expected behavior**
The transaction to go through.

**Screenshots**
N/A

**Additional context**
Here is sample calldata:
```
0x095ea7b3000000000000000000000000a3a7b6f88361f48403514059f1f16c8e78d60eec0000000000000000000000000000000000000000000000000000000000000000
```

**Comment by matejcik** [comment]
Per the definition data, the contract is "Impermax OLD", neither ethereum-lists/tokens nor coingecko knows about it, so the "definition is outdated" message is _technically correct_ (the best kind of correct).

Where do you people keep coming up with all this old junk??

**Comment by matejcik** [comment]
nevertheless.
we deleted the definition file, so next time you try this, you should get the correct thing (contract address confirmation screen and UNKN ticker symbol)
