### ISSUE TITLE
rename device self-test

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#3504]
please rename this test thats not confusing trezorctl users

```
❯ trezorctl device self-test
Error: UnexpectedMessage: Unexpected message
```

**Comment by Hannsek** [comment]
@matejcik @bosomt can you tell more about this issue? 🙏🏻

**Comment by bosomt** [comment]
https://satoshilabs.slack.com/archives/CKZHV2G13/p1706518434267169 :)

**Comment by obrusvit** [comment]
Suggested name of command: `prodtest-t1`. Potentially improve the help message.

Thanks @bosomt, feel free to post the context right away for next issue.
