### ISSUE TITLE
Trezor Ethereum staking pool

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#3517]
Dedicated screens for staking, unstaking and claiming on Ethereum.

Bake these contracts+methods into the firmware.

### ABI + Methods
[Pool.json](https://github.com/trezor/trezor-firmware/files/14167831/Pool.json). Methods: stake, unstake
[Accounting.json](https://github.com/trezor/trezor-firmware/files/14171148/Accounting.json). Method: claimWithdrawRequest

### Contracts
```
        case 'mainnet':
            ADDRESS_CONTRACT_ACCOUNTING = '0x7a7f0b3c23C23a31cFcb0c44709be70d4D545c6e';
            ADDRESS_CONTRACT_POOL = '0xD523794C879D9eC028960a231F866758e405bE34';
            break;
        case 'holesky':
            ADDRESS_CONTRACT_ACCOUNTING = '0x624087DD1904ab122A32878Ce9e933C7071F53B9';
            ADDRESS_CONTRACT_POOL = '0xAFA848357154a6a624686b348303EF9a13F63264';
            break;
```

### Source property
The source attribute identifies where the staking is coming from. `1` identifies Trezor users. The dedicated screens should check the contract address and the source attribute for stake and unstake methods.

### Designs
* [Staking](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6417-25787&mode=design&t=kCOc6dRJu9b5xOmA-4)
* [Unstaking](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=8237-25857&mode=design&t=kCOc6dRJu9b5xOmA-4)
* [Claiming](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=8237-26033&mode=design&t=kCOc6dRJu9b5xOmA-4)

**Comment by Hannsek** [comment]
Final designs ![image](https://github.com/trezor/trezor-firmware/assets/57008159/2b1d1f8f-4050-4f32-a82e-2bed98711f3e). @obrusvit
