### ISSUE TITLE
Unify text during the onboarding on TT with TS3

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3519]
Instead _Select word 3 of 12_
![image](https://github.com/trezor/trezor-firmware/assets/57008159/38704ce3-eff0-4211-8e5c-a5d24e2b25ae)

use _Select 3rd word_

![image](https://github.com/trezor/trezor-firmware/assets/57008159/43f921c3-eeb7-4883-a870-4c8cc7fcbed0)

**Comment by grdddj** [comment]
Not completely sure we want to unify on the second form - using `st`, `nd` etc. --- the issue I see is in translations, where it is much easier to just say `word 3 of 12`, `slovo 3 z 12` etc.
