### ISSUE TITLE
Improve handling of default values in Protobuf

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#352]
1. We should enforce enum is in allowed range.
1. We should support explicit default values. Currently [this](https://github.com/trezor/trezor-firmware/blob/master/common/protob/messages-bitcoin.proto#L74) serves only for documenting, which is confusing.

Connected to https://github.com/trezor/trezor-firmware/issues/16 and https://github.com/trezor/trezor-firmware/issues/14.

**Comment by matejcik** [comment]
(1) is solved in #363 

(2) can be done and seems to work fine, but would break if we wanted to move to proto3

**Comment by ZdenekSL** [comment]
closed in favor of #379
