### ISSUE TITLE
Release Rust `trezor-client` on crates.io

### ISSUE THREAD

**Issue by DaniPopes** [trezor/trezor-firmware#3528]
Would it be possible for a new release of `trezor-client` to be made on crates.io? The last release (0.1.2) was made on 2023-09-10 ([crates.io](https://crates.io/crates/trezor-client)), and numerous changes have been made to the crate since then.

One of these changes is the fix for #3153: we are currently [patching both `trezor-client` and `protobuf` in Alloy](https://github.com/alloy-rs/alloy/blob/098ad5657d55bbc5fe9469ede2a9ca79def738f2/crates/signer-trezor/Cargo.toml#L20-L22) to avoid a compile-time dependency on `protoc` and to reduce build times, and we would appreciate a new release.

cc @prusnak

**Comment by prusnak** [comment]
tagged b5c86a45ed07e347fe636e00c113f4bcb32c7652 as `rust/trezor-client/v0.1.3` and published to crates https://crates.io/crates/trezor-client

**Comment by DaniPopes** [comment]
Thanks!
