### ISSUE TITLE
Implement UI for T3T1

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#3562]
**Design:** [Figma](https://www.figma.com/file/SGZ3zruKm95u4ZkfICHJmd/%E3%80%94-StyleKIT-%E3%80%95Safe-5?type=design&node-id=1-2&mode=design&t=WgpBS9nzwMZyaN7y-0)

we can start by implementing individual stylekit elements:
* header
* options bar
* frame that leaves space for main content

then see what is broken

The implementation should most likely start out as a copy of `model_tt`
(do we want to be cute and introduce codenames? "ford" for model T, "buick" for TS3, "mercury" for TS5)
...more practically, the new model should be `TREZOR_MODEL=T3T1` in preparation of renaming the `T` and `R` symbols to internal names

**Comment by Hannsek** [comment]
This part is done? Other tasks are in Milestone T3T1.
