### ISSUE TITLE
Add production keys for translation blobs to firmware

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#3564]
right now production firmware will only accept translation blobs signed by public key "123456789...", to which presumably we don't have private keys

https://github.com/trezor/trezor-firmware/blob/ae1f4cf5c96be8a2273b76c089607073548b6346/core/embed/rust/src/translations/public_keys.rs#L11

this must be fixed before release

**Comment by mmilata** [comment]
Fixed in #3577.
