### ISSUE TITLE
Bootloader mode - text overflow on vendor change screen

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-firmware#36]
Trezor T

Starting the T2 device in bootloader mode and installing new firmware displays a Vendor change screen where the text overflows to the right.
![bootloadermodeoverflow](https://user-images.githubusercontent.com/10185314/52964429-8f18da80-33a2-11e9-9242-05e25705d849.jpg)

**Comment by tsusanka** [comment]
We will solve this by https://github.com/trezor/trezor-firmware/issues/659

**Comment by ondracja** [comment]
I'm reopenning the issue, it seems that it have slipped back as an regression.

**Comment by prusnak** [comment]
> I'm reopenning the issue, it seems that it have slipped back as an regression.

No, it hasn't. The bootloader with the fix has not been released yet.

**Comment by hynek-jina** [comment]
Bootloader will be redesigned
