### ISSUE TITLE
Unicode font uppercasing issues

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#3600]
turns out our MicroPython can't correctly uppercase unicode characters.
(no surprise really)
so essentially all calls to something.upper() in layouts are now useless and we need to make the uppercase part of the translations data

**Comment by prusnak** [comment]
Aren't we just missing some compile time option that solves the issue?

**Comment by obrusvit** [comment]
Related: https://github.com/trezor/trezor-firmware/issues/3224
