### ISSUE TITLE
Account under "i" in receive flow is always 'ETH #1', regardless of derivation path

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3627]
**Describe the bug**
Account is always 'ETH #1', regardless of derivation path

**Firmware version and revision**
`2.7.0`

<img width="268" alt="image" src="https://github.com/trezor/trezor-firmware/assets/57008159/b9c10ff1-149c-4e59-b20f-ac3ac30c4e7e">
<img width="185" alt="image" src="https://github.com/trezor/trezor-firmware/assets/57008159/9341de64-facb-4543-b374-b23bb19ddb2e">

**Comment by ibz** [comment]
The address format is `m/44'/coin_type'/account'/change/address_index`, so in both screenshots above the account is `/0` which is `#1`.

If I replace the `\0` with `\2`, I get `ETH #3`, for example...

![image](https://github.com/user-attachments/assets/8e2fc116-2eb4-4604-91c9-c1f037dcc0a8)

**Comment by prusnak** [comment]
> The address format is `m/44'/coin_type'/account'/change/address_index`, so in both screenshots above the account is `/0` which is `#1`.

Please sync with Suite on this. I think they use address index as accounts (like other ETH wallets do).

**Comment by Hannsek** [comment]
In Trezor Suite, we use this derivation path for Ethereum when creating new accounts (addresses):`m/44'/60'/0'/0/{account_index}`

So it is like @prusnak says.

We also support discovering Ledger paths:
Ledger (live): m/44'/60'/{account_index}'/0/0 
Ledger (legacy): m/44'/60'/0'/{account_index}

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (65a8499db01e2226de44c748e725e0bf976b3ee5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Device: Trezor T2T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: WebUsbTransport
