### ISSUE TITLE
Missing 2.7.0 firmware changelog for Trezor Safe 3 in github cumulative changelog

### ISSUE THREAD

**Issue by rshxyz** [trezor/trezor-firmware#3642]
When following "Trezor Safe 3 firmware cumulative changelog" there is no mention of 2.7.0 firmware changes.
https://trezor.io/learn/a/firmware-changelog
https://github.com/trezor/trezor-firmware/blob/42e9ed0e09033d474dee1a560fe5870646fa440e/core/CHANGELOG.T2B1.md

**Comment by prusnak** [comment]
The changelog is both in the release branch and in the main branch:

https://github.com/trezor/trezor-firmware/blob/release/24.03/core/CHANGELOG.T2B1.md

Where did you get the commit you are referring to from?

**Comment by Hannsek** [comment]
Thanks for the issue. It will be fixed. 

Closing this issue as it will be fixed on trezor.io side.
