### ISSUE TITLE
Add print screen job to CI

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#366]
Let's add a manual job to CI, which will run emulator with `TREZOR_SAVE_SCREEN=1` and save all the images to artifacts for manual download.

Consider doing after #365

**Comment by tsusanka** [comment]
Also worth mentioning: it'd be cool to prefix the images with the name of the currently runned test are divide the images into folders. However, that's a bit more significant change.

**Comment by matejcik** [comment]
this is actually fixed through the UI testing system
