### ISSUE TITLE
Add device tests for Cardano with SLIP-0039

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#367]
Add the following device tests for Cardano on a device with a SLIP-0039 seed:
- [x] get_address
- [x] get_public_key
- [x] sign_transaction

See existing test vectors in:
trezor-firmware/core/tests/test_apps.cardano.address.py
https://github.com/satoshilabs/slips/blob/andrewkozlik/slip-0023/slip-0023.md

**Comment by ciny** [comment]
implemented via #376
