### ISSUE TITLE
Czech translation bugs

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#3697]
**Describe the bug**
Noticed Czech translation bugs as it was included in TS app yesterday.
- unlock attempts text is overlapping count of remaining count
- verifying pin text  is not translated

**Info:**
 - Suite version: desktop 24.4.1 (979558244707a3d9d577cf9afff6a860c48b137d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**To Reproduce**

**Screenshots**
![telegram-cloud-photo-size-4-5814275916870827983-y](https://github.com/trezor/trezor-firmware/assets/31506317/351bea9a-a95b-4bda-9019-750618c1fbd7)

<img width="360" alt="image" src="https://github.com/trezor/trezor-firmware/assets/31506317/5df8a1f9-531d-4469-8aee-86d5a70da0af">

**Comment by bosomt** [comment]
one more translation missing 
![telegram-cloud-photo-size-4-5814275916870828008-y](https://github.com/trezor/trezor-firmware/assets/31506317/aade1143-82dc-47d3-91f2-cc5c5b521511)

**Comment by STew790** [comment]
There is also "Processing" when setting up a wipe code for example.

**Comment by matejcik** [comment]
> There is also "Processing" when setting up a wipe code for example.

#3610
