### ISSUE TITLE
Change reserved trust flags in vendor header to 0

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#3704]
In the `VendorTrust` word, a `1` byte means "high trust" and `0` means "low trust"
But when generating VendorTrust, we set the reserved unused fields to all-ones. This is a problem, because already signed vendor headers automatically get high-trust values for any new capability added later.

(for this reason, we already had to flip the value of `allow_run_with_secret` flag to consider 0 high-trust and 1 low-trust)

going forward, we'll want to set the unused fields to all-zero.
in order to reproducibly regenerate existing vendor headers, the `build_vendorheader` command must allow the config json to specify the value for the reserved bits (and we'll fill all-ones for the existing VHs)

**Comment by TychoVrahe** [comment]
closed by https://github.com/trezor/trezor-firmware/pull/3683 . 

(build vendorheader is not changed, rather the reserved value is filled in existing json files where needed)
