### ISSUE TITLE
Support info for TS5

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#3781]
We need to add support info for `T3T1` to the relevant files.

This support info should be a copy of `T2B1`.

prerequisite for https://github.com/trezor/definitions/issues/30

**Comment by Hannsek** [comment]
Wondering if we can also prepare the info for T3B1. @matejcik

**Comment by matejcik** [comment]
that's a good question because T2B1 and T3B1 should always be identical, no? which kinda means that we maybe should do the support info by not duplicating it?

**Comment by VojtaStr** [comment]
@matejcik hey guys how does this looks? @matejcik

**Comment by Hannsek** [comment]
As discussed, it will be done this week. :)

**Comment by ibz** [comment]
Closing manually. This has been merged.
