### ISSUE TITLE
Delete (Shamir) from Create wallet (shamir) screen on both T2B1 and T2T1

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3792]
![image](https://github.com/trezor/trezor-firmware/assets/57008159/05c9d270-c789-4c14-86e7-95328f926078)
![image](https://github.com/trezor/trezor-firmware/assets/57008159/9485b31a-3a62-43b1-85df-0dd20a4cb9b8)

**Comment by ibz** [comment]
Closing manually. This was already fixed.
