### ISSUE TITLE
FIDO flow

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3797]
**Design:** [Figma](https://www.figma.com/file/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?type=design&node-id=26%3A4169&mode=design&t=34dvYM1npBbXmJn4-1)

**Comment by mmilata** [comment]
Figma seems to be missing the case where there's only one credential available, and for registering a new credential. Also there's no service icon (which we have in 128x128 and downscale to 64x64 for T2T1) used anywhere.

![emu00000000](https://github.com/user-attachments/assets/f0908118-d245-448f-8979-79c26d80c4b4)

**Comment by Hannsek** [comment]
Isn't it the "Import credentials" section?

**Comment by Hannsek** [comment]
About the icon. Good point. Will talk to Luke.

**Comment by mmilata** [comment]
> Isn't it the "Import credentials" section?

Right, correct, never mind.

**Comment by Hannsek** [comment]
Updated flows [here](https://www.figma.com/design/uIdQ3oz7UJrfurU3ADXVeO/FIDO-%E2%80%93-adding-service-logo-%2F-icon?node-id=3075-3963&t=OMQL7zSsAjiaQFfo-4).
