### ISSUE TITLE
Entropy flow

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3798]
**Design:** [Figma](https://www.figma.com/file/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?type=design&node-id=26%3A4167&mode=design&t=34dvYM1npBbXmJn4-1)

**Comment by mmilata** [comment]
UI exists but has same cosmetic issues as some similar screens, tracked under #3748.
