### ISSUE TITLE
Recovery shamir flow

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3800]
**Design:** [Figma](https://www.figma.com/file/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?type=design&node-id=26%3A4178&mode=design&t=34dvYM1npBbXmJn4-1)

**Comment by obrusvit** [comment]
Known limitation: Success screen between shares is not according to Figma. Tracked in a subtask here: https://github.com/trezor/trezor-firmware/issues/3748
