### ISSUE TITLE
Drop obsolete Trezor boards

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#3816]
We have multiple old boards lying around the source code, and they impose some maintenance burden of keeping the builds up-to-date. The definitions should be dropped -- anyone who wants to run the old board will need to retrieve it from git history.

**Comment by TychoVrahe** [comment]
Does T1B1/Model One qualify as obsolete too and thus should be also dropped from Core at this point? Its not working anyway, yet requires several exceptions in code making things a bit uglier and chances of reviving it are essentially zero.

**Comment by prusnak** [comment]
> Does T1B1/Model One qualify as obsolete too

It never really worked so +1 for dropping T1B1 from Core
