### ISSUE TITLE
Bug in persistence during recovery

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#382]
Start recovery.
Disconnect device.
Reconnect device.
Cancel recovery.

Wallet is loaded but without accounts.
See video. https://photos.app.goo.gl/tLQuXWs3neXxmrDc8

EDIT: Chrome, 2.1.3 FW, MInt Linux, stage wallet 

![image](https://user-images.githubusercontent.com/31506317/62421231-c94f0d80-b69e-11e9-80b6-4bbd649943e4.png)

**Comment by tsusanka** [comment]
@TomasZorvan you probably should also check the `initialized` bool flag during the polling and return to the New/Backup homepage. I believe that could cause this, what do you think?

**Comment by bosomt** [comment]
@TomasZorvan I consider it fixed !
