### ISSUE TITLE
PIN code change dialogue not properly refreshed

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#384]
Firmware 2.1.3
Minut Linux, Chrome, Stage wallet.

During change of pin try some swiping and touching.
Then press back or confirm and new dialogue is not properly displayed.

I was not able to reproduce it in 2.1.1 but i will try few more times. /it's hard to reproduce it even in 2.1.3
 /  
![IMG_20190804_134541](https://user-images.githubusercontent.com/31506317/62423836-78eba600-b6c6-11e9-8bc8-21b8ca6a4934.jpg)
![IMG_20190804_144303](https://user-images.githubusercontent.com/31506317/62423837-79843c80-b6c6-11e9-818b-735fe068ce66.jpg)

**Comment by tsusanka** [comment]
No success in 2.1.1?

**Comment by sorooris** [comment]
Same thing occurred while creating a new wallet/backup, while swiping the screen right after confirming the threshold number.

![image](https://user-images.githubusercontent.com/10185314/62465846-30002400-b790-11e9-932a-3a3f84a5fb1c.png)

**Comment by tsusanka** [comment]
I've reproduced this in debug mode on device and got this in the console.

```
389526000 trezor.loop ERROR exception:
Traceback (most recent call last):
  File "trezor/loop.py", line 145, in _step
  File "trezor/ui/__init__.py", line 227, in handle_input
  File "trezor/ui/pin.py", line 117, in dispatch
  File "trezor/ui/__init__.py", line 165, in dispatch
  File "trezor/ui/button.py", line 232, in on_touch_end
  File "trezor/ui/pin.py", line 148, in on_confirm
Result: 336050995
389577000 trezor.loop DEBUG finish: <generator object '__iter__' at 200201a0>
389589000 trezor.loop DEBUG finish: <generator object 'request_pin' at 2001f180>
392929000 trezor.loop ERROR exception:
Traceback (most recent call last):
  File "trezor/loop.py", line 145, in _step
  File "trezor/ui/popup.py", line 20, in handle_timeout
Result: None
392947000 trezor.wire DEBUG 0:0 write: <ButtonRequest>
392971000 trezor.wire DEBUG 0:0 read: <class 'ButtonAck'>
392994000 trezor.wire DEBUG 0:0 read: None
```

**Comment by prusnak** [comment]
Should be fixed in https://github.com/trezor/trezor-firmware/commit/c9096d9a0a6c1ca7cb34c1c8c205fe5a77d3ea3e

**Comment by tsusanka** [comment]
@bosomt @sorooris so we can close this one?

**Comment by sorooris** [comment]
@tsusanka couldn't reproduce so i think we can.

**Comment by bosomt** [comment]
i was not able to reproduce it anymore after latest fix.
I will close it and if it appers again i will reopen or create new one
