### ISSUE TITLE
Add BOOTLOADER VERSION and BOARDLOADER VERSION to prodtest

### ISSUE THREAD

**Issue by Micka1792** [trezor/trezor-firmware#3842]
To verify the correctness of the TS5 binary version in production, it is useful to read the version of the prodtest, bootloader and boardloader at the end of the production process and compare it with the reference. Now we are only able to enumerate prodtest, if there is a value that always changes with the build of a new binary (bootloader?) we would only need to enumerate that one, but that is probably not likely. It would also be easier for the production process to have all 3 versions implemented together in the new cmd. That is, after sending a cmd for example "VERSIONS READ" the return value should be for example "OK 212 216 026" , if that is not possible anymore, let's create a "BOOTLOADER VERSION" and a "BOARDLOADER VERSION" in addition to the "FIRMWARE VERSION".

**Comment by TychoVrahe** [comment]
duplicate https://github.com/trezor/trezor-firmware/issues/3752
