### ISSUE TITLE
Add Iroha support

### ISSUE THREAD

**Issue by baydarich** [trezor/trezor-firmware#385]
Hello! 

As its maintainers, we would like to present you Hyperledger Iroha and ask you to provide support for a private blockchain in Trezor for the very first time. 
Unlike other projects, Iroha is not a coin but a private blockchain platform hosted by Hyperledger. Hyperledger itself is a project by Linux Foundation -- a global open-source collaboration aiming to advance cross-industry blockchain technologies. 

Hyperledger Iroha is written in C++ incorporating unique chain-based linearly scalable Crash Fault Tolerant consensus algorithm called Yet Another Consensus and CFT ordering service.
It is an efficient and easy-to-use DLT framework with a set of safe predefined commands. Multi-signature transactions, model of roles, permissions and groups as well as ready-to-use SDKs - all are ready to help anyone create their first Hyperledger Iroha network right away.

Iroha on Hyperledger website: https://www.hyperledger.org/projects/iroha
General info with application examples, resources and projects can be found here: https://soramitsu.co.jp/iroha
Documentation: https://iroha.readthedocs.io/en/latest/
GitHub: https://github.com/hyperledger/iroha

* What is the approximate scale?

Iroha is one of the Hyperledger projects, which are considered to be private blockchain frameworks, so scale might be counted differently -- by the projects using Iroha as a base for their decentrilised applications. Iroha is used in a multitude of organisations worldwide including projects for considerable number of clients (hundreds of thousands people making millions transactions per day). By creating this issue/request, we would like to make a first step towards widely known private blockchains being supported by Trezor.

* Do we need any new cryptographic primitives to support this coin?

No, `ed25519-sha3-512` is used for cryptographic operations. It seems Trezor already supports this modification.

* Is there (or will you develop) a frontend wallet that will support Trezor with this coin?

We will develop frontend after your approval. We already have experience in creating such applications so we see no apparent difficultiy with this.
If needed, we are ready to show you our latest mobile app with a wallet feature called Sora as a reference.

* Provide a link to a transaction explorer

There is no link to an explorer since the blockchain is private.

Looking forward to your comments and any questions.
We believe that cooperation between Trezor and our private blockchain might be beneficial and interesting for both parties. 
Thanks in advance.

**Comment by prusnak** [comment]
Yes, feel free to work on a pull request and we'll review it once it is sent to our repo.
