### ISSUE TITLE
Swipe up animation between receive address and tap to confirm screen after tap to confirm animation

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3856]
https://github.com/trezor/trezor-firmware/assets/57008159/ac1b2245-ec66-454f-8bab-d2d1557921a0

**Comment by Hannsek** [comment]
@TychoVrahe this should be fixed, right?

**Comment by obrusvit** [comment]
@Hannsek this task seems obsolete. Just checked and the animations in receive flow seems fine. Reopen if you think, it's not the case.
