### ISSUE TITLE
walletCreation/Backup flow changes

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3880]
- [x] [add copy to the third screen ](https://www.figma.com/design/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?node-id=5706-7185&t=v4bQpNUZWu6zEBYO-4)
![image](https://github.com/trezor/trezor-firmware/assets/57008159/4ef9f418-dbf0-40aa-9d86-4aac1f1c3ad1)

- [x] [add text to the header of the word that is the same as previous one](https://www.figma.com/design/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?node-id=5706-6990&t=v4bQpNUZWu6zEBYO-4). For example, 3rd and 4th words are the same (`academic`), display this header on the 4th word screen. (Don't mind the menu in the top right corner.)
![image](https://github.com/trezor/trezor-firmware/assets/57008159/8c8e34cc-4c08-457c-9133-70755b4ab4c7)

**Comment by obrusvit** [comment]
1st point added in 5d68cc588e9ca4d4c3b8a8ec5a10d74d4ade21a6

**Comment by obrusvit** [comment]
2nd point part of #3954
