### ISSUE TITLE
trezorctl drastically decrease quality of uploaded homescreen

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3893]
Quality of jpgs uploaded through trezorctl is way worse then quality of jpgs uploaded to device through suite.

**Comment by matejcik** [comment]
would be interesting to see Suite-produced jpeg alongside trezorctl's.
can Suite dump the jpeg that it is sending to device?

**Comment by Hannsek** [comment]
Let's wait for [this discussion](https://satoshilabs.slack.com/archives/CKZHV2G13/p1717508192600779).
