### ISSUE TITLE
Homescreen settings

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3907]
**Design:** [Figma](https://www.figma.com/design/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?node-id=6007-1839&t=CZ95t24bIx3Q37Uz-4)

[Change to default homescreen](https://www.figma.com/design/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?node-id=5985-7336&t=CZ95t24bIx3Q37Uz-4)

**Comment by obrusvit** [comment]
Homescreen settings is done according to Figma including the correct flow for setting default homescreen.

The only thing missing is the Success screen with "Wallpaper changed". However, the Success screens are missing for all settings (wallpaper, haptic, label, etc..)

**Comment by obrusvit** [comment]
The success screens are tracked there https://github.com/trezor/trezor-firmware/issues/3748 so I'm closing this issue.
