### ISSUE TITLE
Non-breakable spaces

### ISSUE THREAD

**Issue by mmilata** [trezor/trezor-firmware#3909]
Looks like we started receiving translated strings containing non-breakable spaces in the right places, yet can't handle them.

* we could add the char to `core/tools/codegen/foreign_chars.py` but we'd need to introduce similar mechanism for english which probably doesn't make sense, or
* we could add special handling for 0xA0 codepoint in the text renderer.

After it works the commit 1b31b4033069fc0d4d789e5e3a004b5c8cfc9199 needs to be reverted.

**Comment by TychoVrahe** [comment]
see also https://github.com/trezor/trezor-firmware/issues/2755
