### ISSUE TITLE
Font rendering optimization

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#391]
Now the text is being rendered by rendering the individuals characters.

We can update the renderer to compute the bounding box for the whole text, and render the whole box as one.

**Comment by sime** [comment]
@prusnak @matejcik Is this issue still relevant given the recent efforts to introduce Rust at the UI layer?

**Comment by matejcik** [comment]
Tagging @jpochyla in case he has something to say, but I don't think we can gain anything more here.
