### ISSUE TITLE
Device tests don't work against T3T1 hardware

### ISSUE THREAD

**Issue by mmilata** [trezor/trezor-firmware#3915]
Get stuck on the first tap-to-confirm screen. Reproducible on emulator by leaving animations enabled.

**Comment by TychoVrahe** [comment]
the issue (or at least one of the issues) is that the layout does not change when swipe occurs, but later after some animation frames.

Thus, the notify_layout_change function is called too early and the test does not see the new layout.

Proper solution is probably introduce some notify layout change to EventCtx, call it whenever the layout really changes in rust and handle this flag from python by calling that notify_layout_change function

**Comment by matejcik** [comment]
i'll see if GFL #3110 can help here too -- at least the framework is solid enough for it, but the fact that the flows now happen in Rust brings some challenges
