### ISSUE TITLE
Missing end of sentence after dry run

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#3918]
**Describe the bug**
Missing end of sentence after dry run.

**Steps to reproduce:**
1. Run dry run 
2. Enter loaded seed
3. Success text is shortened by ...

**Info:**
 - Suite version: desktop 24.6.1 (ee1bf19e747daba31bec272b64d09bfa8c6a807e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.1 regular (revision 83d1ce2b8e6e4eefe09539f06b28709c8a7a89dc)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

**Comment by bosomt** [comment]
Guess its only valid for 20w backups

`    backup_type: Slip39_Single_Extendable (3),`

![telegram-cloud-photo-size-4-5836807929485967878-y](https://github.com/user-attachments/assets/512a8407-c79a-4f66-9359-6908adffbe1d)

**Comment by Hannsek** [comment]
The success screen was redesigned. It will be fixed in the upcoming release.
