### ISSUE TITLE
Authentication flow

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3929]
**Design:** [Figma](https://www.figma.com/design/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?node-id=6080-7830&t=byhTNvKkTUaLapxL-4)

**Comment by obrusvit** [comment]
The flow is done according to Figma with the exception of the Success screen - [discussed on Slack](https://satoshilabs.slack.com/archives/C054XGU77QV/p1721828746706339?thread_ts=1721729014.913199&cid=C054XGU77QV) and decided ditching that screen.
