### ISSUE TITLE
Swipes behave as presses of buttons

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#3931]
**Describe the bug**
See video and discussion.
Swipes behave as presses of buttons.
https://satoshilabs.slack.com/archives/CL1D61PQF/p1717911950868149

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 24.6.1 (ee1bf19e747daba31bec272b64d09bfa8c6a807e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision e90cf366243f5686c1452c926dceb8ebfc2279fc)
 - Transport: BridgeTransport 2.0.33

**Comment by TychoVrahe** [comment]
fixed as part of https://github.com/trezor/trezor-firmware/pull/3965
