### ISSUE TITLE
CI: finish migration to GitHub Actions

### ISSUE THREAD

**Issue by mmilata** [trezor/trezor-firmware#3940]
Still missing:

- [x] trezor-user-env tasks
- [x] ARM builds
- [ ] @grdddj 's UI webapp

**Comment by Hannsek** [comment]
Jirka's tool.

**Comment by Hannsek** [comment]
@mmilata isn't this done already?

**Comment by mmilata** [comment]
Right, everything for trezor-user-env should be built in GitHub CI now. Not sure about the status of Jirka's tool?

There are scheduled pipelines that we may want to disable (aren't they currently eating company money? cc @vdovhanych): https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/pipeline_schedules

Can't log in to the private GitLab repo anymore, there may be some also.

**Comment by vdovhanych** [comment]
I disabled the scheduled pipelines in GitLab, I don't think it was running though we disabled the billing account there some time ago. 

I belive that this is done basically.

**Comment by Hannsek** [comment]
Jirka's tool is not done. But it is not that important now. 
So I am closing this issue. Thanks.
