### ISSUE TITLE
Weird UX for Shamir 256-bit shares

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#395]
Firmware 2.1.3

Steps to reproduce:

```
$ trezorctl reset-device -e -t 256 -b shamir
```

![s1](https://user-images.githubusercontent.com/42201/62780205-723da400-bab5-11e9-97bc-4e34df35f3fe.jpg)

![s2](https://user-images.githubusercontent.com/42201/62780206-736ed100-bab5-11e9-9266-7dd3f466431f.jpg)

I would expect that words 31+32+33 will be shown on the same page.

**Comment by tsusanka** [comment]
Option 1:
![xemu00000001](https://user-images.githubusercontent.com/1835345/62953620-26a93400-bdee-11e9-9220-cc9e8e71e23c.png) ![xemu00000002](https://user-images.githubusercontent.com/1835345/62953621-26a93400-bdee-11e9-9bda-8fc1b36279a7.png)

Option 2:
![Bemu00000000](https://user-images.githubusercontent.com/1835345/62953710-48a2b680-bdee-11e9-93fd-0e8e0df3830c.png)

Option 3:
![emu00000000](https://user-images.githubusercontent.com/1835345/62953719-4e000100-bdee-11e9-91cb-1f0475895da4.png)

**Comment by prusnak** [comment]
Option 1 seems the best.

**Comment by tsusanka** [comment]
I've chosen the first option then.

**Comment by tsusanka** [comment]
I've also opened https://github.com/trezor/trezor-firmware/issues/409
