### ISSUE TITLE
Detection error after the last update of the Trezor One

### ISSUE THREAD

**Issue by Veranik89** [trezor/trezor-firmware#3957]
**Describe the bug**
After the last update of the Trezor One firmware, the error "detection error" appears when launching the wallet. The wallet balance is not loaded. Please help me solve the problem

**Firmware version and revision**
suiteVersion": "24.6.1",

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor Suite
 - OS: Windows
 - Browser: chrome
 - Version: "122.0.0.0"
 
**To Reproduce**
1. I connect the hardware wallet Trezor One
2. Entering the pin code
3. See error

**Expected behavior**
The wallet balance should appear
![2024-06-18_00-38-40](https://github.com/trezor/trezor-firmware/assets/173072996/9b836227-858b-412a-aff0-b39d976d8a56)
![2024-06-18_00-38-58](https://github.com/trezor/trezor-firmware/assets/173072996/054b2bcc-59e2-42ed-a333-075de8f9ae37)

**Comment by matejcik** [comment]
this is an internet connection problem unrelated to firmware
are you maybe using a VPN? switch it off, or enable Tor.

please use the support contact at https://trezor.io/support for further enquiries
