### ISSUE TITLE
South display orientation doesn't work properly on TS3

### ISSUE THREAD

**Issue by cepetr** [trezor/trezor-firmware#3990]
When TS3 `display-orientation` is set to `south` the display doesn't show the content properly, see images below:

**Firmware version and revision**
TS3 (rev 6),  firmware 2.8.1, 2.7.1, 2.6.4

**To Reproduce**
1. `trezorctl set display-rotation south` 

<img src="https://github.com/trezor/trezor-firmware/assets/60569462/a43737a2-5a95-4bdb-9228-a29e7a8ad748" width="30%"/>

3. confirm the change by pressing the button
4. `trezorctl set display-rotation north`

<img src ="https://github.com/trezor/trezor-firmware/assets/60569462/264100a7-a60a-43dd-9885-c79af31af917" width="30%"/>

**Comment by bosomt** [comment]
**QA OK**


tested via
```
trezorctl set display-rotation south
trezorctl set display-rotation north
```

**Info:**
 - Suite version: desktop 24.7.3 (19fd64f5b2ab1bc265821e34d4c4b9c910864d0e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.1 regular (revision 33f5d4733065ac631d61ff458a5db32c81641124)
 - Transport: BridgeTransport 2.0.33
