### ISSUE TITLE
Display rotation flow

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#4028]
**Design:** [Figma](https://www.figma.com/design/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?node-id=6585-10103&t=1SgsSkJ2tXUUVn4d-4)

**Comment by bieleluk** [comment]
@Hannsek Should the same be implemented for other layouts, or only mercury one?

**Comment by Hannsek** [comment]
This one is for mercury. But if the wording fits other models, let's put it on all models.
