### ISSUE TITLE
Interaction-less fw update UI design

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#4030]
**Design:** [Figma](https://www.figma.com/design/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?node-id=6629-11570&t=G4vs5TosrzlRiet2-4)

**Comment by TychoVrahe** [comment]
The success screen here is in bootloader, where we don't have (and won't have) swipes, so it needs adjustment.

(the loader is in bootloader too)

**Comment by Hannsek** [comment]
Ahh, sure, forgot about it. 

There is the an automatic restarting. I believe it can be like that: 
![image](https://github.com/user-attachments/assets/45e469f6-9001-42dc-a584-57f9cac312fa)

**Comment by Hannsek** [comment]
Updated in Figma.
