### ISSUE TITLE
Update copy in tutorial flow

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#4033]
"Hold to exit tutorial" instead just "Exit tutorial".

![image](https://github.com/user-attachments/assets/3016a32e-13a6-4545-a9b0-81ad8ce5edc4)
![image](https://github.com/user-attachments/assets/2c9d2b38-5bc7-4e2b-9b35-5057f310c048)

**Comment by obrusvit** [comment]
Small copy change needed in other langs:

De
- `Zum Verlassen des Tutorials halten` -> `Zum Verlassen halten`
- `Halte den Bildschirm um wichtige Schritte bestätigen` -> `Halte den Bildschirm um Schritte bestätigen`

FR
- `Appui pour quitter le tutoriel` -> `Appui pour quitter`


There are still titles in `es`, `fr` which do not fit but the text rendered is logical (only e.g. only "importantes" is not visible). Will keep it as is for now until we solve the translations fitting
