### ISSUE TITLE
Create an enum for valid device rotations

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#4041]
https://github.com/trezor/trezor-suite/issues/13360

this can also make our code slightly nicer in places

**Comment by TychoVrahe** [comment]
Some related thoughts:
- for unix, we introduced `ORIENTATION_NSEW` etc macros to tell unix display driver what roations should it allow, i think we should expand this to hw boards too and bind this enum to it somehow (see i.e. https://github.com/trezor/trezor-firmware/blob/main/core/embed/models/T3T1/boards/t3t1-unix.h)
- in apply_settings, we don't actually check whether the orientation passed is valid for the device, we show the dialog even if invalid (i.e. orientation `east` for `T2B1`) and store the setting into storage, the display does nothing but its clearly wrong. this should be fixed too
