### ISSUE TITLE
July 21, 2024 firmware 2.7.2 ver update partially disables hidden wallet account having 1 token with 2 accounts for token

### ISSUE THREAD

**Issue by F101lp** [trezor/trezor-firmware#4048]
July 21, 2024 firmware 2.7.2 ver update partially disables hidden wallet account having 1 token with 2 accounts for token. ( I had 2 separate BTC wallets under the 1 hidden wallet account .. no issues for over 1 year.. now only 1 is accessible.. 

**Firmware version and revision**
firmware 2.7.2 ( was 2.7.0 when all worked fine).

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: [e.g. Trezor Suite, 
 - OS: [e.g. Windows, PC and on laptop
 - Browser [e.g. Chrome,
 - Version [24.1.2 ... and on alternate laptop running 25.5.4 

**To Reproduce**
Steps to reproduce the behavior:  n/a .. updated the firmware from 2.7.0 to 2.7.2 on device was it.. cant go back ?

**Expected behavior**
I expected BOTH my single hidden wallet accounts to be accessible.. rebuilding the wallet does noting .. unless i go back to earlier firmware version..which i may need 

**Screenshots**
5 account s show but more than 8 exists on the hidden wallet
![image](https://github.com/user-attachments/assets/3a71b65d-8117-4633-b21d-c3140f95029e)
 

**Additional context**

**Comment by Hannsek** [comment]
Hi, I am sorry but I didn't understand your issue. Can you please explain more?

**Comment by Hannsek** [comment]
So, are you saying that after the fw update to 2.7.2 you cannot see second accounts for BTC and Matic? Is that right?

**Comment by F101lp** [comment]
issue solved... unclear cause.. but all back no issue.. maybe clowdstrike issue involved not sure.. but TREZOR tokans are safe
