### ISSUE TITLE
Enter passphrase on device flow - small tweaks

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#4054]
**Design:** [Figma](https://www.figma.com/design/7o71DaOwxBxuYwFvtU4Gsz/Empty-passphrase?node-id=5386-7586&t=DiqoXxqGzzpTUv1A-4)

Adding the button and adding reassuring screen when entering empty passphrase.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.9.0 (492ff5f8f3bb0fddae885f29d678e171305623a0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision c8b811bac51c835545c5f52ec4873c3f0e4e3385)
 - Transport: BridgeTransport 2.0.32
