### ISSUE TITLE
Split Dockerfile to build and testing versions

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#406]
Since we are signing firmware built using the ci/Dockerfile it'd be better to seperate test environment and build environment. We can either have multiple Dockerfiles where one extends the other or use variables.

**Comment by tsusanka** [comment]
We want to do this before any release, meaning we need to do this till September 4th.

**Comment by tsusanka** [comment]
@prusnak I have two questions regarding this:

1. If we remove things needed for tests, the tests will obviously fail on this image. That is fine, because we will use that image for building exclusively, correct?
2. I'm thinking about putting back `debian` instead of `python` docker image, because we have number of Python versions anyway. Should we use Debian 10, which is the latest stable or rather 9?

**Comment by prusnak** [comment]
1. correct
2. `debian:10` sounds nice

**Comment by prusnak** [comment]
Fixed in 82fdf7e03d527e6294da4065b31e41257d015c9a
