### ISSUE TITLE
Reduce unrolling in hash functions

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#4079]
blake2 is the biggest offender here:
https://github.com/trezor/trezor-firmware/blob/c3161f8b18193d648ed6a8a3cf6278655114b891/crypto/blake2b.c#L189-L255
I converted the unrolling to function calls, reducing code size by 12 kB (this is also used in bootloader and possibly in boardloader too?)

@onvej-sl I would like to ask for your help evaluating this change in terms of correctness and performance impact
are there other places that you know of where we could also re-roll code, so to speak?

**Comment by onvej-sl** [comment]
Done in https://github.com/trezor/trezor-firmware/pull/4107.
