### ISSUE TITLE
add support for TON coin (Telegram Open Network)

### ISSUE THREAD

**Issue by l9-admin** [trezor/trezor-firmware#4082]
wow, I was shocked when I bought Trezor Safe 5 and found out that it doesn't support TON 
who needs useless slip39 (from the ordinary user perspective) but does not have TON support. Guys, plz set your priorities right.

**Comment by l9-admin** [comment]
ah, forgot, but instead you support that "Ton Community" scam coin, OMG is was sooo confusing. I thought it was TON but no

**Comment by matejcik** [comment]
Dear valued customer, we value your feedback and forwarded your message to our customer feedback department.
