### ISSUE TITLE
Use the same mnemonic dialog for BIP-39 as for SLIP-39

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#409]
The UI when showing mnemonic words is now different for BIP-39 and SLIP-39. Let's merge it into one (the SLIP-39 one).

BIP:
![emu00000000](https://user-images.githubusercontent.com/1835345/63018159-76443a00-be98-11e9-88d1-53dac2a0474c.png) ![emu00000001](https://user-images.githubusercontent.com/1835345/63018158-76443a00-be98-11e9-984a-1dfc463b5f0d.png)

SLIP:
![shamiremu00000000](https://user-images.githubusercontent.com/1835345/63018161-76443a00-be98-11e9-9435-3d7a4c700af3.png) ![shamiremu00000001](https://user-images.githubusercontent.com/1835345/63018160-76443a00-be98-11e9-94f5-2d6c219e62a4.png)

**Comment by ciny** [comment]
While unifying the layouts I found that when confirming the displayed share words bip39 sends ButtonRequest.ResetDevice while slip39 sends ButtonRequest.Other. Unified to ResetDevice since it makes more sense in this context.

**Comment by ciny** [comment]
Fixed, will be part of PR for #456

**Comment by ciny** [comment]
implemented in #484
