### ISSUE TITLE
Problem with signing big messages

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#410]
If you try to sign big message it will get really slow and data overflows.

See screen and video

https://photos.app.goo.gl/zDAA2KNc7Bzs4qEz7

![IMG_20190814_151835](https://user-images.githubusercontent.com/31506317/63025331-43567200-bea9-11e9-9475-b40305ae9f13.jpg)

edit: 
fw 2.1.4, 
chrome and 
1.3.2 wallet

**Comment by sorooris** [comment]
Please take into consideration that there's no option to scroll through the message on the device screen (T1 and/or TT) and therefore the user is not able to compare what is displayed in the wallet interface to what is on the device screen.

**Comment by tsusanka** [comment]
@bosomt when you have a few seconds could you test this out? Not related to the current Freeze, use current master (5ee6e56). It is currently just a hotfix, where we shorten the text. We should introduce pagination later no to allow the user to read the whole message.

**Comment by bosomt** [comment]
@tsusanka working on it

**Comment by bosomt** [comment]
2.1.1 vs 2.3.0
i don't see difference ;)

![IMG_20200228_160525 (1)](https://user-images.githubusercontent.com/31506317/75559777-5810e680-5a44-11ea-8353-c6e83cc1e8c3.jpg)
![IMG_20200228_160503](https://user-images.githubusercontent.com/31506317/75559773-56dfb980-5a44-11ea-9b0f-c2b9c797cf7e.jpg)

**Comment by tsusanka** [comment]
It is different comparing to the first image.

**Comment by bosomt** [comment]
BUT 2.1.4-2.3.0 is broken

so yes it it fixed. and sign speed is same compared to other versions

**Comment by tsusanka** [comment]
Ok fixed then! (for now)

**Comment by bosomt** [comment]
version:	2.3.0 RC1	revision:	6478b270
works fine, 
same speed and behavior with short or long message

**Comment by sorooris** [comment]
2.3.0 8ae0535e
QA OK
