### ISSUE TITLE
Trezorctl downloads firmwares from Beta Wallet

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#411]
If I run `trezorctl firmware-update` it downloads the firmware from ` https://beta-wallet.trezor.io/data/firmware/2/trezor-2.1.0.bin`, which also means that it currently downloads 2.1.4, which is meant for beta testing only.

I don't think this is a good idea. Is there any reason to download from Beta instead of production?

**Comment by prusnak** [comment]
I think the rationale was that trezorctl users are more advanced and they should get the newest stuff first.

We can discuss this whether this is a good idea.

**Comment by prusnak** [comment]
PR in https://github.com/trezor/trezor-firmware/pull/420
