### ISSUE TITLE
Request for Integration of THORChain (RUNE) Support in Trezor Safe 3

### ISSUE THREAD

**Issue by billeteradeabel** [trezor/trezor-firmware#4122]
Dear Trezor Team,

I hope this message finds you well. I am writing to request the consideration of integrating support for THORChain (RUNE) into the Trezor Safe 3 hardware wallet. As THORChain continues to gain significant traction within the decentralized finance (DeFi) ecosystem, I believe that adding support for RUNE would greatly enhance the versatility and appeal of Trezor products.

Benefits of THORChain Integration:Growing Demand: THORChain facilitates cross-chain swaps in a fully decentralized and non-custodial manner, which is increasingly popular among users who value privacy and security. With daily trading volumes reaching between 50 to 100 million USD, there is a clear and growing demand for secure storage solutions for RUNE, THORChain's native token.Competitiveness: Currently, other hardware wallets, such as Ledger, have already implemented support for RUNE. Integrating THORChain into Trezor Safe 3 would not only meet user demand but also ensure that Trezor remains competitive in the hardware wallet market.Enhanced User Experience: By supporting THORChain, Trezor would enable users to interact with a broader range of decentralized applications (dApps) that rely on THORChain’s cross-chain capabilities. This would provide users with more options and flexibility in managing their assets securely.

Technical Considerations:Blockchain Compatibility: THORChain is a Tendermint-based blockchain. Implementing support for THORChain would require integrating Tendermint’s consensus mechanism into Trezor’s firmware. This would also involve supporting the Bech32 address format used by THORChain.Smart Contract Interaction: To enable users to interact with THORChain’s DeFi protocols, it would be essential to ensure that Trezor Safe 3 can sign and authorize transactions on THORChain’s network. This could be achieved by leveraging existing frameworks that support Tendermint-based blockchains.Security Considerations: Given that THORChain is designed to facilitate cross-chain swaps, ensuring that these transactions are secure and verifiable within the Trezor Suite would be critical. This might require additional layers of security auditing and testing during the development phase.

Conclusion:Integrating support for THORChain (RUNE) in Trezor Safe 3 would significantly enhance the product’s value proposition by providing users with secure access to one of the most innovative DeFi platforms available today. I hope you will consider this request as part of your future development roadmap.

Thank you for your attention to this matter. I would be happy to provide any further information or assist in any way possible to help facilitate this integration.

Best regards,
Abel

**Comment by matejcik** [comment]
hello, the github issue tracker is not the right place for this kind of request. we are passing this feedback on to our customer research department, but i am closing the issue.
going forward, please direct such requests to customer support first
