### ISSUE TITLE
Demo flow

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#4131]
**Design:** [Figma](https://www.figma.com/design/6KdLPxVeL7jcOttbMr1kSx/Demo-Flow?node-id=1-75&t=0Tukpfkeq1Qmf6W9-1)

Please discuss with us anything that would ease the integration effort. E.g. if it would be difficult to show just few seed words, we probably won't do that, etc.

**Comment by obrusvit** [comment]
Branch: https://github.com/trezor/trezor-firmware/tree/demo-safe-family

**Comment by obrusvit** [comment]
Description of usage and binaries: https://www.notion.so/satoshilabs/Demo-Firmwares-cac7e6889050498b810f8e62c84c3213
