### ISSUE TITLE
Unknown path

### ISSUE THREAD

**Issue by keip** [trezor/trezor-firmware#414]
Trezor Model T firmware version 2.0.10

Go to next wallet Ethereum or Ethereum classic with passphrase, after click on "Show full address" in recieve tab:

![Image from iOS](https://user-images.githubusercontent.com/1011630/63093449-94c43700-bf65-11e9-8ff1-c5bee8b44d79.jpg)

**Comment by tsusanka** [comment]
Does not happen on master. @sorooris could you try out with 2.1.4 on device just to make sure?

**Comment by sorooris** [comment]
couldn't replicate on 2.14., closing
