### ISSUE TITLE
GitHub issues repository export script

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-firmware#418]
Please edit script below so its will export issues from a repository with these columns

Name of issue, ID of issue, issues status (open/close), issue link, issue projects, issues milestone, issues priority (label starts always with P), issues severity (label starts always with S), issue weight (label starts always with W).

Thanks

**Comment by tsusanka** [comment]
Link to the script we can use: https://gist.github.com/patrickfuller/e2ea8a94badc5b6967ef3ca0a9452a43
Usage: `python github_to_csv.py username/repository`

All we need to do is modify the labels to have Priority, Severity, Weight separatly.
