### ISSUE TITLE
"USB ERROR, Error reading from USB. Try different cable." RSOD message doesn't fit the screen

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#4183]
<img width="701" alt="image" src="https://github.com/user-attachments/assets/c5c4a02c-689b-41d3-a3e5-11601daf6e19">

@TychoVrahe can we have 3 lines of text in RSODs?

**Comment by TychoVrahe** [comment]
what model/version is this? i actually adjusted the error screen as part of https://github.com/trezor/trezor-firmware/commit/d334b920732b7269618e2269df1cf31d15ef22e0 so that should be solved, though only for TS5

**Comment by Hannsek** [comment]
Forgot to mention that. It is T3T1. So it should be in 2.8.3, right?

**Comment by TychoVrahe** [comment]
yes
