### ISSUE TITLE
Wrong Hyperlink to Trezor Safe 5 firmware cumulative changelog

### ISSUE THREAD

**Issue by rshxyz** [trezor/trezor-firmware#4244]
If you go to https://trezor.io/learn/a/firmware-changelog and click on the hyperlink for "Trezor Safe 5 firmware cumulative changelog" it points to an oudated? link

oudated
https://github.com/trezor/trezor-firmware/blob/dd4671a5104952ef505d28d1f9e94d1484b4607a/core/CHANGELOG.T3T1.md

should point to this
https://github.com/trezor/trezor-firmware/blob/main/core/CHANGELOG.T3T1.md

**Comment by matejcik** [comment]
Thanks for the report. This is not a firmware issue so I'm closing it, but I passed the info onto the people responsible for `trezor.io/learn`
