### ISSUE TITLE
Build T3T1 combined binary w/o touch

### ISSUE THREAD

**Issue by Micka1792** [trezor/trezor-firmware#4252]
For production we need combined binary with prodtest 0.2.9 where a touch flex connector is not required to boot a prodtest, but at the same time the processor triggers TOUCH_ON and switches mosfet Q102 for measuring 3V3 at TP 133.
This is how it was in the previous combined with prodtest 0.2.7.

**Comment by TychoVrahe** [comment]
Would it be enough to turn the mosfet on on some command, or is it required to have it turn on all the time while in prodtest? i assume we dont need to have it on in bootloader.

**Comment by Micka1792** [comment]
If it is a problem to switch it always, we can switch it again with the command
