### ISSUE TITLE
device tests do not recognize the new protobuf field

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#426]
We've added the new field to protobuf messages here:

https://github.com/trezor/trezor-firmware/blob/4323b0ac2abb086afa95df6a1bbb4a788ecc476a/common/protob/messages-management.proto#L61-L77

Once I set the field here: https://github.com/trezor/trezor-firmware/blob/4323b0ac2abb086afa95df6a1bbb4a788ecc476a/legacy/firmware/fsm_msg_common.h#L86-L100

The device tests fail to parse the Features message and bail out.

**Comment by prusnak** [comment]
IMO this should work, because I updated `python/src/trezorlib/messages/Feature{,s}.py` files and python-trezor is used from the currently check outed branch, not from the PyPI, right?

**Comment by prusnak** [comment]
That said I am not sure python-trezor should bail out on new unrecognized fields at all. We do only forward-compatible changes, so we could afford skipping unrecognized fields IMO.

**Comment by prusnak** [comment]
I removed the problematic code via https://github.com/trezor/trezor-firmware/commit/9d8ebfcdbc6118ade9583cce42a7aaf0b8cff4df so master should be OK again, but we need to fix this in order to merge `bitcoin-only` branch.

**Comment by matejcik** [comment]
the problem is not in unrecognized fields but in unrecognized encoding (packed array)

it seems more difficult (or more hacky) to modify nanopb to not use packed arrays, so i'm implementing packed array support in trezorlib
