### ISSUE TITLE
 ARM Bad fw revisionId from emulator

### ISSUE THREAD

**Issue by Lemonexe** [trezor/trezor-firmware#4260]
**Describe the bug**
In some cases, emulator responds with invalid firmware revision Id, failing revision check in trezor suite.
This can break trezor-suite E2E tests.

**Firmware version and revision**
- `trezor-user-env` emulator of T1B1 1.12.1 on Apple ARM
- possibly also in other versions (unknown)
 
**To Reproduce**
1. Go to `trezor-user-env` on Apple ARM
2. Start T1B1 1.12.1
3. Open trezor suite
4. Go to Debug settings, turn **off** Firmware **Hash** check, but leave Firmware **Revision** check **on**
6. See Device compromised modal

This works with ARM 1.11.2, ARM 1.11.1 or x64 1.12.1 (no Device compromised modal with only fw revision check on)

**Screenshots**
Trezor suite failed revision check
![image](https://github.com/user-attachments/assets/c4072ba7-3867-4365-b4d6-5de4bc7b14f8)

**Comment by vdovhanych** [comment]
It should be fixed; please test it and report back. If the issues persist, it must be somewhere else.
