### ISSUE TITLE
the word "academic" is persistent on position 3 and 4 for single share Shamir backups

### ISSUE THREAD

**Issue by hah** [trezor/trezor-firmware#4303]
I own both safe 3 and safe 5, been testing some stuff and noticed that the word "academic" is present in every seed i create for word 3 and 4. is that desireble? I've seen it being mentioned in [#500](https://github.com/trezor/trezor-firmware/issues/500#issuecomment-532713422) but that issue is 5 years old

If needed i can provide screenshots of a dummy seed

repro steps: 
- wipe device
- create new wallet
- (on safe 3 you have to select the 1-1 shamir option cuz 12w is default)
- view words for backup

thanks

**Comment by prusnak** [comment]
Yes. That is normal.
