### ISSUE TITLE
Wanchain not signing anymore

### ISSUE THREAD

**Issue by tyrion70** [trezor/trezor-firmware#437]
As discussed with @matejcik on Gitter. The derivation path should look at chain_id(=1 || 6) and txtype(=1) for Wanchain. Currently its sending a Forbidden key path error. 

Thanks!
Peter

**Comment by prusnak** [comment]
Can you try and prepare a pull request?

**Comment by tyrion70** [comment]
Sure! But can you give me a pointer where it's going wrong now? I see the error is thrown in core/src/apps/common/seed.py but tbh I can't really relate that to the def shortcut_by_chain_id that is already present in core/src/apps/ethereum/networks.py for Wan. It seems wan is not present in the .//common/defs/ethereum/networks.json either.
Could you give me some context as to where and why the error is thrown? Thx!

**Comment by prusnak** [comment]
String search in the repo shows the following line: https://github.com/trezor/trezor-firmware/blob/0a594ea1e982a671f26cb448a5351b44443d2b0f/core/src/apps/common/seed.py#L62

**Comment by tsusanka** [comment]
The paths are defined in the app's \_\_init\_\_ file see https://github.com/trezor/trezor-firmware/blob/0a594ea1e982a671f26cb448a5351b44443d2b0f/core/src/apps/ethereum/__init__.py#L13

**Comment by matejcik** [comment]
i'm taking this, it's quicker to fix than it is to explain ;)
