### ISSUE TITLE
passphrase entry keyboard freezing

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#444]
When entering passphrase on device, the keyboard will sometimes stop responding. After initiating a new action in the wallet, the device will start responding again.

The problem is reproducible, @bosomt can always do it.
The problem does not depend on passphrase length.

**Comment by matejcik** [comment]
@bosomt, could you check if this is reproducible with the emulator?

**Comment by bosomt** [comment]
@matejcik yes i was able to reproduce it via Emulator, come and see ;)

**Comment by matejcik** [comment]
Lowering priorities and moving to backlog.
Let's check on this again when Wallet fixes the "device entered inconsistent state" problem, I suspect the root cause is the same.

**Comment by sorooris** [comment]
https://github.com/satoshilabs/mytrezor/issues/848

**Comment by matejcik** [comment]
the relevant Wallet issue has been fixed. @bosomt would you please retest this issue again?

**Comment by bosomt** [comment]
i was not able to reproduce it for last 11 days.
as soon it happens again i will contact you
