### ISSUE TITLE
trezorctl command behavior with Super Shamir on T1

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-firmware#445]
Nixos, Chromium
T1 BTC-only fw (1.8.3)
wallet Git Commit: 2fd93cffe03f290046355ff17a6dc55930324bef

**Steps to reproduce:**
- install latest fw
- open terminal and type in `trezorctl reset-device -e -t 256 -b shamir`
- observe

**Expected:**
Command for the device reset with Shamir groups is not allowed for T1.

**Actual:**
Using the command `trezorctl reset-device -e -t 256 -b shamir` on a wiped T1 generates a 24-word seed.

**Comment by tsusanka** [comment]
I think we should solve this twofold:

1. Throw an error in trezorctl.
1. Add check to legacy.

What do you think @prusnak @matejcik?

**Comment by matejcik** [comment]
it makes no sense to fix this in T1 firmware, as the bug will affect all non-updated Trezors anyway.

we will add the following warning to `trezorctl`:
> WARNING: Trezor One currently does not support Shamir backup.
> Traditional single-seed backup will be generated instead.

(let me know if you want to change the text)

But I believe that `trezorctl` should not try to *stop* you from sending the request with the appropriate field set.

**Comment by matejcik** [comment]
I pushed a commit that adds the warning. Do we want to keep the issue open for further discussion?

**Comment by tsusanka** [comment]
IMHO better closed

**Comment by matejcik** [comment]
the code should be changed to use capabilities instead of guessing based on model number

**Comment by matejcik** [comment]
right now this depends on #518
