### ISSUE TITLE
SuperShamir: Remaining shares are very confusing and probably incorrect

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#451]
1. Why is the screen displayed _before_ the Success screen? It is in this order:

![emu00000000](https://user-images.githubusercontent.com/1835345/63835264-638d3300-c977-11e9-822d-960149446a9c.png)
![emu00000001](https://user-images.githubusercontent.com/1835345/63835266-638d3300-c977-11e9-92aa-bff4d09639ab.png)
![emu00000002](https://user-images.githubusercontent.com/1835345/63835268-6425c980-c977-11e9-97a6-0275160ddc46.png)

I believe we should first inform the user, what they've entered and then what is remained.

2. I'm not sure this works correctly. I've entered G2, S2 and then G1, S1 in 2of3 groups scenario, where each group is 2of3. After I enter the second share I get:

![emu00000000](https://user-images.githubusercontent.com/1835345/63835541-f29a4b00-c977-11e9-9925-47c12d0f2b44.png)
![emu00000001](https://user-images.githubusercontent.com/1835345/63835543-f332e180-c977-11e9-8371-885dd6a9c8ff.png)
![emu00000002](https://user-images.githubusercontent.com/1835345/63835544-f332e180-c977-11e9-90f9-d391483de1e9.png)

It seems to me the Remaining shares do not take into account the last entered share.

---

Also, I'm not sure it is clear to the user that the screen displays what is left, but not all of that is needed to be entered.

**Comment by andrewkozlik** [comment]
Some thoughts/nitpicks with regard to these screens:
- I am not sure I like "Share 1 from Group 1" being split across three lines if it can fit on one line. If we really want it to be split, then perhaps center-align the three lines.
- How about putting an ellipsis (...) on the line following the last word? Like this: 
  2 more groups starting
  gesture
  negative
  ...
  Any opinions?
- How about making the Success title and/or checkmark green? First please check some other success screens, so that the formatting is consistent.

**Comment by tsusanka** [comment]
> How about making the Success title and/or checkmark green? First please check some other success screens, so that the formatting is consistent.

The Success page should have green checkmark. This indicates it does not use the common.show_success page as it should.

**Comment by ciny** [comment]
I just went through the whole process (on the release/2019-09 branch)
- the screens were in the correct order (enter words->share success->homescreen->remaining shares->enter words->share success etc) including restarting the emulator between shares to test persistence. I was not able to reproduce this behavior
- I was shown the correct remaining shares. The only thing that might be confusing is that we offer "x more groups" even in case we already started enough groups to reach the group threshold. In this case we probably shouldn't display the "x more groups" page at all and just show the already started groups that haven't reached their threshold.

@sorooris please retest on the release firmware so we can be sure it's not some blocker that needs addressing in the release branch. Shares that already reached their threshold being shown is imho a dealbreaker

@andrewkozlik I made the screens according to the designs provided by our designers. @ZdenekSL is probably the one to approve or communicate changes in the UI. 

anyway seems the possible blocker parts of this issue can't be reproduced so we can discuss the rest of the suggestions at standup and solve them in #442

**Comment by tsusanka** [comment]
The issue is a bit different. We correctly show success pages after entering the words, but clicking on `Enter share` leads to the info about Remaining shares, which is really weird and confusing.

**Comment by tsusanka** [comment]
What we need to discuss with UX is this UX screen:

![79b53402-ca43-4703-9cd1-754acda5fcfb](https://user-images.githubusercontent.com/1835345/64237429-9e094980-cefc-11e9-9d65-e26e99281847.png)

which couldn't be implemented because we need also the Wipe button. This caused this whole confusion. To be discussed IRL

**Comment by tsusanka** [comment]
Closed in favor of #512.
