### ISSUE TITLE
Missing U2F feature on BTC-only firmware

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-firmware#452]
Nixos, Chromium
TT BTC-only fw (2.1.5, fd53c72); all seed
github.com with U2F enabled
 
**Steps to reproduce:**
- navigate to a site with U2F login enabled
- log in and wait for a U2F dialog 
- observe
 
**Expected:**
U2F appears and the device prompts the user to cancel/accept the authentication.
 
**Actual:**
No prompt is displayed on the device screen and user is unable to use the security key authentication.

**Comment by tsusanka** [comment]
I think this is expected, cc @prusnak.

**Comment by prusnak** [comment]
Yes, Bitcoin only firmware does not have U2F.
