### ISSUE TITLE
Dry-run - cancelling the process after selecting wrong word number

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-firmware#453]
Nixos, Chromium
TT 2.1.5 (fd53c72)
wallet Git Commit: 2fd93cffe03f290046355ff17a6dc55930324bef

_Precondition: the device is using for example a 12-word seed_
**Steps to reproduce:**
- initiate dry-run in the Trezor wallet
- select a word number other than the correct one on the device screen
- enter any words and finish the dry-run
- observe
 
**Expected:**
The device screen allows the user to either try again or cancel the dry-run process.
 
**Actual:**
The device screen displays only a "Try again" option without a comfortable option to cancel the process and is forced to disconnect the device and after reconnecting the dry-run persists but allowing to cancel the process from there.
Wallet then throws error messages (Unexpected message) both on screen and in the console if the _remember device_ option is selected.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/63849329-27b39700-c992-11e9-91f0-25081e358156.png)
![image](https://user-images.githubusercontent.com/10185314/63849350-300bd200-c992-11e9-8321-420084f879cf.png)
![image](https://user-images.githubusercontent.com/10185314/63849367-369a4980-c992-11e9-8051-98d418335598.png)

**Comment by tsusanka** [comment]
If this is the first share entered, we should prompt the user to enter the number of words again. If this is too complicated, I'm inclined to not doing it.

**Comment by sorooris** [comment]
@tsusanka It is indeed the first share entered, incorrectly (any random words since there is no option to go back or cancel), after selecting a Shamir backup with 20 words instead of a single backup with 12 words as described above.

**Comment by tsusanka** [comment]
PR available. Fixed for normal recovery as well, not just dry run. I hope the UX is not confusing.
