### ISSUE TITLE
Move GroupThresholdReached and ShareAlreadyAdded error checks

### ISSUE THREAD

**Issue by ciny** [trezor/trezor-firmware#457]
GroupThresholdReached:
Currently we're checking if we entered enough shares to reach group threshold only after all the words are entered. We can check for it after the 3rd word is entered to be more user friendly.

ShareAlreadyAdded:
We can check this after 4th word is entered like we do in case of single group. Currently the error is thrown after all the words are entered

Since test improvements are already in review make sure to include tests for both of these errors.

**Comment by tsusanka** [comment]
I've removed both IdentifierMismatchError and ShareAlreadyAddedError in #509. @ciny when you will be doing this issue could you check the GroupThresholdReachedError if it can't be removed as well?

**Comment by ciny** [comment]
implemented in #523
