### ISSUE TITLE
Invalid coin names on trezor1

### ISSUE THREAD

**Issue by random-zebra** [trezor/trezor-firmware#46]
Using functions from `trezorlib.btc`, such as `get_address` (as well as using trezorctl) raises
```
trezorlib.exceptions.TrezorFailure: DataError: Invalid coin name
```

on a Trezor One device (official firmware 1.8.0) with the following coin_names:
- NIX	
- PIVX	
- PIVX Testnet
- Primecoin
- Stakenet
- ZClassic

All should be supported as per [support.json](https://github.com/trezor/trezor-firmware/blob/b4cec0ae541adca38ccfc46ffe6ec6ff0a3038fb/common/defs/support.json) and [COINS_JSON](https://github.com/trezor/trezor-firmware/blob/e78a917502fa16f2472808e0402201a315e0fea5/python/trezorlib/coins.py#L22).

Connecting to a trezor1 emulator instead, works fine.

**Comment by prusnak** [comment]
This is fixed in master. Wait for the next release.
