### ISSUE TITLE
Add cli options to emu.sh

### ISSUE THREAD

**Issue by ciny** [trezor/trezor-firmware#466]
Currently the emulator is configured through manually set environmental variables. With new features (like screenshot saving or disable fade) the number of variables increases and it can get confusing. Let's add options and a help message to ./emu.sh to make it more user/developer friendly

something like

```
#./emu.sh --help
Usage: ./emu.sh [OPTIONS]
Run emulator with selected options

Options:
  -H --help                             this help message
  -D --debug                            run emulator with debuglink
  -S --save-screenshots                 save every screen 
  -N --no-fade                          disable fading 
  -P --profile=PATH                     path to profile directory
  -M --log-memory                       print memory usage after each workflow
```

Questions/discussion:
 - do we want to do this? 
 - names and help descriptions of various options
 - possible enhancements (--wipe to remove trezor.flash/log) from TREZOR_PROFILE, set output path for save-screenshot etc)

**Comment by prusnak** [comment]
I am all for refactoring all runner scripts first and only then adding more options. See https://github.com/trezor/trezor-firmware/issues/468
