### ISSUE TITLE
Unify core emulator running scripts

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#468]
Currently, we have:

* `emu.sh`
* `trezor_cmd.sh`
* `tests/run_tests.sh`
* `tests/run_tests_device_emu.sh`
* `tests/run_tests_device_emu_monero.sh`
* `tests/run_tests_device_emu_u2f.sh`

and this is becoming messier over time.

We should refactor/unify these scripts into something sane.

**Comment by jpochyla** [comment]
It would be convenient to wrap/rewrite monero tests into pytest.

**Comment by prusnak** [comment]
+1 for rewriting these into Python.

Also pytest can accept an option `--emu path/to/emulator` which will start an emulator if needed (before the whole test suite, or before each test separately)

**Comment by ZdenekSL** [comment]
Related to #466

**Comment by malinah** [comment]
File `trezor_cmd.sh` is actually not a running script but rather a bash library for the TT emulator. That was my attempt to unify the control over the TT emulator to fit the existing testing environment and contains handling of features that are not covered elsewhere. So, please take it into account when the whatever is going to be rewritten. Thanks.

**Comment by tsusanka** [comment]
Let's do this after #466
