### ISSUE TITLE
initialization: Select words from list instead of typing them

### ISSUE THREAD

**Issue by slush0** [trezor/trezor-firmware#48]
Currently, during onboarding process, user have to write two words from wordlist back to device, to prove he wrote down the recovery seed. Instead of this, show dialog to ask user to select word on x-th position from his recovery seed:

"Word on 3.position?
cat
stick
slush
all"

I propose to pick all four (maybe more, if it fits the screen layout) words from generated seed, instead of displaying just one real word and three other randomly picked from full wordlist. Also, because this method is much faster than retyping words back, I propose to let user check four, instead of two words.

**Comment by ZdenekSL** [comment]
Implemented as part of Shamir.
