### ISSUE TITLE
Binance: Export Uncompressed Public Key

### ISSUE THREAD

**Issue by notatestuser** [trezor/trezor-firmware#483]
Hi,

The Public Key that is exported from the device is currently in a [compressed format](https://github.com/bitpay/bitcore-lib/blob/master/docs/publickey.md#compressed-vs-uncompressed) with a prefix of either 0x03 or 0x02 depending on whether it’s greater or less than the midpoint of the curve.

However, on the blockchain, we store Public Keys in transactions in an uncompressed format with a prefix of 0x04.

We would like to know if it would be possible to export the full uncompressed Public Key from the firmware when we call the sign routine.

**Comment by prusnak** [comment]
You can easily uncompress the key in your software.
