### ISSUE TITLE
Binance: Show the trading pair on the “Confirm order” screen

### ISSUE THREAD

**Issue by notatestuser** [trezor/trezor-firmware#490]
What is currently shown is: the sender address, the order “side” (buy/sell), the price and the amount.

It would be nice UX to also show the trading pair, which is available in a string in the transaction.

**Comment by prusnak** [comment]
Please prepare and send the pull request

**Comment by prusnak** [comment]
Implemented in https://github.com/trezor/trezor-firmware/pull/494
