### ISSUE TITLE
Binance: Improved display of amounts

### ISSUE THREAD

**Issue by notatestuser** [trezor/trezor-firmware#491]
This is my final UX-related suggestion :)

On Binance Chain, all tokens have a [decimal scale of 8](https://docs.binance.org/faq.html#what-is-the-decimal-precision-for-prices-and-quantities-on-binance-chaindex) and amounts are represented as integers in transactions. This means that an integer value of `100000000` in a transaction represents an amount of `1.00000000` in decimal form.

It would be nice to display amounts in this decimal form when they are shown on the device screen. Ideally, this would apply to both Transfers and Orders.

**Comment by tsusanka** [comment]
@ciny what do we display now?

**Comment by prusnak** [comment]
@notatestuser please prepare and send a pull request

**Comment by prusnak** [comment]
Implemented in https://github.com/trezor/trezor-firmware/pull/494
