### ISSUE TITLE
Missing ToS in recovery

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-firmware#495]
When I use new Trezor to create a wallet, I see the Terms of service as the first screen. This is not true when I use recovery. We need to add this screen before recovery as well into a wallet. 

We need to add the text from create/reset
![emu00000000](https://user-images.githubusercontent.com/50332311/64251981-0286d180-cf1a-11e9-9d5c-d79f729bd1d9.png)

into recovery 
![recovery5](https://user-images.githubusercontent.com/50332311/64251999-116d8400-cf1a-11e9-8e93-f0e07ba82f8f.png)

Text

`By continuing you agree to https://trezor.io/tos`

**Comment by tsusanka** [comment]
I did it the same way as it is in Creating new wallet, PR in #498. Seed check stayed intacted.

![emu00000001](https://user-images.githubusercontent.com/1835345/64263155-7d0e1c00-cf2f-11e9-8b0e-7b7eb568436c.png)
![emu00000000](https://user-images.githubusercontent.com/1835345/64263153-7d0e1c00-cf2f-11e9-91c8-60491ee7ce69.png)

**Comment by tsusanka** [comment]
Closed by 5c9fd58.
