### ISSUE TITLE
bootloader: soft reset after firmware upload

### ISSUE THREAD

**Issue by keepkeyjon** [trezor/trezor-firmware#5]
I believe Trezor T does this. Do you see any reason why the Trezor One should not?

**Comment by tsusanka** [comment]
Might be done along with  #4

**Comment by tsusanka** [comment]
PR in https://github.com/trezor/trezor-firmware/pull/847

**Comment by prusnak** [comment]
Closed via https://github.com/trezor/trezor-firmware/pull/847
