### ISSUE TITLE
Enable derivation paths checks for GetPublicKey

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#50]
When https://github.com/trezor/trezor.js/issues/73 is fixed enable paths checks for GetPublicKey.

**Comment by tsusanka** [comment]
This basically waits for https://github.com/satoshilabs/mytrezor/issues/720 which can wait for suite (imho) and also waits for the passphrase redesign (#1).

**Comment by matejcik** [comment]
This has been done in #959 and reverted in #1020 again. Currently `GetPublicKey` cannot do derivation path checks because too many third parties are using it in too many distinct (and mostly valid) configurations.
