### ISSUE TITLE
Enable 1 of 1 Shamir seed

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-firmware#500]
Let's enable creating 1 of 1 share when creating new a wallet with Shamir backup.

**Comment by tsusanka** [comment]
To clarify: we have agreed we will allow 1of1 share in a Basic Slip39 (meaning no groups). Is that correct?

**Comment by tsusanka** [comment]
We probably should retext this screen then. Maybe we could inform the user that it is very similar to Single Backup?

![emu00000000](https://user-images.githubusercontent.com/1835345/64689580-eab9cb00-d48e-11e9-82a0-47e5dd61ccfc.png)

**Comment by tsusanka** [comment]
@matej_zak could you have a look?

**Comment by tsusanka** [comment]
@matejzak do you think you could come up with some better text?

**Comment by tsusanka** [comment]
Suggestion: `Only one share will be created.`

**Comment by tsusanka** [comment]
Note: we should also fix the possible duplicates in the "words checking" because it is way more likely to happen now (academic, academic).

**Comment by tsusanka** [comment]
Duplicates fixed in  https://github.com/trezor/trezor-firmware/pull/541
