### ISSUE TITLE
Rename all variables with an underscore in its name that are used outside its module

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#504]
On some places we incorectly named variables with a `_` prefix, even though these variables are used outside of the module. This is thrown upon and should be fixed, functions included.

Searching for `._` gives a good idea.

**Comment by prusnak** [comment]
Please note that grepping for `._` finds also `self._`, which is totally OK.

**Comment by prusnak** [comment]
I did a quick fix of the U2F_COUNTER variable to get the CI running again after adding upgrade tests from 2.0.x: 6ad3294f31a1e7484b43c104ff2880b965198cad

I didn't touch the other variables on purpose.
