### ISSUE TITLE
Remove all usage of micropython.const

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#505]
Is using `const` actually worth it? We should measure the impact of not using it and consider its removal in case the difference is quite small.

**Comment by andrewkozlik** [comment]
I don't think that the only purpose of `const` is optimization of the speed and the size of the firmware. It also enforces that the value cannot be accidentally changed. We should take this also into account when evaluating it's usefulness.

**Comment by matejcik** [comment]
using `const` allows us to save nontrivial amount of space, provided that the const symbols are module-local only.
so this won't be done
