### ISSUE TITLE
Rethink passphrase protobuf workflow

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#51]
Currently, Trezor Wallet uses GetPublicKey with an address `m/1/0/0` to find out the state of the device. In other words to find out if Trezor is unlocked or if PIN/passphrase needs to be entered.

This is a little bit hackish and in a slight conflict with #326. There are three proposed solutions:

a) declare `m/1/0/0` as a valid path
b) use `m/44'/1'/0'` which is a testnet path for every coin and therefore should be valid every time
c) add a new protobuf message GetState or similar

**Comment by prusnak** [comment]
Let's close this and discuss in https://github.com/trezor/trezor-firmware/issues/1
