### ISSUE TITLE
Add Info button to Recovery homescreen for Super Shamir

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#512]
In Recovery Homescreen in case we already know it is a Super Shamir, let's display an additional "Info" button, which will show, which groups and shares are needed.

Unfortunately we are using the Confirm dialog, which works with two buttons only, so this will need some refactor.

Fast prototype:

![emu00000000](https://user-images.githubusercontent.com/1835345/64624101-6f064280-d3ea-11e9-8224-c81c1dfed4ac.png)

**Comment by tsusanka** [comment]
Clicking on the Info button will lead to:

![emu00000000](https://user-images.githubusercontent.com/1835345/63835264-638d3300-c977-11e9-822d-960149446a9c.png)

**Comment by andrewkozlik** [comment]
Note about the screenshot: "More shares needed for this recovery" should instead say something like "More shares needed for seed check"

**Comment by tsusanka** [comment]
Good catch. I've removed the second part completely, I think it's fine.

![emu00000000](https://user-images.githubusercontent.com/1835345/64682434-bc81be80-d481-11e9-8ff7-e8095ca4e41b.png)

**Comment by tsusanka** [comment]
Although inconsistent I think "Abort" is clearer than the cross:

![emu00000000](https://user-images.githubusercontent.com/1835345/64963028-cac44600-d898-11e9-9bec-3d5b5d857921.png)

**Comment by ciny** [comment]
To test this screen we will need to modify the debuglink so we can press the info button.

**Comment by matejcik** [comment]
> To test this screen we will need to modify the debuglink so we can press the info button.

let's defer that to #487

**Comment by tsusanka** [comment]
> let's defer that to #487

Agreed.

**Comment by ciny** [comment]
implemented in #524
