### ISSUE TITLE
Confusion in Super Shamir backup with 1-of-n group (n > 1)

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#514]
If the user wants to create a Super Shamir backup which has a group with 1-of-5 shares, then on one of the screens they will choose 5 shares as the group size and then on the next screen they cannot choose threshold 1, because 1-of-n is not allowed for n > 1. But the user doesn't know this and they do not understand why they cannot choose threshold 1. Solutions:
1. For each group, first enter the threshold, then enter the group size. If the threshold is 1, then the group size will be forced to 1 also and the user will be informed why.
2. Let them enter threshold 1 and if they do, then show an info screen saying we changed the number of shares to 1. 
3. Add a back button to the threshold screen. But the user will still be confused why they can't choose threshold 1 and it will probably not occur to them that they need to go back.

**Comment by tsusanka** [comment]
After discussion with @matejzak we have decided we will not do this unless there are concrete data proving that this confuses people. In other words, unless there are some tickets on our customer support, we will leave it as it is.
