### ISSUE TITLE
Add test for Info button in SuperShamir recovery screen

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#527]
In #512 we have introduced a middle Info button which shows remaining shares info.

The device tests currently do not test it, because we can't "press" the button using a debuglink (we would have to add a new channel probably or do some refactoring). We have agreed to wait for #487 and do this after that.

**Comment by tsusanka** [comment]
@ciny isn't this done?

**Comment by matejcik** [comment]
this is not done yet

**Comment by matejcik** [comment]
fixed in #1971 / #1964
