### ISSUE TITLE
Why is this 0x16?

### ISSUE THREAD

**Issue by webees** [trezor/trezor-firmware#529]
Is it **0x19**?

https://github.com/trezor/trezor-firmware/blob/0677a8e570f8787e7f27a6d4022a422364a12463/legacy/bootloader/usb_send.h#L54

https://github.com/trezor/trezor-firmware/blob/0677a8e570f8787e7f27a6d4022a422364a12463/legacy/bootloader/usb_send.h#L40

**Comment by prusnak** [comment]
Ths indeed seems like a bug. Fixed in 101d2e5df6e6d0d094a998406de2c8d90f1e102c

Thanks!
