### ISSUE TITLE
Shamir: clarify usage of backup_type and word_count in recovery flow

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#540]
from this comment: https://github.com/trezor/trezor-firmware/pull/518#issuecomment-532724153
tracking separately because this might not get fixed in time for freeze; we deem it not critical because the code seems correct to the best of our ability to evaluate it.

Problem summary: the method `_continue_recovery_process` uses both `word_count` and `backup_type`. Each is stored separately, but their values are interrelated. This interrelation is not strongly enforced and the code does not use one or the other consistently. In particular, all possible combinations of values are not accounted for.
While the code currently seems correct, it's a nice space for bugs to breed.

**Comment by tsusanka** [comment]
Closed via https://github.com/trezor/trezor-firmware/pull/545
