### ISSUE TITLE
firmware 2.1.6 (702f865e) Firmware error when trying to create wallet with Single Backup (12 words)

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-firmware#550]
Trezor T with 2.1.6 (702f865e). 

Steps to reproduce: 
1. Connect a wiped device, open wallet.trezor.io or beta-wallet.trezor.io
2. Select Create new wallet -> Single Backup, confirm on device
3. Click on Create backup in 3 minutes, Continue

Result: first Firmware error, then Backup failed in the wallet

<img width="894" alt="Screenshot 2019-09-20 at 15 53 00" src="https://user-images.githubusercontent.com/31442634/65332759-9665c800-dbbf-11e9-9279-d3a81ec82eda.png">
<img width="1185" alt="Screenshot 2019-09-20 at 15 53 49" src="https://user-images.githubusercontent.com/31442634/65332777-9cf43f80-dbbf-11e9-9a10-7236b791fc6d.png">

**Comment by matejcik** [comment]
the FW seems to think that backup is already done.

**Comment by matejcik** [comment]
no, i was wrong
```
Traceback (most recent call last):
  File "/home/matejcik/projekty/prace/trezor-firmware/core/src/trezor/wire/__init__.py", line 319, in handle_session
  File "/home/matejcik/projekty/prace/trezor-firmware/core/src/apps/management/backup_device.py", line 19, in backup_device
  File "/home/matejcik/projekty/prace/trezor-firmware/core/src/apps/management/reset_device/__init__.py", line 203, in backup_seed
  File "/home/matejcik/projekty/prace/trezor-firmware/core/src/apps/management/reset_device/__init__.py", line 157, in backup_bip39
ValueError: Invalid data length (only 16, 20, 24, 28 and 32 bytes are allowed)
```

**Comment by matejcik** [comment]
importantly, we do not have a test for this!

`reset_device(skip_backup=True)` then `backup_device()`

**Comment by prusnak** [comment]
Please don't close before adding a test case for this

**Comment by prusnak** [comment]
This can be also reproduced without using wallet (just press skip on the touch screen during normal reset).

**Comment by matejcik** [comment]
the reason is that the common method `backup_seed` takes the secret in one case (when run from reset-device) but the text of the mnemonic in the other (when run from backup-device)
i'm now trying to find out where this happened.

**Comment by matejcik** [comment]
seems to be introduced in e6372ede75fe03792a701b4e6d8e3d8cac31eca0

**Comment by prusnak** [comment]
Delayed backup seems to work with Shamir and Super Shamir but can we have also test for these as well?

**Comment by matejcik** [comment]
I have a fix ready, still making the test

**Comment by prusnak** [comment]
Tests will be tracked in https://github.com/trezor/trezor-firmware/issues/551

Fix submitted to `master`:
* https://github.com/trezor/trezor-firmware/commit/78ecc38b1b1f5f3e547bcd95f3b33b1a1012a402
and cherrypicked to `release/2019-10`:
* https://github.com/trezor/trezor-firmware/commit/f6168b82465e12b5849cb1addfff03e31db1d978
