### ISSUE TITLE
Rename and order device tests

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#556]
We have all device tests in one folder and many of them are called `test_msg_*` even though they test a bit more than just the single message.

I suggest to structure this a little bit better by splitting the tests up to more subfolders (e.g. reset, recovery, ethereum, etc.) or we could follow the src/apps' structure.

**Comment by matejcik** [comment]
the following would also be nice while we're messing with this:

* get rid of classes
* rename all `proto` usages to `messages`
