### ISSUE TITLE
 revision b08a239 - pressing Info leads to Recovery failed, Firmware error

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-firmware#566]
steps to reproduce: 
1) take a wiped device, go to Recover wallet
2) I entered 3 shares from the 2nd group (threshold of the group was 3/5)

share 1

scene
hush
beard
learn
blue
aspect
jacket
fused
sniff
dictate
duration
repair
depend
breathe
painting
column
campus
sugar
script
freshman

share 2

scene
hush
beard
march
dragon
corner
prayer
display
wisdom
adapt
tracks
friar
plastic
boundary
satoshi
wrap
dress
flame
vocal
belong

share 3

scene
hush
beard
method
chemical
hesitate
bulge
branch
thorn
wisdow
unwrap
triumph
trust
shaped
domain
hazard
burden
unusual
violence
pharmacy

After entering each share I was pressing Info to get information about how many shares are needed. 

After entering the 3rd share pressing Info led to Firmware error: 

![image_from_ios](https://user-images.githubusercontent.com/31442634/65515898-4dc04e80-dee0-11e9-9ce6-f57d81de2fb9.jpg)

Clicking Continue in the web wallet doesn't do anything. 

If I reconnect the device I can get back to Recovery mode.
But now pressing Info now just reloads the display. 

![photo_2019-09-24_15-34-27](https://user-images.githubusercontent.com/31442634/65516177-d2ab6800-dee0-11e9-9ad2-8463af07baec.jpg)

**Comment by tsusanka** [comment]
Looks like a one byte fix.. https://github.com/trezor/trezor-firmware/commit/6c6bd44ee887c23b3743eb24d2e5ea989dc55a48
