### ISSUE TITLE
Change firmware update chunk sizes to make UX more smooth

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#568]
When doing a firmware upgrade bootloader does not send ButtonRequest. Wallet then does not know that the user was prompted to confirm the upgrade.

@prusnak can we add it or it is intentionally missing?

Brought up by @szymonlesisz and @mroz22 .

**Comment by prusnak** [comment]
We are reworking the firmware chunk sizes to make the user experience better.

**Comment by tsusanka** [comment]
## Testing

We have tested this with @mroz22 so this should be fine, but please test firmware upgrade just to make double sure. Let's test this on Suite@develop and Wallet@production.

Note: this requires the new bootloader to be signed so you can't test this yet. Let's test this shortly before release / at the end of freeze.

**Comment by tsusanka** [comment]
@prusnak JFYI @mroz22 mentioned this is not needed on T1, that the delay there is quite low. Mybe because the flash erase is faster there?. So this was done for TT only.

**Comment by prusnak** [comment]
ACK

**Comment by bosomt** [comment]
@tsusanka is there still need to test it on our side 
or is it even possible ?

**Comment by tsusanka** [comment]
We have not released the bootloader yet, so there is nothing test at the moment. But maybe leave the `needs QA` so we test it when we finally decide to release new bootloader.

**Comment by sorooris** [comment]
any updates on this?

**Comment by tsusanka** [comment]
I guess it is up to @prusnak to decide _when_ we want to release the next bootloader. But my guess is we will release when there are more changes to it.
