### ISSUE TITLE
Inconsistent texts in backup screens

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-firmware#569]
2.1.6 bd876b31

**Expected:**
Unified texts throughout the backup process.
**Actual:**
Various screens use different words for completing tasks - verified, wrote down, checked.

![image](https://user-images.githubusercontent.com/10185314/65590082-74d35a80-df8a-11e9-8cad-b54e69bcac69.png)
![image](https://user-images.githubusercontent.com/10185314/65590105-7f8def80-df8a-11e9-996e-b7d7947d53cc.png)
![image](https://user-images.githubusercontent.com/10185314/65590123-874d9400-df8a-11e9-9659-383d145cfc2d.png)

**Comment by tsusanka** [comment]
We will tackle this with the UI redesign. Closing here.
