### ISSUE TITLE
Initialize all local variables explicitly

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#571]
We need to review all C code and add explicit initialization of local variables everywhere.

**Comment by prusnak** [comment]
Maybe [clang-tidy](https://clang.llvm.org/extra/clang-tidy/checks/list.html) can help?

**Comment by onvej-sl** [comment]
I did it partly [here](https://github.com/trezor/trezor-firmware/commits/onvej-sl/explicit-initialization).

**Comment by onvej-sl** [comment]
I explicitly initialised automatic variables in `crypto`, `legacy` and `storage`. Variable length arrays (such as `char array[i];`) are initialised with `memset`. I didn't initialise static variables and variables in tests and tools.

**Comment by onvej-sl** [comment]
Trezor T emulator binary increased in size by 8 kB.

**Comment by prusnak** [comment]
Fixed via trezor/trezor-firmware#607
