### ISSUE TITLE
update SD card code to use DMA

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#573]
The work is being done here: https://github.com/trezor/trezor-firmware/tree/sdcard-dma

**Comment by prusnak** [comment]
eb916d5195ce12d902e0176fe2f9718bf6f009f9 contains working DMA for SDIO

I still need to update the code so we don't need privileges later on (and we can drop the eb916d5195ce12d902e0176fe2f9718bf6f009f9 patch)

**Comment by tsusanka** [comment]
> eb916d5 contains working DMA for SDIO

You probably meant https://github.com/trezor/trezor-firmware/commit/8c5a6977f32593103f099f61be20f9e7a907a4f0 . Delete me after edit :)

**Comment by prusnak** [comment]
I indeed meant eb916d5, because the code in 8c5a697 does not work without the hack in eb916d5 at the moment.

**Comment by prusnak** [comment]
Merged in 046ff607d32e050d91d276fd085a24dc51ce5020
