### ISSUE TITLE
[Feature] Stellar signing / missing operations

### ISSUE THREAD

**Issue by MisterTicot** [trezor/trezor-firmware#579]
**Issue**

4 of the Stellar operations are not supported by Trezor: inflation, createPassiveSellOffer, manageSellOffer & manageBuyOffer.

**Notes**

- `createPassiveSellOffer` is the new name for `createPassiveOffer` - `createPassiveOffer` is still supported in Stellar official libraries for backward compatibility purpose.
- `manageSellOffer` is the new name for `manageOffer` - `manageSellOffer` is still supported in Stellar official libraries for backward compatibility purpose.
- `manageBuyOffer` is a new operation similar to `manageSellOffer` but passing orders in the other direction. Parameters are the same.

**Comment by prusnak** [comment]
Please send a pull request implementing these

**Comment by prusnak** [comment]
Citing from https://github.com/trezor/trezor-core/issues/202#issuecomment-393342089 why Inflation is not supported:

"Yes, any user can submit this operation to the network to trigger the inflation calculation, so there wouldn't be any point in using a Trezor to secure it. :)"

**Comment by matejcik** [comment]
perhaps this should be handled in Connect -- if we're trying to match the official API. @szymonlesisz ?

**Comment by MisterTicot** [comment]
I suppose that `createPassiveSellOffer` and `manageSellOffer` can be defined as aliases into Connect - but what other interfaces such as CLI then?

`inflation` is clearly a marginal operation. In fact it is in the process of being removed from stellar-core (not 100% confirmed yet) so I guess there's no point.

`manageBuyOffer` is a new operation and should probably be added to the firmware.

**Comment by matejcik** [comment]
> I suppose that `createPassiveSellOffer` and `manageSellOffer` can be defined as aliases into Connect - but what other interfaces such as CLI then?

Again, our internal interfaces do not aim to match naming of the official API. The CLI tool accepts XDR data so there is no issue either.

> `manageBuyOffer` is a new operation and should probably be added to the firmware.

agreed. are you willing to make a PR for it?

**Comment by MisterTicot** [comment]
Well... That was my plan before I saw all that there are a number of file to change in various languages all over the place. I'm not sure I can deal with it - in fact I'm not sure I could even list them all.

**Comment by MisterTicot** [comment]
@matejcik 

Can provide me the complete list of files to edit? I'll tell you if I can deal with it.

**Comment by matejcik** [comment]
> Can provide me the complete list of files to edit? I'll tell you if I can deal with it. I assume you need to edit at least both firmwares, the API and tests files right?

correct.
here's the general list of places that we would need:

- the new operation needs to be added to protobuf defs, in `common/protob/messages-stellar.proto`
- depending on the fields in the new operation, `legacy/firmware/protob/messages-stellar.options` must be adjusted: all str/bytes fields must have a set `max_size`, all `repeated` fields must have `max_count`.
- implementation must be added to `core/src/apps/stellar`
- implementation must be added to `legacy/firmware`, presumably to `*stellar*`, but i'm not sure how the implementation is structured exactly
- a test must be added to `tests/device_tests/test_msg_stellar_sign_transaction.py`, you can take inspiration in my latest PR for the other Stellar bug
- support for the new operation must be added to `python/src/trezorlib/stellar.py` XDR decoder.

this is for firmware support only. I'm not sure what needs to be done on the Connect side.

**Comment by MisterTicot** [comment]
I'm going to look into this this week.

**Comment by MisterTicot** [comment]
@matejcik https://github.com/trezor/trezor-firmware/pull/627

**Comment by matejcik** [comment]
all operations mentioned in this issue are added in #1838
