### ISSUE TITLE
[BUG?] Stellar signing / manageData

### ISSUE THREAD

**Issue by MisterTicot** [trezor/trezor-firmware#581]
**Issue**

I could not figure a way to get the right signature for setting data entries to
values that have a length that is not a multiple of 4 bytes.

In other words, when setting data entries to values whose length in bytes is a
multiple of 4, the signature is good. This including unsetting data entry (using
an empty buffer as value).

**What I tried**

- Encode value as hex.
- Write value into a 64-byte _Buffer_ then encode as hex.
- Write value into the next higher multiple of 4 byte length _Buffer_ and encode
  as hex.

**Comment by matejcik** [comment]
@MisterTicot please provide an example transaction (ideally both in XDR and the JSON you are using). also please provide instructions on how to verify transaction signature :) is there an online resource we can use?

also please tell us if you're using T1 or TT

**Comment by MisterTicot** [comment]
**Device:** Trezor One, latest firmware

**Comment by MisterTicot** [comment]
**Fail:** https://test.cosmic.link/?manageData&network=test&name=data&value=abc
**Succeed:** https://test.cosmic.link/?manageData&network=test&name=data&value=abcd

You'll have to fund your testnet account to use this interface: https://www.stellar.org/laboratory/#account-creator

The XDR and JSON are logged in the dev console.

**Comment by MisterTicot** [comment]
Oh and you'll know that the signature is invalid when the "tx_bad_auth" error is returned.

**Comment by matejcik** [comment]
confirming. the same bug exists in T1 and TT, in that the value is not correctly padded to 4 bytes per XDR spec
