### ISSUE TITLE
RSK wallet needs access to BTC 44'/0'/0' path ("Failure_DataError": "Forbidden key path" as response)

### ISSUE THREAD

**Issue by jonathansmirnoff** [trezor/trezor-firmware#608]
In addition to his own path, the RSK wallet needs access to the BTC 44'/0'/0' path.
You can see that in the official documentation here: https://github.com/rsksmart/rskj/wiki/Send-funds-to-RSK.

We hope you can help with this issue. This is something new because in the past it was possible to access to BTC 44'/0'/0' path.

Thanks!

**Comment by prusnak** [comment]
I don't think we can help you there. Because what you are doing there is totally wrong. BIP-44 exists to separate the risk of various altcoins. Doing an Ethereum transaction using a Bitcoin private key is illegal.
