### ISSUE TITLE
add Magnum Wallet

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#622]
from slack:

> seznam coinu, ktery jsou podporovany v magnum wallet: btc, eth, xrp, dash, xtz, xem, zec, doge, kmd, clo, btx + vsechny ERC-20 tokeny (nevim, jestli se daj nejak poznat u tebe jednoduse, nebo jestli musim mit taky seznam?)
> melo by to bejt pridany jako "Magnum", link zde: https://magnumwallet.co/assets
> \+ pak budu mit neco podobnyho pro Exodus penezenku jeste.. tak si kdyztak zkus nejak pripravit ve volny chvilce a jakmile to bude mit Czibi nachystany po stranu UI, tak to muzem nahodit.. Kdyby s tim byl jakejkoliv problem, tak rekni co a jak a ja zkusim co nejdriv dodat ten seznam pro exodus

**Comment by prusnak** [comment]
fixed in https://github.com/trezor/trezor-firmware/commit/b23da6acb985daeeb30cb39c5f64a8bc28984e09
