### ISSUE TITLE
[BUG] Stellar Signing / Wrong Handling of Tx Source Account

### ISSUE THREAD

**Issue by MisterTicot** [trezor/trezor-firmware#637]
(I don't know if it comes from Connect of Firmware, please move the issue if relevant)

**Issue:**

Signing a transaction which use another source than the Trezor device leads to a wrong signature (in multi-signers account). Also, the device (T1) doesn't displays the information about the source account pubkey being used.

**Tx Template:**

Cannot come with one - happens with any kind of transaction where the primary source is not the Trezor device.

**Reproduce:**

1. Note the public key of your Trezor device.
2. Go to <https://stellar-authenticator.org> & click on `Guest Mode` to obtain a testnet account.
3. Got to `https://stellar-authenticator.org/?setOptions&network=test&signer=1:key:{TREZOR_PUBKEY}` where you replace `{TREZOR_PUBKEY}` with the required information. 
4. Confirm this transaction that will add your Trezor device as a co-signer for the test account.
5. Note the public key of your test account (one click = copy/paste).
6. Go to `https://test.cosmic.link/?setOptions&source={TEST_ACCOUNT_PUBKEY}`.
7. This is a noop that you should be able to sign with either your new test account or your Trezor device. However, if you try to sign with your Trezor device you'll get a `bad_auth` error.

**Comment by matejcik** [comment]
I believe this is fixed in 24bb4016388fca4b998285b95dcd408f4ed0bff6
