### ISSUE TITLE
Legacy bootloader too big

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#649]
Currently we have too big legacy bootloader as can be seen by running:

```
make -C bootloader align
```

Let's fix the issue (make bootloader smaller again) and replace the line here with the test above:

https://github.com/trezor/trezor-firmware/blob/93062c4cc25cb0b8f45bc184b9fc886e7a3bdb20/ci/build.yml#L175

**Comment by prusnak** [comment]
Fixed via https://github.com/trezor/trezor-firmware/commit/7476e9463f65165da081c8f582de0ab6a632c7ba

**Comment by tsusanka** [comment]
Let's add the check to CI?

**Comment by prusnak** [comment]
I realized it's already in the CI (`legacy/script/cibuild` already does it).

I removed the redundancy here 07cdebeb9be453283cfa5e261e7e8865c7f492e6
