### ISSUE TITLE
sdcard: disable card detect pull-up resistor in card with ACMD42

### ISSUE THREAD

**Issue by mcudev** [trezor/trezor-firmware#65]
Pin 2 of the microSD socket is CD/DAT3 (MCU pin PC11).
When the microSD card gets powered-on, it enables a pull-up resistor internal to the card on CD/DAT3.
This acts as a card detect pin since the card starts up in 1-bit mode and thus DAT3 is unused for data transfer at that time.
Later we change to use a 4-bit data bus, but don't disable the card's internal card detect pull-up resistor with ACMD42.
We should probably do that just to be safe before switching to 4-bit mode at https://github.com/trezor/trezor-core/blob/cb9e7b5885a47f900c24153e22e4f93b39cbb792/embed/trezorhal/sdcard.c#L149

`vendor/micropython/lib/stm32lib/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c` is useful for seeing how the HAL does its work.

Here's some more example code:
https://github.com/LonelyWolf/stm32/blob/master/cube-usb-msc/sdcard-sdio.c

Will probably end up with something functionally similar to this, but need to factor code, etc...
```
    // disable the card's internal CD/DAT3 card detect pull-up resistor
    // to send ACMD42, we have to send CMD55 (APP_CMD) with with the card's RCA as the argument followed by CMD42 (SET_CLR_CARD_DETECT)
    if(SDMMC_CmdAppCommand(sd_handle.Instance, (uint32_t)(sd_handle.SdCard.RelCardAdd << 16U)) != SDMMC_ERROR_NONE) {
    	goto error;
    }
    SDIO_CmdInitTypeDef  sdmmc_cmdinit;
    sdmmc_cmdinit.Argument         = 0U; // disable card detect resistor
    sdmmc_cmdinit.CmdIndex         = SDMMC_CMD_SD_APP_SET_CLR_CARD_DETECT;
    sdmmc_cmdinit.Response         = SDIO_RESPONSE_SHORT;
    sdmmc_cmdinit.WaitForInterrupt = SDIO_WAIT_NO;
    sdmmc_cmdinit.CPSM             = SDIO_CPSM_ENABLE;
    SDIO_SendCommand(sd_handle.Instance, &sdmmc_cmdinit);

    if (SDMMC_GetCmdResp1(sd_handle.Instance, SDMMC_CMD_SD_APP_SET_CLR_CARD_DETECT, SDIO_CMDTIMEOUT) != SDMMC_ERROR_NONE) {
    	goto error;
    }
```

Reference:

http://envoydatamemory.com/datasheets/EN-L0J%20Industrial%20microSD%20Card%20Spec%20Rev1.6.pdf

https://www.kingston.com/datasheets/SDCIT-specsheet-8gb-32gb_en.pdf

https://github.com/trezor/trezor-core/pull/279#issuecomment-406726759

**Comment by prusnak** [comment]
Implemented in dcff4ade013fdbadb8350bffd53aed1467cd5ba2

Thank you!
