### ISSUE TITLE
trezor t: updating to custom firmware results in Invalid firmware header

### ISSUE THREAD

**Issue by backpacker69** [trezor/trezor-firmware#652]
Greetings, I've built trezor firmware for my trezor t using docker-build.sh, fingerprints match those specified in releases json, however, but when I try to update firmware I get that:

```
trezorctl firmware-update -f tmp/firmware.bin
Trezor T firmware image.
Vendor header from SatoshiLabs, version 0.0
Firmware version 2.1.5 build 0
Invalid firmware signature.
Firmware validation failed, aborting.

trezorctl firmware-update -f tmp/firmware.bin -s
Update failed: ProcessError: Invalid firmware header
```

I've tried building v2.1.5, v2.1.6 and v2.1.7, all of them fail to update.

I can update to official firmwares, that works perfectly fine, but as soon as I try to update using self built ones, i get the error as mentioned above.

```
diff  /tmp/trezor.hex /tmp/my.hex
310,314d309
< 00015b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 03
< 00015c0 38 db 19 13 27 bb d8 92 c9 55 09 57 52 df 9a 57
< 00015d0 93 d8 9b 4b 65 00 49 09 4b dc 98 bc 2a a4 76 f8
< 00015e0 8a 50 a4 b3 db ac f9 62 84 39 ca 7a 09 70 a6 a2
< 00015f0 dc 6d 8c e2 5d e9 8d 5f a3 0c 31 08 61 26 9a 02
```

this is the only difference in 1.5 mb bin files. looks like a signature, my version has zeros in that area and it seems it breaks firmware update process.

what can I do to update my Trezor T to custom built firmware?

ps. running latest trezorctl version 0.11.5 installed with pip3, trezor bridge version: 2.0.27, macosx mojave 10.14.6

**Comment by prusnak** [comment]
Use `PRODUCTION=0 ./build-docker.sh` - this will use the firmware signed with the developers keys. What you have built is the production firmware which expects to be still signed with the official SatoshiLabs keys.

Be careful when loading this firmware into the device, it will wipe the storage when upgraded from the official firmware.
