### ISSUE TITLE
"Hold to confirm" in emulator with debug link is stuck sometimes 

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-firmware#655]
![ezgif-2-cafdd647703a](https://user-images.githubusercontent.com/3112191/67770087-f6b91680-fa55-11e9-8196-79871696075d.gif)

**Comment by prusnak** [comment]
This might be an SDL issue on macOS ...

**Comment by tsusanka** [comment]
It happens to me sometimes on Linux as well

**Comment by tsusanka** [comment]
cc @szymonlesisz this should be fixed in master now
