### ISSUE TITLE
Electrum cannot pair with your Trezor

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#656]
Electrum cannot pair with your Trezor error.
latest 2.1.8 regular firmware with seeds loaded.
But Electrum works fine. You see both devices connected + you are able to check QR,address, XPUB.
Send of transaction wasn't tested.
Nixos , Electrum 3.3.8

![image](https://user-images.githubusercontent.com/31506317/67771537-c4f57f00-fa58-11e9-9d5a-62900e6988e4.png)
![image](https://user-images.githubusercontent.com/31506317/67771682-0dad3800-fa59-11e9-89c3-79637337cd39.png)

log from console: https://paste.ofcode.org/mFk5mPKK8jB6eXgHRxiDMU

**Comment by bosomt** [comment]
+ both devices show 2 of 2 + same address :)

![IMG_20191029_151104](https://user-images.githubusercontent.com/31506317/67774972-8fec2b00-fa5e-11e9-843d-6797b025baee.jpg)

**Comment by bosomt** [comment]
tested with older firmware and this error goes way back at least up to 2.1.0 firmware

**Comment by bosomt** [comment]
same result with 2.0.8

**Comment by bosomt** [comment]
same results with Windows 7 + Electrum

**Comment by matejcik** [comment]
please add steps to reproduce

**Comment by bosomt** [comment]
![image](https://user-images.githubusercontent.com/31506317/67856278-74435c00-fb14-11e9-8d10-2ca28c781d8e.png)
![image](https://user-images.githubusercontent.com/31506317/67856291-7b6a6a00-fb14-11e9-923f-ccd8044fa6d8.png)
![image](https://user-images.githubusercontent.com/31506317/67856310-84f3d200-fb14-11e9-892f-1c6bf26d4b5e.png)
![image](https://user-images.githubusercontent.com/31506317/67856330-9210c100-fb14-11e9-837b-e9ec872410d9.png)
![image](https://user-images.githubusercontent.com/31506317/67856346-9dfc8300-fb14-11e9-8f1e-668979b196ed.png)
![image](https://user-images.githubusercontent.com/31506317/67856411-c2585f80-fb14-11e9-9e8c-0e326bb922ae.png)

**Comment by prusnak** [comment]
Oddly enough this does not happen when one of the devices is T1. In other words, both devices need to TT.

**Comment by prusnak** [comment]
The error comes from here: https://github.com/spesmilo/electrum/blob/ccccaf099faa9d3dc920d6895f4e0c4b58fd8e5f/electrum/plugin.py#L496

**Comment by matejcik** [comment]
@bosomt can you reproduce the problem if you make sure you *only* have two Trezors connected?

**Comment by matejcik** [comment]
i am 87 % sure this is an issue on Electrum side, so closing in favor of https://github.com/spesmilo/electrum/issues/5759
