### ISSUE TITLE
Investigate the memory usage of custom homescreen

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#674]
Latest 2.1.8 regular freezing problem

Since i loaded white noise background i'm experiencing freezing of device.
It's not GUI problem, device doesn't communicate with computer.
It's not happening every time but often. and always during address confirmation or sending of transaction. 

See video.
I will try to remove white noise background and i Will continue troubleshooting.

https://photos.app.goo.gl/dpK2vN1KEjxY2auQA

**Comment by bosomt** [comment]
Even it's not responding wallet/computer see it and you see error after you physically disconnect it

**Comment by bosomt** [comment]
And yes it' mem related.
Problem is gone after i load it with standard background.
And it's back after I load white noise background

**Comment by tsusanka** [comment]
Could you try on 2.1.7 and 2.1.6?

**Comment by bosomt** [comment]
i'm on it

**Comment by bosomt** [comment]
it's broken in 2.1.5 :(
same behavior

**Comment by bosomt** [comment]
it's broken in 2.1.6
same behavior

**Comment by bosomt** [comment]
2.1.4 has different behavior, but freezes too.
only backlight goes off, but device can be waken up

**Comment by prusnak** [comment]
Closed in favor of https://github.com/trezor/trezor-firmware/issues/684

**Comment by bosomt** [comment]
works fine with latest 2.1.9 with WN background
I will keep using WN background and if anything goes wrong I will reopen or create new issue
