### ISSUE TITLE
Return better info than FirmwareError when a ValueError is thrown

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#68]
Currently trezor-core returns Firmware Error, for example when modtrezorcrypto raises a ValueError. In some cases we want this to propagate into a wire.ProcessError, however not each time.

This should be investigated further to figure out how we want to approach this and make it somewhat compatible with trezor-mcu.

**Comment by ZdenekSL** [comment]
Closed in favor of #332

**Comment by ZdenekSL** [comment]
Closed in favor of #332
