### ISSUE TITLE
Recovery: unplugging Trezor before clicking on Success leads to an incorrect state

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#695]
After I enter the last share of my Shamir Backup I get:

![emu000000002](https://user-images.githubusercontent.com/1835345/68574038-51486e80-0469-11ea-8164-c2f3ca3881c7.png)

If I unplug the Trezor before clicking on "Continue" and start it again I get:

![emu00000000](https://user-images.githubusercontent.com/1835345/68574037-51486e80-0469-11ea-9f49-0b76b9a99d00.png)

which is incorrect.

**Comment by tsusanka** [comment]
We can either

1. Revert [this](https://github.com/trezor/trezor-firmware/commit/46c10e94021052989c66870c38290ec795bddd53). In another words end the recovery process before showing the success screen. Although this would probably now work with Wallet since we are now accepting all messages, it is a bit weird for the user - the Wallet gets refreshed before the user is able to click Continue.

2. Simly check somewhere in the homescreen if the remaining shares are 0 and identifier / exponent / backup type is set (probably just backup type is enough?) then we would end the progress.

@matejcik is what do you think?

**Comment by tsusanka** [comment]
We have agreed on 1.

**Comment by bosomt** [comment]
now it says starting up and after that PIN NOT SET My Trezor.

So it works fine. Tested
