### ISSUE TITLE
Bootloader: make install progress circle more smooth

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#70]
Currently, the first quarter is the erasure of the blocks. The last three quarters are firmware blocks being loaded.

We can do two optimizations:

a) 16 KiB block is erased 8x faster than 128 KiB block, let's take this into the account

b) if the upload firmware is small, the second part of the process is much shorter than the erasure of all blocks

This is just a nit-pick, so I am not assigning a particular milestone.

**Comment by matejcik** [comment]
this is already present in the current bootloader
