### ISSUE TITLE
Decline button for a new/reset PIN

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-firmware#702]
Just a suggestion for setting a new PIN or resetting a current one.

When you try to decline the set/reset of the PIN, there should be a different button then a lock sign on a red background, for example, a cross.

The lock on a red background should be there only when you want to decline this when you are actually entering a PIN on a locked device.

firmware version 2.1.8

![trezor_pin](https://user-images.githubusercontent.com/48477147/68766344-feb0b300-061e-11ea-9007-47850f96c2ed.png)

**Comment by tsusanka** [comment]
@trezor/qa please retest.

- When setting a new PIN the left lower button should not be a lock but an orange `<-`. Please check that and test that the functionality did not change.

**Comment by bosomt** [comment]
2.3.1

![image](https://user-images.githubusercontent.com/31506317/84773908-5f510580-afdd-11ea-8a35-5fadccc86d6f.png)

vs

2.3.2 current master trezor-fw-regular-2.3.2-b6c8cbc2.bin

![image](https://user-images.githubusercontent.com/31506317/84773995-80195b00-afdd-11ea-8dcc-670290bb1d8b.png)

and yes functionality did not changed, you can set PIN code and you are asked for PIN code next time

**Comment by tsusanka** [comment]
Great. Please add the QA test successful then please.

**Comment by sorooris** [comment]
please ignore, i'm testing markdown

**QA OK**

2.3.1 8859d10 | 2.3.2 b6c8cbc2
------------ | -------------
![image](https://user-images.githubusercontent.com/10185314/84775993-0d5daf00-afe0-11ea-94b1-074f842640bc.png) | ![image](https://user-images.githubusercontent.com/31506317/84773995-80195b00-afdd-11ea-8dcc-670290bb1d8b.png)

Note: Functionality did not change - PIN code can be set is asked for the next time.
