### ISSUE TITLE
Drop U2F counter from Bitcoin-only firmware

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#709]
The u2f functionality is disabled on Bitcoin-only firmware, but the management commands SetU2FCounter and GetNextU2FCounter are still available.

They don't affect much, but they should probably be removed too.

**Comment by matejcik** [comment]
apparently Wallet onboarding sets the U2F counter, so we must investigate whether it's using this call

**Comment by prusnak** [comment]
Also there are `u2f_counter` fields in `ResetDevice`, `LoadDevice` and `RecoverDevice` messages.

**Comment by matejcik** [comment]
This does not seem at all important for the foreseeable future.
