### ISSUE TITLE
Display dry run result on device display

### ISSUE THREAD

**Issue by michal-novacek** [trezor/trezor-firmware#73]
The device responds with a success or failure message after a `recovery_device` with `dry_run: true` is completed. It would be nice if it also displayed the result of the dry run on display.

This is mostly for consistency with T1 and web wallet. The risks of not displaying the result on device are minimal, since modifying it doesn't really benefit potential attacker.

**Comment by pankrats** [comment]
There is the same issue in trezor-qa folder : https://github.com/satoshilabs/trezor-qa/issues/34

**Comment by pankrats** [comment]
Expected: The result of "Check recovery seed" procedure should be displayed **on the device screen** (and preferably on the device screen only). 

At the moment, with Trezor T (firmware 2.1.1) the result is displayed in the wallet only. Nothing is displayed on device screen.
![screenshot from 2018-07-20 12-26-50](https://user-images.githubusercontent.com/31442634/42997798-44e71dfa-8c18-11e8-8c21-fe5f83b0a861.png)

Trezor One (fw 1.8.1) displays the result on the device screen and in the wallet as well. 

![photo_2018-07-20_12-35-52](https://user-images.githubusercontent.com/31442634/42998179-911ded10-8c19-11e8-8f2e-0da43e27b6de.jpg)
![2019-06-13 12 27 29](https://user-images.githubusercontent.com/31442634/59425652-aad34100-8dd6-11e9-9dba-cf73ef1d2f52.jpg)




Reported by @sipak

**Comment by tsusanka** [comment]
This was done during the works on Shamir and the persistance.
