### ISSUE TITLE
inconsistent coin definitions field names: "divisibility" vs "decimals"

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-firmware#743]
**Describe the bug**
Since [this commit](https://github.com/trezor/trezor-firmware/commit/5301c03607471b65e100a5c51ff7f93e708cc0e2) there are new field in every "bitcoin-like" coin called `divisibility`

**Expected behavior**
This type of field already exist in other coins definitions (misc, erc-20) and it's called `decimals`

**Comment by prusnak** [comment]
Ack for renaming `divisibility` into `decimals`

**Comment by prusnak** [comment]
Fix in the `decimals` branch

**Comment by prusnak** [comment]
Fixed in 7646b97dca78c2343bff68458ff7fb694e3e004f

I also updated trezor-common repo to contain this change
