### ISSUE TITLE
FW build is failing on master

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#753]
FW build is failing on master: https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/378241787 on `embed/trezorhal/sdcard.c:49:10: fatal error: mpconfigport.h: No such file or directory` most likely because of the work on the SD card.

**Comment by prusnak** [comment]
Oddly, this works for me locally :-/

**Comment by prusnak** [comment]
Fixed in master. Sorry :-/
