### ISSUE TITLE
ETH address w/o checksum shown WITH checksum on device

### ISSUE THREAD

**Issue by jonathancross** [trezor/trezor-firmware#754]
**Describe the bug**
When sending to a standard, **lowercase** ETH address (without checksum), the Trezor Model T will ask the user to confirm a different address -- one which has been checksummed using uppercase letters.  Also affects ETC.

**Firmware version or revision**
2.1.8

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor Beta Wallet
 - OS: macOS
 - Browser: chrome

**To Reproduce**
1. Go to https://beta-wallet.trezor.io/next/
2. Send any amount of ETH to `0xdecaf9cd2367cdbb726e904cd6397edfcae6068d`
3. When viewing on the Trezor Model T screen, notice that address has changed to `0xDECAF9CD2367cdbb726E904cD6397eDFcAe6068D`

**Expected behavior**
Address entered into Trezor wallet site should be identical to the one shown on device for confirmation.

**Comment by prusnak** [comment]
This is Ethereum bug and more precisely how they introduced (non-mandatory) checksum. Ethereum users should know how this behaves.
