### ISSUE TITLE
Internal error when Wipe PIN code entered

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#757]
Internal error when Wipe PIN code entered.

FW version 2.2.0

Chromium
Nixos
Beta wallet + trezorctl latest github build

How to preproduce

set wipe code
set PIN code
change PIN code
enter wipe PIN code 

or

set wipe code
set PIN code
start dry run
enter wipe PIN code 

expected: Device is wiped and you will see info that it was wiped

Real result:
![IMG_20191217_183610_2](https://user-images.githubusercontent.com/31506317/70994792-41a6f000-20cf-11ea-9e4b-863a9ae87fdc.jpg)

but device is wiped

**Comment by bosomt** [comment]
same behavior when you try to disable wipe code
trezorctl set wipe-code -r
you are asked for pin code, enter wipe pin code


internal error

**Comment by prusnak** [comment]
Resolved in master + release/2020-10 branch.

**Comment by bosomt** [comment]
works fine now
