### ISSUE TITLE
add the option to cancel Wipe and SignTx button requests on device display

### ISSUE THREAD

**Issue by michal-novacek** [trezor/trezor-firmware#76]
After user initiates a wipe or signtx action, they may change their mind and decide to cancel it. However, a cancel button is not displayed anywhere on the device and unplugging the device to cancel the request is inconvenient.

Once a button request is initiated, it is a convention for the web wallet to display a blocking modal that doesn't allow user to navigate elsewhere and doesn't close until the action is finished or cancelled on device. There are ways to close this modal and cancel the action from the web app but they are hacky and go against UX consistency.

**Comment by tsusanka** [comment]
I have discussed this with @matejzak and Petr. Petr came up with this for now, which is basically what @prusnak drafted up:

<img width="295" alt="Screenshot 2020-02-27 at 10 25 07" src="https://user-images.githubusercontent.com/1835345/75561760-d1f69f00-5a47-11ea-8516-3a4eb09f15d7.png">

We have also realized that in some places (such as wipe) a red cancel is probably not a good idea next to a red Hold to confirm button - maybe orange back button or similar?. Also in some cases we might want to leave the inability to cancel the dialog (such as the one when doing backup, see above).

Partially implemented in `tsusanka/hold-to-confirm-cancel`.

**Comment by tsusanka** [comment]
Petr has finished and we have agreed on:

![Screenshot from 2020-03-02 10-07-20](https://user-images.githubusercontent.com/1835345/75661688-106da300-5c6e-11ea-96c9-a97a1231cda8.png)

PR is coming.

**Comment by matejcik** [comment]
wait, shouldn't the "Backup your seed" -> "I understand" be non-cancellable?

right now when you cancel that, you'll probably get a failed backup, isn't that right?

**Comment by tsusanka** [comment]
I have found out the "I understand" button is a regular button, not hold to confirm and therefore not affected by this change.

https://github.com/trezor/trezor-firmware/blob/09c3fd1981ced7013c6e5b55530874b4dc5c9e47/core/src/apps/management/reset_device/layout.py#L259
