### ISSUE TITLE
Make multiple signatures for signature with multiple keys from one device

### ISSUE THREAD

**Issue by achow101** [trezor/trezor-firmware#762]
When there's a multisig that has multiple keys from one device, it is necessary to sign the transaction multiple times and specify a different signing key each time. It would be nice if it were possible to specify multiple signing keys in the same signing and have the Trezor sign the multisig with all of those keys. This way the same transaction does not need to be signed multiple times.

**Comment by matejcik** [comment]
While nice to have, this is an extremely niche usecase that would at the same time seem to complicate the signing protocol.
Closing for now. We might revisit this when implementing more multisig improvements in the future.
