### ISSUE TITLE
USB device enumeration failed

### ISSUE THREAD

**Issue by pengguoguo** [trezor/trezor-firmware#766]
**Is your feature request related to a problem? Please describe.**
I am studying the code; I have been able to boot bootloader to firmware, but when I run firmware, USB cannot be enumerated successfully by PC ; when I try to trace the code, the program can run the norcow_get function in the storage_upgrade function;
Why the USB can't be enumerated successful by PC?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by prusnak** [comment]
This is hard to debug remotely.

Are you sure you got all the hardware details right?
