### ISSUE TITLE
You can enable or disable wipe code when PIN is not enabled

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#768]
**Describe the bug**
You can enable or disable wipe code when PIN is not enabled

**Firmware version or revision**
2.2.0 ffafe2cc

**Desktop/smartphone setup (please complete the following information):**
latest trezorctl
Chromium 78
Nixos

**To Reproduce**
disable PIN code
trezorctl set wipe-code
trezorctl set wipe-code -r

**Expected behavior**
You can't enable or disable wipe code without PIN protection

**Comment by prusnak** [comment]
This is intended behaviour.
