### ISSUE TITLE
trezor-one's inittialization default value for new chips 

### ISSUE THREAD

**Issue by pengguoguo** [trezor/trezor-firmware#771]
What are the initialization defaults for new chips? How are their storage locations distributed? At present, can know the configuration of g_header and address from the code; What about the others values?
I port  codes about firmware, but still can't enum ok by PC;
After  I comment config_init() this function, it can be enum ok by PC,but this isn't the solution to the problem.
PLS, can you provideany ideas and material?

**Comment by prusnak** [comment]
https://github.com/trezor/trezor-firmware/blob/master/legacy/memory.h
