### ISSUE TITLE
Questions about CONFIG_MAGIC_V10

### ISSUE THREAD

**Issue by pengguoguo** [trezor/trezor-firmware#773]
**Is your feature request related to a problem? Please describe.**
Hi, everybody. I am studying codes about trezor-firmware. I have troubles about them. First, about CONFIG_MAGIC_V10, when this magic constant had been written 0x08008100 address and what had tool software  used to write this magic constant to flash?
Thanks!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by prusnak** [comment]
This is written in the storage when you use older firmware than 1.8.0. This are the bytes to identify the config sector v 1.0.
