### ISSUE TITLE
Strange font spacing

### ISSUE THREAD

**Issue by good-lly** [trezor/trezor-firmware#78]
There is some strange spacing behind letters, for example small 'r' and large 'T'

![tap](https://user-images.githubusercontent.com/1671375/35866391-61a6748c-0b57-11e8-972f-20692354fad8.jpg)
![r](https://user-images.githubusercontent.com/1671375/35866399-6465afd0-0b57-11e8-8d81-b31f3b7cf5f2.jpg)

**Comment by ZdenekSL** [comment]
@pankrats Please retest this issues.

**Comment by pankrats** [comment]
Can confirm, the spacing is still the same. 

Here is the strange spacing after "T":
![photo_2019-06-25 15 31 18](https://user-images.githubusercontent.com/31442634/60102622-55941980-975e-11e9-8ff5-fc214f3c18e5.jpeg)

And here is the "re" combination (in "remaining)":
![photo_2019-06-25 15 31 26](https://user-images.githubusercontent.com/31442634/60102669-6f356100-975e-11e9-9537-4f19cd9f3145.jpeg)

**Comment by jpochyla** [comment]
If we decide to fix this, I'd also suggest making the font smaller.

**Comment by ZdenekSL** [comment]
Closed after discussion
