### ISSUE TITLE
python-trezor: Build information outdated

### ISSUE THREAD

**Issue by brandsimon** [trezor/trezor-firmware#788]
I wanted to install python-trezor from the git repository.
In the Docs there is mentioned to run `python3 setup.py prebuild`, which says: `error: Deprecated. Run 'make gen' instead.`
Also the python docs point to the old repository: `https://github.com/trezor/python-trezor`.
Running `make gen` results in the error, that `src/trezorlib/coins.json` got removed, but not recreated.
Can you please update the build information?

**Comment by matejcik** [comment]
the `make gen` problem is also related to #752

**Comment by matejcik** [comment]
FWIW: you don't need to run `make gen` at all actually. use git to restore the `coins.json` file and proceed to install with `python3 setup.py develop`

**Comment by brandsimon** [comment]
@matejcik 
Yes, this worked for me, thank you
