### ISSUE TITLE
install: cannot stat '/src/build/firmware/firmware/trezor-emulator.bin'

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-firmware#8]
Trezor emulator build (build.sh EMU) throws this 

`install: cannot stat '/src/build/firmware/firmware/trezor-emulator.bin'`

Not sure if related to https://github.com/trezor/trezor-mcu/issues/423 ; I am building on macOS

**Comment by prusnak** [comment]
matejcik says this is fixed in 9f8ebcf1833e2f56c86df854c915385b0e9f43af

Please reopen if this doesn't work
