### ISSUE TITLE
Show Wei amount and contract address for unknown tokens 

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#800]
We could improve UX of unknown tokens, by:
1) showing wei amount of the token being transacted
2) showing the contract address on the second page of the confirm dialog

**Comment by bosomt** [comment]
**QA OK**

Nixos
Suite be4e3a36f7dbe15b2b203f66de11edc50a6665b8
Device: fw-regular-2.3.5-889a3699
