### ISSUE TITLE
Disable timing checks in u2f-tests-hid for emulator/CI

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#804]
We have had problems with passing U2F tests running on the CI machine when it is overloaded with jobs, because the emulator fails to respond in time. It doesn't make much sense to check the transfer times against the emulator in the CI. These checks should be done when running the tests on a user system against a real device. We have been hotfixing this by disabling the entire test which causes issues, but the proper solution is to disable just the part of the test which does the timing check.

Re-enable all U2F tests and add a macro to disable the timing checks in the problematic ones:
test_InitOther()
test_LongEcho()
test_Timeout()
test_Limits()
test_Busy()
test_Interleave()
test_OnlyInitOnBroadcast()

**Comment by 1000101** [comment]
This sounds more like an issue on the infrastructure side (not taking into account whether the tests are really necessary). All failing jobs were running on a low(er) performance runners which have now been suspended. Furthermore, high-performance runners have been optimized to run more smoothly. If it's not a demanding, time-consuming task and if it makes your life easier, I would opt for re-enabling them and see if the situation improves.
