### ISSUE TITLE
SD card format feature

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#807]
**Is your feature request related to a problem? Please describe.**
Please add format feature to SD protect feature, it's confusing that there is no info about required SD card format.

**Describe the solution you'd like**
trezorctl device sd-protect format

**Comment by andrewkozlik** [comment]
Good point. Trezor could also offer to format the card if it finds that the filesystem is not recognized. If the user would choose to proceed, then it would show a hold-to-confirm dialog alerting the user that all the data on the SD card will be lost.

**Comment by prusnak** [comment]
Fix in https://github.com/trezor/trezor-firmware/pull/833

**Comment by prusnak** [comment]
I will soon push FatFS update to master which includes:
* `FatFS.mkfs()` for the device (previously it was enabled only for the emulator)
* `FatFS.setlabel()`

We'd need to adapt the `ensure_filesystem` decorator so it does the following instead of `fs.mount()`:

``` python
try:
    fs = io.FatFS()
    fs.mount()
except OSError:
    text = Text("SD card error", ui.ICON_WRONG, ui.RED)
    text.normal("Unrecognized filesystem")
    text.normal("found. Unplug the device")
    text.normal("and remove the card or")
    text.normal("you can format the card")
    text.normal("losing all the data on it.")
    dialog = HoldToConfirm(text, confirm="Format SD card")
    await dialog
    fs.mkfs()
    fs.setlabel("TREZOR")
    fs.mount()
```

This will not be that easy, because the decorator is not a coroutine and we cannot call `await` inside. That's why I am leaving the final fix to someone else who understands async better than me.

**Comment by prusnak** [comment]
More UI suggestions by andrew here: https://github.com/trezor/trezor-firmware/pull/833#discussion_r376432774

**Comment by matejcik** [comment]
QA scenarios:

* use a FAT32-formatted SD card, try Trezor's SD features, they should work as usual
* use an unformatted SD card, try Trezor's SD features. Trezor should ask whether you wish to format. If you format the card, Trezor should work fine, and the SD card should be readable on PC
* if you don't format the card, Trezor should cleanly inform you of the problem

**Comment by matejcik** [comment]
a quirk of the current setup: if you have SD protection enabled, and insert an unformatted SD card, Trezor will first ask to format the card -- even though it could technically just reject with "wrong SD card" immediately.

not sure if we want to change this?

**Comment by andrewkozlik** [comment]
> a quirk of the current setup: if you have SD protection enabled, and insert an unformatted SD card, Trezor will first ask to format the card -- even though it could technically just reject with "wrong SD card" immediately.
> 
> not sure if we want to change this?

Good point. I think we should reject the card in that case.

**Comment by bosomt** [comment]
**QA OK**

solved via https://github.com/trezor/trezor-firmware/pull/833
