### ISSUE TITLE
UI tests: Replace hash.txt for each test with one large hash file

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#813]
@matejcik mentioned it seems to him the GitHub PRs are getting slow because of many hash.txt files. We could improve this by including the hashes in one large file, but still keep it per test.

Do we want use some format for this like YAML/JSON? Or plain text with `;` as a delimiter (`:` is used in the names)?

**Comment by matejcik** [comment]
I think JSON is the superior choice here: it's included in Python (unlike yaml), we get character escaping for free (zero additional work on parsing), and it's still going to be readable with one line per entry.

**Comment by prusnak** [comment]
+1 for JSON
