### ISSUE TITLE
Dry run for supershamir with one share asks for one more after reconnect

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#815]
**Describe the bug**
Dry run for supershamir with one share asks for one more after reconnect when asked to press continue.
Recovery works fine.

**Firmware version or revision**
2.2.1

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: beta
 - OS: win 10
 - Browser chrome
 - Version latest

**To Reproduce**
start dry run
enter 1 of 1 share from group
don't press continue but reconnect device
you are asked to enter share

**Expected behavior**
dry run should end /i think/

**Screenshots**
![image](https://user-images.githubusercontent.com/31506317/73544111-c27c3a00-4438-11ea-87e8-e2e2c145c0be.png)

**Comment by bosomt** [comment]
seed: https://pastebin.com/MHHLBjjZ

**Comment by tsusanka** [comment]
@bosomt please retest with https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/422067169/artifacts/download

**Comment by bosomt** [comment]
@tsusanka works fine!

**Comment by tsusanka** [comment]
Closed by https://github.com/trezor/trezor-firmware/commit/277e494ffa42fbd3ae4e747e5f0e60c99251070e

**Comment by bosomt** [comment]
**QA OK**

FW 2.3.2 e70811c
wallet b3f18eb73765f92dd35eff2c562ef1edb5dd9fa3
latets nixos and Chrome
