### ISSUE TITLE
Fix flashing bootloader from SD card in boardloader after chaning SD card to use DMA

### ISSUE THREAD

**Issue by hiviah** [trezor/trezor-firmware#820]
Flashing bootloader from boardloader doesn't work anymore after switching to use of DMA for SD card transfers.

When attempting to flash bootloader from SD card now, the code gets stuck in infinite cycle in `SystemInit` from `embed/trezorhal/stm32.c`.

**Comment by hiviah** [comment]
Usign normal STLink while debugging boardloader makes it stuck upon system reset in `SystemInit` when oscillators switch from HSI to HSE. Black Magic Probe does not seem to suffer from this issue.

There are 2 interrupt handlers to go with SD card, `DMA2_Stream3_IRQHandler` and `SDIO_IRQHandler` which somewhere in depths call `HAL_SD_IRQHandler`.

In functioning case (e.g. firmware) there should be the same number of DMA and SDIO IRQs (can be seen by enabling irq_stats field).

Strange thing is that just by breaking on DMA handler in debugger, the SDIO handler starts coming. It's always 5 SDIO interrupts and one DMA interrupt no matter how many delay/timeouts or how much time you wait in the debugger

**Comment by hiviah** [comment]
Apparenty STM32F4xx can't do read/write via DMA to CCMRAM (0x10000000), only to SRAM (0x20000000). Which results in the strange behavior only in boardloader which is put in CCMRAM and not in firmware.

**Comment by hiviah** [comment]
Either of moving boardloader to SRAM from CCMRAM in linker script or using buffer at some absolute SRAM address seems to fix this.

**Comment by prusnak** [comment]
Fix in https://github.com/trezor/trezor-firmware/pull/876

**Comment by tsusanka** [comment]
@prusnak @hiviah do I understand correctly that this issue is "QA-covered" by the others and I can apply the `doesn't need QA` tag?

**Comment by prusnak** [comment]
@tsusanka right, I just did apply the tag
