### ISSUE TITLE
QR code button is all white in 1.9.0

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#824]
**Describe the bug**
QR code button is all white in 1.9.0 it should be QR code

**Firmware version or revision**
1.9.0

**Desktop/smartphone setup (please complete the following information):**
Suite and beta wallet
latest chrome

**To Reproduce**
go to wallet and hit show full address

**Expected behavior**
Button must say  QR code

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/31506317/73736642-6a4b7d80-4741-11ea-9691-527cc0932ce2.png)

**Comment by prusnak** [comment]
Fixed in 0ceba808760a61b014f1a0bee9a22919ffdee6d4

**Comment by bosomt** [comment]
works fine in latest master build

**Comment by bosomt** [comment]
**QA OK**

FW 1.9.1 0xc6b2580cd245ee924507f45e9675f857a3d78768,
wallet b3f18eb73765f92dd35eff2c562ef1edb5dd9fa3
