### ISSUE TITLE
Improve Monero UI

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#83]
Monero release is coming (hopefully) and the current UI is indeed unpleasant. Nothing too special is required, simple "circle filling" for signing would be great.

**Comment by ph4r05** [comment]
The overall progress could be computed as: `3*num_ins + num_outs + 4`.

**Comment by prusnak** [comment]
Probably implemented in https://github.com/trezor/trezor-firmware/pull/95

Needs testing

**Comment by tsusanka** [comment]
I've passed this on to testers.

**Comment by prusnak** [comment]
Testing is tracked in https://github.com/trezor/trezor-firmware/issues/104 Let's close this
