### ISSUE TITLE
trezorctl emits warnings when it sees unknown capabilities

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#832]
**Describe the bug**
when enabling sd card protetion it works,
but you see errors 

**trezorctl sd-protect enable**
Value 17 unknown for type Capability
Please confirm action on your Trezor device
Value 17 unknown for type Capability
SD card protection enabled

**Firmware version or revision**
trezorctl

**To Reproduce**
trezorctl sd-protect enable

**Comment by tsusanka** [comment]
@matejcik could you write some test scenarios or mark this one as `doesn't need QA`? We probably do not need QA to test this?

**Comment by matejcik** [comment]
this is a `trezorctl` thing so it probably goes outside QA anyway?
