### ISSUE TITLE
Integrate IoTeX blockchain

### ISSUE THREAD

**Issue by dustinxie** [trezor/trezor-firmware#836]
**Is your feature request related to a problem? Please describe.**
No, a new feature request

**Describe the solution you'd like**
Integrate IoTeX blockchain

**Describe alternatives you've considered**

**Additional context**
IoTeX Mainnet was launched in April of 2019 and has been steadily running for almost 10 months with 6 major upgrades from version 0.5 to version 0.10, processing ~3 million transactions smoothly.
 
Given this level of maturity, and given that more and more applications are emerging on IoTeX blockchain, we officially started the token swap process for exchanging IOTX-E (ERC20 version of IoTeX token which is overwhelmingly used and traded) to IOTX (native coin living on top of IoTeX blockchain). In addition, Binance, Gate.io and Kucoin already support native IOTX.
 
Exciting times ahead! We are inviting you to follow and support IoTeX Mainnet and visit https://github.com/iotexproject/iotex bootstrap/blob/master/integration/exchange.md to learn more on integrating with IoTeX Mainnet and we will be happy to help you with your inquiries.

**Comment by matejcik** [comment]
At this time we are only adding support for coins that are in the Top 30 by market cap.
