### ISSUE TITLE
Investigate and clean up dialog cancelling

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-firmware#838]
The modules `trezor.ui.confirm`, `trezor.ui.pin` and `trezor.ui.passphrase` each define a `CANCELLED` object of their own as `CANCELLED = object()`. We then use it as `if pin is CANCELLED:`. This could easily create a nasty mess if we get these objects mixed up.
1. There should either be only one such object or if there need to be three, then they should have unique names (`PIN_CANCELLED` etc.).
2. In addition to this, `apps.common.request_pin` defines a `PinCancelled` exception. I haven't looked into it myself, but we should evaluate whether it wouldn't be more appropriate to use exceptions in the first place instead of the `CANCELLED` objects.
3. We should also consider whether some of these exceptions should be derived from a wire error like the `SdProtectCancelled` exception. I vaguely recall thinking about using the `DUMMY_CONTEXT` in the PIN entry workflow to simplify the code. This might be related.

**Comment by matejcik** [comment]
this will be resolved by the move to Rust-based UI
