### ISSUE TITLE
Show USB Chrome pop up dialog only if no firmware is present

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#841]
This was brought up by @matejzak and the Suite team again.

![Screenshot from 2020-02-11 15-36-37](https://user-images.githubusercontent.com/1835345/74246211-748eee00-4ce4-11ea-997b-95711e61602f.png)

------

We went back and forth on the Chrome pop up dialog. Removing it at some point and adding it back later because of phishing concerns if I remember correctly.

Many users find this annoying. Also with the introduction of Suite it does not make any sense anymore, does it?

I suggest to remove the pop up completely or we could show it only if the device is new (= no firmware installed) to simplify the onboarding and downloading of Suite.

**Comment by prusnak** [comment]
The dialog is only shown when there is a Chrome browser running and honestly, I think this should be a setting in Chrome whether to show these.

That said, showing the pop-up only if the device is new (only bootloader with no firmware) is acceptable from where I stand.

**Comment by tsusanka** [comment]
> The dialog is only shown when there is a Chrome browser running and honestly, I think this should be a setting in Chrome whether to show these.

Yet that is true, how many users do not have a Chrome browser running in the background these days..

**Comment by matejzak** [comment]
> we could show it only if the device is new (= no firmware installed) to simplify the onboarding and downloading of Suite.

Sounds like a perfect solution to me.

**Comment by prusnak** [comment]
PR in #845
