### ISSUE TITLE
Match the XPUBs on the device with the ones on the client

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#855]
**Describe the bug**

Reported here: https://twitter.com/_benma_/status/1227900614505566208
and here: https://twitter.com/_benma_/status/1227912076368252928

There are two issues with GetAddress for multisig:

- [ ] while Electrum shows `Zpub`, Trezor shows `xpub` - we should be showing the same value
- [x] we should indicate which of the shown XPUBs belongs to the device

**Comment by matejcik** [comment]
re (1) what Electrum shows as "master public key" seems unrelated to the XPUB in the address. Although the `show_xpubs` method does not reflect the address type correctly (legacy / p2sh / segwit), the correct result will be different from the "master public key" anyway

**Comment by prusnak** [comment]
2) is fixed for TT in https://github.com/trezor/trezor-firmware/pull/860

**Comment by prusnak** [comment]
The second issue is fixed for T1 in #862

**Comment by prusnak** [comment]
The first issue is impossible to be fixed without overhauling the multisig protocol. Putting back to backlog.

**Comment by prusnak** [comment]
First issue has fix in PR https://github.com/trezor/trezor-firmware/pull/1415
