### ISSUE TITLE
Do not ask to format SD card when unlocking sd-protect

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#868]
When the user tries to unlock Trezor with an unformatted SD card, and sd-protect is enabled, Trezor will first ask to format the card, and only then reject it as the wrong one.

Instead, it should reject the SD card straight away; an unformatted SD card is clearly not the correct one for sd-protect.

**Comment by matejcik** [comment]
QA scenarios:

* enable SD protect and insert a correct SD card / an incorrect but formatted SD card / an incorrect and not-formatted SD card (make a NTFS filesystem on it or something)
* SD protect should fail the same way with a wrong card and with an unformatted card

**Comment by bosomt** [comment]
**QA OK**

web dev suite master 8cc3650adbb123a224def6e0a024f25a8b7f5cc8
fw 2.3.2 e70811ce
latest nixos and chromium
