### ISSUE TITLE
Passphrase entry dialog stays forever when animations are disabled

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#883]
While hunting for #882 I have noticed another bug. The "Passphrase entry" dialog stays until another screen is shown, which is very confusing to the user.

The dialog should disappear on PassphraseAck.

This applies of course only for `PassphraseAck.on_device = False`.

**Comment by matejcik** [comment]
> The dialog should disappear on PassphraseAck.

the dialog should disappear at the end of the flow, actually, when the homescreen reappears. How did you trigger this?

**Comment by tsusanka** [comment]
Just go to https://suite.corp.sldev.cz/suite-web/develop/, enable passphrase and enter some passphrase.

I am just investigating.

**Comment by matejcik** [comment]
could not reproduce. The text goes away as soon as I enter the passphrase, replaced by a "please wait" empty screen -- as it should, because "please wait" is deriving the seed

**Comment by tsusanka** [comment]
That is really weird. I am getting the same behaviour also using `trezorctl get-address`.

**Comment by tsusanka** [comment]
This happens on emulator with disabled animations only (`-a`).

**Comment by tsusanka** [comment]
@matejcik ACKed. Did you mark the cardano ui tests for some reason or they were just redundant?

**Comment by matejcik** [comment]
There's nothing going on in the test, it's homescreen -> type password -> homescreen. They should have been excluded before.
