### ISSUE TITLE
Trezor One's OLED ModuleSpecification Driver question

### ISSUE THREAD

**Issue by pengguoguo** [trezor/trezor-firmware#897]
**Describe the bug**
OLED Disp Module is UG-2864HSWEG01 OLED  in Trezor One's BOM. I buy the same type module, but use 1.8.3 version code can't initialize and light module; I only read ssd1306's data sheet to program driver code operate disp module.
I have a question What type of  disp module is Trezor One using?

under my codes:
/****************************************************************************/
void Write_Command(unsigned char Data)
{
  /* CS */
    gpio_clear(OLED_CS_PORT, OLED_CS_PIN);
    delay(1);
    /* DC -- > Command*/
    gpio_clear(OLED_DC_PORT,OLED_DC_PIN);
    delay(1);
  SPISend(SPI_BASE,(uint8_t *)&Data,1);
  delay(1);
  /* DC --> Data */
  gpio_set(OLED_DC_PORT,OLED_DC_PIN);
  delay(1);
  gpio_set(OLED_CS_PORT, OLED_CS_PIN);
}

void Write_Data(unsigned char Data)
{
  gpio_clear(OLED_CS_PORT, OLED_CS_PIN);
  delay(1);
  gpio_set(OLED_DC_PORT, OLED_DC_PIN);    // set to DATA
  delay(1);
  SPISend(SPI_BASE, &Data, 1);
  delay(1);
  gpio_set(OLED_DC_PORT, OLED_DC_PIN);    // set to DATA
  delay(1);
  gpio_set(OLED_CS_PORT, OLED_CS_PIN);
}

//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
//  Instruction Setting
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
void Set_Start_Column(unsigned char d)
{
  Write_Command(0x00 + d%16);   // Set Lower Column Start Address for Page Addressing Mode
                        // Default => 0x00
  Write_Command(0x10 + d/16);   // Set Higher Column Start Address for Page Addressing Mode
                        // Default => 0x10
}

void Set_Addressing_Mode(unsigned char d)
{
  Write_Command(0x20);      // Set Memory Addressing Mode
  Write_Command(d);         //   Default => 0x02
                        //   0x00 => Horizontal Addressing Mode
                        //   0x01 => Vertical Addressing Mode
                        //   0x02 => Page Addressing Mode
}

void Set_Column_Address(unsigned char a, unsigned char b)
{
  Write_Command(0x21);      // Set Column Address
  Write_Command(a);         //   Default => 0x00 (Column Start Address)
  Write_Command(b);         //   Default => 0x7F (Column End Address)
}

void Set_Page_Address(unsigned char a, unsigned char b)
{
  Write_Command(0x22);      // Set Page Address
  Write_Command(a);         //   Default => 0x00 (Page Start Address)
  Write_Command(b);         //   Default => 0x07 (Page End Address)
}

void Set_Start_Line(unsigned char d)
{
  Write_Command(0x40 | d);      // Set Display Start Line
                            //   Default => 0x40 (0x00)
}

void Set_Contrast_Control(unsigned char d)
{
  Write_Command(0x81);      // Set Contrast Control
  Write_Command(d);         //   Default => 0x7F
}

void Set_Charge_Pump(unsigned char d)
{
  Write_Command(0x8D);      // Set Charge Pump
  Write_Command(0x10|d);      //   Default => 0x10
                        //     0x10 (0x00) => Disable Charge Pump
                        //     0x14 (0x04) => Enable Charge Pump
}

void Set_Segment_Remap(unsigned char d)
{
  Write_Command(0xA0 | d);      // Set Segment Re-Map
                            //   Default => 0xA0
                            //     0xA0 (0x00) => Column Address 0 Mapped to SEG0
                            //     0xA1 (0x01) => Column Address 0 Mapped to SEG127
}

void Set_Entire_Display(unsigned char d)
{
  Write_Command(0xA4 | d);    // Set Entire Display On / Off
                        //   Default => 0xA4
                        //     0xA4 (0x00) => Normal Display
                        //     0xA5 (0x01) => Entire Display On
}

void Set_Inverse_Display(unsigned char d)
{
  Write_Command(0xA6 | d);    // Set Inverse Display On/Off
                        //   Default => 0xA6
                        //     0xA6 (0x00) => Normal Display
                        //     0xA7 (0x01) => Inverse Display On
}

void Set_Multiplex_Ratio(unsigned char d)
{
  Write_Command(0xA8);      // Set Multiplex Ratio
  Write_Command(d);         //   Default => 0x3F (1/64 Duty)
}

void Set_Display_On_Off(unsigned char d)
{
  Write_Command(0xAE | d);      // Set Display On/Off
                        //   Default => 0xAE
                        //     0xAE (0x00) => Display Off
                        //     0xAF (0x01) => Display On
}

void Set_Start_Page(unsigned char d)
{
  Write_Command(0xB0 | d);      // Set Page Start Address for Page Addressing Mode
                        //   Default => 0xB0 (0x00)
}

void Set_Common_Remap(unsigned char d)
{
  Write_Command(0xC0|d);      // Set COM Output Scan Direction
                        //   Default => 0xC0
                        //     0xC0 (0x00) => Scan from COM0 to 63
                        //     0xC8 (0x08) => Scan from COM63 to 0
}

void Set_Display_Offset(unsigned char d)
{
  Write_Command(0xD3);      // Set Display Offset
  Write_Command(d);         //   Default => 0x00
}

void Set_Display_Clock(unsigned char d)
{
  Write_Command(0xD5);      // Set Display Clock Divide Ratio / Oscillator Frequency
  Write_Command(d);         //   Default => 0x80
                        //     D[3:0] => Display Clock Divider
                        //     D[7:4] => Oscillator Frequency
}

void Set_Precharge_Period(unsigned char d)
{
  Write_Command(0xD9);      // Set Pre-Charge Period
  Write_Command(d);         //   Default => 0x22 (2 Display Clocks [Phase 2] / 2 Display Clocks [Phase 1])
                        //     D[3:0] => Phase 1 Period in 1~15 Display Clocks
                        //     D[7:4] => Phase 2 Period in 1~15 Display Clocks
}

void Set_Common_Config(unsigned char d)
{
  Write_Command(0xDA);      // Set COM Pins Hardware Configuration
  Write_Command(0x02|d);      //   Default => 0x12 (0x10)
                        //     Alternative COM Pin Configuration
                        //     Disable COM Left/Right Re-Map
}

void Set_VCOMH(unsigned char d)
{
  Write_Command(0xDB);      // Set VCOMH Deselect Level
  Write_Command(d);         //   Default => 0x20 (0.77*VCC)
}

void Set_NOP(void)
{
  Write_Command(0xE3);      // Command for No Operation
}

//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// 
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
void Fill_RAM(unsigned char Data)
{
  unsigned char i,j;

  for(i=0;i<8;i++)
  {
    Set_Start_Page(i);
    Set_Start_Column(0x00);
    for(j=0;j<128;j++)
    {
      Write_Data(Data);
    }
  }
}

void Show_Buffer_Data(void)
{
  unsigned char i,j;

  uint8_t *pArray = NULL;
  pArray = _oledbuffer;

  for(i = 0;i < 8;i++)
  {
    Set_Start_Page(i);
    Set_Start_Column(0);

    for(j = 0; j < 128 ;j++)
    {
      Write_Data(*pArray);
      pArray++;
    }

  }
}

/*
 * Initialize the display.
 */
void oledInit() {

  gpio_clear(OLED_RST_PORT,OLED_RST_PIN);

  delay(400);

  gpio_set(OLED_RST_PORT,OLED_RST_PIN);

  Set_Display_On_Off(0x00);       // Display Off (0x00/0x01)
  Set_Display_Clock(0x80);        // Set Clock as 100 Frames/Sec
  Set_Multiplex_Ratio(0x3F);        // 1/64 Duty (0x0F~0x3F)
  Set_Display_Offset(0x00);       // Shift Mapping RAM Counter (0x00~0x3F)
  Set_Start_Line(0x00);         // Set Mapping RAM Display Start Line (0x00~0x3F)
  Set_Charge_Pump(0x04);          // Enable Embedded DC/DC Converter (0x00/0x04)
  Set_Addressing_Mode(0x02);        // Set Page Addressing Mode (0x00/0x01/0x02)
  Set_Segment_Remap(0x00);        // Set SEG/Column Mapping (0x00/0x01)
  Set_Common_Remap(0x00);         // Set COM/Row Scan Direction (0x00/0x08)
  Set_Common_Config(0x10);        // Set Sequential Configuration (0x00/0x10)
  Set_Contrast_Control(Brightness); // Set SEG Output Current
  Set_Precharge_Period(0xF1);       // Set Pre-Charge as 15 Clocks & Discharge as 1 Clock
  Set_VCOMH(0x40);              // Set VCOM Deselect Level
  Set_Entire_Display(0x00);       // Disable Entire Display On (0x00/0x01)
  Set_Inverse_Display(0x00);        // Disable Inverse Display On (0x00/0x01)

  Fill_RAM(0x00);               // Clear Screen

  Set_Display_On_Off(0x01);       // Display On (0x00/0x01)
}

**Firmware version or revision**
1.8.3
**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: [e.g. Trezor Wallet, Trezor Beta Wallet, Trezor Suite, Electrum]
 - OS: [e.g. Windows, macOS, Linux, Android]
 - Browser [e.g. chrome, firefox, safari]
 - Version [e.g. 42]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by prusnak** [comment]
We use UG-2864HSWEG01
