### ISSUE TITLE
DataError: string overflow with T1 when PIN too long

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#903]
**Describe the bug**
When you set wipe code or PIN code via trezorctl, you can enter long code and it will result with error **trezorlib.exceptions.TrezorFailure: DataError: string overflow**

**Firmware version or revision**
Firmware version 1.9.0 

**Desktop/smartphone setup (please complete the following information):**
 trezorctl 12 and 11.6

**To Reproduce**
trezorctl set pin
trezorctl set wipe-code
and enter longer number than max PIN lenght

**Expected behavior**
You will get proper error

**Comment by bosomt** [comment]
Device gets wiped during this operation:

trezorctl set wipe-code
WebUSB transport is disabled: libusb-1.0.so: cannot open shared object file: No such file or directory
Please confirm action on your Trezor device
Use the numeric keypad to describe number positions. The layout is:
    7 8 9
    4 5 6
    1 2 3
Please enter current PIN: 

when I enter 90 device gets wiped,
can this be related or is it different issue ?
@matejcik @tsusanka

**Comment by matejcik** [comment]
different issue, please create a separate one

**Comment by bosomt** [comment]
sent https://github.com/trezor/trezor-firmware/issues/904

**Comment by matejcik** [comment]
fixed in #906

**Comment by tsusanka** [comment]
@matejcik does this need QA?

**Comment by matejcik** [comment]
i don't think so, if #904 is tested
