### ISSUE TITLE
Cannot use the Trezor Wallet

### ISSUE THREAD

**Issue by ladislavmacoun** [trezor/trezor-firmware#905]
**Describe the bug**

I haven't use my trezor for a while, now after wanting use wallet.trezor.io again I can't get my trezor working. I have installed the newest drivers which did not helped. The wallet.trezor.io keeps asking to install the bridge driver over again. I've disabled adblock, and tried to use the chrome app. Neither helped.

On Mac, I can see the Trezor at the "Check for devices", on windows it is not even listed.

**Firmware version or revision**
Bridge Driver 2.0.27

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor Wallet
 - OS: Windows 10, macOS  10.14.6 and 10.15.3
 - Browser Chrome
 - Version 80.0.3987.132 (Official Build) (64-bit)

**To Reproduce**
1. Go to  https://wallet.trezor.io https://old-wallet.trezor.io
2. Click on https://wallet.trezor.io/#/bridge
3. Install the bridge software
4. Reopen 1.

**Expected behavior**
Install the bridge driver and get to wallet.

**Screenshots**
<img width="1031" alt="Screenshot 2020-03-13 at 12 51 08" src="https://user-images.githubusercontent.com/15619993/76619411-121b4e80-652b-11ea-9e94-cf8c77d25a2d.png">
*Additional context**

**Comment by ladislavmacoun** [comment]
I forgot to mention it's Trezor One

**Comment by ladislavmacoun** [comment]
I tried to use Firefox instead of Chrome and it works, however, it's weird since the 2fa is working on chrome. 🤷‍♂️

**Comment by prusnak** [comment]
Since it's working for you in Firefox this is hardly a firmware issue. If you need further help contact our support please.
