### ISSUE TITLE
docker: emulator support refactoring

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#91]
There was a suggestion by ph4r05 how to refactor dockerfiles for emulator.

Let's evaluate this.

Old PR: https://github.com/trezor/trezor-core/pull/481
Old patch: https://github.com/trezor/trezor-core/pull/481/commits/f6a683a4251887e31ad283b88058ae4ce206ed3a

**Comment by tsusanka** [comment]
The docker folder was removed in https://github.com/trezor/trezor-firmware/commit/e30159c000bea180f456ac6bcace0811d274e384 . I'm not sure anyone was actually using this or if we wish to support it in future. Currently, anyone can download frozen emulator artifact, which should run right away.

In case we do decide to support it, we should use the Docker image from CI registry.

**Comment by ZdenekSL** [comment]
Closed after discussion
