### ISSUE TITLE
explicit closing of sessions

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#912]
With the newly introduced multi-session support, there are some usecases where we want to use a session for a short time and then free up the cache slot for further uses.

* when we want to reprompt for a passphrase (e.g. in Trezor Suite empty wallet confirmation), we need to allocate a new session. Every reprompt potentially evicts one of the valid passphrased sessions.
* when enumerating connected devices, we should (although don't _need_ to, technically speaking) initialize a session to get Features. repeated enumerations would also needlessly evict sessions

We propose a new message, `EndSession`, that cancels the current session, erases its ID and removes it from the cache.
Subsequent calls without `Initialize` would return a new failure code, `InvalidSession`. For ease of implementation, we could allow calls that do not touch session data (e.g., device settings), and return the failure only for calls that use the seed.

**Comment by tsusanka** [comment]
This probably doesn't need QA since it is not yet in Suite right?

**Comment by matejcik** [comment]
correct
