### ISSUE TITLE
[Trezor-crypto] Bip32 issue how its handled

### ISSUE THREAD

**Issue by f4r4** [trezor/trezor-firmware#924]
**Describe the bug**
Its a BIP32 bug, specifically in hardened key derivation where private keys are not properly padded when the MSB is a 0x00 byte.

Is a fix available for this on trezor-crypto library ?

**Additional context**
https://github.com/OpenBazaar/openbazaar-go/issues/384
https://github.com/iancoleman/bip39/issues/58

**Comment by prusnak** [comment]
This is of course not a problem with our library.
