### ISSUE TITLE
Latest pipenv update breaks mypy

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#934]
Style fails for master with updated dependencies (39709dea). See [CI](https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/500092171): 

```
mypy --config-file ../setup.cfg \
	src/main.py
mypy: "mocks/sys.pyi" shadows library module "sys"
note: A user-defined top-level module with name "sys" is not supported
```

I actually do not need to update pipenv but since I've encountered this I've figured we might just fix it right away.

@matejcik do you think you would take a look?

**Comment by prusnak** [comment]
Just had the same issue - raising priority.

The error is caused by the following change in the MyPy 0.770: https://github.com/python/mypy/pull/8405/files
