### ISSUE TITLE
Run device tests on an actual TT in CI

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#946]
Related to #935. We need to add support to [tpmb](https://github.com/mmahut/tpmb) for TT first.

**Comment by tsusanka** [comment]
On today's meeting we have realized we can do this also without tpmb (with the debug mode on of course).

We could modify the bootloader and:
- Always enter the bootloader, do not require any screen touch to enter.
- Do not overwrite the unofficial bootloader using firmware.
- Do not wait for the click when the firmware is loading up even if the firmware header says so.

cc @prusnak

**Comment by hiviah** [comment]
Also the firmware should be immediately booted after loading it via bootloader and not reset (otherwise we would get bootloader bootloop).

**Comment by hiviah** [comment]
The bootloader will delete storage on boot to make testing deterministic.

**Comment by tsusanka** [comment]
Let's wait for the "workflow separation" task currently being done by @matejcik .

**Comment by mmilata** [comment]
monero tests take about 10m to run on hardware, should we add them too?

**Comment by matejcik** [comment]
yeah, let's

**Comment by matejcik** [comment]
with #1565, the only tests that fail on hardware are the following:
```
FAILED ../../tests/device_tests/test_msg_signtx_bcash.py::TestMsgSigntxBch::test_send_bch_multisig_change
1198FAILED ../../tests/device_tests/test_msg_signtx_bgold.py::TestMsgSigntxBitcoinGold::test_send_bitcoin_gold_nochange
1199FAILED ../../tests/device_tests/test_msg_signtx_bgold.py::TestMsgSigntxBitcoinGold::test_send_p2sh
1200FAILED ../../tests/device_tests/test_msg_signtx_bgold.py::TestMsgSigntxBitcoinGold::test_attack_change_input
1201FAILED ../../tests/device_tests/test_msg_signtx_bgold.py::TestMsgSigntxBitcoinGold::test_send_multisig_1
1202FAILED ../../tests/device_tests/test_msg_signtx_bgold.py::TestMsgSigntxBitcoinGold::test_send_btg_multisig_change
1203FAILED ../../tests/device_tests/test_msg_signtx_bgold.py::TestMsgSigntxBitcoinGold::test_send_btg_external_presigned
1204FAILED ../../tests/device_tests/test_msg_signtx_bgold.py::TestMsgSigntxBitcoinGold::test_send_mixed_inputs
1205FAILED ../../tests/device_tests/test_msg_signtx_bgold.py::TestMsgSigntxBitcoinGold::test_send_p2sh_witness_change
1206FAILED ../../tests/device_tests/test_msg_signtx_bgold.py::TestMsgSigntxBitcoinGold::test_send_bitcoin_gold_change
```
the Bitcoin Gold failures are extra weird because even simple tests like `test_send_p2sh` fail. This is something to look into.
