### ISSUE TITLE
Running pytest using emu.py captures output even if -s is provided

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#951]
Maybe this is desired but I found it curious. Running:

```
./emu.py --output=a.log -a -c pytest -s ../tests/device_tests/test_msg_getentropy.py
```

prints no test output (entropy data in this case), however running the emulator and pytest separately does.

**Comment by matejcik** [comment]
fixed in master. FWIW the `-s` got parsed as emulator option `--slip0014`, you could have worked around that by using `./emu.py -c -- pytest -s ...`
