### ISSUE TITLE
Electrum + Passphrase Firmware 2.3.0 TT

### ISSUE THREAD

**Issue by rondolfo** [trezor/trezor-firmware#952]
When updating my TT to the new firmware 2.3.0 and using it in conjunction with Electrum 3.3.8 the insertion of the passphrase is only possible via the keyboard.

The option to type on the device screen is disabled with the message:
Please type your passphrase on the connected host

**Comment by prusnak** [comment]
Reported and fixed here: https://github.com/spesmilo/electrum/pull/6064

We need to wait until Electrum team publishes the change in their next version update.
