### ISSUE TITLE
FIDO2 test suite fails for specific random order seed

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#953]
**Describe the bug**
TestGetAssertion.test_empty_allowList fails on specific random seed (`380783`). I was able to reproduce this on my local machine.

**Firmware version or revision**
master 9e4a8ca78552de452572026c5bc064b5c1d1cfe6

**How to reproduce**
1. start emu
2. cd vendor/fido2-tests
3. run pytest: 

```
pytest --sim tests/standard/ --vendor trezor --random-order-seed=380873
```

Test fails on:

```
Failed: DID NOT RAISE <class 'fido2.ctap.CtapError'>
```

**Comment by andrewkozlik** [comment]
Fixed in https://github.com/trezor/trezor-firmware/commit/4a889f34cd5c9b11aca021b9c0e4f44ab8551aa1.
