### ISSUE TITLE
Update token list - RSK Chain - RIF

### ISSUE THREAD

**Issue by jonathansmirnoff** [trezor/trezor-firmware#960]
I have noticed that it is referenced to an older version of ethereum token list (https://github.com/ethereum-lists/tokens/tree/88414ef852e21279f217d2f3f8fd439cd7c5fd9f) in https://github.com/trezor/trezor-firmware/tree/master/common/defs/ethereum. 

Recently the ethereum-lists project has been updated and I was wondering when you will update the reference. It has been added RIF token. This a token from RSK chain. My goal is to allow Trezor to decode the erc20 token transfer transaction in RSK chain.

Added 2 PRs related to this:
https://github.com/ethereum-lists/tokens/pull/339
https://github.com/ethereum-lists/tokens/pull/305

**Comment by jonathansmirnoff** [comment]
Also I'm ready to help with this.

**Comment by matejcik** [comment]
fixed in eeb46eabca24f40e60d41be31b44703d4964e578
