### ISSUE TITLE
U2F authentication broken in 1.9.0 in Github

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-firmware#961]
**Describe the bug**
When you login to GitHub device asks you to Register U2F device
Not asking you to authenticate but to register.
edit: but only when device is not registered, it works fine when device is registered

**Firmware version or revision**
1.9.0 broken
1.8.3 works fine

**Desktop/smartphone setup (please complete the following information):**
nixos
firefox 75.0

**To Reproduce**
1. Go to 'github.com'
2. Login via security key
3. use firmware 1.9.0

**Expected behavior**
1.8.3 firmware says Authenticate

**Screenshots**

![u2f](https://user-images.githubusercontent.com/31506317/80078061-a6c39400-854e-11ea-8356-6504ca1f4656.jpg)

**Comment by prusnak** [comment]
key 000000 means that you have another token registered with the service

**Comment by bosomt** [comment]
@prusnak yes i have couple of them registered

+ when you try to add it again you won't get usual response that it's already registered but this:

![image](https://user-images.githubusercontent.com/31506317/80080936-94e3f000-8552-11ea-8a98-c209e94f3158.png)

**Comment by bosomt** [comment]
but this error is same with 1.8.3 FW

**Comment by andrewkozlik** [comment]
I think I know exactly what this is about. FF uses a different BOGUS_APPID than Chrome. We only check the Chrome BOGUS_APPID in T1 code. Trezor T should be handling this correctly.

@bosomt Please also check Edge and Safari browsers.

**Comment by bosomt** [comment]
@andrewkozlik Win10+Edge and MAC+Safari works fine

**Comment by prusnak** [comment]
So maybe we should use the 000000 bogus ID to T1 codebase same way we did for TT.

**Comment by andrewkozlik** [comment]
@bosomt I prepared a fix here: https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/523731139/artifacts/download.

There are two error scenarios:
1. Trying to register a token which is already registered.
2. Trying to log in with a token which isn't registered.

In Firefox both should work correctly now. In Chrome, the first one doesn't work nicely, it shows an authentication request. I think I investigated this a while back and found that we can't do anything about it, it's a Chrome issue. Can you elaborate on what doesn't work with Edge and Safari? Scenario + what appears in the browser + what appears on Trezor.

**Comment by bosomt** [comment]
FF: says not registered when not registered
FF: when registered , works fine

EDGE: when not registered: unknown key and Trezor has no message, just homepage
EDGE: when registered , works fine

Safari: im not at office anymore, so im not able to test it,

**FIXED**

**Comment by bosomt** [comment]
sorry I forgot about that 1. scenario.

this one is broken

1) you add token, this works fine
2) add one more time, this will ask you: **Authenticate U2F security key** ? 
3) press Authenticate : Already registered

so it works properly but it suppose to ask add Register not Authenticate,  but we can say that it indicates that it's already registered ;)

**Comment by andrewkozlik** [comment]
> so it works properly but it suppose to ask add Register not Authenticate, but we can say that it indicates that it's already registered ;)

Unfortunately, I think we can't do anything about that on our side. As long as the user gets the information about the token being already registered, it's OK.

**Comment by bosomt** [comment]
@andrewkozlik great, so closing

**Comment by danielg4** [comment]
Current firmware here. Just tried to add a Passkey in GitHub a short time ago, and T1 said it was already registered on another device, meaning Chrome was sending its bogus AppId. This is just speculation on my part, but maybe GitHub is trying FIDO2 first, and falling back to FIDO1, which the T1 actually supports, but the legacy firmware gets confused by the way Chrome handles the fallback?
