### ISSUE TITLE
Missing ToS in recovery in T1

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#972]
Similar to #495 but for T1. We do not confirm ToS when doing recovery on T1.

**Comment by tsusanka** [comment]
QA:
Please test the ToS sentence is present on both T1 and TT.

**Comment by sorooris** [comment]
**QA OK.** 

Device:
T1 1.9.1 revision 81553df0

Tested against:
MyTrezor [baking crocodile branch](https://mytrezor.corp.sldev.cz/baking-crocodile/development/#/) 97ec35
Suite [fix/zcash-sign branch](https://suite.corp.sldev.cz/suite-web/develop/wallet/send/?trezor-connect-src=https://connect.corp.sldev.cz/fix/zcash-sign/) 30cb3eb
