### ISSUE TITLE
Change name of "trezor" folder on sd-card for storing the salt

### ISSUE THREAD

**Issue by dnaleor** [trezor/trezor-firmware#986]
**Is your feature request related to a problem? Please describe.**
It doesn't seems to be a good idea to have the SD-card folder named "trezor" when the intended use case (at least for me) is carrying around the SD-card in my wallet so if people break into my house and find my trezor, they can't use it. Also, in case you get questioned by government, it's better to have as little as possible information on that sd-card. 

**Describe the solution you'd like**
At least rename the folder to something boring like "devices"
A better solution would be to encrypt the SD-card with a passphrase. When you want to unlock the Trezor you would first need to type the passphrase on the Trezor screen, which would decrypt the SD-card, which would then unlock the Trezor.

**Describe alternatives you've considered**
I don't see any alternatives for getting better plausible deniability in this case

**Comment by tsusanka** [comment]
Hi there, thank you for your suggestion. After a thorough discussion we have decided we do not wish to implement this feature. We need to prioritize our backlog and focus on features that bring the most value to our customers. We also need to restrict the feature set to keep the firmware small and maintainable. Also this would require some backwards-compatible support in a delicate part of the code which we would like to avoid. Thank you for your understanding.
