### ISSUE TITLE
Design signed data blob for translations

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#988]
During discussions on #987 @prusnak came up with an idea to use one whole memory block in Trezor's [storage](https://docs.trezor.io/trezor-firmware/hardware/model-t/memory.html) for signed blob of data received from the Host. The blob will contain mainly the translation strings for the chosen language, however its usage might be broader (e.g. coininfo etc.). We currently assume it would have 128KB.

This blob can be replaced only as a whole. We might split the blob into parts, provide hashes for each part and update only the parts that has changed. However, since uploading 128KB should take about 1s (fair guesstimate) this should be quite seamless for the user. We will consider this optimization later then, if necessary.

This issue covers:
- [x] Design and document how the blob data will be structured.
- [x] Provide API to access the data.
- [x] Research whether this is applicable for T1 as well.
- [x] Research what the is the appropriate blob size. Is 128K the correct size?

---

Part of #987. Related: signing the blob #1016, exchange mechanism #1017

**Comment by prusnak** [comment]
I came up with the following blob structure: https://github.com/trezor/trezor-firmware/blob/master/docs/storage/addon-block.md 

Let's discuss this further whether this meets our needs.

**Comment by prusnak** [comment]
Push the design of the i18n-block + modtrezori18n prototype to the[`i18n-block`](https://github.com/trezor/trezor-firmware/tree/i18n-block) branch.
