### ISSUE TITLE
Replace all English strings with identifiers and collect them

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#991]
We need to replace all UI texts with identifiers. Firmware will then have no language and we will load the correct strings from the data blob (as defined in #988).

We need to collect all the English strings into a single file. This file will be then fed into [Crowdin](https://crowdin.com/) for the actual translating process.

We are currently considering two options:

1. Extract the strings using libcst/gettext, see @matejcik's comment [here](https://github.com/trezor/trezor-firmware/issues/989#issuecomment-627883458).
2. Collect the strings using device tests. Similarly to UI tests, we would run device tests against the emulator and gather all the strings that are displayed. Each time something is printed on the display we would store the string in some local json/xml file. Later we would concatenate all those files into a single one.

Both should be done automatically on CI.

---

Part of #987.

**Comment by prusnak** [comment]
I think this task is not really blocked by fully implementing #989. We can collect all localized strings to a separate file (e.g. `i18n.py`) before the blob mechanism is in place.

**Comment by matejcik** [comment]
Agreed. We need i18n.py anyway, the emulator-running-from-sources must be able to load strings without using a blob.

**Comment by tsusanka** [comment]
> We can collect all localized strings to a separate file (e.g. i18n.py) before the blob mechanism is in place.

Let's do this first!

**Comment by tsusanka** [comment]
I have merged #989 into this one.
