### ISSUE TITLE
Implement UI tests also for Legacy

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#996]
Core's UI tests help significantly @petrsulc with his work on the UI redesign. He would appreciate having the same UI reports also for the current T1 firmware. It helps him a lot on his quest to map the current UI.

Main question: how difficult is it? Does it make sense? @prusnak might have an idea?

Developing something in a project we try to deprecate kind of sucks, but if it is not too much of a work it would help..

**Comment by prusnak** [comment]
I would not create the full blown UI tests for legacy. But creating a screenshot set is quite easy. I can provided a one-shot solution which screenshots images for Petr

**Comment by tsusanka** [comment]
That'd be great (and enough)!

**Comment by prusnak** [comment]
Sent via Slack
